/**
 * ============================================================================
 * VEHICLE TYPE & PLATFORM REGISTRY (18 CATEGORIES)
 * ============================================================================
 * Master registry defining the 18 vehicle categories, subcategories,
 * baseline dimensions, compatible chassis architectures, body shells,
 * drivetrain possibilities, development trees, and engineering constraints.
 */

import { DriveType, EnginePosition, SuspensionType } from "../types";

export type VehicleCategoryId =
  | "hatchback"
  | "sedan"
  | "coupe"
  | "convertible"
  | "wagon"
  | "crossover"
  | "suv"
  | "offroad_4x4"
  | "grand_tourer"
  | "sports_car"
  | "supercar"
  | "hypercar"
  | "gt3_race"
  | "formula_open_wheel"
  | "prototype_lmp"
  | "pickup"
  | "van_mpv"
  | "ev_platform";

export interface CategoryChassisOption {
  id: string;
  name: string;
  architecture: "monocoque" | "spaceframe" | "carbon_tub" | "tubular_cradle" | "ladder" | "ev_skateboard";
  description: string;
  rigidity: string;
  rigidityNmPerDeg: number;
  massKg: number;
  material: string;
  engineBayVolumeL: number;
  maxWheelbaseMm: number;
  minWheelbaseMm: number;
}

export interface CategoryBodyOption {
  id: string;
  name: string;
  style: string;
  description: string;
  dragDeltaCd: number;
  downforceDeltaKg: number;
  massDeltaKg: number;
  doorsCount: number;
  cargoCapacityL: number;
}

export interface CategoryDevelopmentTree {
  bodyMods: string[];
  chassisMods: string[];
  suspensionMods: string[];
  aeroMods: string[];
  powertrainMods: string[];
}

export interface VehicleCategoryDefinition {
  id: VehicleCategoryId;
  name: string;
  group: "road" | "suv_utility" | "sports_exotic" | "motorsport" | "electric";
  tagline: string;
  description: string;
  subcategories: string[];
  silhouetteType: string;

  // Typical Dimensions Baseline (mm)
  dimensions: {
    wheelbase: { min: number; max: number; default: number };
    frontTrack: { min: number; max: number; default: number };
    rearTrack: { min: number; max: number; default: number };
    rideHeight: { min: number; max: number; default: number };
    overallLength: { min: number; max: number; default: number };
    overallWidth: { min: number; max: number; default: number };
    overallHeight: { min: number; max: number; default: number };
    frontOverhang: { min: number; max: number; default: number };
    rearOverhang: { min: number; max: number; default: number };
    cabinPositionPct: number; // 0% front to 100% rear
  };

  // Mass & Packaging
  typicalWeightKg: { min: number; max: number; default: number };
  typicalSeating: number[];
  luggageVolumeL: { min: number; max: number; default: number };
  engineBayVolumeL: number;

  // Powertrain & Architecture
  recommendedArchitecture: string;
  allowedEnginePositions: EnginePosition[];
  defaultEnginePosition: EnginePosition;
  allowedDrivetrains: DriveType[];
  defaultDrivetrain: DriveType;
  allowedSuspensions: SuspensionType[];
  defaultSuspensionFront: SuspensionType;
  defaultSuspensionRear: SuspensionType;

  // Aero & Engineering
  aeroClass: string;
  baseCd: number;
  baseFrontalAreaM2: number;
  downforcePotential: "minimal" | "moderate" | "high" | "extreme" | "ground_effect";
  engineeringDifficulty: "Entry Level" | "Moderate" | "Advanced" | "Extreme" | "FIA Prototype";
  developmentCost: number; // USD

  // Component Catalogs
  compatibleChassis: CategoryChassisOption[];
  compatibleBodies: CategoryBodyOption[];
  developmentTree: CategoryDevelopmentTree;
}

export const VEHICLE_CATEGORIES: Record<VehicleCategoryId, VehicleCategoryDefinition> = {
  hatchback: {
    id: "hatchback",
    name: "Hatchback",
    group: "road",
    tagline: "Agile 2-box urban commuter & aggressive hot-hatch performance platform.",
    description: "Compact 2-box silhouette with integrated rear liftgate, optimal urban packaging, low weight and sharp transverse cornering dynamics.",
    subcategories: ["City Hatch", "Hot Hatch", "Performance Hatch", "Rallycross Special"],
    silhouetteType: "hatchback",
    dimensions: {
      wheelbase: { min: 2380, max: 2680, default: 2560 },
      frontTrack: { min: 1480, max: 1620, default: 1540 },
      rearTrack: { min: 1470, max: 1610, default: 1530 },
      rideHeight: { min: 110, max: 160, default: 135 },
      overallLength: { min: 3800, max: 4350, default: 4120 },
      overallWidth: { min: 1720, max: 1880, default: 1790 },
      overallHeight: { min: 1400, max: 1520, default: 1450 },
      frontOverhang: { min: 720, max: 880, default: 810 },
      rearOverhang: { min: 620, max: 790, default: 750 },
      cabinPositionPct: 52,
    },
    typicalWeightKg: { min: 1040, max: 1480, default: 1240 },
    typicalSeating: [4, 5],
    luggageVolumeL: { min: 280, max: 450, default: 360 },
    engineBayVolumeL: 220,
    recommendedArchitecture: "Front-engine transverse / FWD",
    allowedEnginePositions: ["front"],
    defaultEnginePosition: "front",
    allowedDrivetrains: ["fwd", "awd"],
    defaultDrivetrain: "fwd",
    allowedSuspensions: ["macpherson", "torsion_beam", "multilink", "double_wishbone"],
    defaultSuspensionFront: "macpherson",
    defaultSuspensionRear: "torsion_beam",
    aeroClass: "Low Drag Urban",
    baseCd: 0.31,
    baseFrontalAreaM2: 2.15,
    downforcePotential: "minimal",
    engineeringDifficulty: "Entry Level",
    developmentCost: 450000,
    compatibleChassis: [
      {
        id: "hatch_unibody_std",
        name: "Lightweight Stamped Steel Unibody",
        architecture: "monocoque",
        description: "High-volume stamped galvanized steel unibody with reinforced A/B pillars and optimized crumple zones.",
        rigidity: "28 kNm/°",
        rigidityNmPerDeg: 28000,
        massKg: 280,
        material: "Galvanized High-Strength Steel",
        engineBayVolumeL: 220,
        minWheelbaseMm: 2380,
        maxWheelbaseMm: 2680,
      },
      {
        id: "hatch_hot_monocoque",
        name: "Hot-Hatch Seam-Welded Reinforced Monocoque",
        architecture: "monocoque",
        description: "Laser-welded ultra-high-strength steel monocoque with strut tower braces and bonded structural foam.",
        rigidity: "38 kNm/°",
        rigidityNmPerDeg: 38000,
        massKg: 310,
        material: "Dual-Phase DP980 Steel & Structural Adhesives",
        engineBayVolumeL: 240,
        minWheelbaseMm: 2420,
        maxWheelbaseMm: 2680,
      },
      {
        id: "hatch_alu_spaceframe",
        name: "Aluminum Subframe Lightweight Platform",
        architecture: "spaceframe",
        description: "Extruded aluminum front and rear subframes mated to an ultra-lightweight hybrid passenger shell.",
        rigidity: "34 kNm/°",
        rigidityNmPerDeg: 34000,
        massKg: 245,
        material: "6000-Series Extruded Aluminum",
        engineBayVolumeL: 230,
        minWheelbaseMm: 2400,
        maxWheelbaseMm: 2650,
      },
    ],
    compatibleBodies: [
      {
        id: "hatch_5door",
        name: "5-Door Practical City Hatch",
        style: "5-door hatchback with split tailgate",
        description: "Maximum daily practicality with wide rear door apertures and low lift-over trunk access.",
        dragDeltaCd: 0.0,
        downforceDeltaKg: 0,
        massDeltaKg: 0,
        doorsCount: 5,
        cargoCapacityL: 380,
      },
      {
        id: "hatch_3door",
        name: "3-Door Sport Hatch Shell",
        style: "Sleek 3-door with elongated front doors",
        description: "Rigid aerodynamic sport coupe-hatch profile with reduced seal count and higher torsional stability.",
        dragDeltaCd: -0.015,
        downforceDeltaKg: 10,
        massDeltaKg: -22,
        doorsCount: 3,
        cargoCapacityL: 340,
      },
      {
        id: "hatch_hothatch_wide",
        name: "Hot-Hatch Widebody Aero Package",
        style: "Flared fenders +25mm, roof spoiler, front splitter",
        description: "Aggressive flared wheel arches accommodating 245mm rubber, roof spoiler, and functional rear diffuser.",
        dragDeltaCd: +0.02,
        downforceDeltaKg: 45,
        massDeltaKg: +18,
        doorsCount: 5,
        cargoCapacityL: 360,
      },
    ],
    developmentTree: {
      bodyMods: ["Reinforced Hatch Gate", "Composite Bonnet", "Flared Arch Extensions", "Roof Spoiler Lip"],
      chassisMods: ["Front Subframe Brace", "Rear Torsion Bar Stiffener", "Underbody Tunnel Shield"],
      suspensionMods: ["Lowering Sport Springs", "Adaptive Dampers", "Uprated Anti-Roll Bars"],
      aeroMods: ["Front Bumper Air Curtains", "Rear Roof Winglet", "Flat Engine Undertray"],
      powertrainMods: ["Short-Shift Linkage", "Limited Slip Differential", "Cold Air Intake Box"],
    },
  },

  sedan: {
    id: "sedan",
    name: "Sedan",
    group: "road",
    tagline: "Classic 3-box architecture balancing executive elegance, high-speed stability & NVH isolation.",
    description: "Distinct 3-box design separating engine bay, passenger cabin, and luggage boot. Exceptional torsional rigidity, low aerodynamic drag, and refined high-speed cruising stability.",
    subcategories: ["Compact Sedan", "Sports Sedan", "Executive Sedan", "Luxury Limousine"],
    silhouetteType: "sedan",
    dimensions: {
      wheelbase: { min: 2650, max: 3150, default: 2880 },
      frontTrack: { min: 1540, max: 1680, default: 1600 },
      rearTrack: { min: 1540, max: 1700, default: 1610 },
      rideHeight: { min: 115, max: 155, default: 135 },
      overallLength: { min: 4550, max: 5250, default: 4820 },
      overallWidth: { min: 1800, max: 1980, default: 1870 },
      overallHeight: { min: 1410, max: 1510, default: 1460 },
      frontOverhang: { min: 820, max: 980, default: 890 },
      rearOverhang: { min: 940, max: 1180, default: 1050 },
      cabinPositionPct: 48,
    },
    typicalWeightKg: { min: 1420, max: 2150, default: 1680 },
    typicalSeating: [5],
    luggageVolumeL: { min: 420, max: 620, default: 510 },
    engineBayVolumeL: 380,
    recommendedArchitecture: "Front-engine longitudinal / RWD",
    allowedEnginePositions: ["front"],
    defaultEnginePosition: "front",
    allowedDrivetrains: ["rwd", "awd", "fwd"],
    defaultDrivetrain: "rwd",
    allowedSuspensions: ["double_wishbone", "multilink", "macpherson"],
    defaultSuspensionFront: "double_wishbone",
    defaultSuspensionRear: "multilink",
    aeroClass: "Low Drag Streamlined",
    baseCd: 0.26,
    baseFrontalAreaM2: 2.22,
    downforcePotential: "moderate",
    engineeringDifficulty: "Moderate",
    developmentCost: 650000,
    compatibleChassis: [
      {
        id: "sedan_longitudinal_rwd",
        name: "Front-Engine Longitudinal RWD Platform",
        architecture: "monocoque",
        description: "Longitudinal drivetrain layout with central transmission tunnel and 50:50 axle weight distribution.",
        rigidity: "42 kNm/°",
        rigidityNmPerDeg: 42000,
        massKg: 345,
        material: "Advanced High-Strength Steel & Boron Pillars",
        engineBayVolumeL: 420,
        minWheelbaseMm: 2750,
        maxWheelbaseMm: 3150,
      },
      {
        id: "sedan_sport_reinforced",
        name: "Sports Sedan Monocoque with Alu Subframes",
        architecture: "monocoque",
        description: "Cast aluminum front strut towers, magnesium crossmembers, and high-tensile steel unibody.",
        rigidity: "52 kNm/°",
        rigidityNmPerDeg: 52000,
        massKg: 330,
        material: "Aluminum-Magnesium Multi-Material Hybrid",
        engineBayVolumeL: 400,
        minWheelbaseMm: 2720,
        maxWheelbaseMm: 3050,
      },
      {
        id: "sedan_transverse_fwd",
        name: "Transverse Compact Sedan Unibody",
        architecture: "monocoque",
        description: "Space-saving transverse engine mounting maximizing rear legroom and trunk packaging.",
        rigidity: "32 kNm/°",
        rigidityNmPerDeg: 32000,
        massKg: 310,
        material: "Galvanized Stamped Steel Unibody",
        engineBayVolumeL: 310,
        minWheelbaseMm: 2650,
        maxWheelbaseMm: 2850,
      },
    ],
    compatibleBodies: [
      {
        id: "sedan_executive",
        name: "Executive 3-Box Saloon",
        style: "Refined 4-door sedan with long hood and prominent C-pillar",
        description: "Prestige design with acoustic double-laminated glass, flush door handles, and classic three-box silhouette.",
        dragDeltaCd: 0.0,
        downforceDeltaKg: 0,
        massDeltaKg: 0,
        doorsCount: 4,
        cargoCapacityL: 520,
      },
      {
        id: "sedan_fastback",
        name: "Sportback / Gran Coupe Fastback",
        style: "Sweeping coupe-like roofline with liftback rear window",
        description: "Aerodynamic fastback silhouette lowering drag coefficient while maintaining 4-door practicality.",
        dragDeltaCd: -0.018,
        downforceDeltaKg: 15,
        massDeltaKg: +12,
        doorsCount: 5,
        cargoCapacityL: 490,
      },
      {
        id: "sedan_sport_m",
        name: "Aggressive Sports Sedan Aero Package",
        style: "Flared rear haunches, functional front air curtains, rear lip spoiler",
        description: "Widened track profile (+30mm), carbon fiber front splitter, quad exhaust rear diffuser, and carbon trunk lip.",
        dragDeltaCd: +0.015,
        downforceDeltaKg: 55,
        massDeltaKg: -14,
        doorsCount: 4,
        cargoCapacityL: 500,
      },
    ],
    developmentTree: {
      bodyMods: ["Acoustic Glass Package", "Carbon Fiber Roof Panel", "Trunk Decklid Spoiler"],
      chassisMods: ["Strut Tower Cross-Brace", "Rear Subframe Solid Bushings", "Drivetrain Tunnel Stiffener"],
      suspensionMods: ["Adaptive Magnetorheological Dampers", "Active Anti-Roll Bars", "Rear Axle Steering System"],
      aeroMods: ["Active Grille Shutters", "Smooth Underbody Paneling", "Rear Bumper Diffuser Fins"],
      powertrainMods: ["Electronic Torque-Vectoring Differential", "Longitudinal 8-Speed Auto", "Dual-Mode Valved Exhaust"],
    },
  },

  coupe: {
    id: "coupe",
    name: "Coupe",
    group: "sports_exotic",
    tagline: "Sleek 2-door design with dramatic rooflines and driver-focused ergonomics.",
    description: "Athletic 2-door silhouette with swept-back A-pillars, pillarless doors, rigid side sills, and low center of mass.",
    subcategories: ["2-Door Coupe", "Grand Touring Coupe", "Performance Coupe"],
    silhouetteType: "coupe",
    dimensions: {
      wheelbase: { min: 2550, max: 2950, default: 2750 },
      frontTrack: { min: 1550, max: 1690, default: 1620 },
      rearTrack: { min: 1560, max: 1720, default: 1640 },
      rideHeight: { min: 105, max: 140, default: 120 },
      overallLength: { min: 4400, max: 4950, default: 4680 },
      overallWidth: { min: 1830, max: 2020, default: 1910 },
      overallHeight: { min: 1320, max: 1420, default: 1370 },
      frontOverhang: { min: 820, max: 960, default: 890 },
      rearOverhang: { min: 880, max: 1080, default: 980 },
      cabinPositionPct: 54,
    },
    typicalWeightKg: { min: 1350, max: 1850, default: 1560 },
    typicalSeating: [2, 4],
    luggageVolumeL: { min: 320, max: 480, default: 390 },
    engineBayVolumeL: 360,
    recommendedArchitecture: "Front-mid longitudinal / RWD",
    allowedEnginePositions: ["front", "mid"],
    defaultEnginePosition: "front",
    allowedDrivetrains: ["rwd", "awd"],
    defaultDrivetrain: "rwd",
    allowedSuspensions: ["double_wishbone", "multilink"],
    defaultSuspensionFront: "double_wishbone",
    defaultSuspensionRear: "multilink",
    aeroClass: "Balanced GT",
    baseCd: 0.28,
    baseFrontalAreaM2: 2.08,
    downforcePotential: "moderate",
    engineeringDifficulty: "Moderate",
    developmentCost: 600000,
    compatibleChassis: [
      {
        id: "coupe_alu_monocoque",
        name: "Bonded Aluminum Coupe Monocoque",
        architecture: "monocoque",
        description: "Riveted and bonded aluminum monocoque with hydroformed side sills and carbon transmission tunnel.",
        rigidity: "46 kNm/°",
        rigidityNmPerDeg: 46000,
        massKg: 290,
        material: "6082-T6 Extruded & Cast Aluminum",
        engineBayVolumeL: 380,
        minWheelbaseMm: 2600,
        maxWheelbaseMm: 2950,
      },
      {
        id: "coupe_carbon_hybrid",
        name: "Carbon Tub + Aluminum Front/Rear Subframes",
        architecture: "carbon_tub",
        description: "Central carbon fiber monocell for unmatched cockpit safety and high torsional stiffness.",
        rigidity: "65 kNm/°",
        rigidityNmPerDeg: 65000,
        massKg: 215,
        material: "T800 Carbon Fiber & Cast Aluminum Cradles",
        engineBayVolumeL: 360,
        minWheelbaseMm: 2550,
        maxWheelbaseMm: 2850,
      },
    ],
    compatibleBodies: [
      {
        id: "coupe_fastback_body",
        name: "Sculpted Fastback Coupe Shell",
        style: "Classic 2-door fastback with flush greenhouse",
        description: "Low-drag coupe styling with frameless glass and integrated rear ducktail.",
        dragDeltaCd: 0.0,
        downforceDeltaKg: 20,
        massDeltaKg: 0,
        doorsCount: 2,
        cargoCapacityL: 410,
      },
      {
        id: "coupe_gt_wide",
        name: "Grand Tourer Widebody Aero Shell",
        style: "Muscular rear hips and vented front fenders",
        description: "Widebody stance accommodating staggered 305mm rear tires and aggressive rear aero diffuser.",
        dragDeltaCd: +0.018,
        downforceDeltaKg: 65,
        massDeltaKg: +14,
        doorsCount: 2,
        cargoCapacityL: 380,
      },
    ],
    developmentTree: {
      bodyMods: ["Carbon Fiber Hood with Heat Extractors", "Ducktail Trunk Lid", "Lightweight Frameless Doors"],
      chassisMods: ["Carbon Strut Tower Brace", "Reinforced Rear Bulkhead", "Chassis Underbody Stiffening V-Brace"],
      suspensionMods: ["Coilover Adjustable Dampers", "Performance Camber Plates", "Heavy-Duty Stabilizer Bars"],
      aeroMods: ["Front Splitter Extension", "Functional Side Skirt Fins", "Rear Undertray Venturi Channels"],
      powertrainMods: ["Titanium Exhaust System", "Clutch-Type Limited Slip Diff", "Short-Throw Manual Shifter"],
    },
  },

  convertible: {
    id: "convertible",
    name: "Convertible",
    group: "sports_exotic",
    tagline: "Open-air motoring experience with reinforced underbody structural bracing.",
    description: "Open-top sports roadster or cabriolet with automated folding soft or hard top, integrated roll-over hoops, and reinforced door sills.",
    subcategories: ["Roadster", "Cabriolet", "Performance Convertible", "Targa Open-Top"],
    silhouetteType: "convertible",
    dimensions: {
      wheelbase: { min: 2450, max: 2850, default: 2620 },
      frontTrack: { min: 1530, max: 1670, default: 1590 },
      rearTrack: { min: 1530, max: 1690, default: 1610 },
      rideHeight: { min: 110, max: 145, default: 125 },
      overallLength: { min: 4250, max: 4800, default: 4520 },
      overallWidth: { min: 1810, max: 1980, default: 1880 },
      overallHeight: { min: 1280, max: 1390, default: 1340 },
      frontOverhang: { min: 810, max: 940, default: 870 },
      rearOverhang: { min: 840, max: 1040, default: 940 },
      cabinPositionPct: 56,
    },
    typicalWeightKg: { min: 1220, max: 1950, default: 1540 },
    typicalSeating: [2, 4],
    luggageVolumeL: { min: 180, max: 360, default: 270 },
    engineBayVolumeL: 320,
    recommendedArchitecture: "Front-mid longitudinal / RWD",
    allowedEnginePositions: ["front", "mid"],
    defaultEnginePosition: "front",
    allowedDrivetrains: ["rwd", "awd"],
    defaultDrivetrain: "rwd",
    allowedSuspensions: ["double_wishbone", "multilink"],
    defaultSuspensionFront: "double_wishbone",
    defaultSuspensionRear: "multilink",
    aeroClass: "Open Top Vortex",
    baseCd: 0.33,
    baseFrontalAreaM2: 2.05,
    downforcePotential: "minimal",
    engineeringDifficulty: "Advanced",
    developmentCost: 680000,
    compatibleChassis: [
      {
        id: "conv_reinforced_monocoque",
        name: "Reinforced Roadster Monocoque with Box Sills",
        architecture: "monocoque",
        description: "Heavy-duty cross-braced underbody floorpan with hydroformed multi-chamber rocker panels.",
        rigidity: "32 kNm/°",
        rigidityNmPerDeg: 32000,
        massKg: 360,
        material: "High-Strength Steel & Boron A-Pillar Tubes",
        engineBayVolumeL: 340,
        minWheelbaseMm: 2450,
        maxWheelbaseMm: 2850,
      },
      {
        id: "conv_carbon_tub",
        name: "Carbon Monocell Roadster Chassis",
        architecture: "carbon_tub",
        description: "Inherent carbon tub torsional rigidity eliminates scuttle shake without extra steel ballast.",
        rigidity: "58 kNm/°",
        rigidityNmPerDeg: 58000,
        massKg: 195,
        material: "Resin-Infused Carbon Monocoque + Roll Hoops",
        engineBayVolumeL: 320,
        minWheelbaseMm: 2450,
        maxWheelbaseMm: 2750,
      },
    ],
    compatibleBodies: [
      {
        id: "conv_roadster_softtop",
        name: "Acoustic Fabric Soft-Top Roadster",
        style: "3-layer insulated canvas soft top with electric folding mechanism",
        description: "Lightweight canvas roof deploying in 10 seconds with heated glass rear window.",
        dragDeltaCd: 0.0,
        downforceDeltaKg: 0,
        massDeltaKg: 0,
        doorsCount: 2,
        cargoCapacityL: 260,
      },
      {
        id: "conv_retractable_hardtop",
        name: "Retractable Aluminum Hardtop",
        style: "Electro-hydraulic two-piece folding metal roof",
        description: "Coupe-like weather and noise insulation when closed, seamless convertible flair when stowed.",
        dragDeltaCd: -0.015,
        downforceDeltaKg: 10,
        massDeltaKg: +48,
        doorsCount: 2,
        cargoCapacityL: 220,
      },
    ],
    developmentTree: {
      bodyMods: ["Deployable Wind Deflector", "Acoustic Roof Insulation", "Pop-Up Roll Over Pyrotechnic Hoops"],
      chassisMods: ["Front & Rear Underbody V-Braces", "Reinforced Windshield Frame", "Transmission Tunnel Shear Plate"],
      suspensionMods: ["Roadster Comfort/Sport Dampers", "Tuned Anti-Roll Stiffness", "Rigid Front Bushings"],
      aeroMods: ["Trunk Lip Vortex Control", "Side Mirror A-Pillar Aero Spoilers", "Underfloor Venturi Plate"],
      powertrainMods: ["Acoustic Exhaust Resonator", "High-Torque Transaxle", "Active Oil Baffles"],
    },
  },

  wagon: {
    id: "wagon",
    name: "Wagon / Estate",
    group: "road",
    tagline: "Elongated roofline providing cavernous cargo space and low-drag touring efficiency.",
    description: "Extended roof architecture preserving low sedan center of gravity while delivering massive luggage capacity and high-speed autobahn cruising stability.",
    subcategories: ["Practical Wagon", "Performance Wagon", "All-Terrain Estate", "Shooting Brake"],
    silhouetteType: "wagon",
    dimensions: {
      wheelbase: { min: 2700, max: 3100, default: 2890 },
      frontTrack: { min: 1560, max: 1690, default: 1610 },
      rearTrack: { min: 1560, max: 1710, default: 1620 },
      rideHeight: { min: 120, max: 175, default: 140 },
      overallLength: { min: 4650, max: 5150, default: 4890 },
      overallWidth: { min: 1820, max: 1990, default: 1890 },
      overallHeight: { min: 1430, max: 1540, default: 1480 },
      frontOverhang: { min: 840, max: 980, default: 900 },
      rearOverhang: { min: 1020, max: 1240, default: 1120 },
      cabinPositionPct: 46,
    },
    typicalWeightKg: { min: 1520, max: 2250, default: 1780 },
    typicalSeating: [5],
    luggageVolumeL: { min: 560, max: 880, default: 680 },
    engineBayVolumeL: 380,
    recommendedArchitecture: "Front-engine longitudinal / AWD",
    allowedEnginePositions: ["front"],
    defaultEnginePosition: "front",
    allowedDrivetrains: ["awd", "rwd"],
    defaultDrivetrain: "awd",
    allowedSuspensions: ["double_wishbone", "multilink"],
    defaultSuspensionFront: "double_wishbone",
    defaultSuspensionRear: "multilink",
    aeroClass: "Long Roof Tourer",
    baseCd: 0.28,
    baseFrontalAreaM2: 2.26,
    downforcePotential: "moderate",
    engineeringDifficulty: "Moderate",
    developmentCost: 620000,
    compatibleChassis: [
      {
        id: "wagon_reinforced_unibody",
        name: "Extended D-Pillar Reinforced Unibody",
        architecture: "monocoque",
        description: "Strengthened rear cargo subframe and D-pillar torsional ring preventing wagon body twist.",
        rigidity: "39 kNm/°",
        rigidityNmPerDeg: 39000,
        massKg: 370,
        material: "Hot-Stamped High-Strength Steel & Tailored Blanks",
        engineBayVolumeL: 400,
        minWheelbaseMm: 2700,
        maxWheelbaseMm: 3100,
      },
    ],
    compatibleBodies: [
      {
        id: "wagon_touring_shell",
        name: "Executive Long-Roof Touring Body",
        style: "5-door estate with full-length roof rails and power tailgate",
        description: "Maximized rear cabin volume with flush roof rails and hands-free electric rear tailgate.",
        dragDeltaCd: 0.0,
        downforceDeltaKg: 10,
        massDeltaKg: 0,
        doorsCount: 5,
        cargoCapacityL: 690,
      },
      {
        id: "wagon_performance_rs",
        name: "High-Performance Widebody Estate",
        style: "Flared box fenders, quad exhausts, aggressive rear roof spoiler",
        description: "Muscular widebody fenders, functional rear roof diffuser, and large front cooling openings.",
        dragDeltaCd: +0.016,
        downforceDeltaKg: 60,
        massDeltaKg: +18,
        doorsCount: 5,
        cargoCapacityL: 670,
      },
    ],
    developmentTree: {
      bodyMods: ["Integrated Low-Profile Roof Rails", "Panoramic Glass Roof", "Cargo Securing Rail System"],
      chassisMods: ["Rear Cargo Subframe Stiffeners", "Self-Leveling Air Springs", "Reinforced Trailer Hitch Crossmember"],
      suspensionMods: ["Adaptive Air Suspension", "Heavy-Duty Rear Springs", "Active Anti-Roll Bars"],
      aeroMods: ["Roof Trailing Edge Spoiler", "Rear Window Air Blades", "Underbody Full Cladding"],
      powertrainMods: ["Permanent AWD Center Differential", "Dual-Clutch Transmission Cooler", "High-Flow Turbo Downpipes"],
    },
  },

  crossover: {
    id: "crossover",
    name: "Crossover",
    group: "suv_utility",
    tagline: "Car-based unibody agility paired with elevated seating and all-weather versatility.",
    description: "Compact unibody platform offering raised ground clearance, hatchback-like maneuverability, rugged wheel arch claddings, and efficient hybrid powertrains.",
    subcategories: ["Compact Crossover", "Sport Crossover", "Luxury Crossover"],
    silhouetteType: "crossover",
    dimensions: {
      wheelbase: { min: 2600, max: 2850, default: 2710 },
      frontTrack: { min: 1540, max: 1660, default: 1590 },
      rearTrack: { min: 1540, max: 1670, default: 1600 },
      rideHeight: { min: 160, max: 215, default: 185 },
      overallLength: { min: 4300, max: 4680, default: 4490 },
      overallWidth: { min: 1800, max: 1940, default: 1860 },
      overallHeight: { min: 1550, max: 1680, default: 1610 },
      frontOverhang: { min: 810, max: 940, default: 870 },
      rearOverhang: { min: 820, max: 980, default: 910 },
      cabinPositionPct: 48,
    },
    typicalWeightKg: { min: 1380, max: 1890, default: 1580 },
    typicalSeating: [5],
    luggageVolumeL: { min: 420, max: 600, default: 510 },
    engineBayVolumeL: 280,
    recommendedArchitecture: "Front-engine transverse / AWD",
    allowedEnginePositions: ["front"],
    defaultEnginePosition: "front",
    allowedDrivetrains: ["awd", "fwd"],
    defaultDrivetrain: "awd",
    allowedSuspensions: ["macpherson", "multilink"],
    defaultSuspensionFront: "macpherson",
    defaultSuspensionRear: "multilink",
    aeroClass: "Elevated Aero",
    baseCd: 0.32,
    baseFrontalAreaM2: 2.45,
    downforcePotential: "minimal",
    engineeringDifficulty: "Moderate",
    developmentCost: 520000,
    compatibleChassis: [
      {
        id: "crossover_unibody_raised",
        name: "Raised Ground-Clearance Unibody",
        architecture: "monocoque",
        description: "Reinforced lower crossmembers with high-angle suspension attachment points for rough road durability.",
        rigidity: "34 kNm/°",
        rigidityNmPerDeg: 34000,
        massKg: 330,
        material: "Galvanized High-Strength Steel Unibody",
        engineBayVolumeL: 290,
        minWheelbaseMm: 2600,
        maxWheelbaseMm: 2850,
      },
    ],
    compatibleBodies: [
      {
        id: "crossover_urban_rugged",
        name: "Urban Rugged Crossover Shell",
        style: "Protective wheel arch cladding, skidplate styling, elevated roofline",
        description: "Durable composite lower armor guards, integrated roof rails, and high approach angle bumpers.",
        dragDeltaCd: 0.0,
        downforceDeltaKg: 0,
        massDeltaKg: 0,
        doorsCount: 5,
        cargoCapacityL: 520,
      },
    ],
    developmentTree: {
      bodyMods: ["Protective Composite Claddings", "Aluminum Roof Crossbars", "Engine Underbody Splash Shield"],
      chassisMods: ["Rough-Road Suspension Braces", "Electronic AWD Coupling Mount", "Reinforced Front Subframe"],
      suspensionMods: ["Long-Travel Twin-Tube Dampers", "Raised Ground Clearance Coil Springs", "Stiffened Stabilizer Bushings"],
      aeroMods: ["Aerodynamic Roof Winglet", "Front Wheel Air Deflectors", "Flush Underbody Shields"],
      powertrainMods: ["Multi-Terrain AWD Drive Modes", "Hill Descent Control", "High-Efficiency Mild-Hybrid System"],
    },
  },

  suv: {
    id: "suv",
    name: "SUV",
    group: "suv_utility",
    tagline: "Commanding road presence, high towing capacity, massive passenger volume & multi-terrain capability.",
    description: "Full-size or midsize sports utility platform offering tall ride height, upright glasshouse, expansive cabin packaging, and heavy-duty drivetrain durability.",
    subcategories: ["Compact SUV", "Performance SUV", "Luxury SUV", "Full-Size SUV"],
    silhouetteType: "suv",
    dimensions: {
      wheelbase: { min: 2800, max: 3250, default: 2990 },
      frontTrack: { min: 1640, max: 1780, default: 1690 },
      rearTrack: { min: 1640, max: 1800, default: 1700 },
      rideHeight: { min: 180, max: 270, default: 215 },
      overallLength: { min: 4750, max: 5380, default: 5040 },
      overallWidth: { min: 1920, max: 2120, default: 1990 },
      overallHeight: { min: 1680, max: 1880, default: 1770 },
      frontOverhang: { min: 840, max: 1020, default: 910 },
      rearOverhang: { min: 980, max: 1220, default: 1140 },
      cabinPositionPct: 45,
    },
    typicalWeightKg: { min: 1980, max: 2850, default: 2350 },
    typicalSeating: [5, 7],
    luggageVolumeL: { min: 650, max: 1250, default: 850 },
    engineBayVolumeL: 480,
    recommendedArchitecture: "Front-engine longitudinal / AWD",
    allowedEnginePositions: ["front"],
    defaultEnginePosition: "front",
    allowedDrivetrains: ["awd", "rwd"],
    defaultDrivetrain: "awd",
    allowedSuspensions: ["double_wishbone", "multilink"],
    defaultSuspensionFront: "double_wishbone",
    defaultSuspensionRear: "multilink",
    aeroClass: "High Clearance Utility",
    baseCd: 0.35,
    baseFrontalAreaM2: 2.95,
    downforcePotential: "minimal",
    engineeringDifficulty: "Moderate",
    developmentCost: 850000,
    compatibleChassis: [
      {
        id: "suv_reinforced_unibody",
        name: "Performance Reinforced SUV Unibody",
        architecture: "monocoque",
        description: "Monocoque architecture combining aluminum suspension shock towers with an ultra-rigid steel floor structure.",
        rigidity: "44 kNm/°",
        rigidityNmPerDeg: 44000,
        massKg: 420,
        material: "Cast Aluminum & Boron-Alloy Safety Cage",
        engineBayVolumeL: 520,
        minWheelbaseMm: 2850,
        maxWheelbaseMm: 3200,
      },
      {
        id: "suv_ladder_frame",
        name: "Hydroformed Steel Ladder Frame",
        architecture: "ladder",
        description: "Full box-section ladder chassis frame providing maximum articulation, impact durability, and 3.5-ton towing capability.",
        rigidity: "29 kNm/°",
        rigidityNmPerDeg: 29000,
        massKg: 490,
        material: "High-Strength Low-Alloy Steel (HSLA)",
        engineBayVolumeL: 540,
        minWheelbaseMm: 2800,
        maxWheelbaseMm: 3250,
      },
    ],
    compatibleBodies: [
      {
        id: "suv_family_7seat",
        name: "Full-Size 7-Passenger SUV Body",
        style: "Upright cabin with 3rd row seating and commanding hood",
        description: "Expansive passenger space, three-zone panoramic roof, and large upright tailgate.",
        dragDeltaCd: 0.0,
        downforceDeltaKg: 0,
        massDeltaKg: 0,
        doorsCount: 5,
        cargoCapacityL: 920,
      },
      {
        id: "suv_sport_coupe",
        name: "Coupe SUV Dynamic Shell",
        style: "Sweeping roofline, flared fenders, aggressive front fascia",
        description: "Sloping fastback roofline lowering drag coefficient while enhancing athletic road stance.",
        dragDeltaCd: -0.024,
        downforceDeltaKg: 25,
        massDeltaKg: -18,
        doorsCount: 5,
        cargoCapacityL: 740,
      },
    ],
    developmentTree: {
      bodyMods: ["Illuminated Electric Running Boards", "Heavy-Duty Roof Rack", "Underbody Armor Skid Plates"],
      chassisMods: ["3.5-Ton Towing Hitch Frame", "Subframe Rubber Isolation Mounts", "Lateral Torsional Crossmembers"],
      suspensionMods: ["3-Chamber Adaptive Air Suspension", "48V Active Roll Stabilization", "Electronic Terrain Management"],
      aeroMods: ["Active Aerodynamic Lowering Mode", "Front Bumper Air Curtains", "Rear Roof Air Deflector"],
      powertrainMods: ["Twin-Turbo V8 Engine Pack", "Dual-Range Transfer Case", "Mechanical Locking Rear Differential"],
    },
  },

  offroad_4x4: {
    id: "offroad_4x4",
    name: "Off-Road / 4x4",
    group: "suv_utility",
    tagline: "Uncompromised all-terrain conqueror with low-range transfer case & rock-crawling articulation.",
    description: "Rugged expedition vehicle built on an indestructible ladder frame with solid axles or long-travel suspension, locking differentials, high approach/departure angles, and waterproofed vitals.",
    subcategories: ["Utility 4x4", "Expedition SUV", "Rock-Crawling Platform", "Desert Baja Pre-Runner"],
    silhouetteType: "offroad",
    dimensions: {
      wheelbase: { min: 2550, max: 3180, default: 2820 },
      frontTrack: { min: 1600, max: 1780, default: 1670 },
      rearTrack: { min: 1600, max: 1780, default: 1670 },
      rideHeight: { min: 220, max: 340, default: 260 },
      overallLength: { min: 4350, max: 5050, default: 4680 },
      overallWidth: { min: 1860, max: 2060, default: 1940 },
      overallHeight: { min: 1820, max: 2020, default: 1890 },
      frontOverhang: { min: 680, max: 840, default: 740 },
      rearOverhang: { min: 720, max: 940, default: 820 },
      cabinPositionPct: 46,
    },
    typicalWeightKg: { min: 1950, max: 2900, default: 2280 },
    typicalSeating: [2, 5],
    luggageVolumeL: { min: 520, max: 1100, default: 780 },
    engineBayVolumeL: 460,
    recommendedArchitecture: "Front-engine longitudinal / 4WD",
    allowedEnginePositions: ["front"],
    defaultEnginePosition: "front",
    allowedDrivetrains: ["awd", "rwd"],
    defaultDrivetrain: "awd",
    allowedSuspensions: ["leaf_spring", "double_wishbone", "multilink"],
    defaultSuspensionFront: "double_wishbone",
    defaultSuspensionRear: "multilink",
    aeroClass: "All-Terrain High Clearance",
    baseCd: 0.44,
    baseFrontalAreaM2: 3.10,
    downforcePotential: "minimal",
    engineeringDifficulty: "Advanced",
    developmentCost: 720000,
    compatibleChassis: [
      {
        id: "offroad_boxed_ladder",
        name: "Heavy-Duty Dual-Rail Boxed Frame",
        architecture: "ladder",
        description: "Fully boxed ladder chassis frame with 8 crossmembers engineered for maximum wheel articulation and torsional punishment.",
        rigidity: "26 kNm/°",
        rigidityNmPerDeg: 26000,
        massKg: 460,
        material: "High-Strength Low-Alloy (HSLA) Steel",
        engineBayVolumeL: 500,
        minWheelbaseMm: 2550,
        maxWheelbaseMm: 3180,
      },
      {
        id: "offroad_tubular_cradle",
        name: "Desert Baja Chromoly Tube Chassis",
        architecture: "spaceframe",
        description: "TIG-welded 4130 chromoly tubular spaceframe designed for high-speed desert whoops and dune jumps.",
        rigidity: "36 kNm/°",
        rigidityNmPerDeg: 36000,
        massKg: 340,
        material: "4130 Aircraft Chromoly Tubing",
        engineBayVolumeL: 480,
        minWheelbaseMm: 2650,
        maxWheelbaseMm: 3150,
      },
    ],
    compatibleBodies: [
      {
        id: "offroad_trail_suv",
        name: "Trail Expedition 4x4 Shell",
        style: "Removable roof panels, tubular steel bumpers, external spare carrier",
        description: "Exposed external spare tire, high-clearance wheel cutouts, heavy-duty rock sliders, and snorkel intake.",
        dragDeltaCd: +0.025,
        downforceDeltaKg: 0,
        massDeltaKg: 0,
        doorsCount: 5,
        cargoCapacityL: 820,
      },
    ],
    developmentTree: {
      bodyMods: ["Air Intake Raised Snorkel", "Steel Winch Front Bumper", "Rock Slider Side Steps", "External Spare Wheel Carrier"],
      chassisMods: ["8mm Aluminum Full Underbody Skid Plates", "Heavy-Duty Recovery Points", "Rock-Crawl Frame Stiffeners"],
      suspensionMods: ["Remote Reservoir Bypass Shocks", "Hydraulic Bump Stops", "Disconnectable Sway Bars"],
      aeroMods: ["Roof Light Bar Wind Deflector", "Hood Air Extraction Vents"],
      powertrainMods: ["Triple Differential Lockers (Front/Center/Rear)", "Crawler Low-Range Gearbox (4:1)", "Waterproof Electrical Enclosure"],
    },
  },

  grand_tourer: {
    id: "grand_tourer",
    name: "GT / Grand Tourer",
    group: "sports_exotic",
    tagline: "Effortless high-speed continental crossing combining supercar performance with bespoke luxury.",
    description: "Front-mid engine grand tourer engineered for 200+ mph autobahn cruising, hand-stitched leather luxury, sophisticated electronic damping, and effortless long-distance stamina.",
    subcategories: ["GT Coupe", "Luxury GT", "High-Performance GT"],
    silhouetteType: "gt",
    dimensions: {
      wheelbase: { min: 2720, max: 2980, default: 2850 },
      frontTrack: { min: 1610, max: 1720, default: 1660 },
      rearTrack: { min: 1620, max: 1740, default: 1680 },
      rideHeight: { min: 105, max: 140, default: 120 },
      overallLength: { min: 4680, max: 4980, default: 4840 },
      overallWidth: { min: 1920, max: 2040, default: 1980 },
      overallHeight: { min: 1270, max: 1370, default: 1320 },
      frontOverhang: { min: 890, max: 1020, default: 950 },
      rearOverhang: { min: 960, max: 1120, default: 1040 },
      cabinPositionPct: 56,
    },
    typicalWeightKg: { min: 1680, max: 2240, default: 1890 },
    typicalSeating: [2, 4],
    luggageVolumeL: { min: 290, max: 440, default: 360 },
    engineBayVolumeL: 520,
    recommendedArchitecture: "Front-mid V12 / RWD Transaxle",
    allowedEnginePositions: ["front"],
    defaultEnginePosition: "front",
    allowedDrivetrains: ["rwd", "awd"],
    defaultDrivetrain: "rwd",
    allowedSuspensions: ["double_wishbone", "multilink"],
    defaultSuspensionFront: "double_wishbone",
    defaultSuspensionRear: "multilink",
    aeroClass: "High-Speed GT",
    baseCd: 0.29,
    baseFrontalAreaM2: 2.12,
    downforcePotential: "moderate",
    engineeringDifficulty: "Advanced",
    developmentCost: 950000,
    compatibleChassis: [
      {
        id: "gt_bonded_aluminum",
        name: "Bonded Aluminum Monocoque & Transaxle Tunnel",
        architecture: "monocoque",
        description: "Carbon fiber torque tube connecting front-mid engine to rear transaxle, bonded aerospace aluminum chassis.",
        rigidity: "48 kNm/°",
        rigidityNmPerDeg: 48000,
        massKg: 310,
        material: "Aerospace 6000/7000 Series Aluminum",
        engineBayVolumeL: 540,
        minWheelbaseMm: 2720,
        maxWheelbaseMm: 2980,
      },
    ],
    compatibleBodies: [
      {
        id: "gt_coupe_classic",
        name: "Bespoke Continental Grand Tourer Shell",
        style: "Dramatic long hood, muscular rear haunches, chrome side strakes",
        description: "Classic British/Italian grand tourer proportions with sweeping roofline and active deployable rear spoiler.",
        dragDeltaCd: 0.0,
        downforceDeltaKg: 35,
        massDeltaKg: 0,
        doorsCount: 2,
        cargoCapacityL: 370,
      },
    ],
    developmentTree: {
      bodyMods: ["Active Deployable Rear Spoiler", "Acoustic Noise-Cancelling Windshield", "Bespoke Luggage Fitted Trays"],
      chassisMods: ["Carbon Fiber Torque Tube", "Rear Transaxle Subframe Mount", "Front Strut Tower Stiffeners"],
      suspensionMods: ["48V Active Anti-Roll System", "Predictive Camera-Based Adaptive Dampers", "Rear-Wheel Steering"],
      aeroMods: ["Underfloor Aerodynamic Venturis", "Front Fender Air Breather Vents", "Active Rear Diffuser Flaps"],
      powertrainMods: ["6.0L Twin-Turbo V12 Engine", "Carbon-Ceramic 10-Piston Brakes", "Electronic Valved Stainless Exhaust"],
    },
  },

  sports_car: {
    id: "sports_car",
    name: "Sports Car",
    group: "sports_exotic",
    tagline: "Pure driver engagement, razor-sharp steering feedback & lightweight kinematic precision.",
    description: "Purpose-built performance machine prioritizing power-to-weight ratio, neutral chassis balance, immediate throttle response, and communicative feedback.",
    subcategories: ["Lightweight Sports Car", "Mid-Engine Sports Car", "Front-Engine Sports Car"],
    silhouetteType: "sportscar",
    dimensions: {
      wheelbase: { min: 2420, max: 2720, default: 2540 },
      frontTrack: { min: 1540, max: 1680, default: 1610 },
      rearTrack: { min: 1550, max: 1710, default: 1630 },
      rideHeight: { min: 95, max: 135, default: 110 },
      overallLength: { min: 4220, max: 4620, default: 4420 },
      overallWidth: { min: 1820, max: 1980, default: 1890 },
      overallHeight: { min: 1220, max: 1320, default: 1270 },
      frontOverhang: { min: 780, max: 920, default: 840 },
      rearOverhang: { min: 760, max: 940, default: 850 },
      cabinPositionPct: 52,
    },
    typicalWeightKg: { min: 1080, max: 1550, default: 1320 },
    typicalSeating: [2],
    luggageVolumeL: { min: 160, max: 320, default: 240 },
    engineBayVolumeL: 310,
    recommendedArchitecture: "Mid-engine longitudinal / RWD",
    allowedEnginePositions: ["mid", "front", "rear"],
    defaultEnginePosition: "mid",
    allowedDrivetrains: ["rwd", "awd"],
    defaultDrivetrain: "rwd",
    allowedSuspensions: ["double_wishbone", "multilink"],
    defaultSuspensionFront: "double_wishbone",
    defaultSuspensionRear: "double_wishbone",
    aeroClass: "Balanced Downforce",
    baseCd: 0.31,
    baseFrontalAreaM2: 1.98,
    downforcePotential: "high",
    engineeringDifficulty: "Advanced",
    developmentCost: 750000,
    compatibleChassis: [
      {
        id: "sports_alu_spaceframe",
        name: "Aluminum Extrusion Spaceframe",
        architecture: "spaceframe",
        description: "Lightweight modular aluminum chassis with integrated roll protection structure and low polar inertia.",
        rigidity: "40 kNm/°",
        rigidityNmPerDeg: 40000,
        massKg: 190,
        material: "6061-T6 Extruded Aluminum Alloy",
        engineBayVolumeL: 320,
        minWheelbaseMm: 2420,
        maxWheelbaseMm: 2720,
      },
      {
        id: "sports_carbon_tub",
        name: "Autoclave Prepreg Carbon Monocoque Tub",
        architecture: "carbon_tub",
        description: "Carbon composite survival cell tub with aluminum subframes front and rear.",
        rigidity: "60 kNm/°",
        rigidityNmPerDeg: 60000,
        massKg: 145,
        material: "T700 Prepreg Carbon Fiber",
        engineBayVolumeL: 340,
        minWheelbaseMm: 2450,
        maxWheelbaseMm: 2680,
      },
    ],
    compatibleBodies: [
      {
        id: "sports_coupe_body",
        name: "Aerodynamic Sports Coupe Body",
        style: "Sculpted mid-engine coupe with side air scoops",
        description: "Curved teardrop canopy, functional side radiator ducts, and rear deck spoiler.",
        dragDeltaCd: 0.0,
        downforceDeltaKg: 40,
        massDeltaKg: 0,
        doorsCount: 2,
        cargoCapacityL: 220,
      },
      {
        id: "sports_targa_body",
        name: "Removable Targa Roof Shell",
        style: "Solid B-pillar halo hoop with stowable roof panel",
        description: "Combines open-air freedom with full coupe structural integrity and rear glass styling.",
        dragDeltaCd: +0.012,
        downforceDeltaKg: 25,
        massDeltaKg: +12,
        doorsCount: 2,
        cargoCapacityL: 200,
      },
    ],
    developmentTree: {
      bodyMods: ["Carbon Fiber Removable Targa Panel", "NACA Duct Engine Lid", "Fender Air Extraction Vents"],
      chassisMods: ["Titanium Subframe Bolts", "Adjustable Sway Bar Mounts", "Chassis Torsional X-Brace"],
      suspensionMods: ["Double Wishbone Rose-Jointed Arms", "2-Way Inverted Coilovers", "Quick-Ratio Steering Rack"],
      aeroMods: ["Front Splitter with Endplates", "Rear Deck Ducktail Spoiler", "Carbon Rear Underbody Diffuser"],
      powertrainMods: ["Lightweight Billet Flywheel", "Close-Ratio 6-Speed Manual", "Dry Sump Lubrication System"],
    },
  },

  supercar: {
    id: "supercar",
    name: "Supercar",
    group: "sports_exotic",
    tagline: "Exotic mid-engine thoroughbred blending 600+ HP, carbon-fiber construction & 205+ mph capability.",
    description: "High-performance mid-engine architecture built around a carbon-fiber monocoque tub, active aerodynamic flaps, multi-link pushrod suspension, and high-revving naturally aspirated or twin-turbo V8/V10 powertrains.",
    subcategories: ["Mid-Engine Supercar", "AWD Supercar", "Track-Focused Supercar"],
    silhouetteType: "supercar",
    dimensions: {
      wheelbase: { min: 2650, max: 2780, default: 2710 },
      frontTrack: { min: 1640, max: 1720, default: 1680 },
      rearTrack: { min: 1660, max: 1760, default: 1710 },
      rideHeight: { min: 85, max: 120, default: 100 },
      overallLength: { min: 4520, max: 4780, default: 4620 },
      overallWidth: { min: 1980, max: 2100, default: 2040 },
      overallHeight: { min: 1140, max: 1230, default: 1180 },
      frontOverhang: { min: 880, max: 980, default: 920 },
      rearOverhang: { min: 860, max: 1040, default: 940 },
      cabinPositionPct: 44,
    },
    typicalWeightKg: { min: 1320, max: 1680, default: 1460 },
    typicalSeating: [2],
    luggageVolumeL: { min: 120, max: 220, default: 160 },
    engineBayVolumeL: 420,
    recommendedArchitecture: "Mid-engine longitudinal / RWD",
    allowedEnginePositions: ["mid"],
    defaultEnginePosition: "mid",
    allowedDrivetrains: ["rwd", "awd"],
    defaultDrivetrain: "rwd",
    allowedSuspensions: ["double_wishbone", "pushrod"],
    defaultSuspensionFront: "double_wishbone",
    defaultSuspensionRear: "double_wishbone",
    aeroClass: "High Downforce Ground Effect",
    baseCd: 0.32,
    baseFrontalAreaM2: 1.95,
    downforcePotential: "high",
    engineeringDifficulty: "Extreme",
    developmentCost: 1500000,
    compatibleChassis: [
      {
        id: "supercar_carbon_monocoque",
        name: "Full Carbon Monocoque Cell",
        architecture: "carbon_tub",
        description: "One-piece autoclave prepreg carbon tub with bonded titanium pickup points and aluminum front/rear subframes.",
        rigidity: "72 kNm/°",
        rigidityNmPerDeg: 72000,
        massKg: 105,
        material: "T1000 High-Modulus Carbon Fiber Prepreg",
        engineBayVolumeL: 440,
        minWheelbaseMm: 2650,
        maxWheelbaseMm: 2780,
      },
      {
        id: "supercar_hybrid_spaceframe",
        name: "Composite Monocoque + Spaceframe Hybrid",
        architecture: "spaceframe",
        description: "Carbon tub passenger cell mated to extruded 7000-series aluminum engine cradle.",
        rigidity: "58 kNm/°",
        rigidityNmPerDeg: 58000,
        massKg: 135,
        material: "Carbon-Aluminum Hybrid Composite",
        engineBayVolumeL: 420,
        minWheelbaseMm: 2650,
        maxWheelbaseMm: 2780,
      },
    ],
    compatibleBodies: [
      {
        id: "supercar_sculpted_body",
        name: "Sculpted Mid-Engine Aero Shell",
        style: "Low wedge profile, dihedral butterfly doors, aggressive side vents",
        description: "Deep body side channels directing airflow into rear radiators, glass engine cover, and integrated active rear wing.",
        dragDeltaCd: 0.0,
        downforceDeltaKg: 120,
        massDeltaKg: 0,
        doorsCount: 2,
        cargoCapacityL: 150,
      },
      {
        id: "supercar_longtail",
        name: "Longtail Extended Aerodynamic Body",
        style: "Extended rear deck (+120mm), roof scoop, massive carbon diffuser",
        description: "Le Mans inspired longtail rear overhang optimizing high-speed boundary layer attachment and reducing turbulence.",
        dragDeltaCd: -0.015,
        downforceDeltaKg: 210,
        massDeltaKg: -18,
        doorsCount: 2,
        cargoCapacityL: 140,
      },
    ],
    developmentTree: {
      bodyMods: ["Dihedral Butterfly Doors", "Roof-Mounted Engine Air Scoop", "Lexan Polycarbonate Engine Cover"],
      chassisMods: ["Titanium Subframe Cradle", "Carbon Fiber Crash Structures", "Ceramic Thermal Bay Barriers"],
      suspensionMods: ["Inboard Pushrod Coilover Suspension", "Hydraulic Front Axle Lift", "Bespoke Dampers"],
      aeroMods: ["Active Dynamic Rear Airbrake", "Underbody Venturi Tunnels", "Front Splitter Diffuser Flaps"],
      powertrainMods: ["Inconel Exhaust Manifolds", "Dual-Clutch 8-Speed Transaxle", "Carbon-Ceramic 420mm Brakes"],
    },
  },

  hypercar: {
    id: "hypercar",
    name: "Hypercar",
    group: "sports_exotic",
    tagline: "Peak automotive engineering, 1,000+ HP hybrid drives, extreme downforce & 250+ mph top speed.",
    description: "The pinnacle of road-legal engineering. Pushing the absolute limits of power, active aerodynamics, lightweight metallurgy, multi-motor hybrid deployment, and ground-effect downforce.",
    subcategories: ["Extreme ICE Hypercar", "Hybrid Hypercar", "High-Downforce Track Hypercar", "Top-Speed Record Architecture"],
    silhouetteType: "hypercar",
    dimensions: {
      wheelbase: { min: 2680, max: 2840, default: 2740 },
      frontTrack: { min: 1680, max: 1760, default: 1720 },
      rearTrack: { min: 1680, max: 1780, default: 1730 },
      rideHeight: { min: 65, max: 110, default: 85 },
      overallLength: { min: 4650, max: 4980, default: 4790 },
      overallWidth: { min: 2020, max: 2180, default: 2080 },
      overallHeight: { min: 1080, max: 1180, default: 1120 },
      frontOverhang: { min: 920, max: 1060, default: 990 },
      rearOverhang: { min: 980, max: 1180, default: 1060 },
      cabinPositionPct: 42,
    },
    typicalWeightKg: { min: 1180, max: 1580, default: 1380 },
    typicalSeating: [2],
    luggageVolumeL: { min: 60, max: 150, default: 90 },
    engineBayVolumeL: 450,
    recommendedArchitecture: "Mid-engine V12 Hybrid / AWD Torque Vectoring",
    allowedEnginePositions: ["mid"],
    defaultEnginePosition: "mid",
    allowedDrivetrains: ["awd", "rwd"],
    defaultDrivetrain: "awd",
    allowedSuspensions: ["pushrod"],
    defaultSuspensionFront: "pushrod",
    defaultSuspensionRear: "pushrod",
    aeroClass: "Extreme Downforce Ground Effect",
    baseCd: 0.35,
    baseFrontalAreaM2: 1.88,
    downforcePotential: "extreme",
    engineeringDifficulty: "Extreme",
    developmentCost: 3200000,
    compatibleChassis: [
      {
        id: "hypercar_full_carbon_tub",
        name: "Full Carbon Monocoque Tub & Structural Engine",
        architecture: "carbon_tub",
        description: "F1-derived structural powertrain chassis where the engine & gearbox act as stressed load-bearing members.",
        rigidity: "85 kNm/°",
        rigidityNmPerDeg: 85000,
        massKg: 88,
        material: "T1100 Autoclave Prepreg & Zylon Anti-Intrusion",
        engineBayVolumeL: 460,
        minWheelbaseMm: 2680,
        maxWheelbaseMm: 2840,
      },
    ],
    compatibleBodies: [
      {
        id: "hypercar_high_downforce",
        name: "High-Downforce Ground-Effect Body",
        style: "Aggressive venturi underbody, dorsal shark fin, active DRS rear wing",
        description: "Generating 1,200 kg of downforce at 150 mph with full-length underbody venturi tunnels and active DRS.",
        dragDeltaCd: +0.035,
        downforceDeltaKg: 450,
        massDeltaKg: 0,
        doorsCount: 2,
        cargoCapacityL: 80,
      },
      {
        id: "hypercar_low_drag_record",
        name: "Low-Drag Top-Speed Record Shell",
        style: "Ultra-low drag streamlined tear drop profile, enclosed rear wheels",
        description: "Optimized for 280+ mph top speed runs with low frontal area and boundary layer vortex energizers.",
        dragDeltaCd: -0.065,
        downforceDeltaKg: 80,
        massDeltaKg: -22,
        doorsCount: 2,
        cargoCapacityL: 70,
      },
    ],
    developmentTree: {
      bodyMods: ["Active Hydraulic DRS Rear Wing", "Dorsal Stability Shark Fin", "Front Diffuser Venturi Flaps"],
      chassisMods: ["Titanium 3D-Printed Suspension Clevises", "Structural Engine Mounting Cradle", "Solid-State Battery Floor Tray"],
      suspensionMods: ["Active Inboard Pushrod Heave Dampers", "Ride Height Active Aero Lowering", "Third Damper Pitch Control"],
      aeroMods: ["Venturi Ground-Effect Underbody Tunnels", "Carbon Ceramic Brake Cooling Scoops", "Active Air Curtains"],
      powertrainMods: ["800V Tri-Motor Hybrid System", "F1 Kinetic Energy Recovery (MGU-K)", "Formula Sequential Gearbox"],
    },
  },

  gt3_race: {
    id: "gt3_race",
    name: "GT3 / Race Car",
    group: "motorsport",
    tagline: "FIA-homologated competition platform with extreme aerodynamics, roll cage & race telemetry.",
    description: "FIA GT3 and endurance race specification car featuring welded roll cage, competition dampers, centerlock forged wheels, pneumatic air jacks, massive swan-neck rear wing, and balance-of-performance telemetry.",
    subcategories: ["GT3 Homologated", "GT4 Endurance", "Cup Competition", "Super GT Spec"],
    silhouetteType: "gt3",
    dimensions: {
      wheelbase: { min: 2640, max: 2780, default: 2700 },
      frontTrack: { min: 1600, max: 1700, default: 1650 },
      rearTrack: { min: 1600, max: 1720, default: 1660 },
      rideHeight: { min: 55, max: 95, default: 75 },
      overallLength: { min: 4580, max: 4850, default: 4720 },
      overallWidth: { min: 2000, max: 2060, default: 2045 },
      overallHeight: { min: 1210, max: 1280, default: 1240 },
      frontOverhang: { min: 940, max: 1080, default: 1010 },
      rearOverhang: { min: 940, max: 1100, default: 1010 },
      cabinPositionPct: 52,
    },
    typicalWeightKg: { min: 1220, max: 1350, default: 1280 },
    typicalSeating: [1],
    luggageVolumeL: { min: 0, max: 50, default: 0 },
    engineBayVolumeL: 400,
    recommendedArchitecture: "Front-mid or Mid-engine / RWD Sequential",
    allowedEnginePositions: ["front", "mid"],
    defaultEnginePosition: "mid",
    allowedDrivetrains: ["rwd"],
    defaultDrivetrain: "rwd",
    allowedSuspensions: ["double_wishbone", "pushrod"],
    defaultSuspensionFront: "double_wishbone",
    defaultSuspensionRear: "double_wishbone",
    aeroClass: "Extreme Wing Downforce",
    baseCd: 0.38,
    baseFrontalAreaM2: 2.10,
    downforcePotential: "extreme",
    engineeringDifficulty: "FIA Prototype",
    developmentCost: 1800000,
    compatibleChassis: [
      {
        id: "gt3_carbon_race_tub",
        name: "FIA Homologated Carbon Race Monocoque",
        architecture: "carbon_tub",
        description: "Carbon survival cell with integrated 25CrMo4 FIA certified multi-point welded roll cage.",
        rigidity: "76 kNm/°",
        rigidityNmPerDeg: 76000,
        massKg: 120,
        material: "Prepreg Carbon & Chromoly Safety Structure",
        engineBayVolumeL: 420,
        minWheelbaseMm: 2640,
        maxWheelbaseMm: 2780,
      },
      {
        id: "gt3_spaceframe_reinforced",
        name: "Tubular Spaceframe Competition Chassis",
        architecture: "tubular_cradle",
        description: "Seamless steel tube chassis with modular bolt-on front and rear crash structures for fast pit repair.",
        rigidity: "55 kNm/°",
        rigidityNmPerDeg: 55000,
        massKg: 165,
        material: "4130 Seamless Motorsport Tubing",
        engineBayVolumeL: 400,
        minWheelbaseMm: 2640,
        maxWheelbaseMm: 2750,
      },
    ],
    compatibleBodies: [
      {
        id: "gt3_widebody_competition",
        name: "GT3 Competition Widebody Shell",
        style: "Flared fenders +60mm, swan-neck wing, front dive planes, rear extraction diffuser",
        description: "Lightweight carbon fiber bodywork with quick-release fasteners, radiator hood exhaust, and 1,800mm rear wing.",
        dragDeltaCd: 0.0,
        downforceDeltaKg: 380,
        massDeltaKg: 0,
        doorsCount: 2,
        cargoCapacityL: 0,
      },
    ],
    developmentTree: {
      bodyMods: ["FIA Quick-Release Carbon Bodywork", "Carbon Louvered Fenders", "Roof Air Escape Hatch"],
      chassisMods: ["Pneumatic 4-Post Air Jack System", "FIA FT3 120L Safety Fuel Cell", "Integrated Fire Extinguisher"],
      suspensionMods: ["4-Way Adjustable Race Dampers", "Blade Adjustable Anti-Roll Bars", "Centerlock Wheel Hubs"],
      aeroMods: ["Swan-Neck Dual Element Rear Wing", "Carbon Front Splitter with Diffuser Ramps", "Venturi Tunnel Exhaust Strakes"],
      powertrainMods: ["Sequential 6-Speed Dog Gearbox", "Motorsport Bosch Race ABS (12-Settings)", "Pit-Lane Speed Limiter"],
    },
  },

  formula_open_wheel: {
    id: "formula_open_wheel",
    name: "Formula / Open-Wheel",
    group: "motorsport",
    tagline: "Single-seater open-cockpit race car designed solely for maximum cornering G-force and aerodynamic efficiency.",
    description: "Ultra-narrow carbon fiber survival cell with exposed wheels, double-wishbone pushrod suspension with heave dampers, halo safety protection, and multi-element front and rear wings.",
    subcategories: ["Formula Single Seater", "High-Downforce Open-Wheel", "Hillclimb Special"],
    silhouetteType: "formula",
    dimensions: {
      wheelbase: { min: 2900, max: 3600, default: 3200 },
      frontTrack: { min: 1500, max: 1650, default: 1600 },
      rearTrack: { min: 1450, max: 1600, default: 1550 },
      rideHeight: { min: 25, max: 55, default: 35 },
      overallLength: { min: 4800, max: 5600, default: 5200 },
      overallWidth: { min: 1800, max: 2000, default: 2000 },
      overallHeight: { min: 950, max: 1050, default: 980 },
      frontOverhang: { min: 1100, max: 1400, default: 1250 },
      rearOverhang: { min: 650, max: 850, default: 750 },
      cabinPositionPct: 48,
    },
    typicalWeightKg: { min: 580, max: 800, default: 690 },
    typicalSeating: [1],
    luggageVolumeL: { min: 0, max: 0, default: 0 },
    engineBayVolumeL: 240,
    recommendedArchitecture: "Mid-engine longitudinal / RWD Stressed Member",
    allowedEnginePositions: ["mid"],
    defaultEnginePosition: "mid",
    allowedDrivetrains: ["rwd"],
    defaultDrivetrain: "rwd",
    allowedSuspensions: ["pushrod", "pullrod"],
    defaultSuspensionFront: "pushrod",
    defaultSuspensionRear: "pushrod",
    aeroClass: "Multi-Element Downforce",
    baseCd: 0.72,
    baseFrontalAreaM2: 1.45,
    downforcePotential: "extreme",
    engineeringDifficulty: "FIA Prototype",
    developmentCost: 4500000,
    compatibleChassis: [
      {
        id: "formula_survival_cell",
        name: "Carbon Monocoque Survival Cell with Titanium Halo",
        architecture: "carbon_tub",
        description: "Ultra-narrow survival monocoque with bonded Titanium Grade 5 Halo cockpit protection hoop.",
        rigidity: "90 kNm/°",
        rigidityNmPerDeg: 90000,
        massKg: 55,
        material: "Autoclave T1100 Toray Carbon + Ti-6Al-4V Halo",
        engineBayVolumeL: 240,
        minWheelbaseMm: 2900,
        maxWheelbaseMm: 3600,
      },
    ],
    compatibleBodies: [
      {
        id: "formula_aero_shell",
        name: "Open-Wheel Aerodynamic Monoposto Shell",
        style: "Needle nose cone, sidepod radiator chimneys, engine airbox intake",
        description: "Needle nose with front wing pylons, sculptured sidepod undercuts, and overhead airbox intake scoop.",
        dragDeltaCd: 0.0,
        downforceDeltaKg: 650,
        massDeltaKg: 0,
        doorsCount: 0,
        cargoCapacityL: 0,
      },
    ],
    developmentTree: {
      bodyMods: ["Multi-Cascade Front Wing", "Overhead Airbox Scoop", "Sidepod Undercut Radiator Vents"],
      chassisMods: ["Titanium Grade 5 Halo Structure", "Nose Crash Absorption Cone", "Rear Impact Attenuator"],
      suspensionMods: ["Heave Spring Inboard Mechanism", "Carbon Aerofoil Suspension Wishbones", "Titanium Uprights"],
      aeroMods: ["Active Drag Reduction System (DRS)", "Complex Beam Wing Elements", "Rear Venturi Tunnels"],
      powertrainMods: ["1.6L V6 Turbo Hybrid Power Unit", "MGU-H Turbo Generator", "Carbon Fiber Gearbox Casing"],
    },
  },

  prototype_lmp: {
    id: "prototype_lmp",
    name: "Prototype / LMP",
    group: "motorsport",
    tagline: "Closed-cockpit 24 Hours of Le Mans endurance prototype engineered for 210 mph stints.",
    description: "Built strictly for endurance sports car racing with enclosed wheels, central cockpit bubble, massive rear dorsal fin, low drag ground effects, and hybrid all-wheel drive.",
    subcategories: ["Prototype Race Car", "Endurance Prototype", "LMDh Hypercar Spec"],
    silhouetteType: "prototype",
    dimensions: {
      wheelbase: { min: 2850, max: 3150, default: 2950 },
      frontTrack: { min: 1620, max: 1720, default: 1680 },
      rearTrack: { min: 1600, max: 1700, default: 1650 },
      rideHeight: { min: 45, max: 80, default: 60 },
      overallLength: { min: 4650, max: 5000, default: 4800 },
      overallWidth: { min: 1980, max: 2020, default: 2000 },
      overallHeight: { min: 1040, max: 1120, default: 1060 },
      frontOverhang: { min: 920, max: 1040, default: 980 },
      rearOverhang: { min: 820, max: 960, default: 870 },
      cabinPositionPct: 45,
    },
    typicalWeightKg: { min: 890, max: 1080, default: 1030 },
    typicalSeating: [1],
    luggageVolumeL: { min: 0, max: 0, default: 0 },
    engineBayVolumeL: 380,
    recommendedArchitecture: "Mid-engine V8 Twin-Turbo Hybrid / AWD",
    allowedEnginePositions: ["mid"],
    defaultEnginePosition: "mid",
    allowedDrivetrains: ["awd", "rwd"],
    defaultDrivetrain: "awd",
    allowedSuspensions: ["pushrod"],
    defaultSuspensionFront: "pushrod",
    defaultSuspensionRear: "pushrod",
    aeroClass: "Endurance Ground Effect",
    baseCd: 0.36,
    baseFrontalAreaM2: 1.80,
    downforcePotential: "extreme",
    engineeringDifficulty: "FIA Prototype",
    developmentCost: 5500000,
    compatibleChassis: [
      {
        id: "lmp_endurance_tub",
        name: "LMP FIA Carbon Endurance Monocoque",
        architecture: "carbon_tub",
        description: "Carbon composite survival monocoque with dual roll hoops and integrated 200 kW front e-axle mounting points.",
        rigidity: "82 kNm/°",
        rigidityNmPerDeg: 82000,
        massKg: 110,
        material: "T1000 Carbon Fiber Prepreg",
        engineBayVolumeL: 400,
        minWheelbaseMm: 2850,
        maxWheelbaseMm: 3150,
      },
    ],
    compatibleBodies: [
      {
        id: "lmp_hypercar_shell",
        name: "Endurance Hypercar Aero Bodywork",
        style: "Enclosed wheels, central cockpit canopy, rear longitudinal dorsal fin",
        description: "High-efficiency body with mandatory longitudinal dorsal fin for spin stabilization and rear wing endplate ducts.",
        dragDeltaCd: 0.0,
        downforceDeltaKg: 520,
        massDeltaKg: 0,
        doorsCount: 2,
        cargoCapacityL: 0,
      },
    ],
    developmentTree: {
      bodyMods: ["Longitudinal Dorsal Fin", "Wheel Arch Pressure Relief Louvers", "Aerodynamic Canopy Gullwing Doors"],
      chassisMods: ["Front Hybrid E-Axle Cradle", "Fast Driver-Change Ergonomics", "Pneumatic Airjack System"],
      suspensionMods: ["Inboard Torsion Bar Pushrod System", "Active Ride Control Dampers", "Tuned Anti-Roll Bars"],
      aeroMods: ["Venturi Underbody Tunnels", "Adjustable Rear Wing Beam", "Front Splitter Diffusers"],
      powertrainMods: ["Endurance 200kW Front E-Motor", "Twin-Turbo 3.5L V6 Engine", "Xtrac 7-Speed Sequential"],
    },
  },

  pickup: {
    id: "pickup",
    name: "Pickup",
    group: "suv_utility",
    tagline: "Tough body-on-frame utility truck with high payload bed and rugged towing capability.",
    description: "Full-size or mid-size pickup truck featuring high-strength steel ladder frame, distinct passenger cab and separate cargo bed, 4WD transfer case, and high payload capacities.",
    subcategories: ["Compact Pickup", "Performance Pickup", "Heavy-Duty Pickup", "Desert Baja Trophy Truck"],
    silhouetteType: "pickup",
    dimensions: {
      wheelbase: { min: 3100, max: 3750, default: 3450 },
      frontTrack: { min: 1680, max: 1840, default: 1740 },
      rearTrack: { min: 1680, max: 1840, default: 1740 },
      rideHeight: { min: 210, max: 320, default: 245 },
      overallLength: { min: 5200, max: 6100, default: 5580 },
      overallWidth: { min: 1980, max: 2180, default: 2060 },
      overallHeight: { min: 1820, max: 2020, default: 1910 },
      frontOverhang: { min: 880, max: 1040, default: 940 },
      rearOverhang: { min: 1150, max: 1450, default: 1290 },
      cabinPositionPct: 40,
    },
    typicalWeightKg: { min: 2100, max: 3300, default: 2480 },
    typicalSeating: [3, 5, 6],
    luggageVolumeL: { min: 1100, max: 2100, default: 1550 },
    engineBayVolumeL: 520,
    recommendedArchitecture: "Front-engine longitudinal / 4WD",
    allowedEnginePositions: ["front"],
    defaultEnginePosition: "front",
    allowedDrivetrains: ["awd", "rwd"],
    defaultDrivetrain: "awd",
    allowedSuspensions: ["leaf_spring", "double_wishbone", "multilink"],
    defaultSuspensionFront: "double_wishbone",
    defaultSuspensionRear: "leaf_spring",
    aeroClass: "Utility Boxy",
    baseCd: 0.42,
    baseFrontalAreaM2: 3.20,
    downforcePotential: "minimal",
    engineeringDifficulty: "Moderate",
    developmentCost: 650000,
    compatibleChassis: [
      {
        id: "pickup_ladder_boxed",
        name: "Hydroformed High-Strength Steel Ladder Chassis",
        architecture: "ladder",
        description: "Fully boxed ladder frame with reinforced bed mounting crossmembers and 12,000 lbs towing capability.",
        rigidity: "28 kNm/°",
        rigidityNmPerDeg: 28000,
        massKg: 520,
        material: "High-Strength Low-Alloy Steel (HSLA 550)",
        engineBayVolumeL: 540,
        minWheelbaseMm: 3100,
        maxWheelbaseMm: 3750,
      },
    ],
    compatibleBodies: [
      {
        id: "pickup_crew_cab",
        name: "Crew Cab & 5.5ft Cargo Bed",
        style: "4 full-size doors, 5-passenger cabin, separate open cargo bed",
        description: "Versatile crew cab with folding rear seats, power tailgate with integrated step, and spray-in bedliner.",
        dragDeltaCd: 0.0,
        downforceDeltaKg: 0,
        massDeltaKg: 0,
        doorsCount: 4,
        cargoCapacityL: 1450,
      },
      {
        id: "pickup_baja_widebody",
        name: "Performance Baja Trophy Body",
        style: "Flared fiberglass fenders (+75mm), chase rack, pre-runner bumper",
        description: "Widebody flared fenders accommodating 37-inch desert tires and spare wheel rack in bed.",
        dragDeltaCd: +0.035,
        downforceDeltaKg: 20,
        massDeltaKg: -25,
        doorsCount: 4,
        cargoCapacityL: 1200,
      },
    ],
    developmentTree: {
      bodyMods: ["Bedliner with Tie-Down Rails", "Roll-Up Tonneau Cover", "Heavy-Duty Steel Winch Bumper", "Bed Chase Rack"],
      chassisMods: ["Class-IV Towing Receiver Hitch", "Underbody Fuel Tank Skid Plate", "Rear Axle Truss Reinforcement"],
      suspensionMods: ["Long-Travel Front Upper Control Arms", "Progressive Leaf Spring Pack", "Electronic Locking Rear Differential"],
      aeroMods: ["Tailgate Aerodynamic Lip", "Active Grille Shutters", "Front Bumper Air Dam"],
      powertrainMods: ["High-Torque Turbo Diesel V6", "Heavy-Duty 10-Speed Auto", "Auxiliary Transmission Oil Cooler"],
    },
  },

  van_mpv: {
    id: "van_mpv",
    name: "Van / MPV",
    group: "suv_utility",
    tagline: "Ultimate interior space efficiency with flat floor, sliding doors & VIP passenger luxury.",
    description: "Monovolume multi-purpose vehicle maximizing cabin space with high roofline, low load floor, dual sliding passenger doors, and configurable modular seating.",
    subcategories: ["Passenger Van", "Premium MPV", "Commercial Cargo Van"],
    silhouetteType: "van",
    dimensions: {
      wheelbase: { min: 2950, max: 3450, default: 3150 },
      frontTrack: { min: 1620, max: 1750, default: 1680 },
      rearTrack: { min: 1620, max: 1750, default: 1680 },
      rideHeight: { min: 140, max: 190, default: 160 },
      overallLength: { min: 4850, max: 5400, default: 5120 },
      overallWidth: { min: 1880, max: 2020, default: 1940 },
      overallHeight: { min: 1780, max: 1980, default: 1860 },
      frontOverhang: { min: 780, max: 940, default: 850 },
      rearOverhang: { min: 980, max: 1180, default: 1080 },
      cabinPositionPct: 40,
    },
    typicalWeightKg: { min: 1950, max: 2750, default: 2280 },
    typicalSeating: [6, 7, 8, 9],
    luggageVolumeL: { min: 850, max: 2400, default: 1350 },
    engineBayVolumeL: 320,
    recommendedArchitecture: "Front-engine transverse / FWD or AWD",
    allowedEnginePositions: ["front"],
    defaultEnginePosition: "front",
    allowedDrivetrains: ["fwd", "awd", "rwd"],
    defaultDrivetrain: "fwd",
    allowedSuspensions: ["macpherson", "torsion_beam", "multilink"],
    defaultSuspensionFront: "macpherson",
    defaultSuspensionRear: "multilink",
    aeroClass: "Monovolume Van",
    baseCd: 0.33,
    baseFrontalAreaM2: 3.15,
    downforcePotential: "minimal",
    engineeringDifficulty: "Moderate",
    developmentCost: 580000,
    compatibleChassis: [
      {
        id: "van_flat_floor_unibody",
        name: "Low-Floor Flat Passenger Unibody",
        architecture: "monocoque",
        description: "Monocoque platform engineered with flat underfloor channel and high-strength roof ring frames.",
        rigidity: "35 kNm/°",
        rigidityNmPerDeg: 35000,
        massKg: 410,
        material: "High-Strength Steel Unibody",
        engineBayVolumeL: 340,
        minWheelbaseMm: 2950,
        maxWheelbaseMm: 3450,
      },
    ],
    compatibleBodies: [
      {
        id: "van_mpv_vip_shell",
        name: "Luxury VIP Executive MPV Body",
        style: "Dual electric sliding doors, privacy glass, high roofline",
        description: "Acoustic laminated privacy glass, dual power sliding doors with foot sensors, and large rear liftgate.",
        dragDeltaCd: 0.0,
        downforceDeltaKg: 0,
        massDeltaKg: 0,
        doorsCount: 5,
        cargoCapacityL: 1400,
      },
    ],
    developmentTree: {
      bodyMods: ["Dual Electric Sliding Doors", "High-Roof Aero Cap", "Modular Interior Floor Rails"],
      chassisMods: ["Subframe Vibration Dampers", "Reinforced Door Aperture Rings", "Low-Load Height Rear Crossmember"],
      suspensionMods: ["Comfort-Tuned Air Suspension", "Heavy-Duty Stabilizer Bars", "Rear Load-Leveling Shocks"],
      aeroMods: ["Aero Wheel Covers", "Roof Edge Deflector", "Underbody Smooth Panels"],
      powertrainMods: ["Efficient Plug-in Hybrid Powertrain", "Front-Wheel Drive Transaxle", "Regenerative Braking Blending"],
    },
  },

  ev_platform: {
    id: "ev_platform",
    name: "EV Platform",
    group: "electric",
    tagline: "Dedicated skateboard EV architecture with structural battery pack & multi-motor e-axles.",
    description: "Pure electric skateboard chassis integrating the high-voltage battery casing as the primary torsional member, low center of gravity, front frunk storage, and independent dual or tri-motor torque vectoring.",
    subcategories: ["Compact EV", "Performance EV", "Luxury EV", "Electric Sports Car"],
    silhouetteType: "ev",
    dimensions: {
      wheelbase: { min: 2750, max: 3200, default: 2950 },
      frontTrack: { min: 1600, max: 1720, default: 1660 },
      rearTrack: { min: 1600, max: 1740, default: 1670 },
      rideHeight: { min: 110, max: 160, default: 130 },
      overallLength: { min: 4600, max: 5100, default: 4850 },
      overallWidth: { min: 1880, max: 2020, default: 1940 },
      overallHeight: { min: 1390, max: 1520, default: 1440 },
      frontOverhang: { min: 780, max: 920, default: 840 },
      rearOverhang: { min: 880, max: 1060, default: 960 },
      cabinPositionPct: 48,
    },
    typicalWeightKg: { min: 1850, max: 2450, default: 2120 },
    typicalSeating: [5],
    luggageVolumeL: { min: 480, max: 750, default: 580 },
    engineBayVolumeL: 120, // Frunk storage
    recommendedArchitecture: "Dual-Motor AWD Skateboard / 800V Architecture",
    allowedEnginePositions: ["mid", "front"],
    defaultEnginePosition: "mid",
    allowedDrivetrains: ["awd", "rwd"],
    defaultDrivetrain: "awd",
    allowedSuspensions: ["double_wishbone", "multilink"],
    defaultSuspensionFront: "double_wishbone",
    defaultSuspensionRear: "multilink",
    aeroClass: "Ultra-Low Drag EV",
    baseCd: 0.22,
    baseFrontalAreaM2: 2.24,
    downforcePotential: "moderate",
    engineeringDifficulty: "Advanced",
    developmentCost: 2100000,
    compatibleChassis: [
      {
        id: "ev_skateboard_diecast",
        name: "Structural Battery Skateboard Chassis",
        architecture: "ev_skateboard",
        description: "Megacasting front and rear aluminum structures with integrated 800V cell-to-pack structural battery case.",
        rigidity: "68 kNm/°",
        rigidityNmPerDeg: 68000,
        massKg: 380, // without battery cells
        material: "A380 Die-Cast Aluminum & Extruded Battery Case",
        engineBayVolumeL: 120,
        minWheelbaseMm: 2750,
        maxWheelbaseMm: 3200,
      },
    ],
    compatibleBodies: [
      {
        id: "ev_fastback_aero",
        name: "Ultra-Low Drag Streamlined Fastback",
        style: "Flush glass, camera mirrors, aerodynamic flat underfloor",
        description: "Extremely low 0.21 Cd coefficient with flush door handles, enclosed nose cone, and tapered boat-tail rear.",
        dragDeltaCd: -0.02,
        downforceDeltaKg: 20,
        massDeltaKg: 0,
        doorsCount: 4,
        cargoCapacityL: 580,
      },
    ],
    developmentTree: {
      bodyMods: ["Virtual Camera Side Mirrors", "Flush Electronic Door Handles", "Illuminated Aero Nose Panel"],
      chassisMods: ["800V Silicon Carbide Inverter Mount", "Liquid Battery Chiller Plate", "Front Frunk Storage Bin"],
      suspensionMods: ["Air Suspension with Highway Auto-Lowering", "Continuous Damping Control", "Rear-Wheel Steering (10°)"],
      aeroMods: ["Aero Disc Wheel Covers", "Active Front Bumper Cooling Flaps", "Rear Diffuser Air Curtains"],
      powertrainMods: ["Dual Permanent Magnet E-Motors", "Silicon-Carbide (SiC) 800V Inverter", "One-Pedal Drive Regenerative System"],
    },
  },
};

/**
 * Returns the list of all 18 categories formatted for UI cards.
 */
export function getAllVehicleCategories(): VehicleCategoryDefinition[] {
  return Object.values(VEHICLE_CATEGORIES);
}

/**
 * Retrieves a category definition by ID with fallback to "sports_car".
 */
export function getVehicleCategory(id?: string): VehicleCategoryDefinition {
  if (id && id in VEHICLE_CATEGORIES) {
    return VEHICLE_CATEGORIES[id as VehicleCategoryId];
  }
  return VEHICLE_CATEGORIES.sports_car;
}
