/**
 * ═══════════════════════════════════════════════════════════════════════
 * NPC INDUSTRIAL SUPPLIER REGISTRY & TIER-1 ECOSYSTEM
 * ═══════════════════════════════════════════════════════════════════════
 *
 * Implements Section 8 & 9 of the Raw Materials & Trade Specification:
 * - 14 Distinct NPC Industrial Corporations
 * - Authentic geographic identities, industrial clusters, and tech levels
 * - Defined material quality vectors, monthly capacities, lead times,
 *   and contract negotiation preferences.
 */

import { SupplierProfile } from "./tradeTypes";

export const NPC_SUPPLIERS: SupplierProfile[] = [
  // ── 1. FERROUS METALLURGY ──────────────────────────────────────────
  {
    id: "atlas_steel_co",
    name: "Atlas Industrial Steel Corp.",
    tagline: "Heavy Industrial Continuous Casting & Stamping Coils",
    country: "Domestic (Rhine Valley)",
    regionCluster: "Rhine Industrial Valley",
    tier: 1,
    specializations: ["BASIC_CARBON_STEEL", "HIGH_STRENGTH_STEEL", "CHASSIS_BODY_PANELS"],
    technologyRating: 74,
    reliabilityRating: 92,
    financialHealth: "AA",
    baseQualityVector: {
      strength: 72,
      weightIndex: 82,
      consistency: 80,
      purity: 82,
      corrosionResistance: 60,
      heatResistance: 72,
      manufacturability: 88,
    },
    minimumOrderVolume: 200, // tonnes/mo
    maximumMonthlyCapacity: 8500,
    relationshipScore: 65,
    baseLeadTimeDays: 7,
    offeredPaymentTerms: ["CASH_UPFRONT", "NET_30", "NET_90"],
    exclusiveContractActive: false,
    description: "Massive integrated blast furnace complex producing dependable automotive stamping coil and structural floorpans at competitive domestic freight rates.",
  },
  {
    id: "nippon_advanced_steel",
    name: "Nippon Shindo Metallurgy Ltd.",
    tagline: "Ultra-High Purity Martensitic & Dual-Phase UHSS",
    country: "Japan (Keihin)",
    regionCluster: "Pacific Export Corridor",
    tier: 1,
    specializations: ["ADVANCED_UHSS_STEEL", "HIGH_STRENGTH_STEEL"],
    technologyRating: 96,
    reliabilityRating: 98,
    financialHealth: "AAA",
    baseQualityVector: {
      strength: 96,
      weightIndex: 60,
      consistency: 98,
      purity: 99,
      corrosionResistance: 88,
      heatResistance: 88,
      manufacturability: 68,
    },
    minimumOrderVolume: 100,
    maximumMonthlyCapacity: 4000,
    relationshipScore: 50,
    baseLeadTimeDays: 24, // Transoceanic
    offeredPaymentTerms: ["CASH_UPFRONT", "NET_30"],
    exclusiveContractActive: false,
    description: "World leader in hot-stamped boron and dual-phase crash steel with near-zero microscopic inclusions. Demands premium prices and strict contract minimums.",
  },
  {
    id: "vulcan_foundry_works",
    name: "Vulcan Iron & Engine Foundry",
    tagline: "Grey Iron Casting, Nodular Crankshafts & Rotor Blanks",
    country: "Domestic (Midlands)",
    regionCluster: "Rhine Industrial Valley",
    tier: 2,
    specializations: ["DUCTILE_CAST_IRON", "BRAKE_DISCS_CALIPERS", "ENGINE_BLOCK_INTERNALS"],
    technologyRating: 68,
    reliabilityRating: 84,
    financialHealth: "A",
    baseQualityVector: {
      strength: 66,
      weightIndex: 92,
      consistency: 74,
      purity: 75,
      corrosionResistance: 48,
      heatResistance: 88,
      manufacturability: 84,
    },
    minimumOrderVolume: 50,
    maximumMonthlyCapacity: 3200,
    relationshipScore: 70,
    baseLeadTimeDays: 5,
    offeredPaymentTerms: ["CASH_UPFRONT", "NET_30", "NET_90"],
    exclusiveContractActive: false,
    description: "Traditional sand-casting and green-sand moulding foundry. Specializes in vibration-damped cylinder blocks and heavy ventilated brake discs.",
  },

  // ── 2. LIGHTWEIGHT ALLOYS ──────────────────────────────────────────
  {
    id: "alba_light_alloys",
    name: "Alba Leichtmetall Extrusions AG",
    tagline: "Hydro-Powered 6000 & 7000 Series Structural Aluminum",
    country: "Switzerland / Germany",
    regionCluster: "Nordic Hydropower Cluster",
    tier: 1,
    specializations: ["ALUMINUM_SHEET_6000", "ALUMINUM_FORGING_7000", "SUSPENSION_ARMS_SPRINGS"],
    technologyRating: 88,
    reliabilityRating: 90,
    financialHealth: "AA",
    baseQualityVector: {
      strength: 84,
      weightIndex: 44,
      consistency: 91,
      purity: 93,
      corrosionResistance: 90,
      heatResistance: 62,
      manufacturability: 75,
    },
    minimumOrderVolume: 80,
    maximumMonthlyCapacity: 2800,
    relationshipScore: 55,
    baseLeadTimeDays: 10,
    offeredPaymentTerms: ["CASH_UPFRONT", "NET_30"],
    exclusiveContractActive: false,
    description: "High-precision extrusion presses forging multi-hollow subframe rails, wishbones, and aluminium door outer panels with clean environmental hydro-power.",
  },
  {
    id: "ural_titanium_solutions",
    name: "Kronos Aerospace Titanium",
    tagline: "Vacuum Arc Remelted Ti-6Al-4V Forgings",
    country: "Austria / International",
    regionCluster: "Alpine Specialty Metallurgy",
    tier: 1,
    specializations: ["TITANIUM_GRADE_5", "MAGNESIUM_ALLOY_CAST"],
    technologyRating: 94,
    reliabilityRating: 82,
    financialHealth: "A",
    baseQualityVector: {
      strength: 97,
      weightIndex: 45,
      consistency: 94,
      purity: 97,
      corrosionResistance: 99,
      heatResistance: 96,
      manufacturability: 38,
    },
    minimumOrderVolume: 10,
    maximumMonthlyCapacity: 450,
    relationshipScore: 40,
    baseLeadTimeDays: 18,
    offeredPaymentTerms: ["CASH_UPFRONT"],
    exclusiveContractActive: false,
    description: "Elite aerospace-spec titanium supplier for high-revving racing connecting rods, titanium valves, and lightweight exhaust manifolds.",
  },

  // ── 3. POLYMERS, RUBBER & GLASS ────────────────────────────────────
  {
    id: "apex_elastomers_tyres",
    name: "Apex Tyre & Rubber Technologies",
    tagline: "Directional Tread Compounds & Viton Bushings",
    country: "Italy",
    regionCluster: "Coastal Megaport Terminal",
    tier: 1,
    specializations: ["VULCANIZED_RUBBER", "TYRES_WHEELS"],
    technologyRating: 86,
    reliabilityRating: 94,
    financialHealth: "AAA",
    baseQualityVector: {
      strength: 78,
      weightIndex: 35,
      consistency: 92,
      purity: 88,
      corrosionResistance: 96,
      heatResistance: 82,
      manufacturability: 85,
    },
    minimumOrderVolume: 250, // wheel/tyre sets
    maximumMonthlyCapacity: 12000,
    relationshipScore: 60,
    baseLeadTimeDays: 8,
    offeredPaymentTerms: ["CASH_UPFRONT", "NET_30", "NET_90"],
    exclusiveContractActive: false,
    description: "Premier motorsport and road tyre manufacturer with advanced silica-reinforced tread compounds and high-durometer suspension bushings.",
  },
  {
    id: "saint_gobain_glassworks",
    name: "Veloce Optical Glassworks",
    tagline: "Acoustic Laminated & Solar Reflective Glazing",
    country: "France",
    regionCluster: "Coastal Megaport Terminal",
    tier: 1,
    specializations: ["AUTOMOTIVE_FLOAT_GLASS", "AUTOMOTIVE_GLASS"],
    technologyRating: 84,
    reliabilityRating: 95,
    financialHealth: "AA",
    baseQualityVector: {
      strength: 70,
      weightIndex: 52,
      consistency: 94,
      purity: 96,
      corrosionResistance: 99,
      heatResistance: 80,
      manufacturability: 82,
    },
    minimumOrderVolume: 100,
    maximumMonthlyCapacity: 6000,
    relationshipScore: 65,
    baseLeadTimeDays: 9,
    offeredPaymentTerms: ["CASH_UPFRONT", "NET_30", "NET_90"],
    exclusiveContractActive: false,
    description: "State-of-the-art float glass furnaces bending acoustic dual-pane windshields, frameless door glass, and heated rear backlight screens.",
  },
  {
    id: "bayer_engineering_polymers",
    name: "Bayer Polymers & Synthetic Chemistry",
    tagline: "Glass-Filled Polyamides, ABS & Soft-Touch Thermoplastics",
    country: "Germany",
    regionCluster: "Rhine Industrial Valley",
    tier: 2,
    specializations: ["ENGINEERING_POLYMERS", "INTERIOR_DASH_TRIM"],
    technologyRating: 82,
    reliabilityRating: 90,
    financialHealth: "AAA",
    baseQualityVector: {
      strength: 65,
      weightIndex: 26,
      consistency: 88,
      purity: 90,
      corrosionResistance: 98,
      heatResistance: 68,
      manufacturability: 94,
    },
    minimumOrderVolume: 40,
    maximumMonthlyCapacity: 4500,
    relationshipScore: 58,
    baseLeadTimeDays: 6,
    offeredPaymentTerms: ["CASH_UPFRONT", "NET_30"],
    exclusiveContractActive: false,
    description: "Petrochemical synthesis leader supplying intake manifold resins, instrument panel armatures, and NVH acoustic sound-deadening mats.",
  },

  // ── 4. COMPOSITES & CARBON FIBER ───────────────────────────────────
  {
    id: "torayca_composites",
    name: "Torayca Prepreg Carbon Systems",
    tagline: "Autoclave-Cured High Modulus Structural Carbon Fiber",
    country: "Japan / UK",
    regionCluster: "Bavarian Precision Valley",
    tier: 1,
    specializations: ["CARBON_FIBER_PREPREG", "CHASSIS_BODY_PANELS"],
    technologyRating: 97,
    reliabilityRating: 88,
    financialHealth: "AA",
    baseQualityVector: {
      strength: 98,
      weightIndex: 20,
      consistency: 96,
      purity: 98,
      corrosionResistance: 100,
      heatResistance: 90,
      manufacturability: 45,
    },
    minimumOrderVolume: 15,
    maximumMonthlyCapacity: 350,
    relationshipScore: 45,
    baseLeadTimeDays: 16,
    offeredPaymentTerms: ["CASH_UPFRONT", "NET_30"],
    exclusiveContractActive: false,
    description: "Aerospace pre-impregnated epoxy carbon fabrics for F1 monocoques, Le Mans aerodynamic diffusers, and carbon-ceramic brake backing plates.",
  },

  // ── 5. POWERTRAIN & BRAKING MECHANICALS ────────────────────────────
  {
    id: "brembo_braking_systems",
    name: "Officine Freni Brembo & Corsa",
    tagline: "Monobloc Calipers, Carbon-Ceramic Rotors & ABS Modulators",
    country: "Italy",
    regionCluster: "Coastal Megaport Terminal",
    tier: 1,
    specializations: ["BRAKE_DISCS_CALIPERS"],
    technologyRating: 93,
    reliabilityRating: 96,
    financialHealth: "AAA",
    baseQualityVector: {
      strength: 92,
      weightIndex: 50,
      consistency: 95,
      purity: 94,
      corrosionResistance: 90,
      heatResistance: 98,
      manufacturability: 70,
    },
    minimumOrderVolume: 50, // brake sets
    maximumMonthlyCapacity: 3500,
    relationshipScore: 65,
    baseLeadTimeDays: 12,
    offeredPaymentTerms: ["CASH_UPFRONT", "NET_30"],
    exclusiveContractActive: false,
    description: "Benchmark braking hardware. Machined aluminum monobloc calipers and cross-drilled carbon-ceramic discs engineered for fade-free 300 km/h deceleration.",
  },
  {
    id: "meridian_transaxle_systems",
    name: "Meridian Precision Drivetrains",
    tagline: "Helical Gearboxes, Sequential Shifters & eLSD Units",
    country: "Germany",
    regionCluster: "Bavarian Precision Valley",
    tier: 1,
    specializations: ["TRANSMISSION_GEARS_SHAFTS"],
    technologyRating: 89,
    reliabilityRating: 92,
    financialHealth: "AA",
    baseQualityVector: {
      strength: 90,
      weightIndex: 70,
      consistency: 92,
      purity: 92,
      corrosionResistance: 75,
      heatResistance: 90,
      manufacturability: 72,
    },
    minimumOrderVolume: 30, // transaxles
    maximumMonthlyCapacity: 2400,
    relationshipScore: 60,
    baseLeadTimeDays: 14,
    offeredPaymentTerms: ["CASH_UPFRONT", "NET_30"],
    exclusiveContractActive: false,
    description: "Dual-clutch and manual transaxle specialist. CNC gear hobbing, case-hardened synchro rings, and electronically controlled locking differentials.",
  },

  // ── 6. ELECTRONICS & ELECTRIFICATION ───────────────────────────────
  {
    id: "nova_microelectronics",
    name: "Nova Automotive Microelectronics",
    tagline: "ECUs, Silicon Gate Drivers & CAN-Bus Telemetry",
    country: "Germany / Taiwan",
    regionCluster: "Bavarian Precision Valley",
    tier: 1,
    specializations: ["WIRING_HARNESS_ECU", "SEMICONDUCTOR_SILICON", "ELECTROLYTIC_COPPER"],
    technologyRating: 95,
    reliabilityRating: 86,
    financialHealth: "AAA",
    baseQualityVector: {
      strength: 55,
      weightIndex: 30,
      consistency: 97,
      purity: 99,
      corrosionResistance: 92,
      heatResistance: 88,
      manufacturability: 60,
    },
    minimumOrderVolume: 100, // ECU kits
    maximumMonthlyCapacity: 8000,
    relationshipScore: 52,
    baseLeadTimeDays: 20,
    offeredPaymentTerms: ["CASH_UPFRONT", "NET_30"],
    exclusiveContractActive: false,
    description: "Silicon microcontrollers, direct-injection engine control computers, and solid-state sensors. Prone to global semiconductor wafer shortages.",
  },
  {
    id: "kyoto_energy_cells",
    name: "Kyoto Cell & Battery Systems",
    tagline: "800V Prismatic Cell Chemistry & Solid-State Precursors",
    country: "Japan / South Korea",
    regionCluster: "Pacific Export Corridor",
    tier: 1,
    specializations: ["BATTERY_CATHODE_NMC", "BATTERY_ANODE_GRAPHITE", "BATTERY_CELL_MODULES"],
    technologyRating: 96,
    reliabilityRating: 89,
    financialHealth: "AA",
    baseQualityVector: {
      strength: 60,
      weightIndex: 58,
      consistency: 95,
      purity: 98,
      corrosionResistance: 85,
      heatResistance: 82,
      manufacturability: 55,
    },
    minimumOrderVolume: 20, // EV pack modules
    maximumMonthlyCapacity: 2500,
    relationshipScore: 48,
    baseLeadTimeDays: 28,
    offeredPaymentTerms: ["CASH_UPFRONT"],
    exclusiveContractActive: false,
    description: "High energy-density nickel-manganese-cobalt (NMC 811) lithium cells and structural pack cooling plates for high-performance EV platforms.",
  },
  {
    id: "midlands_chassis_stampers",
    name: "Midlands Press & Tooling Ltd.",
    tagline: "Budget Subframes, Control Arms & Pressed Steel Brackets",
    country: "UK",
    regionCluster: "Rhine Industrial Valley",
    tier: 3,
    specializations: ["CHASSIS_BODY_PANELS", "SUSPENSION_ARMS_SPRINGS"],
    technologyRating: 60,
    reliabilityRating: 75,
    financialHealth: "BBB",
    baseQualityVector: {
      strength: 60,
      weightIndex: 88,
      consistency: 65,
      purity: 70,
      corrosionResistance: 45,
      heatResistance: 60,
      manufacturability: 85,
    },
    minimumOrderVolume: 150,
    maximumMonthlyCapacity: 6000,
    relationshipScore: 75,
    baseLeadTimeDays: 4,
    offeredPaymentTerms: ["CASH_UPFRONT", "NET_30", "NET_90"],
    exclusiveContractActive: false,
    description: "Low-cost high-volume supplier for economy vehicle brackets and stampings. High tolerance variance requires strict inbound QA inspection.",
  },
];
