// ===================================================================
// EXHAUSTIVE GLOBAL SUPPLIER REGISTRY (Tier 1, Tier 2, Tier 3)
// ===================================================================
// Comprehensive database of specialized automotive component vendors,
// foundry partners, and raw material refiners worldwide.
// ===================================================================

export type SupplyCategory =
  | "CHASSIS_FOUNDRY"
  | "BRAKES_FRICTION"
  | "TIRES_RUBBER"
  | "ECU_SEMICONDUCTORS"
  | "BATTERY_CELLS"
  | "COMPOSITES_CARBON"
  | "TURBO_SUPERCHARGERS"
  | "TRANSMISSION_GEARS"
  | "SUSPENSION_DAMPERS"
  | "EXHAUST_EMISSIONS"
  | "INTERIOR_CABIN"
  | "LIGHTING_OPTICS"
  | "ELECTRIC_MOTORS"
  | "POWER_ELECTRONICS"
  | "HYDROGEN_FUEL_CELLS";

export type SupplierTier = "TIER_1_OEM_PARTNER" | "TIER_2_SUBSYSTEM_VENDOR" | "TIER_3_RAW_MATERIAL_REFINER";

export interface GlobalSupplier {
  id: string;
  name: string;
  tier: SupplierTier;
  category: SupplyCategory;
  headquarters: string;
  country: string;
  continent: "NORTH_AMERICA" | "EUROPE" | "ASIA_PACIFIC" | "SOUTH_AMERICA" | "MIDDLE_EAST";
  reputationScorePct: number; // 0 - 100
  qualityDefectPpm: number; // Defect rate in Parts Per Million
  costMultiplier: number; // Base multiplier vs commodity standard cost
  leadTimeWeeks: number;
  minimumOrderQuantity: number;
  financialStabilityIndex: number; // 0 - 1.0 (Risk of bankruptcy/insolvency)
  esgSustainabilityScore: number; // 0 - 100 (CO2 footprint & social governance)
  technologyRdLevel: number; // 1 - 10 (Cut-edge tech capability)
  specialtyDescription: string;
  capacityUnitsPerYear: number;
  innovationBonus: {
    statKey: string;
    multiplier: number;
  };
}

export const GLOBAL_SUPPLIER_CATALOG: GlobalSupplier[] = [
  // ── CHASSIS & FOUNDRY ──
  {
    id: "dallara_composites",
    name: "Dallara Automobili S.p.A.",
    tier: "TIER_1_OEM_PARTNER",
    category: "COMPOSITES_CARBON",
    headquarters: "Varano de' Melegari",
    country: "Italy",
    continent: "EUROPE",
    reputationScorePct: 99.2,
    qualityDefectPpm: 5,
    costMultiplier: 2.35,
    leadTimeWeeks: 12,
    minimumOrderQuantity: 25,
    financialStabilityIndex: 0.94,
    esgSustainabilityScore: 82.0,
    technologyRdLevel: 10,
    specialtyDescription: "Autoclave cured prepreg T800 carbon-fiber monocoques & aero structures",
    capacityUnitsPerYear: 2500,
    innovationBonus: { statKey: "torsionalRigidityPerKg", multiplier: 1.45 },
  },
  {
    id: "nemak_foundry",
    name: "Nemak S.A.B. de C.V.",
    tier: "TIER_1_OEM_PARTNER",
    category: "CHASSIS_FOUNDRY",
    headquarters: "Monterrey",
    country: "Mexico",
    continent: "NORTH_AMERICA",
    reputationScorePct: 91.5,
    qualityDefectPpm: 48,
    costMultiplier: 0.92,
    leadTimeWeeks: 6,
    minimumOrderQuantity: 10000,
    financialStabilityIndex: 0.88,
    esgSustainabilityScore: 74.0,
    technologyRdLevel: 7,
    specialtyDescription: "High-pressure die-cast aluminum engine blocks & structural subframes",
    capacityUnitsPerYear: 500000,
    innovationBonus: { statKey: "foundryCostEfficiency", multiplier: 1.22 },
  },
  {
    id: "georg_fischer",
    name: "GF Casting Solutions AG",
    tier: "TIER_1_OEM_PARTNER",
    category: "CHASSIS_FOUNDRY",
    headquarters: "Schaffhausen",
    country: "Switzerland",
    continent: "EUROPE",
    reputationScorePct: 95.8,
    qualityDefectPpm: 20,
    costMultiplier: 1.25,
    leadTimeWeeks: 8,
    minimumOrderQuantity: 5000,
    financialStabilityIndex: 0.96,
    esgSustainabilityScore: 91.0,
    technologyRdLevel: 9,
    specialtyDescription: "Bionic lightweight magnesium & aluminum mega-castings",
    capacityUnitsPerYear: 250000,
    innovationBonus: { statKey: "weightReduction", multiplier: 1.30 },
  },

  // ── BRAKES & FRICTION ──
  {
    id: "brembo_performance",
    name: "Brembo S.p.A.",
    tier: "TIER_1_OEM_PARTNER",
    category: "BRAKES_FRICTION",
    headquarters: "Stezzano",
    country: "Italy",
    continent: "EUROPE",
    reputationScorePct: 98.8,
    qualityDefectPpm: 12,
    costMultiplier: 1.55,
    leadTimeWeeks: 4,
    minimumOrderQuantity: 500,
    financialStabilityIndex: 0.97,
    esgSustainabilityScore: 86.0,
    technologyRdLevel: 10,
    specialtyDescription: "Carbon-Silicon Carbide (CCM-R) discs & aluminum-lithium monobloc calipers",
    capacityUnitsPerYear: 120000,
    innovationBonus: { statKey: "brakeFadeResistance", multiplier: 1.35 },
  },
  {
    id: "akebono_corp",
    name: "Akebono Brake Industry Co.",
    tier: "TIER_1_OEM_PARTNER",
    category: "BRAKES_FRICTION",
    headquarters: "Tokyo",
    country: "Japan",
    continent: "ASIA_PACIFIC",
    reputationScorePct: 94.5,
    qualityDefectPpm: 10,
    costMultiplier: 1.12,
    leadTimeWeeks: 5,
    minimumOrderQuantity: 2500,
    financialStabilityIndex: 0.85,
    esgSustainabilityScore: 88.0,
    technologyRdLevel: 8,
    specialtyDescription: "Zero-copper ceramic friction formulas & endurance race calipers",
    capacityUnitsPerYear: 800000,
    innovationBonus: { statKey: "padLongevity", multiplier: 1.40 },
  },
  {
    id: "alcon_brakes",
    name: "Alcon Specialist Components",
    tier: "TIER_2_SUBSYSTEM_VENDOR",
    category: "BRAKES_FRICTION",
    headquarters: "Tamworth",
    country: "United Kingdom",
    continent: "EUROPE",
    reputationScorePct: 96.0,
    qualityDefectPpm: 18,
    costMultiplier: 1.40,
    leadTimeWeeks: 6,
    minimumOrderQuantity: 100,
    financialStabilityIndex: 0.90,
    esgSustainabilityScore: 79.0,
    technologyRdLevel: 9,
    specialtyDescription: "Bespoke motorsport brake assemblies & defense vehicle friction systems",
    capacityUnitsPerYear: 45000,
    innovationBonus: { statKey: "thermalCapacity", multiplier: 1.28 },
  },

  // ── TIRES & RUBBER ──
  {
    id: "michelin_group",
    name: "Manufacture Française des Pneumatiques Michelin",
    tier: "TIER_1_OEM_PARTNER",
    category: "TIRES_RUBBER",
    headquarters: "Clermont-Ferrand",
    country: "France",
    continent: "EUROPE",
    reputationScorePct: 99.4,
    qualityDefectPpm: 6,
    costMultiplier: 1.50,
    leadTimeWeeks: 3,
    minimumOrderQuantity: 1000,
    financialStabilityIndex: 0.98,
    esgSustainabilityScore: 94.0,
    technologyRdLevel: 10,
    specialtyDescription: "Pilot Sport Cup 2R bi-compound tread & RFID embedded telemetry tire beads",
    capacityUnitsPerYear: 2000000,
    innovationBonus: { statKey: "lateralGrip", multiplier: 1.25 },
  },
  {
    id: "pirelli_tire",
    name: "Pirelli & C. S.p.A.",
    tier: "TIER_1_OEM_PARTNER",
    category: "TIRES_RUBBER",
    headquarters: "Milan",
    country: "Italy",
    continent: "EUROPE",
    reputationScorePct: 96.2,
    qualityDefectPpm: 24,
    costMultiplier: 1.42,
    leadTimeWeeks: 4,
    minimumOrderQuantity: 800,
    financialStabilityIndex: 0.92,
    esgSustainabilityScore: 85.0,
    technologyRdLevel: 9,
    specialtyDescription: "P-Zero Trofeo RS semi-slick compounds & Cyber Tire sensor integration",
    capacityUnitsPerYear: 1500000,
    innovationBonus: { statKey: "highSpeedStability", multiplier: 1.20 },
  },
  {
    id: "bridgestone_corp",
    name: "Bridgestone Corporation",
    tier: "TIER_1_OEM_PARTNER",
    category: "TIRES_RUBBER",
    headquarters: "Tokyo",
    country: "Japan",
    continent: "ASIA_PACIFIC",
    reputationScorePct: 95.0,
    qualityDefectPpm: 15,
    costMultiplier: 1.15,
    leadTimeWeeks: 4,
    minimumOrderQuantity: 3000,
    financialStabilityIndex: 0.96,
    esgSustainabilityScore: 90.0,
    technologyRdLevel: 8,
    specialtyDescription: "ENLITEN eco tire technology & Potenza ultra-high performance rubber",
    capacityUnitsPerYear: 3000000,
    innovationBonus: { statKey: "rollingResistanceEfficiency", multiplier: 1.30 },
  },

  // ── ECU & SEMICONDUCTORS ──
  {
    id: "bosch_gmbh",
    name: "Robert Bosch GmbH",
    tier: "TIER_1_OEM_PARTNER",
    category: "ECU_SEMICONDUCTORS",
    headquarters: "Gerlingen",
    country: "Germany",
    continent: "EUROPE",
    reputationScorePct: 98.4,
    qualityDefectPpm: 12,
    costMultiplier: 1.38,
    leadTimeWeeks: 8,
    minimumOrderQuantity: 5000,
    financialStabilityIndex: 0.99,
    esgSustainabilityScore: 92.0,
    technologyRdLevel: 10,
    specialtyDescription: "ASIL-D vehicle control units, Silicon Carbide MOSFET chips & ESP 10.0",
    capacityUnitsPerYear: 10000000,
    innovationBonus: { statKey: "tractionControlSpeed", multiplier: 1.35 },
  },
  {
    id: "nxp_semiconductors",
    name: "NXP Semiconductors N.V.",
    tier: "TIER_2_SUBSYSTEM_VENDOR",
    category: "ECU_SEMICONDUCTORS",
    headquarters: "Eindhoven",
    country: "Netherlands",
    continent: "EUROPE",
    reputationScorePct: 97.0,
    qualityDefectPpm: 8,
    costMultiplier: 1.20,
    leadTimeWeeks: 10,
    minimumOrderQuantity: 10000,
    financialStabilityIndex: 0.95,
    esgSustainabilityScore: 89.0,
    technologyRdLevel: 9,
    specialtyDescription: "S32G domain controllers & automotive Secure Element cryptographic chips",
    capacityUnitsPerYear: 25000000,
    innovationBonus: { statKey: "canBusThroughput", multiplier: 1.40 },
  },
  {
    id: "tsmc_foundry",
    name: "Taiwan Semiconductor Manufacturing Co. (TSMC)",
    tier: "TIER_3_RAW_MATERIAL_REFINER",
    category: "ECU_SEMICONDUCTORS",
    headquarters: "Hsinchu",
    country: "Taiwan",
    continent: "ASIA_PACIFIC",
    reputationScorePct: 99.8,
    qualityDefectPpm: 2,
    costMultiplier: 1.45,
    leadTimeWeeks: 14,
    minimumOrderQuantity: 50000,
    financialStabilityIndex: 0.99,
    esgSustainabilityScore: 87.0,
    technologyRdLevel: 10,
    specialtyDescription: "3nm & 5nm automotive grade FinFET silicon wafer fabrication",
    capacityUnitsPerYear: 50000000,
    innovationBonus: { statKey: "computeEfficiencyTops", multiplier: 1.50 },
  },

  // ── BATTERY CELLS & ENERGY ──
  {
    id: "catl_energy",
    name: "Contemporary Amperex Technology Co. Ltd. (CATL)",
    tier: "TIER_1_OEM_PARTNER",
    category: "BATTERY_CELLS",
    headquarters: "Ningde",
    country: "China",
    continent: "ASIA_PACIFIC",
    reputationScorePct: 95.5,
    qualityDefectPpm: 35,
    costMultiplier: 0.86,
    leadTimeWeeks: 9,
    minimumOrderQuantity: 10000,
    financialStabilityIndex: 0.93,
    esgSustainabilityScore: 80.0,
    technologyRdLevel: 9,
    specialtyDescription: "Shenxing 4C superfast charging LFP & Qilin 255 Wh/kg CTP 3.0 packs",
    capacityUnitsPerYear: 15000000,
    innovationBonus: { statKey: "packEnergyDensity", multiplier: 1.25 },
  },
  {
    id: "panasonic_battery",
    name: "Panasonic Energy Co., Ltd.",
    tier: "TIER_1_OEM_PARTNER",
    category: "BATTERY_CELLS",
    headquarters: "Kadoma",
    country: "Japan",
    continent: "ASIA_PACIFIC",
    reputationScorePct: 97.8,
    qualityDefectPpm: 12,
    costMultiplier: 1.22,
    leadTimeWeeks: 7,
    minimumOrderQuantity: 5000,
    financialStabilityIndex: 0.97,
    esgSustainabilityScore: 93.0,
    technologyRdLevel: 9,
    specialtyDescription: "4680 nickel-rich cylindrical cells with silicon-alloy anodes",
    capacityUnitsPerYear: 8000000,
    innovationBonus: { statKey: "fastChargeCrate", multiplier: 1.35 },
  },
  {
    id: "quantumscape_solid",
    name: "QuantumScape Corporation",
    tier: "TIER_2_SUBSYSTEM_VENDOR",
    category: "BATTERY_CELLS",
    headquarters: "San Jose",
    country: "USA",
    continent: "NORTH_AMERICA",
    reputationScorePct: 91.0,
    qualityDefectPpm: 50,
    costMultiplier: 2.10,
    leadTimeWeeks: 16,
    minimumOrderQuantity: 1000,
    financialStabilityIndex: 0.72,
    esgSustainabilityScore: 90.0,
    technologyRdLevel: 10,
    specialtyDescription: "Solid-state lithium-metal ceramic separator battery cells (800 Wh/L)",
    capacityUnitsPerYear: 500000,
    innovationBonus: { statKey: "dendriteSafetyMargin", multiplier: 1.60 },
  },

  // ── TURBOCHARGERS & FORCED INDUCTION ──
  {
    id: "garrett_motion",
    name: "Garrett Motion Inc.",
    tier: "TIER_1_OEM_PARTNER",
    category: "TURBO_SUPERCHARGERS",
    headquarters: "Rolle",
    country: "Switzerland",
    continent: "EUROPE",
    reputationScorePct: 98.0,
    qualityDefectPpm: 18,
    costMultiplier: 1.32,
    leadTimeWeeks: 5,
    minimumOrderQuantity: 500,
    financialStabilityIndex: 0.91,
    esgSustainabilityScore: 84.0,
    technologyRdLevel: 9,
    specialtyDescription: "E-Turbo 48V electric motor-assisted variable geometry turbochargers",
    capacityUnitsPerYear: 2000000,
    innovationBonus: { statKey: "turboSpoolLag", multiplier: 0.30 }, // 70% reduction in lag
  },
  {
    id: "borgwarner_turbo",
    name: "BorgWarner Inc.",
    tier: "TIER_1_OEM_PARTNER",
    category: "TURBO_SUPERCHARGERS",
    headquarters: "Auburn Hills",
    country: "USA",
    continent: "NORTH_AMERICA",
    reputationScorePct: 96.5,
    qualityDefectPpm: 22,
    costMultiplier: 1.18,
    leadTimeWeeks: 6,
    minimumOrderQuantity: 1500,
    financialStabilityIndex: 0.94,
    esgSustainabilityScore: 87.0,
    technologyRdLevel: 9,
    specialtyDescription: "Twin-scroll EFR titanium-aluminide turbine wheel turbochargers",
    capacityUnitsPerYear: 3500000,
    innovationBonus: { statKey: "boostEfficiency", multiplier: 1.28 },
  },

  // ── TRANSMISSIONS & ELECTRIC DRIVES ──
  {
    id: "zf_friedrichshafen",
    name: "ZF Friedrichshafen AG",
    tier: "TIER_1_OEM_PARTNER",
    category: "TRANSMISSION_GEARS",
    headquarters: "Friedrichshafen",
    country: "Germany",
    continent: "EUROPE",
    reputationScorePct: 98.7,
    qualityDefectPpm: 14,
    costMultiplier: 1.40,
    leadTimeWeeks: 8,
    minimumOrderQuantity: 1000,
    financialStabilityIndex: 0.96,
    esgSustainabilityScore: 91.0,
    technologyRdLevel: 10,
    specialtyDescription: "8HP 8-speed torque converter automatics & 2-speed EV e-Beam axles",
    capacityUnitsPerYear: 4000000,
    innovationBonus: { statKey: "shiftTimeMs", multiplier: 0.65 },
  },
  {
    id: "ricardo_plc",
    name: "Ricardo plc",
    tier: "TIER_1_OEM_PARTNER",
    category: "TRANSMISSION_GEARS",
    headquarters: "Shoreham-by-Sea",
    country: "United Kingdom",
    continent: "EUROPE",
    reputationScorePct: 97.2,
    qualityDefectPpm: 16,
    costMultiplier: 1.85,
    leadTimeWeeks: 10,
    minimumOrderQuantity: 100,
    financialStabilityIndex: 0.92,
    esgSustainabilityScore: 88.0,
    technologyRdLevel: 10,
    specialtyDescription: "Motorsport 7-speed dual-clutch sequential transaxles for hypercars",
    capacityUnitsPerYear: 10000,
    innovationBonus: { statKey: "gearTorqueCapacity", multiplier: 1.50 },
  },

  // ── SUSPENSION & DAMPERS ──
  {
    id: "ohlins_racing",
    name: "Öhlins Racing AB",
    tier: "TIER_1_OEM_PARTNER",
    category: "SUSPENSION_DAMPERS",
    headquarters: "Upplands Väsby",
    country: "Sweden",
    continent: "EUROPE",
    reputationScorePct: 99.6,
    qualityDefectPpm: 4,
    costMultiplier: 1.95,
    leadTimeWeeks: 6,
    minimumOrderQuantity: 50,
    financialStabilityIndex: 0.95,
    esgSustainabilityScore: 89.0,
    technologyRdLevel: 10,
    specialtyDescription: "TTX 36 twin-tube dampers & CES active electro-hydraulic suspension valves",
    capacityUnitsPerYear: 50000,
    innovationBonus: { statKey: "dampingResponseHz", multiplier: 1.45 },
  },
  {
    id: "bilstein_thyssenkrupp",
    name: "Thyssenkrupp Bilstein GmbH",
    tier: "TIER_1_OEM_PARTNER",
    category: "SUSPENSION_DAMPERS",
    headquarters: "Ennepetal",
    country: "Germany",
    continent: "EUROPE",
    reputationScorePct: 96.0,
    qualityDefectPpm: 25,
    costMultiplier: 1.25,
    leadTimeWeeks: 5,
    minimumOrderQuantity: 1000,
    financialStabilityIndex: 0.93,
    esgSustainabilityScore: 86.0,
    technologyRdLevel: 8,
    specialtyDescription: "DampTronic Sky active dual-valve gas-pressure monotube shocks",
    capacityUnitsPerYear: 2500000,
    innovationBonus: { statKey: "rideComfortScore", multiplier: 1.30 },
  },
];
