/**
 * MASTER CAMPUS REGISTRY - 1970 STARTING STATE & 14-UNIT PROGRESSION
 * 
 * 1970 STARTUP REALITY:
 * - 7 Core Starter Buildings: Small 1970 brick-and-mortar offices/workshops.
 *   Total starting employee cap = 108 employees!
 * - Prototype Workshop: Explicit limit of 2 vehicles max simultaneously.
 * - 7 Advanced Expansion Plots: Locked lots (Wind tunnel, Proving grounds, Crash hall, Motorsport, etc.).
 * - ZERO owned manufacturing: 100% outsourced to NPC/rival factories.
 * - Competitor-owned factories impose surcharges, delays, and capacity limits.
 */

import {
  CampusUnitDefinition,
  CampusUnitId,
  CampusUnitKey,
  ContractManufacturerPartner,
  FactoryProgressionState
} from "./campusTypes";
import { getCampusModelPath } from "./campusPlotCoordinates";

export const NPC_CONTRACT_MANUFACTURERS: ContractManufacturerPartner[] = [
  {
    id: "valmet_automotive",
    name: "Valmet Automotive Uusikaupunki",
    country: "Finland",
    specialty: "High-volume series assembly & unibody stamping",
    isCompetitorOwned: false,
    conversionCostPerUnit: 1850,
    factoryProfitMarginPct: 15,
    logisticsFeePerUnit: 450,
    competitorSurchargePct: 0,
    productionCapacityAnnual: 45000,
    defectRate: 0.024,
    reputationRequired: 15,
    leadTimeWeeks: 5,
    flexibility: "low",
    relationsScore: 70,
  },
  {
    id: "karmann_osnabruck",
    name: "Wilhelm Karmann GmbH",
    country: "Germany",
    specialty: "Coupes, convertibles & low-volume hand coachbuilding",
    isCompetitorOwned: false,
    conversionCostPerUnit: 2600,
    factoryProfitMarginPct: 22,
    logisticsFeePerUnit: 600,
    competitorSurchargePct: 0,
    productionCapacityAnnual: 22000,
    defectRate: 0.014,
    reputationRequired: 35,
    leadTimeWeeks: 7,
    flexibility: "high",
    relationsScore: 80,
  },
  {
    id: "magna_steyr",
    name: "Magna Steyr Graz",
    country: "Austria",
    specialty: "High-precision all-wheel-drive & luxury sports assembly",
    isCompetitorOwned: false,
    conversionCostPerUnit: 2950,
    factoryProfitMarginPct: 25,
    logisticsFeePerUnit: 550,
    competitorSurchargePct: 0,
    productionCapacityAnnual: 35000,
    defectRate: 0.011,
    reputationRequired: 45,
    leadTimeWeeks: 6,
    flexibility: "high",
    relationsScore: 75,
  },
  {
    id: "nordic_rival_plant",
    name: "Nordic Auto Plant (Trollhättan)",
    country: "Sweden",
    specialty: "Competitor plant selling surplus stamping line capacity",
    isCompetitorOwned: true,
    competitorBrandName: "Nordic Motors",
    conversionCostPerUnit: 2100,
    factoryProfitMarginPct: 30, // High rival profit margin
    logisticsFeePerUnit: 700,
    competitorSurchargePct: 15, // +15% rival penalty
    productionCapacityAnnual: 18000,
    defectRate: 0.021,
    reputationRequired: 20,
    leadTimeWeeks: 8, // Longer delays due to rival priority
    flexibility: "medium",
    relationsScore: 40, // Rival friction
  },
];

export const INITIAL_FACTORY_STATE: FactoryProgressionState = {
  ownershipStatus: "no_factory_outsourced",
  activeContractPartnerId: "valmet_automotive",
  factoryLevel: 0,
  factoryTier: "workshop_plant",
  landPurchased: false,
  landLocationName: "Bavarian Industrial Park (Plot 7A)",
  landPurchasePrice: 18500000,
  landAreaSqMeters: 450000,
  constructionProgressPct: 0,
  constructionMonthsRemaining: 24,
  constructionBudgetSpent: 0,
  constructionTotalBudget: 42000000,
  factoryName: "Apex Manufacturing Plant 1",
  annualCapacity: 0,
  currentOutputRate: 0,
  automationLevelPct: 15,
  toolingFlexibilityScore: 35,
  shops: {
    bodyShop: {
      name: "Body-in-White Stamping & Framing",
      level: 0,
      maxLevel: 5,
      status: "not_installed",
      efficiencyPct: 0,
      description: "Heavy hydraulic stamping presses, laser blanking lines, and geometric framing jigs.",
      keyEquipment: ["3200-Ton Hydraulic Transfer Press", "KUKA Automated Spot Welding Cells", "Optical CMM Gap Scanner"],
    },
    paintShop: {
      name: "Cathodic Electro-Deposition & Topcoat",
      level: 0,
      maxLevel: 5,
      status: "not_installed",
      efficiencyPct: 0,
      description: "Dip-tank phosphating, robotic electrostatic bell sprayers, and gas-fired baking ovens.",
      keyEquipment: ["Pre-treatment Dip Baths", "Cleanroom Air Handling Unit", "High-Rotational Bell Applicators"],
    },
    assemblyLines: {
      name: "Trim, Chassis Marrying & Final Assembly",
      level: 0,
      maxLevel: 5,
      status: "not_installed",
      efficiencyPct: 0,
      description: "Continuous ergonomic skillet conveyor, automatic powertrain decking station, and fluid filling rigs.",
      keyEquipment: ["Skillet Floor Conveyor", "Automatic Torque Guns with Data Logging", "Hydraulic Decking Table"],
    },
    qualityInspection: {
      name: "End-of-Line Audit & Monsoon Chamber",
      level: 0,
      maxLevel: 5,
      status: "not_installed",
      efficiencyPct: 0,
      description: "High-pressure water leak chamber, 4-wheel alignment laser bench, and roller dyno brake audit.",
      keyEquipment: ["Monsoon Water Leak Test Tunnel", "Beissbarth 3D Laser Alignment Bay", "Transient End-of-Line Roller Dyno"],
    },
    warehousingLogistics: {
      name: "Just-In-Time Component Staging Hall",
      level: 0,
      maxLevel: 5,
      status: "not_installed",
      efficiencyPct: 0,
      description: "Automated high-bay racking, AGV tuggers, and supplier kanban receiving docks.",
      keyEquipment: ["Narrow-Aisle Automated Stacker Cranes", "RFID Pallet Tracking Grid", "Covered Inbound Dock Shelters"],
    },
    utilitiesEnergy: {
      name: "Central Utilities & Cogeneration Power",
      level: 0,
      maxLevel: 5,
      status: "not_installed",
      efficiencyPct: 0,
      description: "High-pressure compressed air loop, industrial cooling towers, and rooftop solar microgrid.",
      keyEquipment: ["Atlas Copco Oil-Free Screw Compressors", "Industrial Chiller Bank", "1.8 MW Rooftop PV Array"],
    },
  },
};

export const UNIT_KEY_TO_ID: Record<CampusUnitKey, CampusUnitId> = {
  UNIT_01: "CENTRAL_CORPORATE_HQ",
  UNIT_02: "POWERTRAIN_EV_HQ",
  UNIT_03: "AERO_HQ",
  UNIT_04: "VEHICLE_DESIGN_HQ",
  UNIT_05: "CHASSIS_DYNAMICS_HQ",
  UNIT_06: "INTERIOR_HQ",
  UNIT_07: "TESTING_VALIDATION_HQ",
  UNIT_08: "MOTORSPORT_HQ",
  UNIT_09: "COMMERCIAL_VEHICLES_HQ",
  UNIT_10: "FACTORY",
  UNIT_11: "SUPPLIER_PROCUREMENT_HQ",
  UNIT_12: "QUALITY_RELIABILITY_HQ",
  UNIT_13: "SAFETY_HQ",
  UNIT_14: "MARKETING_SALES_HQ",
};

export const ID_TO_UNIT_KEY: Record<CampusUnitId, CampusUnitKey> = {
  CENTRAL_CORPORATE_HQ: "UNIT_01",
  POWERTRAIN_EV_HQ: "UNIT_02",
  AERO_HQ: "UNIT_03",
  VEHICLE_DESIGN_HQ: "UNIT_04",
  CHASSIS_DYNAMICS_HQ: "UNIT_05",
  INTERIOR_HQ: "UNIT_06",
  TESTING_VALIDATION_HQ: "UNIT_07",
  MOTORSPORT_HQ: "UNIT_08",
  COMMERCIAL_VEHICLES_HQ: "UNIT_09",
  FACTORY: "UNIT_10",
  SUPPLIER_PROCUREMENT_HQ: "UNIT_11",
  QUALITY_RELIABILITY_HQ: "UNIT_12",
  SAFETY_HQ: "UNIT_13",
  MARKETING_SALES_HQ: "UNIT_14",
};

export const CAMPUS_UNITS_REGISTRY: Record<CampusUnitId, CampusUnitDefinition> = {
  // ── UNIT_01: CENTRAL CORPORATE HQ (Zone C) ──
  CENTRAL_CORPORATE_HQ: {
    id: "CENTRAL_CORPORATE_HQ",
    unitNumber: 1,
    unitKey: "UNIT_01",
    name: "Central Corporate HQ",
    shortName: "Corporate HQ",
    code: "UNIT_01",
    sector: "CORPORATE_MANAGEMENT",
    sectorLabel: "Corporate / Management",
    zone: "ZONE_C",
    zoneLabel: "Zone C: Core Styling & Corporate",
    footprintClass: "$4 \\times 4$ Standard",
    startingState1970: "Active (Level 1 Root)",
    gridFootprintTiles: { width: 4, length: 4 },
    description: "Executive leadership, strategic direction, corporate finance & budgeting, legal, HR, server data, and prototype engineering bays.",
    isFactory: false,
    isStarterBuilding: true,
    tier: "office",
    level: 1,
    maxLevel: 7,
    status: "operational",
    glbModelPath: getCampusModelPath("CENTRAL_CORPORATE_HQ", 1),
    mapCoordinates: {
      x: 25,
      y: 0,
      z: -20,
      rotationY: 0,
      footprint: { width: 24, length: 24, height: 18 },
    },
    staffCapacity: 18,
    currentStaff: 14,
    monthlyMaintenanceCost: 14000,
    upgradeCost: 1800000,
    prototypeCapacity: 2, // Prototype garage (Capacity: 2 vehicles max simultaneously)
    activePrototypes: [
      { slotId: 1, vehicleName: "Apex Falcon Prototype A", activeTask: "engine_swap", progressPct: 65 },
      { slotId: 2, vehicleName: undefined, activeTask: "idle", progressPct: 0 },
    ],
    corePerks: [
      "Executive Decision Velocity & Corporate Planning",
      "Financial Accounting, Payroll & Budget Control",
      "Prototype Garage: 2 Vehicles Simultaneously",
    ],
    subDepartments: [
      {
        id: "corp_management_office",
        name: "CEO & Executive Directorate",
        type: "department",
        description: "Leadership office establishing product roadmaps, capital allocation, and company milestones.",
        level: 1,
        maxLevel: 5,
        unlocked: true,
        requiredUnitLevel: 1,
        staffAssigned: 4,
        maxStaff: 6,
        monthlyOperatingCost: 5000,
        specialEquipment: ["Typewriters & Filing Archives", "Executive Teletype Datalink"],
        perks: ["+10% Management Speed", "Controls Company Strategy"],
      },
      {
        id: "corp_finance_budget",
        name: "Finance, Accounting & Budget Control",
        type: "department",
        description: "Manages company ledger, payroll, monthly cash flow, and audits outsourced factory invoices.",
        level: 1,
        maxLevel: 5,
        unlocked: true,
        requiredUnitLevel: 1,
        staffAssigned: 5,
        maxStaff: 8,
        monthlyOperatingCost: 4500,
        specialEquipment: ["Mechanical Adding Machines & Paper Ledgers"],
        perks: ["Prevents payroll disputes", "Monitors Monthly Income & Expenses"],
      },
      {
        id: "corp_prototype_garage",
        name: "Prototype Engineering Garage (2 Bays)",
        type: "workshop",
        description: "Two hydraulic vehicle post lifts for hand-building experimental engineering prototypes (not a production factory!).",
        level: 1,
        maxLevel: 5,
        unlocked: true,
        requiredUnitLevel: 1,
        staffAssigned: 3,
        maxStaff: 4,
        monthlyOperatingCost: 3500,
        specialEquipment: ["2x 2-Post Vehicle Lifts", "Snap-on Tool Chests & Torque Wrenches"],
        perks: ["Assembles prototypes before mass manufacturing", "Enables test engine swaps"],
      },
      {
        id: "corp_planning_admin",
        name: "Strategy & Administration Records",
        type: "department",
        description: "Maintains official vehicle patents, commercial filings, and competitor monitoring ledgers.",
        level: 1,
        maxLevel: 4,
        unlocked: true,
        requiredUnitLevel: 1,
        staffAssigned: 2,
        maxStaff: 4,
        monthlyOperatingCost: 2000,
        specialEquipment: ["Secure Vault Records"],
        perks: ["-5% Corporate Administrative Errors"],
      },
    ],
  },

  // ── UNIT_02: POWERTRAIN & EV HQ (Zone B) ──
  POWERTRAIN_EV_HQ: {
    id: "POWERTRAIN_EV_HQ",
    unitNumber: 2,
    unitKey: "UNIT_02",
    name: "Powertrain & EV HQ",
    shortName: "Powertrain HQ",
    code: "UNIT_02",
    sector: "ENGINEERING_RND",
    sectorLabel: "Engineering / Product Development",
    zone: "ZONE_B",
    zoneLabel: "Zone B: Engineering & Validation",
    footprintClass: "$6 \\times 6$ Industrial",
    startingState1970: "Active (Analog Dynos)",
    gridFootprintTiles: { width: 6, length: 6 },
    description: "ICE engines, transmissions, cooling, exhaust/emissions, analog water-brake dynos, and future hybrid/EV battery labs.",
    isFactory: false,
    isStarterBuilding: true,
    tier: "office",
    level: 1,
    maxLevel: 5,
    status: "operational",
    glbModelPath: getCampusModelPath("POWERTRAIN_EV_HQ", 1),
    mapCoordinates: {
      x: -75,
      y: 0,
      z: -20,
      rotationY: 0,
      footprint: { width: 36, length: 36, height: 16 },
    },
    staffCapacity: 20,
    currentStaff: 16,
    monthlyMaintenanceCost: 17500,
    upgradeCost: 2200000,
    corePerks: [
      "First-Generation ICE Engine Design",
      "Manual Drafting & Slide-Rule Calculations",
      "Engine Carburetor & Dyno Test Bench",
    ],
    subDepartments: [
      {
        id: "pw_engine_department",
        name: "Engine Engineering Department",
        type: "department",
        description: "Drafting tables and thermodynamic calculations for engine blocks, cylinder heads, and crankshafts.",
        level: 1,
        maxLevel: 5,
        unlocked: true,
        requiredUnitLevel: 1,
        staffAssigned: 8,
        maxStaff: 12,
        monthlyOperatingCost: 8000,
        specialEquipment: ["Drafting Tables & Precision Calipers", "Mechanical Tensile Tester"],
        perks: ["+10% Engine Thermal Efficiency"],
      },
      {
        id: "pw_transmission_drivetrain",
        name: "Transmission & Drivetrain Department",
        type: "department",
        description: "Calculates gear ratios, clutch friction tolerances, and driveshaft rotational balance.",
        level: 1,
        maxLevel: 5,
        unlocked: true,
        requiredUnitLevel: 1,
        staffAssigned: 4,
        maxStaff: 8,
        monthlyOperatingCost: 5000,
        specialEquipment: ["Gearbox Tooth Contact Rig"],
        perks: ["Optimizes Drivetrain Power Transfer"],
      },
      {
        id: "pw_engine_dyno_cell",
        name: "Engine Dyno & Test Cells",
        type: "lab",
        description: "Monitors prototype engine brake horsepower, torque curves, and water/oil temperature telemetry.",
        level: 1,
        maxLevel: 4,
        unlocked: true,
        requiredUnitLevel: 1,
        staffAssigned: 4,
        maxStaff: 7,
        monthlyOperatingCost: 4500,
        specialEquipment: ["Water-Brake Engine Dynamometer"],
        perks: ["Accurate HP and Torque Output Curves"],
      },
    ],
  },

  // ── UNIT_03: AERO HQ (Zone D) ──
  AERO_HQ: {
    id: "AERO_HQ",
    unitNumber: 3,
    unitKey: "UNIT_03",
    name: "Aero HQ",
    shortName: "Aero Plot",
    code: "UNIT_03",
    sector: "ENGINEERING_RND",
    sectorLabel: "Engineering / Product Development",
    zone: "ZONE_D",
    zoneLabel: "Zone D: Special Operations & Track Perimeter",
    footprintClass: "$6 \\times 8$ Complex",
    startingState1970: "Locked (Tech Unlock)",
    gridFootprintTiles: { width: 6, length: 8 },
    description: "Shared technology/facility base for road-car aerodynamics, motorsport aerodynamics, CFD clusters, and wind tunnel complex.",
    isFactory: false,
    isStarterBuilding: false,
    tier: "office",
    level: 0,
    maxLevel: 5,
    status: "locked", // LOCKED AT 1970 START
    constructionUnlockCost: 3800000,
    glbModelPath: getCampusModelPath("AERO_HQ", 0, true),
    mapCoordinates: {
      x: -75,
      y: 0,
      z: 95,
      rotationY: 0,
      footprint: { width: 36, length: 48, height: 18 },
    },
    staffCapacity: 0,
    currentStaff: 0,
    monthlyMaintenanceCost: 0,
    upgradeCost: 4100000,
    sharedWithUnitId: "MOTORSPORT_HQ",
    sharedRelationshipNote: "Shared technology/facility base with Motorsport HQ once constructed.",
    corePerks: [
      "Requires $3.8M investment to construct",
      "Unlocks Rolling-Road Wind Tunnel",
      "Unlocks Active Aerodynamics & Cooling Aero",
    ],
    subDepartments: [
      {
        id: "aero_wind_tunnel_facility",
        name: "Subsonic Wind Tunnel Complex",
        type: "facility",
        description: "Closed-loop wind tunnel measuring downforce and drag coefficients.",
        level: 1,
        maxLevel: 4,
        unlocked: false,
        requiredUnitLevel: 1,
        staffAssigned: 0,
        maxStaff: 25,
        monthlyOperatingCost: 35000,
        specialEquipment: ["Wind Tunnel Air Turbine"],
        perks: ["+25% Aero Accuracy"],
      },
    ],
  },

  // ── UNIT_04: VEHICLE DESIGN HQ (Zone C) ──
  VEHICLE_DESIGN_HQ: {
    id: "VEHICLE_DESIGN_HQ",
    unitNumber: 4,
    unitKey: "UNIT_04",
    name: "Vehicle Design HQ",
    shortName: "Vehicle Design",
    code: "UNIT_04",
    sector: "ENGINEERING_RND",
    sectorLabel: "Engineering / Product Development",
    zone: "ZONE_C",
    zoneLabel: "Zone C: Core Styling & Corporate",
    footprintClass: "$6 \\times 6$ Studio",
    startingState1970: "Active (Drafting/Clay)",
    gridFootprintTiles: { width: 6, length: 6 },
    description: "Exterior design, body styling bays, clay studio, CMF, VR review, surface development, and colour/trim.",
    isFactory: false,
    isStarterBuilding: true,
    tier: "office",
    level: 1,
    maxLevel: 5,
    status: "operational",
    glbModelPath: getCampusModelPath("VEHICLE_DESIGN_HQ", 1),
    mapCoordinates: {
      x: 75,
      y: 0,
      z: -20,
      rotationY: 0,
      footprint: { width: 36, length: 36, height: 15 },
    },
    staffCapacity: 15,
    currentStaff: 11,
    monthlyMaintenanceCost: 12000,
    upgradeCost: 1900000,
    corePerks: [
      "Custom Body Styling & Silhouettes",
      "Clay Modeling Studio & Proportions Review",
      "Surface Curvature & Highlight Lines",
    ],
    subDepartments: [
      {
        id: "des_styling_sketch_studio",
        name: "Exterior Styling & Concept Sketching",
        type: "department",
        description: "Hand-drawn rendering boards exploring vehicle shoulder lines, greenhouses, and front grilles.",
        level: 1,
        maxLevel: 5,
        unlocked: true,
        requiredUnitLevel: 1,
        staffAssigned: 5,
        maxStaff: 7,
        monthlyOperatingCost: 5500,
        specialEquipment: ["Artist Easels & Airbrush Stations"],
        perks: ["+12% Styling Appeal Score"],
      },
      {
        id: "des_clay_modeling_room",
        name: "1:4 Scale Clay Modeling Studio",
        type: "workshop",
        description: "Sculpts physical clay models to verify proportions and surface reflections.",
        level: 1,
        maxLevel: 4,
        unlocked: true,
        requiredUnitLevel: 1,
        staffAssigned: 4,
        maxStaff: 5,
        monthlyOperatingCost: 4000,
        specialEquipment: ["Clay Sculpting Armature Rigs"],
        perks: ["Refines surface highlight curvature"],
      },
      {
        id: "des_prototype_display_area",
        name: "Design Review & Trim Presentation Area",
        type: "facility",
        description: "Indoor viewing space with floodlights for executive styling and color sign-offs.",
        level: 1,
        maxLevel: 4,
        unlocked: true,
        requiredUnitLevel: 1,
        staffAssigned: 2,
        maxStaff: 3,
        monthlyOperatingCost: 2500,
        specialEquipment: ["Spotlight Presentation Turntable"],
        perks: ["Enables Design Approvals"],
      },
    ],
  },

  // ── UNIT_05: CHASSIS & DYNAMICS HQ (Zone B) ──
  CHASSIS_DYNAMICS_HQ: {
    id: "CHASSIS_DYNAMICS_HQ",
    unitNumber: 5,
    unitKey: "UNIT_05",
    name: "Chassis & Dynamics HQ",
    shortName: "Chassis & Dynamics",
    code: "UNIT_05",
    sector: "ENGINEERING_RND",
    sectorLabel: "Engineering / Product Development",
    zone: "ZONE_B",
    zoneLabel: "Zone B: Engineering & Validation",
    footprintClass: "$4 \\times 6$ Standard",
    startingState1970: "Active (Rig Testing)",
    gridFootprintTiles: { width: 4, length: 6 },
    description: "Suspension, steering, brakes, wheels/tyres, 7-post shaker rig, DIL simulation, weight distribution, and ride/handling.",
    isFactory: false,
    isStarterBuilding: true,
    tier: "office",
    level: 1,
    maxLevel: 5,
    status: "operational",
    glbModelPath: getCampusModelPath("CHASSIS_DYNAMICS_HQ", 1),
    mapCoordinates: {
      x: -75,
      y: 0,
      z: 25,
      rotationY: 0,
      footprint: { width: 24, length: 36, height: 14 },
    },
    staffCapacity: 12,
    currentStaff: 9,
    monthlyMaintenanceCost: 13000,
    upgradeCost: 1800000,
    corePerks: [
      "Suspension Hardpoint Geometry & Spring Rates",
      "Steering Rack & Ackermann Angle Optimization",
      "Hydraulic Brake Sizing & Weight Distribution",
    ],
    subDepartments: [
      {
        id: "chassis_suspension_dept",
        name: "Suspension & Kinematics Department",
        type: "department",
        description: "Designs double-wishbones, MacPherson struts, leaf springs, and damper curves.",
        level: 1,
        maxLevel: 5,
        unlocked: true,
        requiredUnitLevel: 1,
        staffAssigned: 4,
        maxStaff: 6,
        monthlyOperatingCost: 4500,
        specialEquipment: ["Suspension Kinematic Geometry Rig"],
        perks: ["+15% Handling Stability"],
      },
      {
        id: "chassis_steering_brakes",
        name: "Steering & Braking Systems",
        type: "department",
        description: "Engineers master cylinders, disc/drum brake calipers, and steering ratios.",
        level: 1,
        maxLevel: 5,
        unlocked: true,
        requiredUnitLevel: 1,
        staffAssigned: 3,
        maxStaff: 5,
        monthlyOperatingCost: 4000,
        specialEquipment: ["Brake Inertia Dynamometer"],
        perks: ["-10% 100-0 km/h Braking Distance"],
      },
      {
        id: "chassis_dynamics_tuning",
        name: "Ride, Handling & Weight Distribution Lab",
        type: "lab",
        description: "Calculates roll centers, center-of-mass offsets, and corner weight balancing.",
        level: 1,
        maxLevel: 4,
        unlocked: true,
        requiredUnitLevel: 1,
        staffAssigned: 2,
        maxStaff: 4,
        monthlyOperatingCost: 3500,
        specialEquipment: ["4-Corner Wheel Scales & CG Pendulum"],
        perks: ["Optimizes 50:50 Weight Distribution"],
      },
    ],
  },

  // ── UNIT_06: INTERIOR HQ (Zone B) ──
  INTERIOR_HQ: {
    id: "INTERIOR_HQ",
    unitNumber: 6,
    unitKey: "UNIT_06",
    name: "Interior HQ",
    shortName: "Interior HQ",
    code: "UNIT_06",
    sector: "ENGINEERING_RND",
    sectorLabel: "Engineering / Product Development",
    zone: "ZONE_B",
    zoneLabel: "Zone B: Engineering & Validation",
    footprintClass: "$4 \\times 4$ Studio",
    startingState1970: "Active (Mockup Bucks)",
    gridFootprintTiles: { width: 4, length: 4 },
    description: "Cabin NVH, ergonomic mockup bucks, climate control, cockpit architecture, dashboard, and luxury seating features.",
    isFactory: false,
    isStarterBuilding: true,
    tier: "office",
    level: 1,
    maxLevel: 5,
    status: "operational",
    glbModelPath: getCampusModelPath("INTERIOR_HQ", 1),
    mapCoordinates: {
      x: -35,
      y: 0,
      z: -15,
      rotationY: 0,
      footprint: { width: 24, length: 24, height: 13 },
    },
    staffCapacity: 10,
    currentStaff: 7,
    monthlyMaintenanceCost: 9500,
    upgradeCost: 1600000,
    corePerks: [
      "Dashboard & Instrument Cluster Layout",
      "Ergonomic Seat Cushioning & H-Point Clearance",
      "Cabin Ventilation & Upholstery Craftsmanship",
    ],
    subDepartments: [
      {
        id: "int_cockpit_dashboard",
        name: "Dashboard & Instrument Cluster Department",
        type: "department",
        description: "Designs driver-oriented instrument binacles, analog dials, switchgear, and gloveboxes.",
        level: 1,
        maxLevel: 5,
        unlocked: true,
        requiredUnitLevel: 1,
        staffAssigned: 3,
        maxStaff: 5,
        monthlyOperatingCost: 3500,
        specialEquipment: ["Ergonomic Reach Fixture"],
        perks: ["+10% Driver Ergonomics Score"],
      },
      {
        id: "int_seating_ergonomics",
        name: "Seats & Ergonomics Workshop",
        type: "workshop",
        description: "Crafts anatomical seat foam contours, spring supports, and lumbar adjustments.",
        level: 1,
        maxLevel: 5,
        unlocked: true,
        requiredUnitLevel: 1,
        staffAssigned: 2,
        maxStaff: 4,
        monthlyOperatingCost: 3000,
        specialEquipment: ["SAE H-Point Manikin Dummy"],
        perks: ["Ensures anatomical seat comfort and spinal support"],
      },
      {
        id: "int_materials_hvac",
        name: "Cabin Materials, Leather & HVAC Comfort",
        type: "department",
        description: "Tests upholstery fabrics, vinyls, real wood veneers, and heater ventilation blowers.",
        level: 1,
        maxLevel: 4,
        unlocked: true,
        requiredUnitLevel: 1,
        staffAssigned: 2,
        maxStaff: 3,
        monthlyOperatingCost: 2500,
        specialEquipment: ["Fabric Abrasion Martindale Tester"],
        perks: ["+15% Interior Luxury Perception"],
      },
    ],
  },

  // ── UNIT_07: TESTING & VALIDATION HQ (Zone B) ──
  TESTING_VALIDATION_HQ: {
    id: "TESTING_VALIDATION_HQ",
    unitNumber: 7,
    unitKey: "UNIT_07",
    name: "Testing & Validation HQ",
    shortName: "Testing Ground",
    code: "UNIT_07",
    sector: "ENGINEERING_RND",
    sectorLabel: "Engineering / Product Development",
    zone: "ZONE_B",
    zoneLabel: "Zone B: Engineering & Validation",
    footprintClass: "$8 \\times 8$ Field Rig",
    startingState1970: "Active (Skid Pad only)",
    gridFootprintTiles: { width: 8, length: 8 },
    description: "Weather cells, hemi-anechoic NVH chamber, durability rigs, and initial circular asphalt skid pad.",
    isFactory: false,
    isStarterBuilding: true,
    tier: "office",
    level: 1,
    maxLevel: 5,
    status: "operational",
    glbModelPath: getCampusModelPath("TESTING_VALIDATION_HQ", 1),
    mapCoordinates: {
      x: -35,
      y: 0,
      z: 35,
      rotationY: 0,
      footprint: { width: 48, length: 48, height: 10 },
    },
    staffCapacity: 6,
    currentStaff: 4,
    monthlyMaintenanceCost: 8000,
    upgradeCost: 2800000,
    corePerks: [
      "Asphalt Circular Skid Pad & Slalom Cones",
      "Lateral G-Force Vehicle Calibration",
      "Pre-Production Durability Screening",
    ],
    subDepartments: [
      {
        id: "test_skid_pad",
        name: "Asphalt Circular Skid Pad",
        type: "proving_ground",
        description: "Low-friction circular asphalt skid pad with telemetry pylons for lateral acceleration evaluation.",
        level: 1,
        maxLevel: 5,
        unlocked: true,
        requiredUnitLevel: 1,
        staffAssigned: 4,
        maxStaff: 6,
        monthlyOperatingCost: 3500,
        specialEquipment: ["Concentric Radius Markings", "Lateral G-Sensor Pylons"],
        perks: ["Enables Cornering G-Force Calibration"],
      },
    ],
  },

  // ── UNIT_08: MOTORSPORT HQ (Zone D) ──
  MOTORSPORT_HQ: {
    id: "MOTORSPORT_HQ",
    unitNumber: 8,
    unitKey: "UNIT_08",
    name: "Motorsport HQ",
    shortName: "Motorsport HQ",
    code: "UNIT_08",
    sector: "MOTORSPORT_COMMERCIAL",
    sectorLabel: "Motorsport & Commercial",
    zone: "ZONE_D",
    zoneLabel: "Zone D: Special Operations & Track Perimeter",
    footprintClass: "$12 \\times 16$ Perimeter",
    startingState1970: "Locked (Reputation Gate)",
    gridFootprintTiles: { width: 12, length: 16 },
    description: "Race garages, dedicated perimeter circuit track, telemetry telemetry command center, and Grand Prix team.",
    isFactory: false,
    isStarterBuilding: false,
    isMotorsportTrackCollider: true, // Hugs southern boundary of cyan baseplate
    tier: "office",
    level: 0,
    maxLevel: 5,
    status: "locked", // LOCKED AT 1970 START
    constructionUnlockCost: 4500000,
    glbModelPath: getCampusModelPath("MOTORSPORT_HQ", 0, true),
    mapCoordinates: {
      x: 0,
      y: 0,
      z: 155,
      rotationY: 0,
      footprint: { width: 72, length: 96, height: 16 },
    },
    staffCapacity: 0,
    currentStaff: 0,
    monthlyMaintenanceCost: 0,
    upgradeCost: 4800000,
    sharedWithUnitId: "AERO_HQ",
    sharedRelationshipNote: "Shares wind tunnel and CFD with Aero HQ.",
    corePerks: [
      "Requires $4.5M and high reputation to unlock",
      "Includes Dedicated Southern Perimeter Circuit Loop",
      "Enables Grand Prix & Sports Car entries",
    ],
    subDepartments: [
      {
        id: "ms_race_workshop",
        name: "Race Team Preparation Garage",
        type: "workshop",
        description: "High-spec race car setup flat pads and scales.",
        level: 1,
        maxLevel: 4,
        unlocked: false,
        requiredUnitLevel: 1,
        staffAssigned: 0,
        maxStaff: 25,
        monthlyOperatingCost: 30000,
        specialEquipment: ["Air Jacks & Race Scales"],
        perks: ["Enables motorsport participation"],
      },
    ],
  },

  // ── UNIT_09: COMMERCIAL VEHICLES HQ (Zone D) ──
  COMMERCIAL_VEHICLES_HQ: {
    id: "COMMERCIAL_VEHICLES_HQ",
    unitNumber: 9,
    unitKey: "UNIT_09",
    name: "Commercial Vehicles HQ",
    shortName: "Commercial Vehicles",
    code: "UNIT_09",
    sector: "MOTORSPORT_COMMERCIAL",
    sectorLabel: "Motorsport & Commercial",
    zone: "ZONE_D",
    zoneLabel: "Zone D: Special Operations & Track Perimeter",
    footprintClass: "$8 \\times 8$ Heavy Bay",
    startingState1970: "Locked (Commercial License)",
    gridFootprintTiles: { width: 8, length: 8 },
    description: "Heavy chassis bays, fleet powertrains, payload testing, buses, and commercial transport engineering.",
    isFactory: false,
    isStarterBuilding: false,
    tier: "office",
    level: 0,
    maxLevel: 5,
    status: "locked", // LOCKED AT 1970 START
    constructionUnlockCost: 3200000,
    glbModelPath: getCampusModelPath("COMMERCIAL_VEHICLES_HQ", 0, true),
    mapCoordinates: {
      x: -10,
      y: 0,
      z: 100,
      rotationY: 0,
      footprint: { width: 48, length: 48, height: 18 },
    },
    staffCapacity: 0,
    currentStaff: 0,
    monthlyMaintenanceCost: 0,
    upgradeCost: 2500000,
    corePerks: [
      "Requires $3.2M and Commercial License to unlock",
      "Unlocks Heavy-Duty Ladder Chassis Builds",
    ],
    subDepartments: [],
  },

  // ── UNIT_10: PRODUCTION FACTORY (Zone A - Outsource Boundary) ──
  FACTORY: {
    id: "FACTORY",
    unitNumber: 10,
    unitKey: "UNIT_10",
    name: "Production Factory",
    shortName: "Production Plant",
    code: "UNIT_10",
    sector: "MANUFACTURING_SUPPLY_CHAIN",
    sectorLabel: "Logistics & Production",
    zone: "ZONE_A",
    zoneLabel: "Zone A: Logistics & Production",
    footprintClass: "$16 \\times 20$ Industrial",
    startingState1970: "Unowned / Outsourced",
    gridFootprintTiles: { width: 16, length: 20 },
    description: "Full production factory: Stamping, paint shop, body-in-white, final assembly, and logistics docks. Unowned in 1970.",
    isFactory: true,
    isStarterBuilding: false,
    isOutsourceBoundary: true, // Sits across unpaved perimeter boundary line
    tier: "office",
    level: 0,
    maxLevel: 5,
    status: "outsourced", // EXACT INVARIANT: Player owns NO factory in 1970!
    glbModelPath: getCampusModelPath("FACTORY", 0, true),
    mapCoordinates: {
      x: 40,
      y: 0,
      z: -130,
      rotationY: 0,
      footprint: { width: 96, length: 120, height: 22 },
    },
    staffCapacity: 0,
    currentStaff: 0,
    monthlyMaintenanceCost: 3500, // Site holding / administration
    upgradeCost: 18500000, // Land purchase cost
    corePerks: [
      "Player starts with NO FACTORY (100% Outsourced)",
      "Requires acquiring unowned land parcel ($18.5M) to break ground",
      "Upgradable from Workshop Plant (5,000/yr) to Advanced Campus (200,000+/yr)",
    ],
    subDepartments: [],
  },

  // ── UNIT_11: SUPPLIER & PROCUREMENT HQ (Zone A) ──
  SUPPLIER_PROCUREMENT_HQ: {
    id: "SUPPLIER_PROCUREMENT_HQ",
    unitNumber: 11,
    unitKey: "UNIT_11",
    name: "Supplier & Procurement HQ",
    shortName: "Supplier & Procurement",
    code: "UNIT_11",
    sector: "MANUFACTURING_SUPPLY_CHAIN",
    sectorLabel: "Logistics & Production",
    zone: "ZONE_A",
    zoneLabel: "Zone A: Logistics & Production",
    footprintClass: "$6 \\times 6$ Warehouse",
    startingState1970: "Active (Manual Depot)",
    gridFootprintTiles: { width: 6, length: 6 },
    description: "Vendor bids, intake logistics, raw-material contracts (steel, aluminium, rubber, glass, tyres), and high-bay JIT depot.",
    isFactory: false,
    isStarterBuilding: true,
    tier: "office",
    level: 1,
    maxLevel: 5,
    status: "operational",
    glbModelPath: getCampusModelPath("SUPPLIER_PROCUREMENT_HQ", 1),
    mapCoordinates: {
      x: -55,
      y: 0,
      z: -75,
      rotationY: 0,
      footprint: { width: 36, length: 36, height: 15 },
    },
    staffCapacity: 8,
    currentStaff: 6,
    monthlyMaintenanceCost: 8500,
    upgradeCost: 1500000,
    corePerks: [
      "Manages Raw Material Deliveries (Steel, Aluminium, Rubber)",
      "Negotiates Outsourced Rival Factory Capacity",
      "Manual Intake Depot & Staging for Components",
    ],
    subDepartments: [
      {
        id: "proc_supplier_contracts",
        name: "Supplier & Factory Contracting Desk",
        type: "department",
        description: "Manages contracts with Tier-1 component makers and rival assembly plants.",
        level: 1,
        maxLevel: 5,
        unlocked: true,
        requiredUnitLevel: 1,
        staffAssigned: 3,
        maxStaff: 4,
        monthlyOperatingCost: 4000,
        specialEquipment: ["Supplier Directory & Telex Network"],
        perks: ["Secures outsourced factory assembly slots"],
      },
      {
        id: "proc_materials_logistics",
        name: "Raw Materials Procurement",
        type: "department",
        description: "Orders sheet steel coils, window glass, and rubber compounds for vehicle builds.",
        level: 1,
        maxLevel: 4,
        unlocked: true,
        requiredUnitLevel: 1,
        staffAssigned: 3,
        maxStaff: 4,
        monthlyOperatingCost: 3500,
        specialEquipment: ["Commodity Price Indices"],
        perks: ["Ensures raw materials arrive at outsourced plants on time"],
      },
    ],
  },

  // ── UNIT_12: QUALITY & RELIABILITY HQ (Zone C) ──
  QUALITY_RELIABILITY_HQ: {
    id: "QUALITY_RELIABILITY_HQ",
    unitNumber: 12,
    unitKey: "UNIT_12",
    name: "Quality & Reliability HQ",
    shortName: "Quality & Kaizen",
    code: "UNIT_12",
    sector: "MANUFACTURING_SUPPLY_CHAIN",
    sectorLabel: "Core Styling & Corporate",
    zone: "ZONE_C",
    zoneLabel: "Zone C: Core Styling & Corporate",
    footprintClass: "$4 \\times 4$ Standard",
    startingState1970: "Active (Manual CMM)",
    gridFootprintTiles: { width: 4, length: 4 },
    description: "Metrology, stress testing, manual CMM inspection arms, Kaizen lab, and warranty failure tracking.",
    isFactory: false,
    isStarterBuilding: true,
    tier: "office",
    level: 1,
    maxLevel: 5,
    status: "operational",
    glbModelPath: getCampusModelPath("QUALITY_RELIABILITY_HQ", 1),
    mapCoordinates: {
      x: 25,
      y: 0,
      z: 25,
      rotationY: 0,
      footprint: { width: 24, length: 24, height: 14 },
    },
    staffCapacity: 6,
    currentStaff: 4,
    monthlyMaintenanceCost: 7500,
    upgradeCost: 1900000,
    corePerks: [
      "Manual CMM Metrology & Dial Indicators",
      "Reduces Component Tolerance Errors",
      "Tracks Pre-Delivery Defect Trends",
    ],
    subDepartments: [
      {
        id: "qa_manual_cmm",
        name: "Manual CMM & Metrology Bench",
        type: "lab",
        description: "Granite surface table and dial indicator arms for checking sample part tolerances.",
        level: 1,
        maxLevel: 5,
        unlocked: true,
        requiredUnitLevel: 1,
        staffAssigned: 4,
        maxStaff: 6,
        monthlyOperatingCost: 3000,
        specialEquipment: ["Granite Surface Table", "Manual CMM Dial Arm"],
        perks: ["Reduces initial component fitment defects"],
      },
    ],
  },

  // ── UNIT_13: SAFETY HQ (Zone D - Linear Collider) ──
  SAFETY_HQ: {
    id: "SAFETY_HQ",
    unitNumber: 13,
    unitKey: "UNIT_13",
    name: "Safety HQ",
    shortName: "Safety HQ",
    code: "UNIT_13",
    sector: "MANUFACTURING_SUPPLY_CHAIN",
    sectorLabel: "Special Operations & Track Perimeter",
    zone: "ZONE_D",
    zoneLabel: "Zone D: Special Operations & Track Perimeter",
    footprintClass: "$6 \\times 12$ Linear Run",
    startingState1970: "Locked (Safety Mandate)",
    gridFootprintTiles: { width: 6, length: 12 },
    description: "Crash barrier propulsion hall, sled track, ATD dummy calibration lab, and uninterrupted 150m linear acceleration rail run.",
    isFactory: false,
    isStarterBuilding: false,
    isLinearCollider: true, // 150m rail run parallel to perimeter
    tier: "office",
    level: 0,
    maxLevel: 5,
    status: "locked", // LOCKED AT 1970 START
    constructionUnlockCost: 3400000,
    glbModelPath: getCampusModelPath("SAFETY_HQ", 0, true),
    mapCoordinates: {
      x: 65,
      y: 0,
      z: 95,
      rotationY: 0,
      footprint: { width: 36, length: 72, height: 14 },
    },
    staffCapacity: 0,
    currentStaff: 0,
    monthlyMaintenanceCost: 0,
    upgradeCost: 2800000,
    corePerks: [
      "Requires $3.4M and Safety Mandate to build",
      "Contains 150m Linear Crash Acceleration Corridor",
      "Unlocks 5-Star NCAP Crash Engineering",
    ],
    subDepartments: [],
  },

  // ── UNIT_14: MARKETING & SALES HQ (Zone C) ──
  MARKETING_SALES_HQ: {
    id: "MARKETING_SALES_HQ",
    unitNumber: 14,
    unitKey: "UNIT_14",
    name: "Marketing & Sales HQ",
    shortName: "Marketing & Sales",
    code: "UNIT_14",
    sector: "COMMERCIAL_MARKET",
    sectorLabel: "Core Styling & Corporate",
    zone: "ZONE_C",
    zoneLabel: "Zone C: Core Styling & Corporate",
    footprintClass: "$6 \\times 6$ Pavilion",
    startingState1970: "Active (Dealer Liaison)",
    gridFootprintTiles: { width: 6, length: 6 },
    description: "Studios, customer showrooms, reveal rotunda, dealer liaison desk, advertising campaigns, and product launches.",
    isFactory: false,
    isStarterBuilding: true,
    tier: "office",
    level: 1,
    maxLevel: 5,
    status: "operational",
    glbModelPath: getCampusModelPath("MARKETING_SALES_HQ", 1),
    mapCoordinates: {
      x: 75,
      y: 0,
      z: 25,
      rotationY: 0,
      footprint: { width: 36, length: 36, height: 16 },
    },
    staffCapacity: 13,
    currentStaff: 10,
    monthlyMaintenanceCost: 11500,
    upgradeCost: 1750000,
    corePerks: [
      "Vehicle Sales & Dealer Distribution",
      "Print Advertising & Showroom Brochures",
      "Customer Support & Order Inquiries",
    ],
    subDepartments: [
      {
        id: "mkt_dealer_sales_office",
        name: "Dealer Sales & Franchising",
        type: "department",
        description: "Coordinates vehicle shipments to regional dealer showrooms.",
        level: 1,
        maxLevel: 5,
        unlocked: true,
        requiredUnitLevel: 1,
        staffAssigned: 5,
        maxStaff: 7,
        monthlyOperatingCost: 5500,
        specialEquipment: ["Dealer Territory Map Board"],
        perks: ["Enables selling cars to the public"],
      },
      {
        id: "mkt_advertising_promotions",
        name: "Print Advertising & Press Relations",
        type: "department",
        description: "Produces glossy magazine advertisements and press releases for motoring magazines.",
        level: 1,
        maxLevel: 4,
        unlocked: true,
        requiredUnitLevel: 1,
        staffAssigned: 4,
        maxStaff: 5,
        monthlyOperatingCost: 4000,
        specialEquipment: ["Graphic Layout Lightbox"],
        perks: ["+15% Brand Awareness"],
      },
      {
        id: "mkt_customer_relations",
        name: "Customer Support & Inquiries",
        type: "department",
        description: "Responds to owner letters, service inquiries, and spare parts requests.",
        level: 1,
        maxLevel: 4,
        unlocked: true,
        requiredUnitLevel: 1,
        staffAssigned: 2,
        maxStaff: 3,
        monthlyOperatingCost: 2000,
        specialEquipment: ["Customer Service Telephone Bank"],
        perks: ["Builds early customer trust"],
      },
    ],
  },
};
