/**
 * AUTO TYCOON CAMPUS HQ - SUB-DEPARTMENT TREE (PHASES 6–20)
 * 
 * Exhaustive sub-department definition tree across all 14 campus units
 * for all 8 building progression levels (Level 0 Empty Plot to Level 7 Hypermodern Campus).
 */

import { CampusUnitId, CampusSubDepartment, DepartmentType } from "./campusTypes";

export interface SubDepartmentTreeEntry {
  id: string;
  parentUnitId: CampusUnitId;
  name: string;
  type: DepartmentType;
  description: string;
  requiredBuildingLevel: number;
  staffMin: number;
  staffMax: number;
  monthlyOperatingCost: number;
  specialEquipment: string[];
  perks: string[];
}

export const SUB_DEPARTMENT_DEFINITIONS: Record<CampusUnitId, SubDepartmentTreeEntry[]> = {
  // ── PHASE 7: UNIT_01 CENTRAL CORPORATE HQ ──
  CENTRAL_CORPORATE_HQ: [
    // L1
    {
      id: "corp_ceo_office",
      parentUnitId: "CENTRAL_CORPORATE_HQ",
      name: "CEO Executive Directorate",
      type: "department",
      description: "Leadership suite establishing product roadmaps, capital allocation, and executive approvals.",
      requiredBuildingLevel: 1,
      staffMin: 2,
      staffMax: 4,
      monthlyOperatingCost: 6500,
      specialEquipment: ["Executive Desk", "Secure Teletype Link", "Safes & Ledgers"],
      perks: ["+15% Corporate Decision Velocity", "Unlocks Company Strategy Setting"],
    },
    {
      id: "corp_finance_desk",
      parentUnitId: "CENTRAL_CORPORATE_HQ",
      name: "Finance & Accounting Desk",
      type: "department",
      description: "Audits outsourced factory invoices, oversees accounts payable, and maintains general ledgers.",
      requiredBuildingLevel: 1,
      staffMin: 3,
      staffMax: 6,
      monthlyOperatingCost: 4500,
      specialEquipment: ["Mechanical Adding Machines", "Auditing Ledger Tables"],
      perks: ["Accurate Monthly Cash Flow Tracking", "-5% Financial Accounting Discrepancies"],
    },
    {
      id: "corp_admin_pool",
      parentUnitId: "CENTRAL_CORPORATE_HQ",
      name: "General Administration Pool",
      type: "department",
      description: "Clerical typing pool, intra-campus courier routing, and internal communication dispatch.",
      requiredBuildingLevel: 1,
      staffMin: 4,
      staffMax: 8,
      monthlyOperatingCost: 3500,
      specialEquipment: ["Typewriters", "Carbon Copy Desks", "Pneumatic Tube Dispatch"],
      perks: ["Standard Administrative Baseline", "Reduces Cross-Unit Friction"],
    },
    {
      id: "corp_records_vault",
      parentUnitId: "CENTRAL_CORPORATE_HQ",
      name: "Corporate Records & Archives",
      type: "department",
      description: "Fireproof repository storing vehicle patents, chassis blueprints, and board minutes.",
      requiredBuildingLevel: 1,
      staffMin: 1,
      staffMax: 3,
      monthlyOperatingCost: 2000,
      specialEquipment: ["Steel Archive Shelving", "Class-A Fireproof Safe"],
      perks: ["Prevents Intellectual Property Disputes", "Preserves Historic Engineering Drawings"],
    },
    {
      id: "corp_prototype_garage",
      parentUnitId: "CENTRAL_CORPORATE_HQ",
      name: "Executive Prototype Engineering Garage",
      type: "workshop",
      description: "Two hydraulic vehicle post lifts for hand-building experimental engineering prototypes (not a production line!).",
      requiredBuildingLevel: 1,
      staffMin: 3,
      staffMax: 6,
      monthlyOperatingCost: 5500,
      specialEquipment: ["2x Heavy-Duty 2-Post Lifts", "Snap-on Tool Chests", "MIG Welder"],
      perks: ["Allows Assembly of 2 Working Prototypes Simultaneously", "Direct Hand Fabrication"],
    },
    // L2
    {
      id: "corp_legal_counsel",
      parentUnitId: "CENTRAL_CORPORATE_HQ",
      name: "In-House Legal & Patents Counsel",
      type: "department",
      description: "Patent filings, supplier contractual disputes, trademark defenses, and licensing agreements.",
      requiredBuildingLevel: 2,
      staffMin: 2,
      staffMax: 5,
      monthlyOperatingCost: 7500,
      specialEquipment: ["Law Library", "Notarization Desk"],
      perks: ["-20% Supplier Contract Dispute Delays", "+10% Patent Defense Strength"],
    },
    {
      id: "corp_hr_department",
      parentUnitId: "CENTRAL_CORPORATE_HQ",
      name: "Human Resources & Talent Acquisition",
      type: "department",
      description: "Recruits senior engineers, oversees campus compensation tiers, and monitors employee morale.",
      requiredBuildingLevel: 2,
      staffMin: 3,
      staffMax: 6,
      monthlyOperatingCost: 4000,
      specialEquipment: ["Personnel Records Cabinets", "Interview Suites"],
      perks: ["+15% Senior Engineering Recruitment Pool", "-10% Employee Turnover"],
    },
    {
      id: "corp_board_room",
      parentUnitId: "CENTRAL_CORPORATE_HQ",
      name: "Expanded Boardroom & Investor Suite",
      type: "facility",
      description: "Formal mahogany boardroom for hosting external banking syndicates and major institutional shareholders.",
      requiredBuildingLevel: 2,
      staffMin: 1,
      staffMax: 3,
      monthlyOperatingCost: 3000,
      specialEquipment: ["Mahogany Conference Table", "Slide Projector Array"],
      perks: ["+10% Bank Loan Credit Limit", "+5% Investor Confidence"],
    },
    // L3
    {
      id: "corp_server_room",
      parentUnitId: "CENTRAL_CORPORATE_HQ",
      name: "Mainframe & Data Processing Center",
      type: "facility",
      description: "Raised-floor air-conditioned room housing magnetic tape drives and company business computing mainframes.",
      requiredBuildingLevel: 3,
      staffMin: 2,
      staffMax: 5,
      monthlyOperatingCost: 9000,
      specialEquipment: ["IBM Mainframe Cabinets", "Air Handling Chiller", "Magnetic Tape Drives"],
      perks: ["Real-Time Daily Inventory Auditing", "+12% Financial Forecasting Accuracy"],
    },
    {
      id: "corp_strategy_lab",
      parentUnitId: "CENTRAL_CORPORATE_HQ",
      name: "Corporate Strategy & Market Forecasting Lab",
      type: "lab",
      description: "Analyzes competitor product lifecycles, demographic shifts, and fuel price volatility projections.",
      requiredBuildingLevel: 3,
      staffMin: 3,
      staffMax: 6,
      monthlyOperatingCost: 8000,
      specialEquipment: ["Statistical Plotters", "Econometric Forecasting Terminal"],
      perks: ["Early Warning of Market Segment Shifts", "+15% Product Planning Accuracy"],
    },
    // L4
    {
      id: "corp_advanced_projects",
      parentUnitId: "CENTRAL_CORPORATE_HQ",
      name: "Skunkworks Advanced Projects Division",
      type: "department",
      description: "Top-secret advanced development unit tasked with revolutionary vehicle architectures.",
      requiredBuildingLevel: 4,
      staffMin: 6,
      staffMax: 12,
      monthlyOperatingCost: 18000,
      specialEquipment: ["Secure Access Biometric Airlock", "Dedicated Prototype Fabrication Cell"],
      perks: ["Enables Breakthrough Technology Concepts", "+25% Radical Innovation Chance"],
    },
    // L5
    {
      id: "corp_global_ops",
      parentUnitId: "CENTRAL_CORPORATE_HQ",
      name: "Global Operations Command Center",
      type: "facility",
      description: "24/7 mission control monitoring worldwide shipping routes, regional sales, and subsidiary operations.",
      requiredBuildingLevel: 5,
      staffMin: 4,
      staffMax: 8,
      monthlyOperatingCost: 22000,
      specialEquipment: ["Multi-Screen Video Wall", "Satellite Telemetry Downlink"],
      perks: ["Unlocks Multi-Continental Production Scheduling", "-15% Global Logistics Bottlenecks"],
    },
    // L6
    {
      id: "corp_ai_decision_support",
      parentUnitId: "CENTRAL_CORPORATE_HQ",
      name: "AI Decision Support & Digital Twin Command",
      type: "lab",
      description: "Neural network models simulating enterprise cash flow, supply shocks, and pricing elasticity.",
      requiredBuildingLevel: 6,
      staffMin: 4,
      staffMax: 8,
      monthlyOperatingCost: 35000,
      specialEquipment: ["GPU Deep Learning Cluster", "Neural Simulation Nodes"],
      perks: ["Automated Dynamic Pricing Optimization", "Zero-Latency Anomaly Detection"],
    },
    // L7
    {
      id: "corp_quantum_strategy",
      parentUnitId: "CENTRAL_CORPORATE_HQ",
      name: "Quantum Computing Strategy Wing",
      type: "lab",
      description: "Quantum annealing systems solving global supply chain routing and combinatorial chemistry optimizations.",
      requiredBuildingLevel: 7,
      staffMin: 3,
      staffMax: 6,
      monthlyOperatingCost: 65000,
      specialEquipment: ["Cryogenic Dilution Refrigerator", "Superconducting Quantum Processor"],
      perks: ["Instantaneous Optimal Logistics Pathing", "+50% Corporate Strategic Agility"],
    },
  ],

  // ── PHASE 8: UNIT_02 POWERTRAIN & EV HQ ──
  POWERTRAIN_EV_HQ: [
    // L1
    {
      id: "pwr_engine_drafting",
      parentUnitId: "POWERTRAIN_EV_HQ",
      name: "Engine Block Drafting & Geometry Office",
      type: "department",
      description: "Manual drafting boards laying out cylinder bores, combustion chambers, valvetrain, and crank journals.",
      requiredBuildingLevel: 1,
      staffMin: 4,
      staffMax: 8,
      monthlyOperatingCost: 5000,
      specialEquipment: ["Drafting Tables", "Beam Compasses", "Section View Light Tables"],
      perks: ["Base Engine Design Velocity", "Calculates Compression & Displacement"],
    },
    {
      id: "pwr_carb_dyno",
      parentUnitId: "POWERTRAIN_EV_HQ",
      name: "Analog Water-Brake Dynamometer Cell",
      type: "lab",
      description: "Single-cell water brake absorbing engine torque to measure horsepower and brake specific fuel consumption.",
      requiredBuildingLevel: 1,
      staffMin: 3,
      staffMax: 6,
      monthlyOperatingCost: 6500,
      specialEquipment: ["Heenan & Froude Water Brake", "Mercury Manometer Array", "Exhaust Scavenge Duct"],
      perks: ["Accurate Horsepower & Torque Curves", "Validates Carburetor Jetting"],
    },
    {
      id: "pwr_gearbox_desk",
      parentUnitId: "POWERTRAIN_EV_HQ",
      name: "Transmission & Gear Calculations Desk",
      type: "department",
      description: "Designs manual gearbox ratios, synchronizer cones, planetary gearsets, and differential bevel gears.",
      requiredBuildingLevel: 1,
      staffMin: 3,
      staffMax: 6,
      monthlyOperatingCost: 4200,
      specialEquipment: ["Gear Tooth Calculators", "Hardness Testing Anvils"],
      perks: ["Optimizes Transmission Gear Ratios", "Reduces Gear Whine & Wear"],
    },
    // L2
    {
      id: "pwr_machining_shop",
      parentUnitId: "POWERTRAIN_EV_HQ",
      name: "Precision Engine Machining Workshop",
      type: "workshop",
      description: "Boring mills, cylinder hones, surface grinders, and valve seating cutters for rapid test part creation.",
      requiredBuildingLevel: 2,
      staffMin: 4,
      staffMax: 8,
      monthlyOperatingCost: 8000,
      specialEquipment: ["Cylinder Boring Mill", "Sunnen Hone", "Bridgeport Milling Machines"],
      perks: ["-25% Prototype Cylinder Head Fabrication Time", "+5% Engine Tolerances"],
    },
    // L3
    {
      id: "pwr_multi_dyno",
      parentUnitId: "POWERTRAIN_EV_HQ",
      name: "Automated Multi-Cell Dyno Bank",
      type: "lab",
      description: "Triple-cell transient eddy-current dynos with automated endurance throttle actuators and data loggers.",
      requiredBuildingLevel: 3,
      staffMin: 5,
      staffMax: 10,
      monthlyOperatingCost: 16000,
      specialEquipment: ["Eddy-Current Dynamometers", "High-Speed Data Loggers", "Emissions Gas Analyzers"],
      perks: ["Allows Continuous 24/7 Engine Endurance Runs", "-30% Engine Development Cycle"],
    },
    // L4
    {
      id: "pwr_hybrid_battery_cell",
      parentUnitId: "POWERTRAIN_EV_HQ",
      name: "Hybrid Integration & High-Voltage Battery Lab",
      type: "lab",
      description: "Thermal cycling chambers for battery modules, high-voltage bus bar testing, and motor-inverter coupling.",
      requiredBuildingLevel: 4,
      staffMin: 5,
      staffMax: 10,
      monthlyOperatingCost: 24000,
      specialEquipment: ["HV Battery Cycler", "Climatic Battery Chamber", "Inverter Dyno"],
      perks: ["Enables Hybrid & Plug-in Powertrains", "+15% Battery Thermal Efficiency"],
    },
    // L5
    {
      id: "pwr_ev_motor_lab",
      parentUnitId: "POWERTRAIN_EV_HQ",
      name: "Axial-Flux & Hairpin EV Motor Winding Lab",
      type: "lab",
      description: "Automated hairpin stator winding, permanent magnet rotor balancing, and high-RPM back-EMF measurement.",
      requiredBuildingLevel: 5,
      staffMin: 5,
      staffMax: 10,
      monthlyOperatingCost: 32000,
      specialEquipment: ["Laser Wire Stripper", "Dynamic Rotor Balancer", "25,000 RPM Motor Dyno"],
      perks: ["+20% EV Motor Power Density", "High-Efficiency Inverter Pairing"],
    },
    // L6
    {
      id: "pwr_fuel_cell_cleanroom",
      parentUnitId: "POWERTRAIN_EV_HQ",
      name: "Hydrogen Fuel Cell & SiC Inverter Cleanroom",
      type: "lab",
      description: "Class 10,000 cleanroom for assembling proton-exchange membrane stacks and silicon-carbide MOSFETs.",
      requiredBuildingLevel: 6,
      staffMin: 4,
      staffMax: 8,
      monthlyOperatingCost: 45000,
      specialEquipment: ["Class 10k Cleanroom Enclosure", "Hydrogen Sniffer Leak Detector", "Wire Bonder"],
      perks: ["Unlocks Hydrogen Fuel Cell Powertrains", "99.2% Inverter Electrical Efficiency"],
    },
    // L7
    {
      id: "pwr_quantum_solid_state",
      parentUnitId: "POWERTRAIN_EV_HQ",
      name: "Quantum Battery & Fusion Tech Center",
      type: "lab",
      description: "Lithium-metal solid-state electrolytes with atomic-layer deposition and AI powertrain neural controllers.",
      requiredBuildingLevel: 7,
      staffMin: 3,
      staffMax: 6,
      monthlyOperatingCost: 75000,
      specialEquipment: ["Atomic Layer Deposition Reactor", "Cryo-TEM Microscope", "Quantum Co-Simulator"],
      perks: ["+70% Battery Energy Density (800 Wh/kg)", "10-Minute 10-80% Ultra-Fast Charging"],
    },
  ],

  // ── PHASE 9: UNIT_03 AERO HQ ──
  AERO_HQ: [
    {
      id: "aero_scale_tunnel",
      parentUnitId: "AERO_HQ",
      name: "1:4 Scale Boundary Layer Wind Tunnel",
      type: "facility",
      description: "Wooden contraction cone and axial fan pulling air across quarter-scale clay models to measure drag force.",
      requiredBuildingLevel: 1,
      staffMin: 3,
      staffMax: 6,
      monthlyOperatingCost: 7000,
      specialEquipment: ["Axial Fan Duct", "Scale Balance Balance-Beam Scale", "Kerosene Smoke Wand"],
      perks: ["Calculates Basic Vehicle Drag Coefficient (Cd)", "Identifies High-Pressure Separation Zones"],
    },
    {
      id: "aero_pressure_tap",
      parentUnitId: "AERO_HQ",
      name: "Multichannel Pressure Tap & Visualization Lab",
      type: "lab",
      description: "Installs hundreds of miniature hypodermic pressure taps on surface models wired to digital manometer banks.",
      requiredBuildingLevel: 2,
      staffMin: 3,
      staffMax: 6,
      monthlyOperatingCost: 9500,
      specialEquipment: ["64-Channel Scanivalve Pressure Transducer", "Surface Wool Tuft Cameras"],
      perks: ["+15% Lift/Downforce Measurement Accuracy", "Detects Underbody Flow Choking"],
    },
    {
      id: "aero_full_tunnel",
      parentUnitId: "AERO_HQ",
      name: "Full-Scale Subsonic Wind Tunnel (250 km/h)",
      type: "facility",
      description: "Full-scale closed-circuit Göttingen-type tunnel with continuous moving ground plane belt and 6-component balance.",
      requiredBuildingLevel: 3,
      staffMin: 6,
      staffMax: 12,
      monthlyOperatingCost: 26000,
      specialEquipment: ["5-Meter Diameter Carbon Fan", "Moving Ground Belt", "6-Axis Force Balance"],
      perks: ["100% Real-World Aerodynamic Correlation", "Measures High-Speed Downforce & Pitch Sensitivity"],
    },
    {
      id: "aero_cfd_supercomputer",
      parentUnitId: "AERO_HQ",
      name: "Transient Aerodynamic CFD Cluster",
      type: "lab",
      description: "Massively parallel cluster running Detached Eddy Simulation (DES) for aerodynamic wake vortices.",
      requiredBuildingLevel: 4,
      staffMin: 4,
      staffMax: 8,
      monthlyOperatingCost: 32000,
      specialEquipment: ["2,048-Core HPC Blade Rack", "Infiniband Switch Matrix"],
      perks: ["Virtual Aerodynamic Shape Iteration in Hours", "-40% Physical Tunnel Testing Dependency"],
    },
    {
      id: "aero_quantum_solver",
      parentUnitId: "AERO_HQ",
      name: "Quantum Lattice-Boltzmann Aero Optimization",
      type: "lab",
      description: "Direct simulation of turbulent micro-boundary layers and active plasma actuator flow control.",
      requiredBuildingLevel: 7,
      staffMin: 3,
      staffMax: 6,
      monthlyOperatingCost: 65000,
      specialEquipment: ["Quantum Flow Solver Interface", "Plasma Actuator Test Rig"],
      perks: ["Ultra-Low Drag Hypercar Shapes (Cd < 0.18)", "Active Boundary Layer Boundary Suction"],
    },
  ],

  // ── PHASE 10: UNIT_04 VEHICLE DESIGN HQ ──
  VEHICLE_DESIGN_HQ: [
    {
      id: "dsgn_exterior_sketch",
      parentUnitId: "VEHICLE_DESIGN_HQ",
      name: "Exterior Styling Studio & Drafting Bays",
      type: "department",
      description: "North-facing angled skylights illuminate traditional drafting tables for concept sketching and tape drawings.",
      requiredBuildingLevel: 1,
      staffMin: 4,
      staffMax: 8,
      monthlyOperatingCost: 5500,
      specialEquipment: ["Drafting Tables", "Prismacolor Marker Sets", "Full-Size Wall Chalkboards"],
      perks: ["Generates Vehicle Concept Silhouettes", "Sets Brand Styling Direction"],
    },
    {
      id: "dsgn_clay_bays",
      parentUnitId: "VEHICLE_DESIGN_HQ",
      name: "1:4 & 1:1 Scale Clay Sculpting Studio",
      type: "workshop",
      description: "Heated styling clay ovens, steel armatures, and bridge-mounted coordinate scribers for master sculptors.",
      requiredBuildingLevel: 1,
      staffMin: 4,
      staffMax: 8,
      monthlyOperatingCost: 7000,
      specialEquipment: ["Clay Warming Ovens", "Cast Iron Surface Plate", "Curvature Sweeps"],
      perks: ["Transforms 2D Drawings into Tangible 3D Proportions", "+10% Exterior Aesthetic Appeal"],
    },
    {
      id: "dsgn_cmf_library",
      parentUnitId: "VEHICLE_DESIGN_HQ",
      name: "Colour, Materials & Finish (CMF) Library",
      type: "department",
      description: "Curates exterior paint formulations, interior textile swatches, genuine leathers, and metal trims.",
      requiredBuildingLevel: 2,
      staffMin: 2,
      staffMax: 5,
      monthlyOperatingCost: 4500,
      specialEquipment: ["Macbeth Light Booth", "Spectrophotometer", "Textile Swatch Bins"],
      perks: ["Enables Exclusive Paint & Leather Options", "+15% Trim Level Profit Margins"],
    },
    {
      id: "dsgn_cas_surface",
      parentUnitId: "VEHICLE_DESIGN_HQ",
      name: "Computer-Aided Styling (CAS) & Class-A Surfacing",
      type: "lab",
      description: "Translates digitised clay scans into mathematical Bezier G2/G3 curvature-continuous surfaces for tooling.",
      requiredBuildingLevel: 3,
      staffMin: 4,
      staffMax: 8,
      monthlyOperatingCost: 14000,
      specialEquipment: ["Optical Surface Digitizer", "Alias AutoStudio Workstations"],
      perks: ["Flawless Reflection Highlights", "-35% Stamping Die Redesign Rework"],
    },
    {
      id: "dsgn_vr_cave",
      parentUnitId: "VEHICLE_DESIGN_HQ",
      name: "Virtual Reality Ergonomic CAVE & Design Theater",
      type: "facility",
      description: "Full-scale projection room and high-fidelity headsets allowing designers and executives to walk around 1:1 concepts.",
      requiredBuildingLevel: 4,
      staffMin: 3,
      staffMax: 6,
      monthlyOperatingCost: 19000,
      specialEquipment: ["Barco Multi-Projector CAVE", "Optical Tracking Cameras", "Haptic Seating Buck"],
      perks: ["Eliminates Need for Multiple Physical Show Mocks", "Accelerates Executive Sign-Off by 50%"],
    },
    {
      id: "dsgn_ai_generative",
      parentUnitId: "VEHICLE_DESIGN_HQ",
      name: "Generative AI Aesthetics & Holographic Stage",
      type: "lab",
      description: "Diffusion algorithms exploring millions of aerodynamic form factors and light-guided holographic review tables.",
      requiredBuildingLevel: 6,
      staffMin: 3,
      staffMax: 6,
      monthlyOperatingCost: 38000,
      specialEquipment: ["Holographic Volumetric Display", "Aesthetic Neural Weight Server"],
      perks: ["Instant Variant Evolution", "+25% Consumer Emotional Desirability"],
    },
  ],

  // ── PHASE 11: UNIT_05 CHASSIS & DYNAMICS HQ ──
  CHASSIS_DYNAMICS_HQ: [
    {
      id: "chs_suspension_drafting",
      parentUnitId: "CHASSIS_DYNAMICS_HQ",
      name: "Suspension Kinematics & Geometry Room",
      type: "department",
      description: "Calculates roll centers, camber gain curves, anti-dive/anti-squat, and steering Ackerman angles.",
      requiredBuildingLevel: 1,
      staffMin: 3,
      staffMax: 6,
      monthlyOperatingCost: 4800,
      specialEquipment: ["Kinematics Calculation Desk", "Suspension Travel Mocks"],
      perks: ["Base Ride Comfort & Handling Balance", "Optimizes Cornering Stability"],
    },
    {
      id: "chs_spring_damper_bench",
      parentUnitId: "CHASSIS_DYNAMICS_HQ",
      name: "Hydraulic Damper & Spring Dynamometer Bench",
      type: "lab",
      description: "Strokes shock absorbers at variable velocities to plot force-velocity curves and test valve shims.",
      requiredBuildingLevel: 1,
      staffMin: 2,
      staffMax: 5,
      monthlyOperatingCost: 5200,
      specialEquipment: ["Roehrig Damper Dyno", "Spring Rate Scale"],
      perks: ["Fine-Tunes Rebound & Compression Damping", "-15% Harshness Feedback"],
    },
    {
      id: "chs_kc_rig",
      parentUnitId: "CHASSIS_DYNAMICS_HQ",
      name: "Kinematics & Compliance (K&C) Rig",
      type: "facility",
      description: "Applies precision multi-axis loads to vehicle wheel hubs to measure suspension bushing deflections.",
      requiredBuildingLevel: 2,
      staffMin: 4,
      staffMax: 7,
      monthlyOperatingCost: 11000,
      specialEquipment: ["Anthony Best Dynamics K&C Rig", "Laser Deflection Sensors"],
      perks: ["Eliminates Unwanted Bump-Steer", "+20% High-Speed Tracking Precision"],
    },
    {
      id: "chs_7post_shaker",
      parentUnitId: "CHASSIS_DYNAMICS_HQ",
      name: "7-Post Hydraulic Shaker Rig",
      type: "facility",
      description: "Four road input hydraulic actuators plus three aerodynamic load simulators for testing body heave, pitch, and roll.",
      requiredBuildingLevel: 3,
      staffMin: 4,
      staffMax: 8,
      monthlyOperatingCost: 18000,
      specialEquipment: ["7x High-Flow Hydraulic Actuators", "Seismic Isolation Concrete Mass"],
      perks: ["Optimizes Tire Contact Patch Under High Downforce", "-35% Track Setup Dial-In Time"],
    },
    {
      id: "chs_dil_simulator",
      parentUnitId: "CHASSIS_DYNAMICS_HQ",
      name: "Driver-in-the-Loop (DIL) Hexapod Motion Simulator",
      type: "facility",
      description: "Full vehicle cockpit mounted atop 6-DOF hydraulic hexapod actuators with 270° wraparound collimated projection.",
      requiredBuildingLevel: 4,
      staffMin: 5,
      staffMax: 10,
      monthlyOperatingCost: 28000,
      specialEquipment: ["Moog 6-DOF Motion Hexapod", "Wraparound Collimated Screen", "Force Feedback Steering Rack"],
      perks: ["Human Subjective Steering Feel Tuning in Virtual Space", "Accelerates Suspension Calibration by 60%"],
    },
  ],

  // ── PHASE 12: UNIT_06 INTERIOR & HMI HQ ──
  INTERIOR_HQ: [
    {
      id: "int_dash_layout",
      parentUnitId: "INTERIOR_HQ",
      name: "Instrument Panel & Dashboard Ergonomics Desk",
      type: "department",
      description: "Designs sightlines to gauge needles, switchgear reach distances, and HVAC vent discharge paths.",
      requiredBuildingLevel: 1,
      staffMin: 3,
      staffMax: 6,
      monthlyOperatingCost: 4200,
      specialEquipment: ["SAE 2D Seating Buck", "Sightline Gauges"],
      perks: ["Prevents Steering Wheel Gauge Obscuration", "Optimizes Primary Switch Reach"],
    },
    {
      id: "int_seating_foam",
      parentUnitId: "INTERIOR_HQ",
      name: "Seat Foam, Spring & Upholstery Workshop",
      type: "workshop",
      description: "Dual-density polyurethane pouring molds, spring suspension webs, and leather stitching benches.",
      requiredBuildingLevel: 1,
      staffMin: 3,
      staffMax: 6,
      monthlyOperatingCost: 4600,
      specialEquipment: ["Polyurethane Mixing Tank", "Industrial Sewing Machines", "Pressure Contour Mat"],
      perks: ["Long-Distance Ischial Support", "Reduces Driver Spinal Fatigue"],
    },
    {
      id: "int_climate_chamber",
      parentUnitId: "INTERIOR_HQ",
      name: "HVAC Thermal Comfort Environmental Chamber",
      type: "lab",
      description: "Full cabin climatic simulation testing heater defrost rates in sub-zero cold and AC pulldown under solar lamps.",
      requiredBuildingLevel: 3,
      staffMin: 4,
      staffMax: 7,
      monthlyOperatingCost: 15000,
      specialEquipment: ["Refrigeration Chiller Array", "Infrared Solar Radiation Lamps"],
      perks: ["Rapid Cabin Temperature Regulation", "Windshield Defogging Compliance"],
    },
    {
      id: "int_digital_cockpit",
      parentUnitId: "INTERIOR_HQ",
      name: "Curved OLED Display & HMI UX Lab",
      type: "lab",
      description: "Software testbenches for automotive graphics chipsets, capacitive touchscreens, and heads-up displays.",
      requiredBuildingLevel: 4,
      staffMin: 4,
      staffMax: 8,
      monthlyOperatingCost: 22000,
      specialEquipment: ["Optical Display Calibration Cameras", "Haptic Actuator Testers"],
      perks: ["Fluid 60 FPS Infotainment Interfaces", "Sub-50ms Haptic Touch Response"],
    },
    {
      id: "int_nvh_chamber",
      parentUnitId: "INTERIOR_HQ",
      name: "Hemi-Anechoic Acoustic NVH Chamber",
      type: "facility",
      description: "Wedge-lined soundproof room with quiet 4-wheel chassis dynamometer to pinpoint interior rattles and wind hiss.",
      requiredBuildingLevel: 5,
      staffMin: 4,
      staffMax: 8,
      monthlyOperatingCost: 31000,
      specialEquipment: ["Acoustic Foam Wedges", "Acoustic Camera Beamforming Array", "Ultra-Quiet Chassis Dyno"],
      perks: ["Whisper-Quiet Cabin Luxury Index", "Eliminates High-Frequency Gear Whine"],
    },
  ],

  // ── PHASE 13: UNIT_07 TESTING & VALIDATION HQ ──
  TESTING_VALIDATION_HQ: [
    {
      id: "test_torture_track",
      parentUnitId: "TESTING_VALIDATION_HQ",
      name: "Belgian Block & Rough Road Torture Track",
      type: "proving_ground",
      description: "Cobblestone pavers, sinusoidal washboard ruts, and pothole strips stressing body structures.",
      requiredBuildingLevel: 1,
      staffMin: 3,
      staffMax: 6,
      monthlyOperatingCost: 6500,
      specialEquipment: ["Telemetry Transponders", "Wheel Hub Accelerometer Kits"],
      perks: ["Identifies Structural Weaknesses Early", "Ensures Unibody Fatigue Rigidity"],
    },
    {
      id: "test_salt_chamber",
      parentUnitId: "TESTING_VALIDATION_HQ",
      name: "Salt-Fog Corrosion & Humidity Chamber",
      type: "chamber",
      description: "Sprays 5% sodium chloride mist under 95% humidity at 35°C to test rust resistance of sheetmetal and fasteners.",
      requiredBuildingLevel: 2,
      staffMin: 3,
      staffMax: 5,
      monthlyOperatingCost: 8500,
      specialEquipment: ["Cyclic Corrosion Spray Cabinet", "Chemical Titration Station"],
      perks: ["Guarantees 10-Year Anti-Perforation Warranty", "Improves Galvanized Steel Bonding"],
    },
    {
      id: "test_high_speed_oval",
      parentUnitId: "TESTING_VALIDATION_HQ",
      name: "3.8km High-Speed Banked Oval Track",
      type: "proving_ground",
      description: "Steep parabolic concrete banking allowing continuous 280+ km/h sustained endurance runs without steering input.",
      requiredBuildingLevel: 3,
      staffMin: 5,
      staffMax: 10,
      monthlyOperatingCost: 24000,
      specialEquipment: ["Electronic Timing Lights", "Tire Infrared Thermal Scanner"],
      perks: ["Verifies Sustained Top Speed & Cooling Stability", "Accelerates Powertrain Lifespan Testing"],
    },
    {
      id: "test_climatic_altitude",
      parentUnitId: "TESTING_VALIDATION_HQ",
      name: "Extreme Altitude & Thermal Chamber (-40°C to +55°C)",
      type: "chamber",
      description: "Hermetically sealed chamber varying barometric pressure to simulate 4,500m mountain passes and desert heat.",
      requiredBuildingLevel: 4,
      staffMin: 4,
      staffMax: 8,
      monthlyOperatingCost: 32000,
      specialEquipment: ["Vacuum Decompression Pumps", "Cryogenic Nitrogen Injection"],
      perks: ["Prevents High-Altitude Fuel Starvation", "Validates Arctic Cold-Start Reliability"],
    },
    {
      id: "test_autonomous_loop",
      parentUnitId: "TESTING_VALIDATION_HQ",
      name: "Autonomous Driving & Sensor Fusion Loop",
      type: "proving_ground",
      description: "Simulated urban intersection with moving pedestrian dummies, GPS spoofers, and weather spray gantries.",
      requiredBuildingLevel: 5,
      staffMin: 4,
      staffMax: 8,
      monthlyOperatingCost: 40000,
      specialEquipment: ["Soft Crash Target Dummies", "RTK-GPS Base Stations", "LIDAR Ground Truth Array"],
      perks: ["Unlocks Level 3/4 ADAS Safety Certification", "Reduces Sensor Edge-Case Failure Rate"],
    },
  ],

  // ── PHASE 14: UNIT_08 MOTORSPORT HQ ──
  MOTORSPORT_HQ: [
    {
      id: "msport_race_bays",
      parentUnitId: "MOTORSPORT_HQ",
      name: "Works Racing Preparation Bays",
      type: "workshop",
      description: "Precision alignment surface plates, quick-lift jacks, air gun lines, and corner-weight scales.",
      requiredBuildingLevel: 1,
      staffMin: 4,
      staffMax: 8,
      monthlyOperatingCost: 8500,
      specialEquipment: ["Intercomp Corner Scales", "Titanium Alignment Strings", "Quick-Fill Fuel Rigs"],
      perks: ["Builds Custom Competition Vehicles", "+10% Motorsport Brand Halo"],
    },
    {
      id: "msport_autoclave",
      parentUnitId: "MOTORSPORT_HQ",
      name: "Autoclave Carbon-Fiber Composites Oven",
      type: "workshop",
      description: "Pressurized heated autoclave baking pre-preg carbon-fiber monocoques, wings, and splitters.",
      requiredBuildingLevel: 3,
      staffMin: 4,
      staffMax: 8,
      monthlyOperatingCost: 19000,
      specialEquipment: ["3-Meter Diameter Heated Autoclave", "Cleanroom Layup Table", "Ultrasonic Ply Cutter"],
      perks: ["-45% Weight for Specialized Aerodynamic Components", "High-Stiffness Monocoque Shells"],
    },
    {
      id: "msport_pit_telemetry",
      parentUnitId: "MOTORSPORT_HQ",
      name: "Telemetry Mission Control & Strategy Pit",
      type: "facility",
      description: "Direct trackside pitwall datalink recording suspension travel, tire pressures, and predictive fuel burn.",
      requiredBuildingLevel: 4,
      staffMin: 4,
      staffMax: 8,
      monthlyOperatingCost: 26000,
      specialEquipment: ["Microwave Trackside Receiver", "High-Bandwidth Radio Matrix", "Strategy Computing Rack"],
      perks: ["Real-Time Race Strategy Optimization", "+25% Track Win Probability"],
    },
    {
      id: "msport_hypercar_bay",
      parentUnitId: "MOTORSPORT_HQ",
      name: "Le Mans Hypercar & Formula 1 Engine Bay",
      type: "workshop",
      description: "Hermetic cleanroom for assembling MGU-K hybrid units, titanium inconel headers, and sequential racing gearboxes.",
      requiredBuildingLevel: 7,
      staffMin: 5,
      staffMax: 10,
      monthlyOperatingCost: 75000,
      specialEquipment: ["Cleanroom Assembly Pods", "Dyno Coupling Spindles", "Laser Sintering Additive Printer"],
      perks: ["Builds Pinnacle Halo Hypercars", "+50% Global Brand Value"],
    },
  ],

  // ── PHASE 15: UNIT_09 COMMERCIAL VEHICLES HQ ──
  COMMERCIAL_VEHICLES_HQ: [
    {
      id: "comm_heavy_drafting",
      parentUnitId: "COMMERCIAL_VEHICLES_HQ",
      name: "Heavy-Duty Ladder Frame & Axle Drafting",
      type: "department",
      description: "Engineers high-tensile channel-section steel frame rails, multi-leaf spring packs, and tandem drive axles.",
      requiredBuildingLevel: 1,
      staffMin: 3,
      staffMax: 6,
      monthlyOperatingCost: 4500,
      specialEquipment: ["Heavy Vehicle Drafting Boards", "Beam Deflection Software"],
      perks: ["Calculates Gross Vehicle Weight Ratings (GVWR)", "Designs Commercial Truck Chassis"],
    },
    {
      id: "comm_hoist_bays",
      parentUnitId: "COMMERCIAL_VEHICLES_HQ",
      name: "High-Tonnage Vehicle Hoist Bays",
      type: "workshop",
      description: "Reinforced 40-ton wireless mobile column lifts capable of lifting fully loaded commercial buses and prime movers.",
      requiredBuildingLevel: 2,
      staffMin: 4,
      staffMax: 8,
      monthlyOperatingCost: 9000,
      specialEquipment: ["4x 10-Ton Stertil-Koni Mobile Column Lifts", "Heavy Air Impact Tools"],
      perks: ["Under-Chassis Service for Large Commercial Fleets", "+15% Heavy Fleet Durability"],
    },
    {
      id: "comm_fleet_telematics",
      parentUnitId: "COMMERCIAL_VEHICLES_HQ",
      name: "Commercial Fleet Telematics & Logistics Lab",
      type: "lab",
      description: "Develops commercial fleet management telemetry, driver fatigue monitoring, and remote diagnostics.",
      requiredBuildingLevel: 3,
      staffMin: 3,
      staffMax: 6,
      monthlyOperatingCost: 14000,
      specialEquipment: ["Cellular Fleet Gateway Simulator", "CAN-Bus J1939 Decoders"],
      perks: ["Commercial Fleet Sales Attraction", "+20% Fleet Contract Appeal"],
    },
    {
      id: "comm_hydrogen_truck",
      parentUnitId: "COMMERCIAL_VEHICLES_HQ",
      name: "Heavy-Duty Fuel Cell & Mega-Watt EV Charging Lab",
      type: "lab",
      description: "700-bar hydrogen tank stress testing and 1.2-megawatt heavy vehicle charging architecture test stands.",
      requiredBuildingLevel: 5,
      staffMin: 4,
      staffMax: 8,
      monthlyOperatingCost: 35000,
      specialEquipment: ["700-bar Pressure Burst Vault", "Megawatt Liquid-Cooled Charger Stand"],
      perks: ["Zero-Emission Long-Haul Truck Architectures", "High Range Under 40-Ton Payloads"],
    },
  ],

  // ── PHASE 16: UNIT_10 FACTORY (MANUFACTURING) ──
  FACTORY: [
    {
      id: "mfg_stamping_body",
      parentUnitId: "FACTORY",
      name: "Body-in-White Stamping & Robotic Framing Shop",
      type: "assembly_shop",
      description: "Hydraulic transfer presses stamping body panels, joined by automated multi-axis spot-welding robots.",
      requiredBuildingLevel: 1,
      staffMin: 8,
      staffMax: 25,
      monthlyOperatingCost: 12000,
      specialEquipment: ["2,000-Ton Hydraulic Stamping Press", "Spot Welding Guns", "Framing Fixtures"],
      perks: ["Produces Unibody Sheetmetal Panels", "Scales with Annual Unit Volume"],
    },
    {
      id: "mfg_paint_shop",
      parentUnitId: "FACTORY",
      name: "Cathodic Electro-Deposition & Robotic Topcoat Booths",
      type: "assembly_shop",
      description: "Immersion phosphate dip tanks, primer bake ovens, and cleanroom paint bells applying primer and clearcoat.",
      requiredBuildingLevel: 1,
      staffMin: 6,
      staffMax: 20,
      monthlyOperatingCost: 15000,
      specialEquipment: ["Cathodic Dip Tank", "High-Rotational Bell Atomizers", "Gas-Fired Curing Ovens"],
      perks: ["Corrosion-Resistant Exterior Finish", "Reduces Orange Peel Defects"],
    },
    {
      id: "mfg_final_assembly",
      parentUnitId: "FACTORY",
      name: "Continuous Conveyor Final Trim & Chassis Marrying",
      type: "assembly_shop",
      description: "Skillet conveyor where cockpit harnesses, glass, engines, and suspensions are married to painted bodies.",
      requiredBuildingLevel: 1,
      staffMin: 12,
      staffMax: 40,
      monthlyOperatingCost: 20000,
      specialEquipment: ["Overhead Skillet Conveyor", "Hydraulic Powertrain Decking Table", "Torque Guns"],
      perks: ["Primary Vehicle Assembly Throughput", "Determines Annual Manufacturing Capacity"],
    },
    {
      id: "mfg_end_of_line",
      parentUnitId: "FACTORY",
      name: "End-of-Line Quality Audit & Monsoon Water Test",
      type: "assembly_shop",
      description: "Dynamic roller brake test, laser wheel alignment, headlight aim, and high-pressure monsoon water leak chamber.",
      requiredBuildingLevel: 1,
      staffMin: 5,
      staffMax: 15,
      monthlyOperatingCost: 8000,
      specialEquipment: ["Chassis Roller Test Bench", "Laser 4-Wheel Aligner", "Monsoon Water Jet Chamber"],
      perks: ["Catches Assembly Defects Before Shipment", "-50% Initial Delivery Flaws"],
    },
    {
      id: "mfg_robotics_automation",
      parentUnitId: "FACTORY",
      name: "High-Density Robotic Automation Cells",
      type: "assembly_shop",
      description: "Swarm of six-axis articulated industrial robots replacing manual handling and laser seam sealing.",
      requiredBuildingLevel: 4,
      staffMin: 10,
      staffMax: 30,
      monthlyOperatingCost: 45000,
      specialEquipment: ["KUKA 6-Axis Articulated Robots", "Vision-Guided Glue Applicators"],
      perks: ["+80% Assembly Speed", "-40% Unit Assembly Labor Cost"],
    },
    {
      id: "mfg_lights_out_ai",
      parentUnitId: "FACTORY",
      name: "Lights-Out AI Autonomous Assembly Campus",
      type: "assembly_shop",
      description: "Completely autonomous factory floor where automated guided vehicles (AGVs) and AI vision assemble vehicles without human intervention.",
      requiredBuildingLevel: 7,
      staffMin: 5,
      staffMax: 15,
      monthlyOperatingCost: 85000,
      specialEquipment: ["Omnidirectional AGV Fleet", "Quantum Quality Scanners", "Microgrid Solar Arrays"],
      perks: ["500,000+ Units/Year Capacity", "Near-Zero Assembly Defect Rate (<0.01%)"],
    },
  ],

  // ── PHASE 17: UNIT_11 SUPPLIER & PROCUREMENT HQ ──
  SUPPLIER_PROCUREMENT_HQ: [
    {
      id: "proc_purchasing_desk",
      parentUnitId: "SUPPLIER_PROCUREMENT_HQ",
      name: "Component Purchasing & Bill of Materials Office",
      type: "department",
      description: "Negotiates bulk supply contracts for steel coils, tires, glass, copper wiring, and cast engine pistons.",
      requiredBuildingLevel: 1,
      staffMin: 3,
      staffMax: 6,
      monthlyOperatingCost: 4000,
      specialEquipment: ["Teletype Price Quotation Terminal", "Contract Binders"],
      perks: ["Reduces Per-Vehicle Bill of Materials (BOM) Cost", "Controls Component Deliveries"],
    },
    {
      id: "proc_incoming_inspection",
      parentUnitId: "SUPPLIER_PROCUREMENT_HQ",
      name: "Incoming Quality & Receiving Docks",
      type: "workshop",
      description: "Receiving docks with calipers, hardness testers, and micrometer benches inspecting supplier batches.",
      requiredBuildingLevel: 1,
      staffMin: 3,
      staffMax: 6,
      monthlyOperatingCost: 4500,
      specialEquipment: ["Forklifts", "Hardness Tester", "Granite Inspection Surface Table"],
      perks: ["Rejects Substandard Tier-2 Castings", "Prevents Defective Parts Entering Production"],
    },
    {
      id: "proc_jit_logistics",
      parentUnitId: "SUPPLIER_PROCUREMENT_HQ",
      name: "Just-In-Time (JIT) Kanban Logistics Control",
      type: "department",
      description: "Synchronizes supplier deliveries directly to factory workstations, eliminating warehouse holding costs.",
      requiredBuildingLevel: 3,
      staffMin: 4,
      staffMax: 8,
      monthlyOperatingCost: 12000,
      specialEquipment: ["Kanban Electronic Tracking Boards", "Direct EDI Datalink"],
      perks: ["-30% Warehouse Inventory Holding Overhead", "Eliminates Component Stockouts"],
    },
    {
      id: "proc_blockchain_twin",
      parentUnitId: "SUPPLIER_PROCUREMENT_HQ",
      name: "Predictive Shortage AI & Supply Chain Digital Twin",
      type: "lab",
      description: "Monitors global raw material pricing, geopolitical freight disruptions, and autonomous supplier re-routing.",
      requiredBuildingLevel: 6,
      staffMin: 3,
      staffMax: 6,
      monthlyOperatingCost: 32000,
      specialEquipment: ["Supply Chain Digital Twin Server", "Predictive Logistics Cluster"],
      perks: ["Zero-Delay Supply Shock Immunity", "Secures Raw Materials at Lowest Historical Cost"],
    },
  ],

  // ── PHASE 18: UNIT_12 QUALITY & RELIABILITY HQ ──
  QUALITY_RELIABILITY_HQ: [
    {
      id: "qa_inspector_desk",
      parentUnitId: "QUALITY_RELIABILITY_HQ",
      name: "Master Quality Inspector Office & Defect Logs",
      type: "department",
      description: "Maintains official scrap ledgers, dealer warranty claim logs, and dimensional tolerance standards.",
      requiredBuildingLevel: 1,
      staffMin: 3,
      staffMax: 6,
      monthlyOperatingCost: 4200,
      specialEquipment: ["Statistical Control Charts", "Defect Log Books"],
      perks: ["Pinpoints Repeat Assembly Flaws", "Reduces Initial Warranty Claims"],
    },
    {
      id: "qa_metrology_cmm",
      parentUnitId: "QUALITY_RELIABILITY_HQ",
      name: "Precision Metrology & 3D CMM Measurement Lab",
      type: "lab",
      description: "Temperature-controlled cleanroom housing granite-bed coordinate measuring machines (CMM) inspecting tolerances to microns.",
      requiredBuildingLevel: 2,
      staffMin: 3,
      staffMax: 6,
      monthlyOperatingCost: 11000,
      specialEquipment: ["Granite Surface Plate", "Zeiss 3D Coordinate Measuring Machine", "Optical Laser Gauge"],
      perks: ["Sub-Millimeter Panel Gap Tolerances (3.5mm Flushness)", "Zero Frame Twist"],
    },
    {
      id: "qa_accelerated_life",
      parentUnitId: "QUALITY_RELIABILITY_HQ",
      name: "Accelerated Life Testing & Thermal Shock Lab",
      type: "lab",
      description: "Rapidly cycles door latches 100,000 times, vibrates electronics at extreme frequencies, and cooks plastic trims.",
      requiredBuildingLevel: 3,
      staffMin: 4,
      staffMax: 7,
      monthlyOperatingCost: 17000,
      specialEquipment: ["Pneumatic Actuator Cycling Rigs", "Thermal Shock Chamber", "Electrodynamic Shaker"],
      perks: ["Validates 150,000-Mile Component Durability", "-40% Long-Term Warranty Costs"],
    },
    {
      id: "qa_zero_defect_ai",
      parentUnitId: "QUALITY_RELIABILITY_HQ",
      name: "Zero-Defect AI Computer Vision & Telemetry Center",
      type: "lab",
      description: "Processes connected car fleet sensor telemetry to identify emerging failures before customer breakdown.",
      requiredBuildingLevel: 6,
      staffMin: 3,
      staffMax: 6,
      monthlyOperatingCost: 35000,
      specialEquipment: ["Fleet Telemetry Big Data Cluster", "Defect Prediction Neural Models"],
      perks: ["Industry #1 J.D. Power Initial Quality Rating", "Over-The-Air Predictive Maintenance"],
    },
  ],

  // ── PHASE 19: UNIT_13 SAFETY & CRASH HQ ──
  SAFETY_HQ: [
    {
      id: "safe_barrier_sled",
      parentUnitId: "SAFETY_HQ",
      name: "Hydraulic Barrier Impact Sled & Dummy Prep Room",
      type: "workshop",
      description: "Accelerates interior passenger bucks into decelerator pins to test seatbelt webbing, dash padding, and steering column collapse.",
      requiredBuildingLevel: 1,
      staffMin: 3,
      staffMax: 6,
      monthlyOperatingCost: 6500,
      specialEquipment: ["Hydraulic Deceleration Sled", "Early Hybrid II Crash Dummies", "High-Speed Film Camera"],
      perks: ["Measures Chest G-Forces", "Calibrates Energy-Absorbing Steering Columns"],
    },
    {
      id: "safe_linear_rail_150m",
      parentUnitId: "SAFETY_HQ",
      name: "150-Meter Cable-Pull Crash Propulsion Hall",
      type: "facility",
      description: "Subterranean cable-pull mechanism towing complete vehicles up to 64 km/h into an instrumented 100-ton concrete barrier.",
      requiredBuildingLevel: 3,
      staffMin: 6,
      staffMax: 12,
      monthlyOperatingCost: 28000,
      specialEquipment: ["150m Steel Track Cable System", "100-Ton Reinforced Concrete Load Cell Barrier", "10,000 FPS Cameras"],
      perks: ["Euro NCAP & US FMVSS 5-Star Compliance", "Tunes Frontal Crumple Zones & Structural Shedding"],
    },
    {
      id: "safe_multi_angle_rig",
      parentUnitId: "SAFETY_HQ",
      name: "Multi-Angle Oblique & Rollover Pitch Rig",
      type: "facility",
      description: "Dynamic moving barrier vehicles for side pole impacts, offset deformable barriers, and dynamic roof crush tests.",
      requiredBuildingLevel: 4,
      staffMin: 4,
      staffMax: 8,
      monthlyOperatingCost: 36000,
      specialEquipment: ["MDB Side Impact Cart", "Rollover Spit Rig", "Thor-50M Sensorized Dummies"],
      perks: ["Best-in-Class Side Curtain Airbag Calibration", "Surpasses All Global Rollover Roof Standards"],
    },
    {
      id: "safe_quantum_simulation",
      parentUnitId: "SAFETY_HQ",
      name: "Quantum Biomechanics & Crash Finite Element Modeling",
      type: "lab",
      description: "Full-human organ tissue finite element simulations predicting soft-tissue micro-trauma and pre-crash evasive maneuvers.",
      requiredBuildingLevel: 7,
      staffMin: 3,
      staffMax: 6,
      monthlyOperatingCost: 70000,
      specialEquipment: ["Quantum Finite Element Supercomputer", "Active Restraint Pyrotechnic Rig"],
      perks: ["Zero Occupant Fatalities Safety Shield Rating", "Pre-Crash Millisecond Autonomous Braking & Evasion"],
    },
  ],

  // ── PHASE 20: UNIT_14 MARKETING & SALES HQ ──
  MARKETING_SALES_HQ: [
    {
      id: "mkt_press_studio",
      parentUnitId: "MARKETING_SALES_HQ",
      name: "Press Relations, Brochure & Print Studio",
      type: "department",
      description: "Layout desks, darkrooms, and typesetting for glossy sales catalogs, motoring press releases, and launch photography.",
      requiredBuildingLevel: 1,
      staffMin: 3,
      staffMax: 6,
      monthlyOperatingCost: 4500,
      specialEquipment: ["Photo Darkroom", "Typesetting Tables", "Press Archives"],
      perks: ["Generates Automotive Press Buzz", "Increases Showroom Footfall"],
    },
    {
      id: "mkt_dealer_network",
      parentUnitId: "MARKETING_SALES_HQ",
      name: "Dealership Franchise Network Management",
      type: "department",
      description: "Recruits independent regional automotive dealers, establishes regional sales quotas, and audits showroom floor displays.",
      requiredBuildingLevel: 1,
      staffMin: 4,
      staffMax: 8,
      monthlyOperatingCost: 5500,
      specialEquipment: ["Territory Maps & Ledgers", "Franchise Contracts Desk"],
      perks: ["Expands Regional Dealer Footprint", "Directly Drives Vehicle Order Volume"],
    },
    {
      id: "mkt_motor_show_stage",
      parentUnitId: "MARKETING_SALES_HQ",
      name: "International Motor Show & Exhibition Wing",
      type: "facility",
      description: "Rotating vehicle turntable stage, theatrical spotlights, and sound system for rehearsing Geneva and Detroit reveals.",
      requiredBuildingLevel: 3,
      staffMin: 4,
      staffMax: 8,
      monthlyOperatingCost: 16000,
      specialEquipment: ["Motorized Rotating Stage", "Stage Lighting Truss", "Show Car Transport Rigs"],
      perks: ["+35% Media Coverage on Vehicle World Premieres", "Generates Massive Pre-Order Deposits"],
    },
    {
      id: "mkt_digital_configurator",
      parentUnitId: "MARKETING_SALES_HQ",
      name: "3D Real-Time Vehicle Configurator Studio",
      type: "lab",
      description: "High-performance GPU cluster rendering photorealistic real-time vehicle customizers for online consumers.",
      requiredBuildingLevel: 5,
      staffMin: 4,
      staffMax: 8,
      monthlyOperatingCost: 28000,
      specialEquipment: ["Real-Time Cloud Render Farm", "Web 3D Interactive Servers"],
      perks: ["+25% Customer Option Selection (High Margin Add-Ons)", "Direct Online Customer Orders"],
    },
    {
      id: "mkt_global_ai_demand",
      parentUnitId: "MARKETING_SALES_HQ",
      name: "Global Demand AI & Neural Brand Positioning",
      type: "lab",
      description: "Real-time social sentiment scraping, dynamic localized lease rate optimization, and predictive viral marketing.",
      requiredBuildingLevel: 6,
      staffMin: 3,
      staffMax: 6,
      monthlyOperatingCost: 40000,
      specialEquipment: ["Market Sentiment AI Node", "Dynamic Residual Value Server"],
      perks: ["Guaranteed Sell-Out of Production Runs", "Maximizes Brand Equity & Secondary Market Value"],
    },
  ],
};

/**
 * Helper to fetch all sub-departments for a unit that are unlocked at or before a given building level.
 */
export function getUnlockedSubDepartmentsForLevel(
  unitId: CampusUnitId,
  buildingLevel: number
): SubDepartmentTreeEntry[] {
  const allDepts = SUB_DEPARTMENT_DEFINITIONS[unitId] || [];
  return allDepts.filter((d) => d.requiredBuildingLevel <= buildingLevel);
}

/**
 * Helper to get a single sub-department definition
 */
export function getSubDepartmentDefinition(
  unitId: CampusUnitId,
  subDeptId: string
): SubDepartmentTreeEntry | undefined {
  const allDepts = SUB_DEPARTMENT_DEFINITIONS[unitId] || [];
  return allDepts.find((d) => d.id === subDeptId);
}
