/**
 * ============================================================================
 * EXPANDED AUTOMOTIVE INTERIOR PRESET CATALOG
 * ============================================================================
 * Comprehensive catalog of production & motorsport interior configurations:
 * 1. Hypercar Carbon Monocoque Cockpit
 * 2. Grand Touring Executive Luxury Lounge
 * ============================================================================
 */

import { MasterModularInteriorState } from "./masterInteriorTypes";
import { MasterInteriorSolver } from "./masterInteriorSolver";

export const EXPANDED_INTERIOR_CATALOG: Record<string, MasterModularInteriorState> = {
  PRESET_HYPERCAR_CARBON_MONOCOQUE: {
    id: "PRESET_HYPERCAR_CARBON_MONOCOQUE",
    name: "Hypercar Carbon Monocoque GT",
    version: 1,
    createdAt: "2026-08-25T00:00:00.000Z",
    updatedAt: "2026-08-25T00:00:00.000Z",
    author: "Apex Motorsport Engineering",
    bodyType: "supercar",
    wheelbaseMm: 2700,
    trackWidthMm: 1680,
    hasTransmissionTunnel: true,
    seating: {
      frontSeatType: "carbon_monocoque_fixed_bucket",
      rearSeatType: "rear_seat_delete_roll_cage_x_brace",
      hasSeatHeating: false,
      hasSeatVentilation: true,
      hasPneumaticMassage: false,
      has6PointRacingHarness: true,
      harnessColorHex: "#00f0ff",
      lumbarAdjustAxes: 2,
      frontSeatsMassKgTotal: 22.0,
      rearSeatsMassKgTotal: 0.0,
      costUSD: 16500,
    },
    dashboard: {
      typology: "gt3_competition_dry_carbon",
      instrumentClusterStyle: "motec_track_racing_dash",
      hvacVentStyle: "aircraft_quad_nozzle",
      hasPassengerCoPilotDisplay: false,
      hasWindshieldHolographicHUD: true,
      hasAnalogChronoClock: false,
      massKg: 9.2,
      costUSD: 7800,
    },
    steering: {
      typology: "formula_gt3_carbon_yoke",
      diameterMm: 330,
      hasMagneticPaddleShifters: true,
      hasRotaryDriveModeDial: true,
      hasIntegratedRpmShiftLights: true,
      hasElectricSteeringColumnAdjust: false,
      hasSteeringHeating: false,
      massKg: 1.8,
      costUSD: 4200,
    },
    console: {
      typology: "open_gated_manual_tunnel",
      hasWirelessPhoneCharger: false,
      hasCoolerCompartment: false,
      hasMechanicalHandbrake: true,
      hasCarbonCupholders: false,
      massKg: 5.4,
      costUSD: 4500,
    },
    doors: {
      hasIntegratedAudioGrilles: false,
      hasAmbientLightBars: true,
      hasSoftCloseActuators: false,
      doorReleaseType: "nylon_pull_strap_race",
      massKgTotal: 11.2,
      costUSD: 3600,
    },
    infotainment: {
      screenSize: "compact_8_inch",
      hasTrackTelemetryApp: true,
      hasAppleCarPlayAndroidAuto: true,
      has360SurroundViewCameras: false,
      hasRearSeatEntertainmentScreens: false,
      massKg: 6.5,
      costUSD: 3200,
    },
    materials: {
      seatPrimaryMaterial: "perforated_alcantara",
      seatSecondaryMaterial: "nappa_leather",
      seatStitchingColorHex: "#00f0ff",
      dashboardPrimaryMaterial: "3k_twill_carbon_fiber",
      dashboardTrimInsert: "3k_twill_carbon_fiber",
      accentMetalFinish: "titanium_satin_finish",
      centerConsolePrimary: "3k_twill_carbon_fiber",
      doorCardInsert: "3k_twill_carbon_fiber",
      headlinerMaterial: "perforated_alcantara",
      carpetColorHex: "#090d16",
    },
    lighting: {
      enabled: true,
      theme: "cyberpunk_cyan",
      colorHex: "#00f0ff",
      brightnessPercent: 85,
      illuminatedZones: {
        footwells: true,
        doorStrips: true,
        dashboardStrip: true,
        centerConsole: true,
        starlightRoofHeadliner: false,
        seatBackBuckets: true,
      },
      massKg: 2.2,
      costUSD: 1400,
    },
    audio: {
      tier: "spatial_18_speaker_dolby_atmos",
      speakerCount: 18,
      amplifierWatts: 1400,
      hasSubwooferUnderseat: true,
      hasActiveNoiseCancellation: true,
      massKg: 11.2,
      costUSD: 6200,
    },
    safety: {
      rollCage: "fia_gt3_6_point_welded_cage",
      airbagModuleCount: 6,
      hasOnboardFireSuppressionSystem: true,
      hasEmergencyElectricalCutoffSwitch: true,
      massKg: 34.0,
      costUSD: 4800,
    },
    metrics: MasterInteriorSolver.solveMetrics({} as any),
  },

  PRESET_EXECUTIVE_LUXURY_LOUNGE: {
    id: "PRESET_EXECUTIVE_LUXURY_LOUNGE",
    name: "Grand Touring Executive Lounge",
    version: 1,
    createdAt: "2026-08-25T00:00:00.000Z",
    updatedAt: "2026-08-25T00:00:00.000Z",
    author: "Antigravity Bespoke Atelier",
    bodyType: "sedan",
    wheelbaseMm: 2980,
    trackWidthMm: 1640,
    hasTransmissionTunnel: true,
    seating: {
      frontSeatType: "executive_22way_massage_ottoman",
      rearSeatType: "executive_2passenger_lounge",
      hasSeatHeating: true,
      hasSeatVentilation: true,
      hasPneumaticMassage: true,
      has6PointRacingHarness: false,
      harnessColorHex: "#1e293b",
      lumbarAdjustAxes: 6,
      frontSeatsMassKgTotal: 62.0,
      rearSeatsMassKgTotal: 48.0,
      costUSD: 28500,
    },
    dashboard: {
      typology: "pillar_to_pillar_hyperscreen_blade",
      instrumentClusterStyle: "curved_hyper_oled_16inch",
      hvacVentStyle: "hidden_continuous_slits",
      hasPassengerCoPilotDisplay: true,
      hasWindshieldHolographicHUD: true,
      hasAnalogChronoClock: true,
      massKg: 16.5,
      costUSD: 11200,
    },
    steering: {
      typology: "flat_bottom_alcantara_sport",
      diameterMm: 370,
      hasMagneticPaddleShifters: true,
      hasRotaryDriveModeDial: true,
      hasIntegratedRpmShiftLights: false,
      hasElectricSteeringColumnAdjust: true,
      hasSteeringHeating: true,
      massKg: 3.4,
      costUSD: 2800,
    },
    console: {
      typology: "crystal_glass_monostable_rotary",
      hasWirelessPhoneCharger: true,
      hasCoolerCompartment: true,
      hasMechanicalHandbrake: false,
      hasCarbonCupholders: false,
      massKg: 18.2,
      costUSD: 5200,
    },
    doors: {
      hasIntegratedAudioGrilles: true,
      hasAmbientLightBars: true,
      hasSoftCloseActuators: true,
      doorReleaseType: "electronic_push_button",
      massKgTotal: 18.4,
      costUSD: 4800,
    },
    infotainment: {
      screenSize: "hyperscreen_56_inch",
      hasTrackTelemetryApp: false,
      hasAppleCarPlayAndroidAuto: true,
      has360SurroundViewCameras: true,
      hasRearSeatEntertainmentScreens: true,
      massKg: 14.0,
      costUSD: 6800,
    },
    materials: {
      seatPrimaryMaterial: "semi_aniline_leather",
      seatSecondaryMaterial: "nappa_leather",
      seatStitchingColorHex: "#d9a64e",
      dashboardPrimaryMaterial: "semi_aniline_leather",
      dashboardTrimInsert: "open_pore_walnut",
      accentMetalFinish: "brushed_billet_aluminum",
      centerConsolePrimary: "semi_aniline_leather",
      doorCardInsert: "open_pore_walnut",
      headlinerMaterial: "perforated_alcantara",
      carpetColorHex: "#1c1917",
    },
    lighting: {
      enabled: true,
      theme: "amber_gold_lounge",
      colorHex: "#f59e0b",
      brightnessPercent: 90,
      illuminatedZones: {
        footwells: true,
        doorStrips: true,
        dashboardStrip: true,
        centerConsole: true,
        starlightRoofHeadliner: true,
        seatBackBuckets: true,
      },
      massKg: 4.5,
      costUSD: 2400,
    },
    audio: {
      tier: "bespoke_24_speaker_diamond_2100w",
      speakerCount: 24,
      amplifierWatts: 2100,
      hasSubwooferUnderseat: true,
      hasActiveNoiseCancellation: true,
      massKg: 18.5,
      costUSD: 9500,
    },
    safety: {
      rollCage: "none_standard_chassis",
      airbagModuleCount: 12,
      hasOnboardFireSuppressionSystem: false,
      hasEmergencyElectricalCutoffSwitch: false,
      massKg: 16.0,
      costUSD: 2200,
    },
    metrics: MasterInteriorSolver.solveMetrics({} as any),
  },
};
