// ============================================================================
// F1 CONSTRUCTOR EXPERIENCE — DEFAULT F1 CAR CONFIGURATION
// ============================================================================
// Factory specification for the baseline Apex Formula 1 car complying with
// all FIA 2024/2026 Technical Regulations.
// ============================================================================

import type { F1CarDesign } from "../types/f1Types";

export const DEFAULT_F1_CAR: F1CarDesign = {
  id: "f1-apex-works-01",
  name: "Apex APX-24 Works",
  seasonYear: 2026,
  monocoque: {
    survivalCellLengthMm: 1980,
    cockpitOpeningWidthMm: 550,
    monocoqueTorsionalRigidityKNmDeg: 54,
    carbonFiberGrade: "T800_HIGH_STRENGTH",
    resinMatrix: "EPOXY_TOUGHENED_180C",
    coreMaterial: "NOMEX_HONEYCOMB_HRH10",
    monocoqueWallThicknessMm: 3.8,
    skinPlyCount: 24,
    haloMaterial: "TITANIUM_GRADE_5_DMLS",
    haloFairingAeroRamp: true,
    sideImpactStructureLayers: 3,
    frontNoseCrashAttenuatorVolumeDm3: 24,
    rearCrashAttenuatorLengthMm: 320,
    plankMaterial: "TITANIUM_SKID_INSERTS",
    ballastTungstenKg: 18,
    ballastPositionXPercent: 46.5,
    totalMonocoqueMassKg: 118,
  },
  powerUnit: {
    iceBoreMm: 80.0,
    iceStrokeMm: 53.0,
    compressionRatio: 16.5,
    prechamberTechnology: "ACTIVE_DUAL_STAGE_MAHLE",
    fuelRailPressureBar: 480,
    crankshaftMassKg: 9.8,
    crankshaftMaterial: "TI_6AL_4V_GRADE5",
    pistonCrownCoating: "DLC_DIAMOND_LIKE",
    connectingRodMaterial: "POWDER_FORGED_AERMET",
    turboCompressorInducerDiaMm: 62,
    turboTurbineExducerDiaMm: 64,
    turboMaxRpm: 122000,
    wastegatePortCount: 2,
    mguKPowerKw: 120,
    mguKMaxTorqueNm: 200,
    mguKDeployment: "CORNER_EXIT_TORQUE_FILL",
    mguHMaxHarvestKw: 90,
    mguHControl: "DIRECT_MGU_K_ENERGY_FEED",
    energyStoreCapacityMj: 4.0,
    energyStoreVoltage: 920,
    energyStoreChemistry: "NMC_811_HIGH_POWER",
    energyStoreCellCount: 240,
    energyStoreCoolingFlowLMin: 26,
    exhaustHeaderLengthMm: 540,
    exhaustCollectorType: "MERGE_COLLECTOR_3_INTO_1",
    exhaustMaterial: "INCONEL_625",
    coolingWaterRadiatorAreaM2: 0.52,
    coolingOilRadiatorAreaM2: 0.26,
    intercoolerType: "WATER_TO_AIR_CHEST",
    totalPowerUnitMassKg: 151,
  },
  aero: {
    packagePreset: "MEDIUM_DOWNFORCE_GLOBAL",
    frontWingConcept: "OUTWASH_WAKE_DEFLECTOR",
    frontWingSpanMm: 1980,
    frontWingElementsCount: 4,
    frontWingFlapAngleDeg: 19,
    frontWingEndplateOutwashSlot: true,
    frontWingGurneyFlapHeightMm: 4,
    sidepodPhilosophy: "AGGRESSIVE_DOWNWASH_RAMP",
    sidepodUndercutDepthMm: 260,
    sidepodCoolingLouverCount: 12,
    floorVenturiInletHeightMm: 85,
    floorVenturiThroatHeightMm: 16,
    floorFencesCountPerSide: 4,
    floorEdgeWingStrakeAngleDeg: 11,
    diffuserExpansionAngleDeg: 18,
    diffuserExitHeightMm: 185,
    diffuserStrakeLayout: "QUAD_VORTEX_FENCE_FIA",
    rearWingBeamWingProfile: "DOUBLE_CASCADE",
    rearWingMainPlaneAngleDeg: 24,
    rearWingDrsActuatorSpeedMs: 160,
    rearWingDrsFlapGapOpenMm: 85,
    sharkFinSpillPlateSize: "FULL_LENGTH_SAIL",
    totalDownforceAt250KmhKg: 1780,
    totalDragAt250KmhKg: 460,
    frontAeroBalancePercent: 44.5,
  },
  suspension: {
    frontLayout: "FRONT_PULLROD_REAR_PUSHROD",
    rearLayout: "FRONT_PULLROD_REAR_PUSHROD",
    frontWishboneMaterial: "M55J_HIGH_MODULUS",
    rearWishboneMaterial: "M55J_HIGH_MODULUS",
    frontRideHeightStaticMm: 28,
    rearRideHeightStaticMm: 68,
    frontWheelRateNmm: 220,
    rearWheelRateNmm: 270,
    frontTorsionBarDiameterMm: 22,
    rearTorsionBarDiameterMm: 24,
    frontAntiRollBarStiffness: 6,
    rearAntiRollBarStiffness: 5,
    antiRollBarType: "TORSION_BAR_ROTARY_BLADE",
    frontHeaveSpringRateNmm: 620,
    rearHeaveSpringRateNmm: 780,
    frontCamberDeg: -3.4,
    rearCamberDeg: -1.9,
    frontToeDeg: -0.15,
    rearToeDeg: 0.35,
    casterAngleDeg: 6.8,
    kingpinAngleDeg: 11.2,
    ackermannGeometryPercent: 55,
    steeringRackRatio: 14.2,
    powerSteeringAssistanceLevel: 3,
  },
  gearbox: {
    forwardGearsCount: 8,
    casingType: "FULL_CARBON_MONOCOQUE",
    gearboxWeightKg: 44,
    shiftTimeMs: 14,
    differentialPreloadNm: 110,
    differentialLockOnPowerPercent: 75,
    differentialLockOffPowerPercent: 45,
    differentialMidCornerUnlockPercent: 35,
    finalDriveRatio: 3.64,
    gearRatios: [3.18, 2.45, 1.95, 1.62, 1.38, 1.20, 1.05, 0.92],
    driveshaftMaterial: "CARBON_FIBER_OVERWRAPPED_TI",
    tripodJointLubricant: "NANO_MOLY_SYNTHETIC",
  },
  brakes: {
    frontDiscDiameterMm: 278,
    frontDiscThicknessMm: 32,
    frontDiscHoleCount: "1050_HOLE_HIGH_VENT",
    rearDiscDiameterMm: 280,
    rearDiscThicknessMm: 30,
    rearDiscHoleCount: "1050_HOLE_HIGH_VENT",
    caliperFrontPistons: 6,
    caliperRearPistons: 4,
    brakePadCompound: "CARBONE_INDUSTRIE_CCR",
    frontBrakeDuctInletAreaCm2: 78,
    rearBrakeDuctInletAreaCm2: 58,
    brakeBiasDefaultFrontPercent: 56.5,
    brakeByWireReactionTimeMs: 6,
    brakeFluidType: "SILICONE_ESTER_350C",
  },
  cockpit: {
    steeringWheelDisplayType: "5_0_INCH_HIGH_NIT_TFT",
    rotarySwitchCount: 6,
    thumbWheelCount: 4,
    pushbuttonCount: 16,
    clutchPaddleCount: 2,
    driverSeatCustomFoamScan: true,
    hansDeviceTetherAngleDeg: 38,
    fireExtinguisherGas: "NOVEC_1230",
    telemetrySampleRateHz: 500,
    telemetryChannelsCount: 320,
    ecuModel: "TAG_320_STANDARD_FIA",
    rainLightModel: "FIA_STANDARD_4_LED_FLASH",
  },
  livery: {
    primaryColorHex: "#0F172A",
    secondaryColorHex: "#06B6D4",
    tertiaryColorHex: "#F59E0B",
    finishType: "MATTE_LIGHTWEIGHT",
    carNumber: 44,
    carNumberFont: "MODERN_RACING_BOLD",
    nationalFlagCode: "GB",
    titleSponsorName: "APEX HORIZON DYNAMICS",
    titleSponsorLogoEmoji: "⚡",
    titleSponsorColor: "#06B6D4",
    technicalPartners: ["Pirelli", "Brembo", "Mahle", "Snap-on", "Siemens"],
  },
  computedTotalMassKg: 798,
  computedFrontWeightDistPercent: 45.8,
  computedTotalPeakHp: 1018,
  computedIcePeakHp: 858,
  computedErsPeakHp: 160,
  computedTopSpeedKmh: 354,
  computedZeroToHundredSec: 2.38,
  computedZeroToTwoHundredSec: 4.42,
  computedMaxCorneringGLat: 5.68,
  computedMaxBrakingGLong: 5.85,
  computedFiaHomologationScore: 100,
  computedEstCostMillionUsd: 118.5,
};
