// ============================================================================
// MODULE 15: AEROELASTIC WING FLEX & DYNAMIC ACTIVE AERO CONTROL ENGINE
// ============================================================================
// Structural aeroelasticity & dynamic active aerodynamic control:
// 1. Carbon composite aeroelastic beam bending under dynamic pressure (passive shedding)
// 2. High-speed airbrake emergency deployment under threshold braking
// 3. Active cornering flap roll-stabilization trim (independent left/right aero)
// 4. Closed-loop DRS hydraulic/servo actuator kinematics & response latency
// ============================================================================

export interface ActiveAeroHardwareSpecs {
  hasActiveFrontFlaps: boolean;
  hasActiveRearWing: boolean;
  hasAirbrakeFunction: boolean;
  maxAirbrakeAngleDeg: number;       // e.g. 72 deg
  airbrakeDeploymentRateDegPerS: number; // e.g. 350 deg/s (high speed hydraulic actuator)
  wingFlexComplianceDegPerKN: number; // Structural aeroelastic flex (e.g. 0.85 deg/kN)
  maxAeroRollTrimMomentNm: number;   // e.g. 850 Nm
  drsActuatorTimeConstantS: number;  // e.g. 0.12 s
}

export interface ActiveAeroControlInput {
  vehicleSpeedMs: number;
  longitudinalAccelG: number;
  lateralAccelG: number;
  chassisRollAngleDeg: number;
  isBrakingZone: boolean;
  isDrsRequested: boolean;
  dtSeconds: number;
}

export interface ActiveAeroState {
  currentRearWingAngleDeg: number;
  currentAirbrakeAngleDeg: number;
  leftFlapTrimAngleDeg: number;
  rightFlapTrimAngleDeg: number;
  drsFlapPositionFraction: number;   // 0 to 1.0
  elasticFlexAngleDeg: number;
}

export interface ActiveAeroOutput {
  airbrakeDragForceN: number;
  airbrakeDownforceRearN: number;
  passiveFlexDragReductionPct: number;
  aeroRightingRollMomentNm: number;
  effectiveRearAoADeg: number;
  isAirbrakeDeployed: boolean;
  state: ActiveAeroState;
}

export class ActiveAeroWingFlexDynamics {
  /**
   * Initializes baseline active aero actuator state.
   */
  public static createActiveAeroState(): ActiveAeroState {
    return {
      currentRearWingAngleDeg: 12.0, // Static angle of attack
      currentAirbrakeAngleDeg: 0,
      leftFlapTrimAngleDeg: 0,
      rightFlapTrimAngleDeg: 0,
      drsFlapPositionFraction: 0,
      elasticFlexAngleDeg: 0,
    };
  }

  /**
   * Evaluates aeroelastic wing flex, airbrake deployment, roll-stabilization trim,
   * and DRS actuator position.
   */
  public static evaluateActiveAero(
    specs: ActiveAeroHardwareSpecs,
    state: ActiveAeroState,
    input: ActiveAeroControlInput,
    staticRearWingAoADeg: number = 14.0
  ): ActiveAeroOutput {
    const dt = Math.max(0.001, input.dtSeconds);
    const v = Math.max(0.1, input.vehicleSpeedMs);
    const qDynamicPressure = 0.5 * 1.225 * Math.pow(v, 2);

    // ------------------------------------------------------------------------
    // 1. PASSIVE AEROELASTIC BEAM BENDING (FLEX)
    // ------------------------------------------------------------------------
    // Total aerodynamic vertical load on rear wing bends carbon fiber pylons:
    // Flap angle twists backward at high speed: Theta_flex = k * F_aero
    const nominalWingArea = 0.85; // m2
    const approxWingLoadN = qDynamicPressure * nominalWingArea * 1.8;
    const flexAngleDeg = (approxWingLoadN / 1000.0) * specs.wingFlexComplianceDegPerKN;

    // Passive flex sheds up to 12% drag at top speed without moving parts
    const flexDragReductionPct = Math.min(12.0, flexAngleDeg * 3.8);

    // ------------------------------------------------------------------------
    // 2. ACTIVE AIRBRAKE EMERGENCY DEPLOYMENT
    // ------------------------------------------------------------------------
    let airbrakeAngle = state.currentAirbrakeAngleDeg;
    let isAirbrakeActive = false;

    if (specs.hasAirbrakeFunction && input.longitudinalAccelG < -0.85 && v > 35.0) {
      isAirbrakeActive = true;
      // Deploy rapidly toward max angle
      const targetAngle = specs.maxAirbrakeAngleDeg;
      const maxDelta = specs.airbrakeDeploymentRateDegPerS * dt;
      airbrakeAngle = Math.min(targetAngle, airbrakeAngle + maxDelta);
    } else {
      // Retract
      const maxDelta = specs.airbrakeDeploymentRateDegPerS * dt;
      airbrakeAngle = Math.max(0, airbrakeAngle - maxDelta);
    }

    // Direct aerodynamic deceleration force generated by upright airbrake:
    // F_airbrake = 0.5 * rho * v^2 * A_flap * Cd_flat_plate * sin(angle)
    const airbrakeFlapArea = 0.52; // m2
    const airbrakeRad = (airbrakeAngle * Math.PI) / 180.0;
    const airbrakeDragForceN = qDynamicPressure * airbrakeFlapArea * 1.95 * Math.sin(airbrakeRad);
    const airbrakeDownforceN = qDynamicPressure * airbrakeFlapArea * 1.45 * Math.pow(Math.sin(airbrakeRad), 1.5);

    // ------------------------------------------------------------------------
    // 3. ACTIVE CORNERING ROLL STABILIZATION FLAP TRIM
    // ------------------------------------------------------------------------
    // Inside wing flap increases AoA to push inside down, outside trims to balance:
    let aeroRollMomentNm = 0;
    let leftTrimDeg = 0;
    let rightTrimDeg = 0;

    if (specs.hasActiveRearWing && Math.abs(input.lateralAccelG) > 0.5) {
      // Proportional roll stabilization control
      const trimDemandDeg = Math.min(8.0, Math.abs(input.chassisRollAngleDeg) * 2.5);
      if (input.lateralAccelG > 0) {
        // Left turn: vehicle rolls right -> increase left (inside) downforce
        leftTrimDeg = trimDemandDeg;
        rightTrimDeg = -trimDemandDeg;
        aeroRollMomentNm = Math.min(specs.maxAeroRollTrimMomentNm, (qDynamicPressure * 0.25 * trimDemandDeg) * 0.85);
      } else {
        // Right turn: vehicle rolls left -> increase right (inside) downforce
        leftTrimDeg = -trimDemandDeg;
        rightTrimDeg = trimDemandDeg;
        aeroRollMomentNm = -Math.min(specs.maxAeroRollTrimMomentNm, (qDynamicPressure * 0.25 * trimDemandDeg) * 0.85);
      }
    }

    // ------------------------------------------------------------------------
    // 4. CLOSED-LOOP DRS HYDRAULIC / SERVO ACTUATION
    // ------------------------------------------------------------------------
    const targetDrs = input.isDrsRequested && !isAirbrakeActive ? 1.0 : 0.0;
    const tauDrs = specs.drsActuatorTimeConstantS;
    const alphaDrs = dt / (tauDrs + dt);
    const drsPos = state.drsFlapPositionFraction + alphaDrs * (targetDrs - state.drsFlapPositionFraction);

    // Effective angle of attack: static - flex - drs + airbrake
    const effectiveAoA = Math.max(2.0, staticRearWingAoADeg - flexAngleDeg - (drsPos * 10.5) + airbrakeAngle);

    const updatedState: ActiveAeroState = {
      currentRearWingAngleDeg: Number(effectiveAoA.toFixed(2)),
      currentAirbrakeAngleDeg: Number(airbrakeAngle.toFixed(1)),
      leftFlapTrimAngleDeg: Number(leftTrimDeg.toFixed(2)),
      rightFlapTrimAngleDeg: Number(rightTrimDeg.toFixed(2)),
      drsFlapPositionFraction: Number(drsPos.toFixed(3)),
      elasticFlexAngleDeg: Number(flexAngleDeg.toFixed(2)),
    };

    return {
      airbrakeDragForceN: Number(airbrakeDragForceN.toFixed(1)),
      airbrakeDownforceRearN: Number(airbrakeDownforceN.toFixed(1)),
      passiveFlexDragReductionPct: Number(flexDragReductionPct.toFixed(1)),
      aeroRightingRollMomentNm: Number(aeroRollMomentNm.toFixed(1)),
      effectiveRearAoADeg: Number(effectiveAoA.toFixed(2)),
      isAirbrakeDeployed: airbrakeAngle > 5.0,
      state: updatedState,
    };
  }
}
