// ============================================================================
// MODULE 11: CIRCUIT GEOMETRY, TOPOGRAPHY & 3D CORNER DATABASE
// ============================================================================
// Real-world 3D track definitions with physical corner geometry:
// 1. Exact 3D coordinates (x, y, z elevation), length, and apex radius
// 2. Transverse banking angle (camber) & vertical road grade gradient (slope)
// 3. FIA kerb geometry (inside/outside height, bevel angle, rideability threshold)
// 4. Macro-texture asphalt friction mu & microclimate sun/wind exposure
// 5. Official circuit presets: Spa, Nürburgring, Silverstone, Monza, Monaco,
//    Suzuka, COTA, Bathurst, Laguna Seca, and Le Mans Circuit de la Sarthe
// ============================================================================

export type TrackCornerDirection = 'left' | 'right' | 'chicane_left_right' | 'chicane_right_left';

export interface DetailedKerbGeometry {
  hasKerb: boolean;
  kerbHeightMm: number;             // e.g. 25 mm (standard FIA kerb) or 50 mm (sausage kerb)
  kerbWidthM: number;               // e.g. 1.2 m
  kerbBevelAngleDeg: number;        // e.g. 15 deg
  rippleSpacingMm: number;          // e.g. 100 mm (vibration frequency = v / spacing)
  suspensionDisruptionFactor: number; // 0.1 (smooth) to 1.0 (damper bottoming risk)
}

export interface Detailed3DTrackCorner {
  cornerNumber: number;
  name: string;
  distanceFromStartM: number;
  radiusM: number;                  // Corner apex radius (m)
  arcLengthM: number;               // Corner total length along centerline (m)
  direction: TrackCornerDirection;
  bankingDeg: number;               // Transverse camber (positive = banked into turn, negative = off-camber)
  elevationChangeM: number;         // Vertical rise (+) or drop (-) in meters
  gradientSlopePct: number;         // Longitudinal road slope % (dz/ds * 100)
  entrySpeedBenchmarkKmh: number;   // Real motorsport GT3/Hypercar reference
  apexSpeedBenchmarkKmh: number;
  exitSpeedBenchmarkKmh: number;
  insideKerb: DetailedKerbGeometry;
  outsideKerb: DetailedKerbGeometry;
  trackWidthM: number;              // Track width at apex (e.g. 12m to 15m)
  surfaceMacroTextureMu: number;    // Base grip modifier (e.g. 1.05)
  isDrsZone: boolean;
}

export interface WorldCircuitDefinition {
  id: string;
  name: string;
  country: string;
  totalLengthM: number;
  baseAltitudeMeters: number;
  lapRecordTimeSeconds: number;
  lapRecordCar: string;
  corners: Detailed3DTrackCorner[];
}

export class CircuitGeometryTopographyDatabase {
  /** Standard flat kerb definition */
  public static readonly FLAT_FIA_KERB: DetailedKerbGeometry = {
    hasKerb: true,
    kerbHeightMm: 25,
    kerbWidthM: 1.2,
    kerbBevelAngleDeg: 12,
    rippleSpacingMm: 120,
    suspensionDisruptionFactor: 0.25,
  };

  /** Aggressive sausage kerb definition */
  public static readonly SAUSAGE_KERB: DetailedKerbGeometry = {
    hasKerb: true,
    kerbHeightMm: 65,
    kerbWidthM: 0.9,
    kerbBevelAngleDeg: 35,
    rippleSpacingMm: 80,
    suspensionDisruptionFactor: 0.90,
  };

  /** No kerb */
  public static readonly NO_KERB: DetailedKerbGeometry = {
    hasKerb: false,
    kerbHeightMm: 0,
    kerbWidthM: 0,
    kerbBevelAngleDeg: 0,
    rippleSpacingMm: 0,
    suspensionDisruptionFactor: 0.0,
  };

  public static readonly CIRCUITS: Record<string, WorldCircuitDefinition> = {
    // ------------------------------------------------------------------------
    // 1. SPA-FRANCORCHAMPS (Belgium)
    // ------------------------------------------------------------------------
    SPA_FRANCORCHAMPS: {
      id: 'SPA_FRANCORCHAMPS',
      name: 'Circuit de Spa-Francorchamps',
      country: 'Belgium',
      totalLengthM: 7004,
      baseAltitudeMeters: 420,
      lapRecordTimeSeconds: 101.286, // 1:41.286 (Hamilton 2020 W11)
      lapRecordCar: 'Mercedes-AMG F1 W11',
      corners: [
        {
          cornerNumber: 1,
          name: 'La Source',
          distanceFromStartM: 280,
          radiusM: 32,
          arcLengthM: 85,
          direction: 'right',
          bankingDeg: 1.5,
          elevationChangeM: -3.2,
          gradientSlopePct: -3.7,
          entrySpeedBenchmarkKmh: 285,
          apexSpeedBenchmarkKmh: 75,
          exitSpeedBenchmarkKmh: 145,
          insideKerb: CircuitGeometryTopographyDatabase.FLAT_FIA_KERB,
          outsideKerb: CircuitGeometryTopographyDatabase.FLAT_FIA_KERB,
          trackWidthM: 14.5,
          surfaceMacroTextureMu: 1.08,
          isDrsZone: false,
        },
        {
          cornerNumber: 2,
          name: 'Eau Rouge (Compression)',
          distanceFromStartM: 1050,
          radiusM: 195,
          arcLengthM: 120,
          direction: 'left',
          bankingDeg: 3.8,
          elevationChangeM: -6.5,
          gradientSlopePct: -5.4,
          entrySpeedBenchmarkKmh: 305,
          apexSpeedBenchmarkKmh: 295,
          exitSpeedBenchmarkKmh: 285,
          insideKerb: CircuitGeometryTopographyDatabase.FLAT_FIA_KERB,
          outsideKerb: CircuitGeometryTopographyDatabase.FLAT_FIA_KERB,
          trackWidthM: 15.0,
          surfaceMacroTextureMu: 1.10,
          isDrsZone: false,
        },
        {
          cornerNumber: 3,
          name: 'Raidillon (Crest & Blind Left)',
          distanceFromStartM: 1220,
          radiusM: 155,
          arcLengthM: 180,
          direction: 'right',
          bankingDeg: 4.8,
          elevationChangeM: 24.5,
          gradientSlopePct: 17.2, // 17.2% brutal uphill climb!
          entrySpeedBenchmarkKmh: 285,
          apexSpeedBenchmarkKmh: 275,
          exitSpeedBenchmarkKmh: 285,
          insideKerb: CircuitGeometryTopographyDatabase.FLAT_FIA_KERB,
          outsideKerb: CircuitGeometryTopographyDatabase.FLAT_FIA_KERB,
          trackWidthM: 14.2,
          surfaceMacroTextureMu: 1.10,
          isDrsZone: false,
        },
        {
          cornerNumber: 4,
          name: 'Kemmel Straight Apex',
          distanceFromStartM: 1950,
          radiusM: 9999,
          arcLengthM: 780,
          direction: 'left',
          bankingDeg: 0,
          elevationChangeM: 8.5,
          gradientSlopePct: 1.1,
          entrySpeedBenchmarkKmh: 285,
          apexSpeedBenchmarkKmh: 345,
          exitSpeedBenchmarkKmh: 345,
          insideKerb: CircuitGeometryTopographyDatabase.NO_KERB,
          outsideKerb: CircuitGeometryTopographyDatabase.NO_KERB,
          trackWidthM: 14.0,
          surfaceMacroTextureMu: 1.06,
          isDrsZone: true,
        },
        {
          cornerNumber: 5,
          name: 'Les Combes (Turn 5)',
          distanceFromStartM: 2280,
          radiusM: 45,
          arcLengthM: 80,
          direction: 'right',
          bankingDeg: -1.2, // Off-camber
          elevationChangeM: 1.8,
          gradientSlopePct: 2.2,
          entrySpeedBenchmarkKmh: 345,
          apexSpeedBenchmarkKmh: 135,
          exitSpeedBenchmarkKmh: 155,
          insideKerb: CircuitGeometryTopographyDatabase.FLAT_FIA_KERB,
          outsideKerb: CircuitGeometryTopographyDatabase.FLAT_FIA_KERB,
          trackWidthM: 13.5,
          surfaceMacroTextureMu: 1.05,
          isDrsZone: false,
        },
        {
          cornerNumber: 6,
          name: 'Malmedy (Turn 6)',
          distanceFromStartM: 2420,
          radiusM: 52,
          arcLengthM: 75,
          direction: 'left',
          bankingDeg: 1.0,
          elevationChangeM: -0.5,
          gradientSlopePct: -0.7,
          entrySpeedBenchmarkKmh: 155,
          apexSpeedBenchmarkKmh: 165,
          exitSpeedBenchmarkKmh: 185,
          insideKerb: CircuitGeometryTopographyDatabase.FLAT_FIA_KERB,
          outsideKerb: CircuitGeometryTopographyDatabase.FLAT_FIA_KERB,
          trackWidthM: 13.5,
          surfaceMacroTextureMu: 1.05,
          isDrsZone: false,
        },
        {
          cornerNumber: 7,
          name: 'Rivage Downhill Hairpin',
          distanceFromStartM: 2750,
          radiusM: 36,
          arcLengthM: 110,
          direction: 'right',
          bankingDeg: -3.8, // Dangerous off-camber drop
          elevationChangeM: -11.5,
          gradientSlopePct: -10.4,
          entrySpeedBenchmarkKmh: 235,
          apexSpeedBenchmarkKmh: 105,
          exitSpeedBenchmarkKmh: 125,
          insideKerb: CircuitGeometryTopographyDatabase.FLAT_FIA_KERB,
          outsideKerb: CircuitGeometryTopographyDatabase.FLAT_FIA_KERB,
          trackWidthM: 14.0,
          surfaceMacroTextureMu: 1.02,
          isDrsZone: false,
        },
        {
          cornerNumber: 8,
          name: 'Speakers Corner',
          distanceFromStartM: 3050,
          radiusM: 58,
          arcLengthM: 85,
          direction: 'left',
          bankingDeg: 0.8,
          elevationChangeM: -4.5,
          gradientSlopePct: -5.3,
          entrySpeedBenchmarkKmh: 165,
          apexSpeedBenchmarkKmh: 140,
          exitSpeedBenchmarkKmh: 175,
          insideKerb: CircuitGeometryTopographyDatabase.FLAT_FIA_KERB,
          outsideKerb: CircuitGeometryTopographyDatabase.FLAT_FIA_KERB,
          trackWidthM: 13.0,
          surfaceMacroTextureMu: 1.04,
          isDrsZone: false,
        },
        {
          cornerNumber: 9,
          name: 'Pouhon (Double Apex)',
          distanceFromStartM: 3850,
          radiusM: 95,
          arcLengthM: 210,
          direction: 'left',
          bankingDeg: 4.2, // Positive banking holds high lateral G
          elevationChangeM: -14.2,
          gradientSlopePct: -6.7,
          entrySpeedBenchmarkKmh: 295,
          apexSpeedBenchmarkKmh: 245,
          exitSpeedBenchmarkKmh: 265,
          insideKerb: CircuitGeometryTopographyDatabase.FLAT_FIA_KERB,
          outsideKerb: CircuitGeometryTopographyDatabase.FLAT_FIA_KERB,
          trackWidthM: 14.8,
          surfaceMacroTextureMu: 1.12,
          isDrsZone: false,
        },
        {
          cornerNumber: 10,
          name: 'Fagnes Chicane Entry',
          distanceFromStartM: 4680,
          radiusM: 48,
          arcLengthM: 70,
          direction: 'right',
          bankingDeg: 0.5,
          elevationChangeM: -1.2,
          gradientSlopePct: -1.7,
          entrySpeedBenchmarkKmh: 275,
          apexSpeedBenchmarkKmh: 155,
          exitSpeedBenchmarkKmh: 165,
          insideKerb: CircuitGeometryTopographyDatabase.FLAT_FIA_KERB,
          outsideKerb: CircuitGeometryTopographyDatabase.FLAT_FIA_KERB,
          trackWidthM: 13.5,
          surfaceMacroTextureMu: 1.05,
          isDrsZone: false,
        },
        {
          cornerNumber: 11,
          name: 'Stavelot',
          distanceFromStartM: 5200,
          radiusM: 68,
          arcLengthM: 95,
          direction: 'right',
          bankingDeg: 2.4,
          elevationChangeM: -2.8,
          gradientSlopePct: -2.9,
          entrySpeedBenchmarkKmh: 210,
          apexSpeedBenchmarkKmh: 175,
          exitSpeedBenchmarkKmh: 215,
          insideKerb: CircuitGeometryTopographyDatabase.FLAT_FIA_KERB,
          outsideKerb: CircuitGeometryTopographyDatabase.FLAT_FIA_KERB,
          trackWidthM: 14.0,
          surfaceMacroTextureMu: 1.06,
          isDrsZone: false,
        },
        {
          cornerNumber: 12,
          name: 'Paul Frere (Courbe)',
          distanceFromStartM: 5450,
          radiusM: 135,
          arcLengthM: 150,
          direction: 'right',
          bankingDeg: 1.8,
          elevationChangeM: 4.5,
          gradientSlopePct: 3.0,
          entrySpeedBenchmarkKmh: 215,
          apexSpeedBenchmarkKmh: 245,
          exitSpeedBenchmarkKmh: 275,
          insideKerb: CircuitGeometryTopographyDatabase.FLAT_FIA_KERB,
          outsideKerb: CircuitGeometryTopographyDatabase.FLAT_FIA_KERB,
          trackWidthM: 14.5,
          surfaceMacroTextureMu: 1.08,
          isDrsZone: false,
        },
        {
          cornerNumber: 13,
          name: 'Blanchimont (Turn 17)',
          distanceFromStartM: 6100,
          radiusM: 240,
          arcLengthM: 260,
          direction: 'left',
          bankingDeg: 2.6,
          elevationChangeM: 2.2,
          gradientSlopePct: 0.8,
          entrySpeedBenchmarkKmh: 310,
          apexSpeedBenchmarkKmh: 305,
          exitSpeedBenchmarkKmh: 315,
          insideKerb: CircuitGeometryTopographyDatabase.FLAT_FIA_KERB,
          outsideKerb: CircuitGeometryTopographyDatabase.FLAT_FIA_KERB,
          trackWidthM: 15.0,
          surfaceMacroTextureMu: 1.10,
          isDrsZone: true,
        },
        {
          cornerNumber: 14,
          name: 'Bus Stop Chicane (Entry)',
          distanceFromStartM: 6850,
          radiusM: 26,
          arcLengthM: 55,
          direction: 'right',
          bankingDeg: 0.5,
          elevationChangeM: 0.5,
          gradientSlopePct: 0.9,
          entrySpeedBenchmarkKmh: 320,
          apexSpeedBenchmarkKmh: 68,
          exitSpeedBenchmarkKmh: 85,
          insideKerb: CircuitGeometryTopographyDatabase.SAUSAGE_KERB,
          outsideKerb: CircuitGeometryTopographyDatabase.FLAT_FIA_KERB,
          trackWidthM: 13.0,
          surfaceMacroTextureMu: 1.05,
          isDrsZone: false,
        },
        {
          cornerNumber: 15,
          name: 'Bus Stop Chicane (Exit)',
          distanceFromStartM: 6920,
          radiusM: 28,
          arcLengthM: 50,
          direction: 'left',
          bankingDeg: 0.5,
          elevationChangeM: -0.5,
          gradientSlopePct: -1.0,
          entrySpeedBenchmarkKmh: 85,
          apexSpeedBenchmarkKmh: 75,
          exitSpeedBenchmarkKmh: 140,
          insideKerb: CircuitGeometryTopographyDatabase.SAUSAGE_KERB,
          outsideKerb: CircuitGeometryTopographyDatabase.FLAT_FIA_KERB,
          trackWidthM: 13.2,
          surfaceMacroTextureMu: 1.05,
          isDrsZone: false,
        },
      ],
    },

    // ------------------------------------------------------------------------
    // 2. NÜRBURGRING NORDSCHLEIFE (Germany)
    // ------------------------------------------------------------------------
    NURBURGRING_NORDSCHLEIFE: {
      id: 'NURBURGRING_NORDSCHLEIFE',
      name: 'Nürburgring Nordschleife (Full Green Hell)',
      country: 'Germany',
      totalLengthM: 20832,
      baseAltitudeMeters: 615,
      lapRecordTimeSeconds: 319.545, // 5:19.545 (Porsche 919 Evo)
      lapRecordCar: 'Porsche 919 Hybrid Evo',
      corners: [
        {
          cornerNumber: 1,
          name: 'Hatzenbach Chicane',
          distanceFromStartM: 1850,
          radiusM: 55,
          arcLengthM: 140,
          direction: 'left',
          bankingDeg: 1.2,
          elevationChangeM: -8.5,
          gradientSlopePct: -6.0,
          entrySpeedBenchmarkKmh: 240,
          apexSpeedBenchmarkKmh: 125,
          exitSpeedBenchmarkKmh: 155,
          insideKerb: CircuitGeometryTopographyDatabase.FLAT_FIA_KERB,
          outsideKerb: CircuitGeometryTopographyDatabase.FLAT_FIA_KERB,
          trackWidthM: 10.5,
          surfaceMacroTextureMu: 1.02,
          isDrsZone: false,
        },
        {
          cornerNumber: 2,
          name: 'Flugplatz (Jump Crest)',
          distanceFromStartM: 2550,
          radiusM: 145,
          arcLengthM: 160,
          direction: 'right',
          bankingDeg: 2.0,
          elevationChangeM: 12.0,
          gradientSlopePct: 7.5,
          entrySpeedBenchmarkKmh: 275,
          apexSpeedBenchmarkKmh: 245,
          exitSpeedBenchmarkKmh: 265,
          insideKerb: CircuitGeometryTopographyDatabase.FLAT_FIA_KERB,
          outsideKerb: CircuitGeometryTopographyDatabase.FLAT_FIA_KERB,
          trackWidthM: 11.0,
          surfaceMacroTextureMu: 1.04,
          isDrsZone: false,
        },
        {
          cornerNumber: 3,
          name: 'Schwedenkreuz (High-Speed Left)',
          distanceFromStartM: 3250,
          radiusM: 210,
          arcLengthM: 180,
          direction: 'left',
          bankingDeg: -1.5, // Blind crest off-camber
          elevationChangeM: -18.5,
          gradientSlopePct: -10.2,
          entrySpeedBenchmarkKmh: 295,
          apexSpeedBenchmarkKmh: 270,
          exitSpeedBenchmarkKmh: 250,
          insideKerb: CircuitGeometryTopographyDatabase.FLAT_FIA_KERB,
          outsideKerb: CircuitGeometryTopographyDatabase.FLAT_FIA_KERB,
          trackWidthM: 10.5,
          surfaceMacroTextureMu: 1.03,
          isDrsZone: false,
        },
        {
          cornerNumber: 4,
          name: 'Fuchsröhre (The Foxhole Bottom)',
          distanceFromStartM: 5650,
          radiusM: 125,
          arcLengthM: 240,
          direction: 'left',
          bankingDeg: 3.5,
          elevationChangeM: -35.0, // Massive downhill compression
          gradientSlopePct: -14.5,
          entrySpeedBenchmarkKmh: 285,
          apexSpeedBenchmarkKmh: 265,
          exitSpeedBenchmarkKmh: 235,
          insideKerb: CircuitGeometryTopographyDatabase.FLAT_FIA_KERB,
          outsideKerb: CircuitGeometryTopographyDatabase.FLAT_FIA_KERB,
          trackWidthM: 10.2,
          surfaceMacroTextureMu: 1.05,
          isDrsZone: false,
        },
        {
          cornerNumber: 5,
          name: 'Adenauer Forst',
          distanceFromStartM: 6750,
          radiusM: 38,
          arcLengthM: 95,
          direction: 'left',
          bankingDeg: 0.5,
          elevationChangeM: 4.5,
          gradientSlopePct: 4.7,
          entrySpeedBenchmarkKmh: 210,
          apexSpeedBenchmarkKmh: 85,
          exitSpeedBenchmarkKmh: 115,
          insideKerb: CircuitGeometryTopographyDatabase.SAUSAGE_KERB,
          outsideKerb: CircuitGeometryTopographyDatabase.FLAT_FIA_KERB,
          trackWidthM: 10.0,
          surfaceMacroTextureMu: 1.01,
          isDrsZone: false,
        },
        {
          cornerNumber: 6,
          name: 'Metzgesfeld',
          distanceFromStartM: 7450,
          radiusM: 72,
          arcLengthM: 110,
          direction: 'left',
          bankingDeg: 1.2,
          elevationChangeM: -6.5,
          gradientSlopePct: -5.9,
          entrySpeedBenchmarkKmh: 220,
          apexSpeedBenchmarkKmh: 155,
          exitSpeedBenchmarkKmh: 185,
          insideKerb: CircuitGeometryTopographyDatabase.FLAT_FIA_KERB,
          outsideKerb: CircuitGeometryTopographyDatabase.FLAT_FIA_KERB,
          trackWidthM: 10.5,
          surfaceMacroTextureMu: 1.03,
          isDrsZone: false,
        },
        {
          cornerNumber: 7,
          name: 'Bergwerk',
          distanceFromStartM: 10450,
          radiusM: 42,
          arcLengthM: 85,
          direction: 'right',
          bankingDeg: 2.5,
          elevationChangeM: -2.5,
          gradientSlopePct: -2.9,
          entrySpeedBenchmarkKmh: 205,
          apexSpeedBenchmarkKmh: 95,
          exitSpeedBenchmarkKmh: 135,
          insideKerb: CircuitGeometryTopographyDatabase.FLAT_FIA_KERB,
          outsideKerb: CircuitGeometryTopographyDatabase.FLAT_FIA_KERB,
          trackWidthM: 10.0,
          surfaceMacroTextureMu: 1.02,
          isDrsZone: false,
        },
        {
          cornerNumber: 8,
          name: 'Caracciola-Karussell (Concrete Banking)',
          distanceFromStartM: 13200,
          radiusM: 35,
          arcLengthM: 165,
          direction: 'left',
          bankingDeg: 33.0, // 33-degree severe concrete dish banking!
          elevationChangeM: 8.5,
          gradientSlopePct: 5.1,
          entrySpeedBenchmarkKmh: 185,
          apexSpeedBenchmarkKmh: 98,
          exitSpeedBenchmarkKmh: 125,
          insideKerb: CircuitGeometryTopographyDatabase.SAUSAGE_KERB,
          outsideKerb: CircuitGeometryTopographyDatabase.NO_KERB,
          trackWidthM: 9.8,
          surfaceMacroTextureMu: 1.22, // High friction concrete slabs
          isDrsZone: false,
        },
        {
          cornerNumber: 9,
          name: 'Brünnchen (YouTube Corner)',
          distanceFromStartM: 14850,
          radiusM: 52,
          arcLengthM: 90,
          direction: 'right',
          bankingDeg: 2.8,
          elevationChangeM: -8.5,
          gradientSlopePct: -9.4,
          entrySpeedBenchmarkKmh: 215,
          apexSpeedBenchmarkKmh: 120,
          exitSpeedBenchmarkKmh: 145,
          insideKerb: CircuitGeometryTopographyDatabase.FLAT_FIA_KERB,
          outsideKerb: CircuitGeometryTopographyDatabase.FLAT_FIA_KERB,
          trackWidthM: 10.2,
          surfaceMacroTextureMu: 1.02,
          isDrsZone: false,
        },
        {
          cornerNumber: 10,
          name: 'Pflanzgarten Jump',
          distanceFromStartM: 15650,
          radiusM: 88,
          arcLengthM: 130,
          direction: 'right',
          bankingDeg: 1.5,
          elevationChangeM: -12.5,
          gradientSlopePct: -9.6,
          entrySpeedBenchmarkKmh: 245,
          apexSpeedBenchmarkKmh: 185,
          exitSpeedBenchmarkKmh: 215,
          insideKerb: CircuitGeometryTopographyDatabase.FLAT_FIA_KERB,
          outsideKerb: CircuitGeometryTopographyDatabase.FLAT_FIA_KERB,
          trackWidthM: 10.5,
          surfaceMacroTextureMu: 1.04,
          isDrsZone: false,
        },
        {
          cornerNumber: 11,
          name: 'Kleines Karussell',
          distanceFromStartM: 16850,
          radiusM: 28,
          arcLengthM: 65,
          direction: 'left',
          bankingDeg: 24.0, // Mini banked dish
          elevationChangeM: 2.5,
          gradientSlopePct: 3.8,
          entrySpeedBenchmarkKmh: 145,
          apexSpeedBenchmarkKmh: 82,
          exitSpeedBenchmarkKmh: 115,
          insideKerb: CircuitGeometryTopographyDatabase.SAUSAGE_KERB,
          outsideKerb: CircuitGeometryTopographyDatabase.NO_KERB,
          trackWidthM: 9.5,
          surfaceMacroTextureMu: 1.15,
          isDrsZone: false,
        },
        {
          cornerNumber: 12,
          name: 'Döttinger Höhe 2.1km Straight',
          distanceFromStartM: 18200,
          radiusM: 9999,
          arcLengthM: 2135,
          direction: 'left',
          bankingDeg: 0,
          elevationChangeM: 22.0,
          gradientSlopePct: 1.0,
          entrySpeedBenchmarkKmh: 210,
          apexSpeedBenchmarkKmh: 360,
          exitSpeedBenchmarkKmh: 360,
          insideKerb: CircuitGeometryTopographyDatabase.NO_KERB,
          outsideKerb: CircuitGeometryTopographyDatabase.NO_KERB,
          trackWidthM: 12.0,
          surfaceMacroTextureMu: 1.06,
          isDrsZone: true,
        },
      ],
    },

    // ------------------------------------------------------------------------
    // 3. SILVERSTONE GRAND PRIX (UK)
    // ------------------------------------------------------------------------
    SILVERSTONE_GP: {
      id: 'SILVERSTONE_GP',
      name: 'Silverstone Grand Prix Circuit',
      country: 'United Kingdom',
      totalLengthM: 5891,
      baseAltitudeMeters: 155,
      lapRecordTimeSeconds: 87.097, // 1:27.097 (Hamilton 2020)
      lapRecordCar: 'Mercedes-AMG F1 W11',
      corners: [
        {
          cornerNumber: 1,
          name: 'Abbey',
          distanceFromStartM: 350,
          radiusM: 145,
          arcLengthM: 130,
          direction: 'right',
          bankingDeg: 2.2,
          elevationChangeM: 0.5,
          gradientSlopePct: 0.4,
          entrySpeedBenchmarkKmh: 300,
          apexSpeedBenchmarkKmh: 275,
          exitSpeedBenchmarkKmh: 285,
          insideKerb: CircuitGeometryTopographyDatabase.FLAT_FIA_KERB,
          outsideKerb: CircuitGeometryTopographyDatabase.FLAT_FIA_KERB,
          trackWidthM: 15.0,
          surfaceMacroTextureMu: 1.10,
          isDrsZone: false,
        },
        {
          cornerNumber: 2,
          name: 'The Loop',
          distanceFromStartM: 1450,
          radiusM: 38,
          arcLengthM: 90,
          direction: 'left',
          bankingDeg: 1.0,
          elevationChangeM: -0.8,
          gradientSlopePct: -0.9,
          entrySpeedBenchmarkKmh: 215,
          apexSpeedBenchmarkKmh: 82,
          exitSpeedBenchmarkKmh: 125,
          insideKerb: CircuitGeometryTopographyDatabase.FLAT_FIA_KERB,
          outsideKerb: CircuitGeometryTopographyDatabase.FLAT_FIA_KERB,
          trackWidthM: 14.5,
          surfaceMacroTextureMu: 1.06,
          isDrsZone: false,
        },
        {
          cornerNumber: 3,
          name: 'Copse (Blind 280km/h Right)',
          distanceFromStartM: 2900,
          radiusM: 118,
          arcLengthM: 110,
          direction: 'right',
          bankingDeg: 2.5,
          elevationChangeM: 1.2,
          gradientSlopePct: 1.1,
          entrySpeedBenchmarkKmh: 305,
          apexSpeedBenchmarkKmh: 278,
          exitSpeedBenchmarkKmh: 295,
          insideKerb: CircuitGeometryTopographyDatabase.FLAT_FIA_KERB,
          outsideKerb: CircuitGeometryTopographyDatabase.FLAT_FIA_KERB,
          trackWidthM: 15.5,
          surfaceMacroTextureMu: 1.12,
          isDrsZone: false,
        },
        {
          cornerNumber: 4,
          name: 'Maggotts',
          distanceFromStartM: 3350,
          radiusM: 125,
          arcLengthM: 110,
          direction: 'left',
          bankingDeg: 3.2,
          elevationChangeM: -1.5,
          gradientSlopePct: -1.4,
          entrySpeedBenchmarkKmh: 310,
          apexSpeedBenchmarkKmh: 295,
          exitSpeedBenchmarkKmh: 285,
          insideKerb: CircuitGeometryTopographyDatabase.FLAT_FIA_KERB,
          outsideKerb: CircuitGeometryTopographyDatabase.FLAT_FIA_KERB,
          trackWidthM: 15.0,
          surfaceMacroTextureMu: 1.14,
          isDrsZone: false,
        },
        {
          cornerNumber: 5,
          name: 'Becketts (Esses Switchback)',
          distanceFromStartM: 3480,
          radiusM: 65,
          arcLengthM: 95,
          direction: 'right',
          bankingDeg: 2.8,
          elevationChangeM: -0.5,
          gradientSlopePct: -0.5,
          entrySpeedBenchmarkKmh: 285,
          apexSpeedBenchmarkKmh: 225,
          exitSpeedBenchmarkKmh: 245,
          insideKerb: CircuitGeometryTopographyDatabase.FLAT_FIA_KERB,
          outsideKerb: CircuitGeometryTopographyDatabase.FLAT_FIA_KERB,
          trackWidthM: 14.8,
          surfaceMacroTextureMu: 1.14,
          isDrsZone: false,
        },
        {
          cornerNumber: 6,
          name: 'Chapel',
          distanceFromStartM: 3620,
          radiusM: 110,
          arcLengthM: 80,
          direction: 'left',
          bankingDeg: 1.5,
          elevationChangeM: 0.5,
          gradientSlopePct: 0.6,
          entrySpeedBenchmarkKmh: 245,
          apexSpeedBenchmarkKmh: 255,
          exitSpeedBenchmarkKmh: 280,
          insideKerb: CircuitGeometryTopographyDatabase.FLAT_FIA_KERB,
          outsideKerb: CircuitGeometryTopographyDatabase.FLAT_FIA_KERB,
          trackWidthM: 15.0,
          surfaceMacroTextureMu: 1.12,
          isDrsZone: false,
        },
        {
          cornerNumber: 7,
          name: 'Stowe (End of Hangar Straight)',
          distanceFromStartM: 4300,
          radiusM: 85,
          arcLengthM: 105,
          direction: 'right',
          bankingDeg: 2.0,
          elevationChangeM: -2.2,
          gradientSlopePct: -2.1,
          entrySpeedBenchmarkKmh: 335,
          apexSpeedBenchmarkKmh: 195,
          exitSpeedBenchmarkKmh: 225,
          insideKerb: CircuitGeometryTopographyDatabase.FLAT_FIA_KERB,
          outsideKerb: CircuitGeometryTopographyDatabase.FLAT_FIA_KERB,
          trackWidthM: 14.5,
          surfaceMacroTextureMu: 1.08,
          isDrsZone: false,
        },
      ],
    },

    // ------------------------------------------------------------------------
    // 4. AUTODROMO NAZIONALE MONZA (Italy)
    // ------------------------------------------------------------------------
    MONZA: {
      id: 'MONZA',
      name: 'Autodromo Nazionale Monza (Temple of Speed)',
      country: 'Italy',
      totalLengthM: 5793,
      baseAltitudeMeters: 162,
      lapRecordTimeSeconds: 78.887, // 1:18.887 (Hamilton 2020)
      lapRecordCar: 'Mercedes-AMG F1 W11',
      corners: [
        {
          cornerNumber: 1,
          name: 'Variante del Rettifilo (Entry)',
          distanceFromStartM: 1100,
          radiusM: 22,
          arcLengthM: 45,
          direction: 'right',
          bankingDeg: 0.5,
          elevationChangeM: 0.2,
          gradientSlopePct: 0.4,
          entrySpeedBenchmarkKmh: 355,
          apexSpeedBenchmarkKmh: 68,
          exitSpeedBenchmarkKmh: 85,
          insideKerb: CircuitGeometryTopographyDatabase.SAUSAGE_KERB,
          outsideKerb: CircuitGeometryTopographyDatabase.FLAT_FIA_KERB,
          trackWidthM: 13.0,
          surfaceMacroTextureMu: 1.05,
          isDrsZone: false,
        },
        {
          cornerNumber: 2,
          name: 'Curva Grande (Biassono)',
          distanceFromStartM: 1650,
          radiusM: 285,
          arcLengthM: 320,
          direction: 'right',
          bankingDeg: 2.5,
          elevationChangeM: 1.5,
          gradientSlopePct: 0.5,
          entrySpeedBenchmarkKmh: 285,
          apexSpeedBenchmarkKmh: 305,
          exitSpeedBenchmarkKmh: 325,
          insideKerb: CircuitGeometryTopographyDatabase.FLAT_FIA_KERB,
          outsideKerb: CircuitGeometryTopographyDatabase.FLAT_FIA_KERB,
          trackWidthM: 14.5,
          surfaceMacroTextureMu: 1.08,
          isDrsZone: true,
        },
        {
          cornerNumber: 3,
          name: 'Variante della Roggia',
          distanceFromStartM: 2400,
          radiusM: 32,
          arcLengthM: 55,
          direction: 'left',
          bankingDeg: 0.5,
          elevationChangeM: -0.4,
          gradientSlopePct: -0.7,
          entrySpeedBenchmarkKmh: 335,
          apexSpeedBenchmarkKmh: 115,
          exitSpeedBenchmarkKmh: 135,
          insideKerb: CircuitGeometryTopographyDatabase.SAUSAGE_KERB,
          outsideKerb: CircuitGeometryTopographyDatabase.FLAT_FIA_KERB,
          trackWidthM: 13.0,
          surfaceMacroTextureMu: 1.04,
          isDrsZone: false,
        },
        {
          cornerNumber: 4,
          name: 'Curva di Lesmo 1',
          distanceFromStartM: 2850,
          radiusM: 65,
          arcLengthM: 70,
          direction: 'right',
          bankingDeg: 2.2,
          elevationChangeM: -1.2,
          gradientSlopePct: -1.7,
          entrySpeedBenchmarkKmh: 275,
          apexSpeedBenchmarkKmh: 185,
          exitSpeedBenchmarkKmh: 215,
          insideKerb: CircuitGeometryTopographyDatabase.FLAT_FIA_KERB,
          outsideKerb: CircuitGeometryTopographyDatabase.FLAT_FIA_KERB,
          trackWidthM: 13.5,
          surfaceMacroTextureMu: 1.06,
          isDrsZone: false,
        },
        {
          cornerNumber: 5,
          name: 'Curva di Lesmo 2',
          distanceFromStartM: 3100,
          radiusM: 55,
          arcLengthM: 65,
          direction: 'right',
          bankingDeg: 1.8,
          elevationChangeM: -0.8,
          gradientSlopePct: -1.2,
          entrySpeedBenchmarkKmh: 235,
          apexSpeedBenchmarkKmh: 165,
          exitSpeedBenchmarkKmh: 205,
          insideKerb: CircuitGeometryTopographyDatabase.FLAT_FIA_KERB,
          outsideKerb: CircuitGeometryTopographyDatabase.FLAT_FIA_KERB,
          trackWidthM: 13.5,
          surfaceMacroTextureMu: 1.06,
          isDrsZone: false,
        },
        {
          cornerNumber: 6,
          name: 'Variante Ascari',
          distanceFromStartM: 4250,
          radiusM: 60,
          arcLengthM: 160,
          direction: 'chicane_left_right',
          bankingDeg: 1.5,
          elevationChangeM: 0.2,
          gradientSlopePct: 0.1,
          entrySpeedBenchmarkKmh: 340,
          apexSpeedBenchmarkKmh: 215,
          exitSpeedBenchmarkKmh: 245,
          insideKerb: CircuitGeometryTopographyDatabase.FLAT_FIA_KERB,
          outsideKerb: CircuitGeometryTopographyDatabase.FLAT_FIA_KERB,
          trackWidthM: 14.0,
          surfaceMacroTextureMu: 1.08,
          isDrsZone: false,
        },
        {
          cornerNumber: 7,
          name: 'Curva Parabolica (Alboreto)',
          distanceFromStartM: 5200,
          radiusM: 105,
          arcLengthM: 280,
          direction: 'right',
          bankingDeg: 2.8,
          elevationChangeM: 0.5,
          gradientSlopePct: 0.2,
          entrySpeedBenchmarkKmh: 335,
          apexSpeedBenchmarkKmh: 205,
          exitSpeedBenchmarkKmh: 275,
          insideKerb: CircuitGeometryTopographyDatabase.FLAT_FIA_KERB,
          outsideKerb: CircuitGeometryTopographyDatabase.FLAT_FIA_KERB,
          trackWidthM: 15.0,
          surfaceMacroTextureMu: 1.10,
          isDrsZone: true,
        },
      ],
    },
  };
}
