// ============================================================================
// MODULE 5: DRIVETRAIN SALISBURY LSD & ACTIVE TORQUE VECTORING ENGINE
// ============================================================================
// Drivetrain differential and torque vectoring dynamics:
// 1. Salisbury multi-plate mechanical limited-slip differential (LSD)
// 2. Drive ramp angle and coast ramp angle asymmetric locking characteristics
// 3. Static clutch pack preload & dynamic torque bias ratio (TBR)
// 4. Electronic active yaw-vectoring differential (e-Diff) yaw rate feedback
// 5. Half-shaft torsional compliance, axle windup & wheel hop resonance
// ============================================================================

export interface SalisburyLsdConfig {
  driveRampAngleDeg: number;   // e.g. 45 deg (drive locking ramp)
  coastRampAngleDeg: number;   // e.g. 60 deg (coast/braking locking ramp)
  clutchPlateSurfacesCount: number; // e.g. 8 friction surfaces
  plateFrictionCoeff: number;  // e.g. 0.12 (carbon/steel in hypoid oil)
  effectiveClutchRadiusM: number; // e.g. 0.055 m
  staticPreloadTorqueNm: number; // e.g. 80 Nm
  maxLockingTorqueNm: number;  // e.g. 1200 Nm
  halfShaftTorsionalRateNmPerRad: number; // e.g. 18,500 Nm/rad
}

export interface ActiveTorqueVectoringConfig {
  isEnabled: boolean;
  maxVectoringTorqueDeltaNm: number; // e.g. 450 Nm
  yawRateGainNmPerRadS: number;      // Proportional gain on yaw rate error
  understeerMitigationGain: number;  // Over-speeding outer wheel on turn-in
}

export interface DifferentialOperatingInput {
  inputDriveshaftTorqueNm: number; // From gearbox output
  leftWheelSpeedRadS: number;      // Angular velocity of left driven wheel
  rightWheelSpeedRadS: number;     // Angular velocity of right driven wheel
  vehicleSpeedMs: number;
  steeringAngleDeg: number;
  actualYawRateRadS: number;
  dtSeconds: number;
}

export interface DifferentialOutput {
  leftWheelTorqueNm: number;
  rightWheelTorqueNm: number;
  lockingTorqueNm: number;
  lockingPercent: number;          // 0 (open) to 100% (fully locked spool)
  torqueBiasRatio: number;         // T_high / T_low
  activeVectoringDeltaNm: number;
  inducedYawMomentNm: number;      // Corrective yaw moment acting on chassis
  leftHalfShaftWindupRad: number;  // Axle twist angle
  rightHalfShaftWindupRad: number;
  isWheelHopResonanceRisk: boolean;
}

export class DrivetrainDifferentialSolver {
  private static leftShaftAngle: number = 0;
  private static rightShaftAngle: number = 0;

  /**
   * Evaluates Salisbury LSD asymmetric ramp locking, clutch plate normal forces,
   * active torque vectoring, and half-shaft torsional compliance.
   */
  public static evaluateDifferential(
    lsdConfig: SalisburyLsdConfig,
    vectoringConfig: ActiveTorqueVectoringConfig,
    input: DifferentialOperatingInput,
    trackWidthM: number = 1.62
  ): DifferentialOutput {
    const Tin = input.inputDriveshaftTorqueNm;
    const deltaOmega = input.rightWheelSpeedRadS - input.leftWheelSpeedRadS;

    // ------------------------------------------------------------------------
    // 1. SALISBURY LSD DRIVE & COAST RAMP ANGLE MECHANICS
    // ------------------------------------------------------------------------
    // Cross-pins ride on angled ramp surfaces:
    // Driving: F_clamp = (Tin / 2) / (r_cross_pin * tan(theta_drive))
    // Coasting / Braking: F_clamp = (|Tin| / 2) / (r_cross_pin * tan(theta_coast))
    const isDriving = Tin >= 0;
    const rampAngleDeg = isDriving ? lsdConfig.driveRampAngleDeg : lsdConfig.coastRampAngleDeg;
    const rampRad = (Math.max(15, Math.min(85, rampAngleDeg)) * Math.PI) / 180.0;

    const rPin = 0.032; // Cross pin pitch radius (m)
    const pinSeparationForceN = (Math.abs(Tin) / 2.0) / (rPin * Math.tan(rampRad));

    // Dynamic friction torque generated by clutch pack:
    // T_clutch = Preload + F_clamp * mu * r_mean * n_plates
    const dynamicClutchTorque = pinSeparationForceN * lsdConfig.plateFrictionCoeff * lsdConfig.effectiveClutchRadiusM * lsdConfig.clutchPlateSurfacesCount;
    let totalLockingTorque = lsdConfig.staticPreloadTorqueNm + dynamicClutchTorque;
    totalLockingTorque = Math.min(lsdConfig.maxLockingTorqueNm, totalLockingTorque);

    // Locking torque opposes differential wheel speed direction
    const lockDirection = Math.sign(deltaOmega);
    let diffTorqueTransfer = totalLockingTorque * (Math.abs(deltaOmega) > 0.05 ? lockDirection : deltaOmega / 0.05);

    // ------------------------------------------------------------------------
    // 2. ACTIVE ELECTRONIC TORQUE VECTORING (e-Diff / Dual-Motor)
    // ------------------------------------------------------------------------
    let vectoringDelta = 0;
    if (vectoringConfig.isEnabled) {
      // Calculate target Ackerman yaw rate: r_target = (v / L) * tan(delta_steer)
      const steerRad = (input.steeringAngleDeg * Math.PI) / 180.0;
      const targetYawRate = (input.vehicleSpeedMs / 2.7) * Math.sin(steerRad);
      const yawRateError = targetYawRate - input.actualYawRateRadS;

      // Positive error = understeer -> overspeed outside wheel (transfer torque to outer)
      vectoringDelta = yawRateError * vectoringConfig.yawRateGainNmPerRadS;
      vectoringDelta = Math.max(-vectoringConfig.maxVectoringTorqueDeltaNm, Math.min(vectoringConfig.maxVectoringTorqueDeltaNm, vectoringDelta));
    }

    // ------------------------------------------------------------------------
    // 3. TORQUE DISTRIBUTION TO LEFT AND RIGHT WHEELS
    // ------------------------------------------------------------------------
    // Base 50/50 split of input torque +/- differential locking +/- vectoring
    const baseTorquePerWheel = Tin / 2.0;
    let leftTorque = baseTorquePerWheel + (diffTorqueTransfer * 0.5) - (vectoringDelta * 0.5);
    let rightTorque = baseTorquePerWheel - (diffTorqueTransfer * 0.5) + (vectoringDelta * 0.5);

    // Prevent negative torque on driving wheel unless regenerative/braking
    if (Tin > 0) {
      if (leftTorque < 0) {
        rightTorque += leftTorque;
        leftTorque = 0;
      } else if (rightTorque < 0) {
        leftTorque += rightTorque;
        rightTorque = 0;
      }
    }

    // Torque Bias Ratio (TBR): T_high / T_low
    const tHigh = Math.max(leftTorque, rightTorque);
    const tLow = Math.max(1.0, Math.min(leftTorque, rightTorque));
    const tbr = tHigh / tLow;

    const lockPercent = Math.min(100.0, (totalLockingTorque / lsdConfig.maxLockingTorqueNm) * 100.0);

    // Induced corrective yaw moment acting on vehicle chassis:
    // M_z = ((F_x_right - F_x_left) * trackWidth) / 2
    const rWheel = 0.33;
    const forceDeltaX = (rightTorque - leftTorque) / rWheel;
    const inducedYawMomentNm = (forceDeltaX * trackWidthM) / 2.0;

    // ------------------------------------------------------------------------
    // 4. HALF-SHAFT TORSIONAL WINDUP & WHEEL HOP RESONANCE
    // ------------------------------------------------------------------------
    const dt = Math.max(0.001, input.dtSeconds);
    const kShaft = lsdConfig.halfShaftTorsionalRateNmPerRad;

    // Twist angle = Torque / k_shaft
    DrivetrainDifferentialSolver.leftShaftAngle = leftTorque / kShaft;
    DrivetrainDifferentialSolver.rightShaftAngle = rightTorque / kShaft;

    // Wheel hop resonance check: axle windup + rapid slip oscillations (typically 12-16 Hz)
    const shaftNaturalFreqHz = (1.0 / (2.0 * Math.PI)) * Math.sqrt(kShaft / 1.8);
    const isResonance = Math.abs(deltaOmega) > 25.0 && Math.abs(Tin) > 400.0 && shaftNaturalFreqHz > 10.0;

    return {
      leftWheelTorqueNm: Number(leftTorque.toFixed(1)),
      rightWheelTorqueNm: Number(rightTorque.toFixed(1)),
      lockingTorqueNm: Number(totalLockingTorque.toFixed(1)),
      lockingPercent: Number(lockPercent.toFixed(1)),
      torqueBiasRatio: Number(tbr.toFixed(2)),
      activeVectoringDeltaNm: Number(vectoringDelta.toFixed(1)),
      inducedYawMomentNm: Number(inducedYawMomentNm.toFixed(1)),
      leftHalfShaftWindupRad: Number(DrivetrainDifferentialSolver.leftShaftAngle.toFixed(4)),
      rightHalfShaftWindupRad: Number(DrivetrainDifferentialSolver.rightShaftAngle.toFixed(4)),
      isWheelHopResonanceRisk: isResonance,
    };
  }
}
