import { ComponentId, AssemblyPhase } from "../../sim/assemblyTypes";

export interface ComponentAnimationConfig {
  id: ComponentId;
  timings: {
    picking: number;
    traveling: number;
    aligning: number;
    inserting: number;
    locking: number;
    confirming: number;
  };
  totalDuration: number;
  rotationDegrees: number;
  vibrateOnInsert: boolean;
  flashOnLock: boolean;
  repeatCount: number;
  // Physics Spring Dynamics Parameters
  springStiffness: number;
  springDamping: number;
  springMass: number;
  // Trajectory Arc Offset
  arcControlPoints: { x: number; y: number };
  // Sub-step Torque Count (e.g. 4x head bolts)
  torqueSubSteps?: number;
}

export const COMPONENT_ANIMATION_PRESETS: Record<ComponentId, ComponentAnimationConfig> = {
  block: {
    id: "block",
    timings: { picking: 350, traveling: 500, aligning: 300, inserting: 400, locking: 250, confirming: 350 },
    totalDuration: 2150,
    rotationDegrees: 0,
    vibrateOnInsert: true,
    flashOnLock: true,
    repeatCount: 1,
    springStiffness: 120,
    springDamping: 14,
    springMass: 3.5,
    arcControlPoints: { x: -40, y: -60 },
  },
  crankshaft: {
    id: "crankshaft",
    timings: { picking: 400, traveling: 600, aligning: 350, inserting: 500, locking: 250, confirming: 400 },
    totalDuration: 2500,
    rotationDegrees: 90,
    vibrateOnInsert: true,
    flashOnLock: true,
    repeatCount: 1,
    springStiffness: 140,
    springDamping: 12,
    springMass: 2.8,
    arcControlPoints: { x: 50, y: -80 },
  },
  pistons: {
    id: "pistons",
    timings: { picking: 300, traveling: 450, aligning: 300, inserting: 400, locking: 200, confirming: 350 },
    totalDuration: 2000,
    rotationDegrees: 0,
    vibrateOnInsert: true,
    flashOnLock: true,
    repeatCount: 4,
    springStiffness: 180,
    springDamping: 10,
    springMass: 1.2,
    arcControlPoints: { x: -20, y: -40 },
  },
  rods: {
    id: "rods",
    timings: { picking: 300, traveling: 400, aligning: 250, inserting: 350, locking: 200, confirming: 300 },
    totalDuration: 1800,
    rotationDegrees: 15,
    vibrateOnInsert: true,
    flashOnLock: false,
    repeatCount: 4,
    springStiffness: 200,
    springDamping: 9,
    springMass: 1.0,
    arcControlPoints: { x: 30, y: -30 },
  },
  oil_pan: {
    id: "oil_pan",
    timings: { picking: 300, traveling: 450, aligning: 250, inserting: 300, locking: 200, confirming: 300 },
    totalDuration: 1800,
    rotationDegrees: 0,
    vibrateOnInsert: false,
    flashOnLock: false,
    repeatCount: 1,
    springStiffness: 160,
    springDamping: 11,
    springMass: 1.8,
    arcControlPoints: { x: 0, y: 50 },
  },
  head_gasket: {
    id: "head_gasket",
    timings: { picking: 250, traveling: 350, aligning: 200, inserting: 250, locking: 150, confirming: 250 },
    totalDuration: 1450,
    rotationDegrees: 0,
    vibrateOnInsert: false,
    flashOnLock: false,
    repeatCount: 1,
    springStiffness: 220,
    springDamping: 8,
    springMass: 0.6,
    arcControlPoints: { x: 0, y: -40 },
  },
  cylinder_head: {
    id: "cylinder_head",
    timings: { picking: 400, traveling: 550, aligning: 350, inserting: 450, locking: 300, confirming: 400 },
    totalDuration: 2450,
    rotationDegrees: 0,
    vibrateOnInsert: true,
    flashOnLock: true,
    repeatCount: 1,
    springStiffness: 130,
    springDamping: 13,
    springMass: 3.0,
    arcControlPoints: { x: 40, y: -70 },
    torqueSubSteps: 6,
  },
  camshaft: {
    id: "camshaft",
    timings: { picking: 300, traveling: 450, aligning: 300, inserting: 350, locking: 200, confirming: 300 },
    totalDuration: 1900,
    rotationDegrees: 180,
    vibrateOnInsert: false,
    flashOnLock: false,
    repeatCount: 1,
    springStiffness: 170,
    springDamping: 10,
    springMass: 1.5,
    arcControlPoints: { x: -30, y: -50 },
  },
  valves: {
    id: "valves",
    timings: { picking: 250, traveling: 350, aligning: 250, inserting: 300, locking: 150, confirming: 250 },
    totalDuration: 1550,
    rotationDegrees: 0,
    vibrateOnInsert: false,
    flashOnLock: false,
    repeatCount: 16,
    springStiffness: 240,
    springDamping: 7,
    springMass: 0.5,
    arcControlPoints: { x: 0, y: -30 },
  },
  intake_manifold: {
    id: "intake_manifold",
    timings: { picking: 300, traveling: 450, aligning: 300, inserting: 350, locking: 200, confirming: 300 },
    totalDuration: 1900,
    rotationDegrees: -15,
    vibrateOnInsert: false,
    flashOnLock: false,
    repeatCount: 1,
    springStiffness: 160,
    springDamping: 10,
    springMass: 1.4,
    arcControlPoints: { x: -60, y: -30 },
  },
  exhaust_headers: {
    id: "exhaust_headers",
    timings: { picking: 300, traveling: 450, aligning: 300, inserting: 350, locking: 200, confirming: 300 },
    totalDuration: 1900,
    rotationDegrees: 15,
    vibrateOnInsert: false,
    flashOnLock: false,
    repeatCount: 1,
    springStiffness: 160,
    springDamping: 10,
    springMass: 1.6,
    arcControlPoints: { x: 60, y: -30 },
  },
  turbocharger: {
    id: "turbocharger",
    timings: { picking: 450, traveling: 650, aligning: 400, inserting: 500, locking: 300, confirming: 450 },
    totalDuration: 2750,
    rotationDegrees: 45,
    vibrateOnInsert: true,
    flashOnLock: true,
    repeatCount: 1,
    springStiffness: 130,
    springDamping: 12,
    springMass: 2.2,
    arcControlPoints: { x: 80, y: 40 },
  },
  hybrid_motor: {
    id: "hybrid_motor",
    timings: { picking: 350, traveling: 500, aligning: 300, inserting: 400, locking: 250, confirming: 350 },
    totalDuration: 2150,
    rotationDegrees: 0,
    vibrateOnInsert: true,
    flashOnLock: true,
    repeatCount: 1,
    springStiffness: 140,
    springDamping: 12,
    springMass: 2.5,
    arcControlPoints: { x: -60, y: 40 },
  },
  inverter_ecu: {
    id: "inverter_ecu",
    timings: { picking: 250, traveling: 350, aligning: 250, inserting: 300, locking: 150, confirming: 250 },
    totalDuration: 1550,
    rotationDegrees: 0,
    vibrateOnInsert: false,
    flashOnLock: true,
    repeatCount: 1,
    springStiffness: 200,
    springDamping: 9,
    springMass: 0.8,
    arcControlPoints: { x: -60, y: -40 },
  },
  // Vehicle Subsystem Presets
  chassis_frame: {
    id: "block",
    timings: { picking: 400, traveling: 600, aligning: 400, inserting: 500, locking: 300, confirming: 400 },
    totalDuration: 2600,
    rotationDegrees: 0,
    vibrateOnInsert: true,
    flashOnLock: true,
    repeatCount: 1,
    springStiffness: 100,
    springDamping: 15,
    springMass: 4.0,
    arcControlPoints: { x: 0, y: -80 },
  },
  engine_bay: {
    id: "block",
    timings: { picking: 350, traveling: 500, aligning: 350, inserting: 450, locking: 250, confirming: 350 },
    totalDuration: 2250,
    rotationDegrees: 0,
    vibrateOnInsert: true,
    flashOnLock: true,
    repeatCount: 1,
    springStiffness: 120,
    springDamping: 14,
    springMass: 3.0,
    arcControlPoints: { x: 40, y: -50 },
  },
  transmission: {
    id: "crankshaft",
    timings: { picking: 300, traveling: 450, aligning: 300, inserting: 400, locking: 250, confirming: 350 },
    totalDuration: 2050,
    rotationDegrees: 15,
    vibrateOnInsert: true,
    flashOnLock: true,
    repeatCount: 1,
    springStiffness: 140,
    springDamping: 12,
    springMass: 2.2,
    arcControlPoints: { x: -30, y: 30 },
  },
  exhaust_system: {
    id: "exhaust_manifold",
    timings: { picking: 300, traveling: 400, aligning: 250, inserting: 350, locking: 200, confirming: 300 },
    totalDuration: 1800,
    rotationDegrees: 0,
    vibrateOnInsert: false,
    flashOnLock: false,
    repeatCount: 1,
    springStiffness: 160,
    springDamping: 11,
    springMass: 1.5,
    arcControlPoints: { x: 50, y: 20 },
  },
  suspension_front: {
    id: "pistons",
    timings: { picking: 300, traveling: 400, aligning: 250, inserting: 350, locking: 200, confirming: 300 },
    totalDuration: 1800,
    rotationDegrees: 0,
    vibrateOnInsert: true,
    flashOnLock: true,
    repeatCount: 2,
    springStiffness: 170,
    springDamping: 10,
    springMass: 1.4,
    arcControlPoints: { x: -40, y: -40 },
  },
  suspension_rear: {
    id: "pistons",
    timings: { picking: 300, traveling: 400, aligning: 250, inserting: 350, locking: 200, confirming: 300 },
    totalDuration: 1800,
    rotationDegrees: 0,
    vibrateOnInsert: true,
    flashOnLock: true,
    repeatCount: 2,
    springStiffness: 170,
    springDamping: 10,
    springMass: 1.4,
    arcControlPoints: { x: 40, y: -40 },
  },
  brakes: {
    id: "valves",
    timings: { picking: 250, traveling: 350, aligning: 250, inserting: 300, locking: 200, confirming: 250 },
    totalDuration: 1600,
    rotationDegrees: 0,
    vibrateOnInsert: true,
    flashOnLock: true,
    repeatCount: 4,
    springStiffness: 190,
    springDamping: 9,
    springMass: 1.0,
    arcControlPoints: { x: 0, y: 0 },
  },
  wheels_tires: {
    id: "crankshaft",
    timings: { picking: 350, traveling: 450, aligning: 300, inserting: 400, locking: 250, confirming: 350 },
    totalDuration: 2100,
    rotationDegrees: 360,
    vibrateOnInsert: true,
    flashOnLock: true,
    repeatCount: 4,
    springStiffness: 150,
    springDamping: 12,
    springMass: 2.0,
    arcControlPoints: { x: 0, y: 60 },
  },
  aero_package: {
    id: "intake_manifold",
    timings: { picking: 300, traveling: 400, aligning: 250, inserting: 350, locking: 200, confirming: 300 },
    totalDuration: 1800,
    rotationDegrees: 0,
    vibrateOnInsert: false,
    flashOnLock: false,
    repeatCount: 1,
    springStiffness: 160,
    springDamping: 11,
    springMass: 1.2,
    arcControlPoints: { x: 60, y: -30 },
  },
  electronics_ecu: {
    id: "inverter_ecu",
    timings: { picking: 250, traveling: 350, aligning: 200, inserting: 250, locking: 150, confirming: 250 },
    totalDuration: 1450,
    rotationDegrees: 0,
    vibrateOnInsert: false,
    flashOnLock: true,
    repeatCount: 1,
    springStiffness: 200,
    springDamping: 9,
    springMass: 0.8,
    arcControlPoints: { x: 0, y: -30 },
  },
};

export const ASSEMBLY_PHASE_ORDER: AssemblyPhase[] = [
  "picking",
  "traveling",
  "aligning",
  "inserting",
  "locking",
  "confirming",
];
