// ============================================================================
// ENGINE GLB ANIMATOR — DEEP KINEMATIC GLB NODE BINDER & MESH SYNCHRONIZER
// ============================================================================
// Binds to the procedural V12 twin-turbo racing engine GLB (generated by
// scripts/blender/generate_realistic_engine.py) and drives:
// - Crankshaft_Kinematic_Pivot: main journal, 12 counterweight throws & flywheel
// - 12 Piston_Assembly_Cyl_* empties reciprocating along their 60° V-bank bores
// - 4 Camshaft_Intake/Exhaust_{Left|Right} shafts at half crankshaft speed (ω/2)
// - Front accessory pulleys (harmonic balancer, alternator, water pump)
// - Synchronized spark ignition flash & power stroke combustion flame kernels
// - Exhaust header primary heat pulses
// - Real-time Cylinder Cutaway (X-Ray) mode & Exploded View mode
// ============================================================================

import * as THREE from 'three';
import {
  solveCylinderCycle,
  V12_FIRING_ORDER_DEGREES,
  getV12PistonPhaseDeg,
  PISTON_CONFIGS,
  type CylinderCycleState,
  type EngineType,
} from './engineRuntimeAnimations';
import type { EngineSimulationSnapshot } from '../physics/EngineSimulationState';

export interface EngineGlbAnimatorConfig {
  engineType?: EngineType;
  cutawayEnabled?: boolean;
  explodedFactor?: number; // 0.0 to 1.0
  combustionVfxEnabled?: boolean;
}

interface BoundPiston {
  /** Piston_Assembly_Cyl_N kinematic empty (owns the crown & conrod meshes). */
  node: THREE.Object3D;
  cylinderIndex: number;
  initialPos: THREE.Vector3;
  /** Unit vector along the cylinder bore (60° V: tilted ±30° around Y in X-Z). */
  boreDir: THREE.Vector3;
  strokeOffsetDeg: number;
}

interface BoundCamshaft {
  /** Camshaft_{Intake|Exhaust}_{Left|Right} kinematic empty. */
  node: THREE.Object3D;
  bank: 'intake' | 'exhaust';
}

interface BoundPulley {
  node: THREE.Object3D;
  ratio: number;
}

interface BoundInjector {
  injectorNode: THREE.Object3D;
  cylinderIndex: number;
  sprayConeMesh: THREE.Mesh;
  sprayConeMat: THREE.MeshBasicMaterial;
  nozzleLed: THREE.Mesh;
  nozzleLedMat: THREE.MeshBasicMaterial;
}

export class EngineGlbAnimator {
  private rootModel: THREE.Object3D | null = null;
  private isGlbBound: boolean = false;

  // Bound Mechanical Nodes
  private crankshaftPivot: THREE.Object3D | null = null;
  private pistons: BoundPiston[] = [];
  private camshafts: BoundCamshaft[] = [];
  private pulleys: BoundPulley[] = [];
  private injectors: BoundInjector[] = [];
  private headerPipes: THREE.Mesh[] = [];

  // VFX Nodes (Created & Attached to Model)
  private vfxGroup: THREE.Group = new THREE.Group();
  private sparkLights: THREE.PointLight[] = [];
  private combustionSpheres: THREE.Mesh[] = [];
  private combustionMats: THREE.MeshBasicMaterial[] = [];

  // Cutaway (X-Ray) Caches
  private cutawayMeshes: { mesh: THREE.Mesh; originalMat: THREE.Material | THREE.Material[] }[] = [];
  private cutawayGlassMat: THREE.MeshPhysicalMaterial;
  private isCutawayActive: boolean = false;

  // Exploded View Subsystem Groups
  private explodedGroups: {
    node: THREE.Object3D;
    initialPos: THREE.Vector3;
    vector: THREE.Vector3;
  }[] = [];

  // Live Simulation States
  private latestSnapshot: EngineSimulationSnapshot | null = null;
  private cylinderCycleStates: CylinderCycleState[] = [];

  constructor() {
    this.vfxGroup.name = 'Engine_Combustion_VFX';

    // Premium Scratch-Resistant Quartz Glass for Cutaway X-Ray Mode
    this.cutawayGlassMat = new THREE.MeshPhysicalMaterial({
      color: 0xa5b4fc,
      metalness: 0.1,
      roughness: 0.12,
      transmission: 0.82,
      transparent: true,
      opacity: 0.38,
      ior: 1.52,
      reflectivity: 0.6,
      clearcoat: 0.8,
      clearcoatRoughness: 0.1,
      wireframe: false,
    });
  }

  /** World-space cylinder bore centers (mirrors generate_realistic_engine.py layout). */
  private static getCylinderPosition(cylinderNumber1Based: number): THREE.Vector3 {
    // Odd cylinders = Left bank (bank sign -1), even = Right bank (+1)
    const bank = cylinderNumber1Based % 2 === 1 ? -1 : 1;
    const c = Math.floor((cylinderNumber1Based - 1) / 2);
    const cy = -0.35 + c * 0.14;
    return new THREE.Vector3(bank * 0.13, cy, 0.22);
  }

  /**
   * Binds to the loaded Three.js GLB model hierarchy and caches all kinematic nodes.
   */
  public bindModel(model: THREE.Object3D): boolean {
    this.rootModel = model;
    this.pistons = [];
    this.camshafts = [];
    this.pulleys = [];
    this.injectors = [];
    this.cutawayMeshes = [];
    this.explodedGroups = [];
    this.headerPipes = [];

    // Map all nodes by exact name for quick lookup
    const nodeMap = new Map<string, THREE.Object3D>();
    model.traverse((child) => {
      if (child.name) {
        nodeMap.set(child.name, child);
      }
    });

    // 1. Bind Crankshaft Kinematic Pivot (main journal + 12 throws + flywheel)
    this.crankshaftPivot = nodeMap.get('Crankshaft_Kinematic_Pivot') || null;

    // 2. Bind 12 Pistons & Connecting Rods (owned by Piston_Assembly_Cyl_N empties)
    // Odd = Left Bank (-30° around Y, toward -X), Even = Right Bank (+30° toward +X)
    const sin30 = Math.sin((30 * Math.PI) / 180);
    const cos30 = Math.cos((30 * Math.PI) / 180);

    for (let i = 1; i <= 12; i++) {
      const pNode = nodeMap.get(`Piston_Assembly_Cyl_${i}`);
      if (!pNode) continue;

      const bankSign = i % 2 === 1 ? -1 : 1;
      this.pistons.push({
        node: pNode,
        cylinderIndex: i - 1,
        initialPos: pNode.position.clone(),
        boreDir: new THREE.Vector3(bankSign * sin30, 0, cos30).normalize(),
        strokeOffsetDeg: getV12PistonPhaseDeg(i - 1),
      });
    }

    // 3. Bind 4 Dual Overhead Camshafts (Intake & Exhaust, Left & Right Banks)
    for (const side of ['Left', 'Right'] as const) {
      for (const camType of ['Intake', 'Exhaust'] as const) {
        const camNode = nodeMap.get(`Camshaft_${camType}_${side}`);
        if (camNode) {
          this.camshafts.push({
            node: camNode,
            bank: camType === 'Intake' ? 'intake' : 'exhaust',
          });
        }
      }
    }

    // 4. Bind Front Accessory Drive Pulleys
    const pulleyDefs: { name: string; ratio: number }[] = [
      { name: 'Harmonic_Balancer_Pulley', ratio: 1.0 },
      { name: 'Alternator_Drive_Pulley', ratio: 2.2 },
      { name: 'Water_Pump_Drive_Pulley', ratio: 1.35 },
    ];
    for (const p of pulleyDefs) {
      const pNode = nodeMap.get(p.name);
      if (pNode) {
        this.pulleys.push({ node: pNode, ratio: p.ratio });
      }
    }

    // 5. Bind Exhaust Header Primary Pipes for Exhaust Wave Glow
    for (const side of ['Left', 'Right'] as const) {
      for (let h = 1; h <= 6; h++) {
        const pipe = nodeMap.get(`Exhaust_Header_Runner_${side}_${h}`) as THREE.Mesh;
        if (pipe && pipe.isMesh) {
          this.headerPipes.push(pipe);
        }
      }
    }

    // 6. Collect Meshes for Cutaway (X-Ray) Mode
    const cutawayNames = [
      'Engine_Block_V12',
      'Cylinder_Head_Right',
      'Cylinder_Head_Left',
      'Valve_Cover_Right',
      'Valve_Cover_Left',
    ];
    model.traverse((child) => {
      if ((child as THREE.Mesh).isMesh) {
        const mesh = child as THREE.Mesh;
        for (const name of cutawayNames) {
          if (mesh.name.includes(name) || (mesh.parent && mesh.parent.name.includes(name))) {
            this.cutawayMeshes.push({
              mesh,
              originalMat: Array.isArray(mesh.material) ? [...mesh.material] : mesh.material,
            });
            break;
          }
        }
      }
    });

    // 7. Configure Exploded View Groups (actual GLB subsystem node names)
    const explodeDefs: { name: string; vec: [number, number, number] }[] = [
      { name: 'Cylinder_Head_Left', vec: [0, 0, 0.22] },
      { name: 'Cylinder_Head_Right', vec: [0, 0, 0.22] },
      { name: 'Valve_Cover_Left', vec: [0, 0, 0.36] },
      { name: 'Valve_Cover_Right', vec: [0, 0, 0.36] },
      { name: 'Intake_Plenum_Carbon_Left', vec: [0, 0, 0.30] },
      { name: 'Intake_Plenum_Carbon_Right', vec: [0, 0, 0.30] },
      { name: 'Throttle_Body_Left', vec: [0, 0, 0.32] },
      { name: 'Throttle_Body_Right', vec: [0, 0, 0.32] },
      { name: 'Turbocharger_Assembly_Left', vec: [-0.44, 0, 0] },
      { name: 'Turbocharger_Assembly_Right', vec: [0.44, 0, 0] },
      { name: 'Dry_Sump_Oil_Pan', vec: [0, 0, -0.26] },
      { name: 'Harmonic_Balancer_Pulley', vec: [0, 0.30, 0] },
      { name: 'Alternator_Drive_Pulley', vec: [0, 0.30, 0] },
      { name: 'Water_Pump_Drive_Pulley', vec: [0, 0.30, 0] },
      { name: 'Serpentine_Accessory_Belt', vec: [0, 0.30, 0] },
    ];
    for (const side of ['Left', 'Right'] as const) {
      const sideVec = side === 'Left' ? -0.18 : 0.18;
      for (let h = 1; h <= 6; h++) {
        explodeDefs.push({ name: `Exhaust_Header_Runner_${side}_${h}`, vec: [sideVec, 0, 0.20] });
      }
    }

    for (const exp of explodeDefs) {
      const grp = nodeMap.get(exp.name);
      if (grp) {
        this.explodedGroups.push({
          node: grp,
          initialPos: grp.position.clone(),
          vector: new THREE.Vector3(...exp.vec),
        });
      }
    }

    // 8. Setup Combustion & Spark VFX Layer
    this.setupCombustionVfx(model);

    this.isGlbBound = true;
    return true;
  }

  /**
   * Initializes real-time combustion chamber fire glow spheres and spark flash lights.
   * Positioned at the actual cylinder head dome centers of the procedural V12 GLB.
   */
  private setupCombustionVfx(model: THREE.Object3D): void {
    // Clean old VFX if any
    while (this.vfxGroup.children.length > 0) {
      this.vfxGroup.remove(this.vfxGroup.children[0]);
    }
    this.sparkLights = [];
    this.combustionSpheres = [];
    this.combustionMats = [];

    // Create 12 combustion glow kernels positioned in each cylinder head dome
    const sphereGeo = new THREE.SphereGeometry(0.024, 12, 12);

    for (let i = 1; i <= 12; i++) {
      const bore = EngineGlbAnimator.getCylinderPosition(i);
      // Head dome sits ~0.14 above the liner center in the generated model
      const pos = new THREE.Vector3(bore.x, bore.y, bore.z + 0.16);

      // Emissive combustion fireball mesh
      const mat = new THREE.MeshBasicMaterial({
        color: 0xff3b00,
        transparent: true,
        opacity: 0.0,
      });
      const sphere = new THREE.Mesh(sphereGeo, mat);
      sphere.position.copy(pos);
      sphere.scale.set(0.1, 0.1, 0.1);
      sphere.name = `Combustion_Kernel_Cyl_${i}`;

      this.combustionMats.push(mat);
      this.combustionSpheres.push(sphere);
      this.vfxGroup.add(sphere);

      // High-intensity point light for ignition spark flash
      const sparkLight = new THREE.PointLight(0xffffff, 0, 0.25);
      sparkLight.position.copy(pos);
      sparkLight.position.z += 0.015;
      sparkLight.name = `Spark_Light_Cyl_${i}`;
      this.sparkLights.push(sparkLight);
      this.vfxGroup.add(sparkLight);
    }

    model.add(this.vfxGroup);
  }

  /**
   * Main Frame Tick: Updates all mechanical transforms, 4-stroke cycle, and VFX.
   */
  public update(snapshot: EngineSimulationSnapshot): void {
    this.latestSnapshot = snapshot;
    if (!this.isGlbBound || !this.rootModel) return;

    const crankAngleDeg = snapshot.crankAngleDeg;
    const crankAngleRad = (crankAngleDeg * Math.PI) / 180;
    const rpm = snapshot.rpm;
    const throttle = snapshot.throttle;
    const isEngineRunning = snapshot.state !== 'OFF';

    // ── 1. Crankshaft Main Assembly Rotation ──
    // The procedural GLB runs the crank along Y through (0, 0, 0.06); rotating
    // the kinematic pivot spins the main journal, 12 counterweight throws and
    // the dual-mass flywheel together.
    if (this.crankshaftPivot) {
      this.crankshaftPivot.rotation.y = crankAngleRad;
    }

    // ── 2. 12 Pistons & Connecting Rods — Exact Slider-Crank Motion ──
    this.cylinderCycleStates = [];

    for (let i = 0; i < this.pistons.length; i++) {
      const p = this.pistons[i];
      const cycleState = solveCylinderCycle(
        p.cylinderIndex,
        crankAngleDeg,
        V12_FIRING_ORDER_DEGREES[p.cylinderIndex] ?? 0,
        PISTON_CONFIGS.V12,
        undefined,
        p.strokeOffsetDeg
      );
      this.cylinderCycleStates.push(cycleState);

      // Slider-crank displacement (0 at TDC, -0.076m at BDC) along the 60° V bore
      const dispM = cycleState.pistonDisplacementMm / 1000.0;
      p.node.position.copy(p.initialPos).addScaledVector(p.boreDir, dispM);
    }

    // ── 3. Camshafts at Half Crankshaft Speed (ω/2) ──
    const camAngleRad = crankAngleRad * 0.5;
    for (let i = 0; i < this.camshafts.length; i++) {
      this.camshafts[i].node.rotation.y = camAngleRad;
    }

    // ── 4. Front Accessory Pulleys ──
    for (let i = 0; i < this.pulleys.length; i++) {
      const p = this.pulleys[i];
      p.node.rotation.y = crankAngleRad * p.ratio;
    }

    // ── 5. Combustion & Spark Ignition VFX ──
    if (isEngineRunning) {
      for (let i = 0; i < this.cylinderCycleStates.length && i < 12; i++) {
        const state = this.cylinderCycleStates[i];
        const sparkLight = this.sparkLights[i];
        const sphereMesh = this.combustionSpheres[i];
        const sphereMat = this.combustionMats[i];

        if (sparkLight && sphereMesh && sphereMat) {
          // Spark Plug Flash: intense burst at TDC ignition point
          if (state.isSparkFiring) {
            sparkLight.intensity = 2.8;
            sparkLight.color.setHex(0xffffff); // Brilliant electric white
            sphereMat.color.setHex(0xffffff);
            sphereMat.opacity = 0.95;
            sphereMesh.scale.setScalar(1.2);
          }
          // Power Stroke: fireball expanding down cylinder
          else if (state.phase === 'POWER') {
            sparkLight.intensity = state.combustionIntensity * 1.5;
            sparkLight.color.setHex(0xff4400); // Fiery orange
            sphereMat.color.setHex(parseInt(state.glowColorHex.replace('#', '0x'), 16));
            sphereMat.opacity = state.combustionIntensity * 0.85;
            const expansion = 0.4 + (1.0 - state.pistonNormalized01) * 1.4;
            sphereMesh.scale.set(expansion, expansion, expansion * 1.2);
          }
          // Intake & Compression & Exhaust
          else {
            sparkLight.intensity = 0;
            sphereMat.color.setHex(parseInt(state.glowColorHex.replace('#', '0x'), 16));
            sphereMat.opacity = state.combustionIntensity * 0.35;
            sphereMesh.scale.setScalar(0.5);
          }
        }
      }

      // Exhaust Header Thermal Pulse
      for (let h = 0; h < this.headerPipes.length; h++) {
        const pipe = this.headerPipes[h];
        const mat = pipe.material as THREE.MeshStandardMaterial;
        if (mat && mat.emissive) {
          const isOverrun = snapshot.state === 'ENGINE_BRAKING' || snapshot.state === 'REV_LIMITER';
          const headerIntensity = Math.min(1.0, (rpm / 8500) * 0.8 + (isOverrun ? 0.35 : 0.0));
          mat.emissive.setRGB(headerIntensity * 0.95, headerIntensity * 0.28, 0.04);
          mat.emissiveIntensity = headerIntensity * 2.2;
        }
      }
    } else {
      // Engine OFF: extinguish lights
      for (let i = 0; i < this.sparkLights.length; i++) {
        this.sparkLights[i].intensity = 0;
        this.combustionMats[i].opacity = 0;
      }
    }

    // ── 6. Direct Fuel Injector Mist Pulses (injector nodes absent in the
    //       current procedural GLB — reserved for future high-fidelity assets) ──
    if (isEngineRunning) {
      for (let i = 0; i < this.injectors.length; i++) {
        const inj = this.injectors[i];
        const state = this.cylinderCycleStates[inj.cylinderIndex];
        if (!state) continue;

        // Fresh intake charge injection pulse: active between 15° and 135° of 720° cycle
        const cycleAngle = state.cycleAngleDeg;
        const isInjecting = cycleAngle >= 15 && cycleAngle <= 135;

        if (isInjecting) {
          // Bell-curve atomized pulse intensity
          const normTime = (cycleAngle - 15) / 120;
          const pulseShape = Math.sin(normTime * Math.PI);
          const mistAlpha = (0.35 + throttle * 0.55) * pulseShape;

          inj.sprayConeMat.opacity = mistAlpha;
          inj.nozzleLedMat.opacity = Math.min(1.0, mistAlpha * 1.6);

          const sprayScale = 0.85 + pulseShape * 0.65 + throttle * 0.35;
          inj.sprayConeMesh.scale.set(sprayScale, sprayScale * 1.25, sprayScale);
        } else {
          inj.sprayConeMat.opacity = 0;
          inj.nozzleLedMat.opacity = 0;
        }
      }
    } else {
      for (let i = 0; i < this.injectors.length; i++) {
        this.injectors[i].sprayConeMat.opacity = 0;
        this.injectors[i].nozzleLedMat.opacity = 0;
      }
    }
  }

  /**
   * Toggles Cylinder Cutaway (X-Ray) Mode:
   * Replaces engine block and valve covers with crystal quartz glass to reveal internal moving parts.
   */
  public setCutawayMode(enabled: boolean): void {
    if (this.isCutawayActive === enabled) return;
    this.isCutawayActive = enabled;

    for (let i = 0; i < this.cutawayMeshes.length; i++) {
      const entry = this.cutawayMeshes[i];
      if (enabled) {
        entry.mesh.material = this.cutawayGlassMat;
      } else {
        entry.mesh.material = entry.originalMat;
      }
    }
  }

  public getIsCutawayActive(): boolean {
    return this.isCutawayActive;
  }

  /**
   * Sets Exploded View Factor (0.0 to 1.0) while preserving synchronized reciprocation.
   */
  public setExplodedFactor(factor: number): void {
    const f = Math.max(0, Math.min(1, factor));
    for (let i = 0; i < this.explodedGroups.length; i++) {
      const entry = this.explodedGroups[i];
      entry.node.position.copy(entry.initialPos).addScaledVector(entry.vector, f);
    }
  }

  public getCylinderCycleStates(): CylinderCycleState[] {
    return this.cylinderCycleStates;
  }

  public dispose(): void {
    if (this.cutawayGlassMat) this.cutawayGlassMat.dispose();
    for (const m of this.combustionMats) m.dispose();
    for (const inj of this.injectors) {
      inj.sprayConeMat.dispose();
      inj.nozzleLedMat.dispose();
    }
  }
}