// ===================================================================
// EXTERIOR VEHICLE ASSEMBLY PRESETS & SPECIFICATION PACKS
// ===================================================================
// Curated factory presets configuring full 40+ component variant maps,
// paint finishes, aero setups, and wheel/tire specs for distinct vehicle archetypes.
// ===================================================================

import type {
  ExteriorEngineeringConfig,
  PaintSystemConfig,
  AeroSurfaceConfig,
  LightingConfig,
  GlassConfig,
  ExteriorWheelConfig,
  ExteriorTireConfig,
  ExteriorBrakeVisualConfig,
} from "../sim/types/exterior";
import type { ExteriorComponentId } from "../sim/exteriorAssemblyTypes";
import type { MaterialGrade } from "../sim/assemblyTypes";
import {
  createDefaultExteriorConfig,
  createDefaultPaintConfig,
  createDefaultAeroConfig,
  createDefaultLightingConfig,
  createDefaultGlassConfig,
  createDefaultWheelConfig,
  createDefaultTireConfig,
  createDefaultBrakeVisualConfig,
} from "../sim/constants/exteriorConstants";

export interface ExteriorPresetSpecification {
  id: string;
  name: string;
  badge: string;
  category: "Motorsport" | "Hypercar" | "Grand Tourer" | "Sport" | "Specialty";
  description: string;
  variants: Record<ExteriorComponentId, MaterialGrade>;
  exteriorConfig: ExteriorEngineeringConfig;
  paintConfig: PaintSystemConfig;
  aeroConfig: AeroSurfaceConfig;
  lightingConfig: LightingConfig;
  glassConfig: GlassConfig;
  wheelConfig: ExteriorWheelConfig;
  tireConfig: ExteriorTireConfig;
  brakeConfig: ExteriorBrakeVisualConfig;
}

// ── 1. GT3 HOMOLOGATION RACE SPEC ──
const GT3_RACE_SPEC: ExteriorPresetSpecification = {
  id: "gt3_homologation_race",
  name: "Apex GT3 Homologation Spec-R",
  badge: "FIA GT3",
  category: "Motorsport",
  description: "Carbon-tub chassis with aggressive aero package, dual-element swan-neck rear wing, lightweight Lexan glass, and centerlock magnesium wheels.",
  variants: {
    chassis_frame: "billet",
    front_subframe: "forged",
    rear_subframe: "forged",
    floor_pan: "billet",
    firewall_bulkhead: "billet",
    a_pillar_assembly: "titanium",
    b_pillar_assembly: "titanium",
    c_pillar_assembly: "titanium",
    rocker_panels: "billet",
    crash_boxes_front_rear: "forged",
    roll_cage_safety: "titanium",
    suspension_front_assembly: "titanium",
    suspension_rear_assembly: "titanium",
    brake_rotors_calipers: "titanium",
    wheels_tires_assembly: "titanium",
    hood_panel: "billet",
    front_fenders: "billet",
    doors_assembly: "billet",
    rear_quarter_panels: "billet",
    trunk_decklid: "billet",
    roof_panel: "billet",
    front_bumper_fascia: "billet",
    rear_bumper_fascia: "billet",
    front_splitter_tray: "titanium",
    rear_diffuser_tunnel: "titanium",
    side_skirts_aero: "billet",
    rear_wing_spoiler: "titanium",
    canards_dive_planes: "billet",
    hood_fender_vents: "billet",
    windshield_glass: "titanium",
    side_door_glass: "titanium",
    rear_window_backlite: "titanium",
    headlights_matrix: "titanium",
    taillights_oled: "titanium",
    fog_drl_lights: "titanium",
    side_mirrors: "billet",
    front_grille_mesh: "titanium",
    exhaust_tips_surround: "titanium",
    door_handles_latches: "billet",
    wiper_cowl_assembly: "billet",
    badges_emblems: "titanium",
  },
  exteriorConfig: {
    ...createDefaultExteriorConfig(),
    bodyStyle: "gt3_homologation",
    groundClearance: 65,
    sideTumblehomeAngle: 28,
    widebodyFlareFrontMm: 45,
    widebodyFlareRearMm: 65,
  },
  paintConfig: {
    ...createDefaultPaintConfig(),
    finishType: "exposed_tinted_carbon",
    primaryColorHex: "#0a0a0a",
    secondaryColorHex: "#0284c7",
    tertiaryColorHex: "#f59e0b",
    liveryStyle: "gulf_heritage",
  },
  aeroConfig: {
    ...createDefaultAeroConfig(),
    splitterExtensionMm: 160,
    diffuserFinCount: 9,
    wingSpanMm: 1850,
    wingAngleOfAttackDeg: 22,
    wingEndplateHeightMm: 280,
  },
  lightingConfig: {
    ...createDefaultLightingConfig(),
    lensTint: "amber_endurance_yellow",
  },
  glassConfig: {
    ...createDefaultGlassConfig(),
    windshieldGlass: "polycarbonate_lexan_race",
    sideDoorGlass: "polycarbonate_lexan_race",
    rearBackliteGlass: "polycarbonate_lexan_race",
  },
  wheelConfig: {
    ...createDefaultWheelConfig(),
    construction: "forged_magnesium_az91",
    finish: "matte_magnesium",
  },
  tireConfig: {
    ...createDefaultTireConfig(),
    tireCompound: "full_race_slick",
    sidewallLettering: "yellow_pirelli_f1",
  },
  brakeConfig: {
    ...createDefaultBrakeVisualConfig(),
    caliperLogo: "TITANIUM_SPEC_R",
    rotorType: "carbon_carbon_race",
  },
};

// ── 2. HYPERCAR TRACK ATTACK ──
const HYPERCAR_TRACK: ExteriorPresetSpecification = {
  id: "hypercar_track_attack",
  name: "Apex Valkyrie Hypercar Prototype",
  badge: "V12 PROTOTYPE",
  category: "Hypercar",
  description: "Ultra-extreme downforce prototype with underbody Venturi ground effect tunnels, active DRS wing, and forged carbon body panels.",
  variants: {
    chassis_frame: "titanium",
    front_subframe: "titanium",
    rear_subframe: "titanium",
    floor_pan: "titanium",
    firewall_bulkhead: "titanium",
    a_pillar_assembly: "titanium",
    b_pillar_assembly: "titanium",
    c_pillar_assembly: "titanium",
    rocker_panels: "titanium",
    crash_boxes_front_rear: "billet",
    roll_cage_safety: "titanium",
    suspension_front_assembly: "titanium",
    suspension_rear_assembly: "titanium",
    brake_rotors_calipers: "titanium",
    wheels_tires_assembly: "titanium",
    hood_panel: "titanium",
    front_fenders: "titanium",
    doors_assembly: "titanium",
    rear_quarter_panels: "titanium",
    trunk_decklid: "titanium",
    roof_panel: "titanium",
    front_bumper_fascia: "titanium",
    rear_bumper_fascia: "titanium",
    front_splitter_tray: "titanium",
    rear_diffuser_tunnel: "titanium",
    side_skirts_aero: "titanium",
    rear_wing_spoiler: "titanium",
    canards_dive_planes: "titanium",
    hood_fender_vents: "titanium",
    windshield_glass: "billet",
    side_door_glass: "billet",
    rear_window_backlite: "billet",
    headlights_matrix: "titanium",
    taillights_oled: "titanium",
    fog_drl_lights: "titanium",
    side_mirrors: "titanium",
    front_grille_mesh: "titanium",
    exhaust_tips_surround: "titanium",
    door_handles_latches: "titanium",
    wiper_cowl_assembly: "titanium",
    badges_emblems: "titanium",
  },
  exteriorConfig: {
    ...createDefaultExteriorConfig(),
    bodyStyle: "prototype_lmdh",
    doorOpening: "canopy_fighter",
    roofStyle: "active_chute_roof",
    overallHeight: 1110,
    groundClearance: 60,
  },
  paintConfig: {
    ...createDefaultPaintConfig(),
    finishType: "chameleon_colorshift",
    primaryColorHex: "#581c87",
    secondaryColorHex: "#0284c7",
    tertiaryColorHex: "#22c55e",
  },
  aeroConfig: {
    ...createDefaultAeroConfig(),
    underbodyFloorType: "ground_effect_suction_skirts",
    diffuserFinCount: 9,
    wingSpanMm: 1950,
    hasActiveDRS: true,
  },
  lightingConfig: {
    ...createDefaultLightingConfig(),
    headlightTech: "laser_high_beam_phosphor",
  },
  glassConfig: {
    ...createDefaultGlassConfig(),
    windshieldGlass: "gorilla_glass_thin_film",
    sideDoorGlass: "gorilla_glass_thin_film",
  },
  wheelConfig: {
    ...createDefaultWheelConfig(),
    construction: "full_autoclaved_carbon_fiber",
    finish: "raw_gloss_carbon",
  },
  tireConfig: {
    ...createDefaultTireConfig(),
    tireCompound: "track_r_compound",
  },
  brakeConfig: {
    ...createDefaultBrakeVisualConfig(),
    rotorType: "carbon_ceramic_matrix",
    caliperColorHex: "#22c55e",
  },
};

// ── 3. LUXURY GRAND TOURER ──
const LUXURY_GT: ExteriorPresetSpecification = {
  id: "luxury_grand_tourer",
  name: "Apex Continental GT Berlina",
  badge: "V12 COUTURE",
  category: "Grand Tourer",
  description: "Superformed aluminum body closures, triple-coat pearl metallic finish, acoustic double-laminated glass, and subtle active aero elegance.",
  variants: {
    chassis_frame: "forged",
    front_subframe: "forged",
    rear_subframe: "forged",
    floor_pan: "forged",
    firewall_bulkhead: "forged",
    a_pillar_assembly: "forged",
    b_pillar_assembly: "forged",
    c_pillar_assembly: "forged",
    rocker_panels: "forged",
    crash_boxes_front_rear: "forged",
    roll_cage_safety: "cast",
    suspension_front_assembly: "forged",
    suspension_rear_assembly: "forged",
    brake_rotors_calipers: "forged",
    wheels_tires_assembly: "forged",
    hood_panel: "forged",
    front_fenders: "forged",
    doors_assembly: "forged",
    rear_quarter_panels: "forged",
    trunk_decklid: "forged",
    roof_panel: "forged",
    front_bumper_fascia: "forged",
    rear_bumper_fascia: "forged",
    front_splitter_tray: "forged",
    rear_diffuser_tunnel: "forged",
    side_skirts_aero: "forged",
    rear_wing_spoiler: "forged",
    canards_dive_planes: "cast",
    hood_fender_vents: "forged",
    windshield_glass: "forged",
    side_door_glass: "forged",
    rear_window_backlite: "forged",
    headlights_matrix: "forged",
    taillights_oled: "forged",
    fog_drl_lights: "forged",
    side_mirrors: "forged",
    front_grille_mesh: "forged",
    exhaust_tips_surround: "forged",
    door_handles_latches: "forged",
    wiper_cowl_assembly: "forged",
    badges_emblems: "forged",
  },
  exteriorConfig: {
    ...createDefaultExteriorConfig(),
    bodyStyle: "gt_fastback",
    doorOpening: "frameless_coupe",
    roofStyle: "panoramic_electrochromic",
    overallLength: 4890,
    overallHeight: 1280,
    groundClearance: 120,
    widebodyFlareFrontMm: 0,
    widebodyFlareRearMm: 0,
  },
  paintConfig: {
    ...createDefaultPaintConfig(),
    finishType: "tri_coat_pearl_iridescent",
    primaryColorHex: "#064e3b", // British Dark Emerald
    secondaryColorHex: "#e2e8f0",
    tertiaryColorHex: "#f59e0b",
    liveryStyle: "monotone",
    clearCoatGrade: "ultra_high_solid_uhs",
  },
  aeroConfig: {
    ...createDefaultAeroConfig(),
    frontSplitterProfile: "oem_integrated_chin",
    splitterExtensionMm: 35,
    rearWingType: "clean_ducktail_lip",
    wingSpanMm: 1100,
    wingAngleOfAttackDeg: 4,
  },
  lightingConfig: {
    ...createDefaultLightingConfig(),
    headlightTech: "full_matrix_led_84_pixel",
    taillightTech: "flexible_3d_oled_surface",
    projectorBezelFinish: "polished_chrome",
  },
  glassConfig: {
    ...createDefaultGlassConfig(),
    windshieldGlass: "dual_laminated_acoustic",
    sideDoorGlass: "dual_laminated_acoustic",
    roofGlass: "electrochromic_smart_tint",
  },
  wheelConfig: {
    ...createDefaultWheelConfig(),
    spokePattern: "classic_mesh_cross_lace",
    construction: "6061_t6_forged_monoblock",
    finish: "diamond_cut_face",
    centerLockNut: false,
  },
  tireConfig: {
    ...createDefaultTireConfig(),
    tireCompound: "street_comfort",
    sidewallLettering: "none",
  },
  brakeConfig: {
    ...createDefaultBrakeVisualConfig(),
    caliperColorHex: "#1e293b",
    rotorType: "vented_slotted_steel",
  },
};

// ── 4. STREET SPORT COUPE ──
const STREET_SPORT: ExteriorPresetSpecification = {
  id: "street_sport_coupe",
  name: "Apex Carrera Clubsport",
  badge: "CLUBSPORT",
  category: "Sport",
  description: "Balanced lightweight aluminum/composite construction, sport aero package with ducktail spoiler, and high-performance cross-drilled brakes.",
  variants: {
    chassis_frame: "forged",
    front_subframe: "forged",
    rear_subframe: "forged",
    floor_pan: "cast",
    firewall_bulkhead: "cast",
    a_pillar_assembly: "forged",
    b_pillar_assembly: "forged",
    c_pillar_assembly: "forged",
    rocker_panels: "forged",
    crash_boxes_front_rear: "forged",
    roll_cage_safety: "forged",
    suspension_front_assembly: "forged",
    suspension_rear_assembly: "forged",
    brake_rotors_calipers: "forged",
    wheels_tires_assembly: "forged",
    hood_panel: "forged",
    front_fenders: "forged",
    doors_assembly: "forged",
    rear_quarter_panels: "forged",
    trunk_decklid: "forged",
    roof_panel: "billet",
    front_bumper_fascia: "cast",
    rear_bumper_fascia: "cast",
    front_splitter_tray: "billet",
    rear_diffuser_tunnel: "billet",
    side_skirts_aero: "billet",
    rear_wing_spoiler: "billet",
    canards_dive_planes: "cast",
    hood_fender_vents: "cast",
    windshield_glass: "forged",
    side_door_glass: "cast",
    rear_window_backlite: "cast",
    headlights_matrix: "forged",
    taillights_oled: "forged",
    fog_drl_lights: "cast",
    side_mirrors: "billet",
    front_grille_mesh: "cast",
    exhaust_tips_surround: "billet",
    door_handles_latches: "cast",
    wiper_cowl_assembly: "cast",
    badges_emblems: "forged",
  },
  exteriorConfig: {
    ...createDefaultExteriorConfig(),
    bodyStyle: "hypercar_coupe",
    doorOpening: "conventional",
    roofStyle: "solid_carbon_double_bubble",
    groundClearance: 100,
  },
  paintConfig: {
    ...createDefaultPaintConfig(),
    finishType: "high_gloss_mirror",
    primaryColorHex: "#d40000", // Apex Rosso
    secondaryColorHex: "#18181b",
    tertiaryColorHex: "#facc15",
    liveryStyle: "centre_racing_stripe",
  },
  aeroConfig: {
    ...createDefaultAeroConfig(),
    frontSplitterProfile: "track_extended_carbon",
    splitterExtensionMm: 75,
    rearWingType: "pedestal_sport_spoiler",
    wingSpanMm: 1350,
    wingAngleOfAttackDeg: 8,
  },
  lightingConfig: {
    ...createDefaultLightingConfig(),
  },
  glassConfig: {
    ...createDefaultGlassConfig(),
  },
  wheelConfig: {
    ...createDefaultWheelConfig(),
    spokePattern: "twin_5_spoke_split",
    finish: "gloss_jet_black",
    centerLockNut: false,
  },
  tireConfig: {
    ...createDefaultTireConfig(),
    tireCompound: "sport_uhp",
  },
  brakeConfig: {
    ...createDefaultBrakeVisualConfig(),
    caliperColorHex: "#d40000",
    rotorType: "cross_drilled_iron",
  },
};

// ── 5. RALLY CROSS ADVENTURE ──
const RALLY_CROSS: ExteriorPresetSpecification = {
  id: "rally_cross_safari",
  name: "Apex Safari Dakar Spec",
  badge: "SAFARI 4X4",
  category: "Specialty",
  description: "Reinforced steel/boron structure with skid plates, roof rack, pod rally lights, mud guards, and high-travel rally suspension.",
  variants: {
    chassis_frame: "cast",
    front_subframe: "cast",
    rear_subframe: "cast",
    floor_pan: "cast",
    firewall_bulkhead: "cast",
    a_pillar_assembly: "cast",
    b_pillar_assembly: "cast",
    c_pillar_assembly: "cast",
    rocker_panels: "cast",
    crash_boxes_front_rear: "cast",
    roll_cage_safety: "forged",
    suspension_front_assembly: "forged",
    suspension_rear_assembly: "forged",
    brake_rotors_calipers: "forged",
    wheels_tires_assembly: "forged",
    hood_panel: "cast",
    front_fenders: "cast",
    doors_assembly: "cast",
    rear_quarter_panels: "cast",
    trunk_decklid: "cast",
    roof_panel: "cast",
    front_bumper_fascia: "cast",
    rear_bumper_fascia: "cast",
    front_splitter_tray: "cast",
    rear_diffuser_tunnel: "cast",
    side_skirts_aero: "cast",
    rear_wing_spoiler: "cast",
    canards_dive_planes: "cast",
    hood_fender_vents: "cast",
    windshield_glass: "forged",
    side_door_glass: "cast",
    rear_window_backlite: "cast",
    headlights_matrix: "forged",
    taillights_oled: "forged",
    fog_drl_lights: "forged",
    side_mirrors: "cast",
    front_grille_mesh: "cast",
    exhaust_tips_surround: "cast",
    door_handles_latches: "cast",
    wiper_cowl_assembly: "cast",
    badges_emblems: "cast",
  },
  exteriorConfig: {
    ...createDefaultExteriorConfig(),
    bodyStyle: "sport_wagon",
    doorOpening: "conventional",
    roofStyle: "fixed_coupe",
    overallHeight: 1380,
    groundClearance: 165,
    frontOverhang: 780,
    rearOverhang: 820,
  },
  paintConfig: {
    ...createDefaultPaintConfig(),
    finishType: "deep_satin_matte",
    primaryColorHex: "#78716c", // Safari Warm Stone Grey
    secondaryColorHex: "#ea580c",
    tertiaryColorHex: "#1c1917",
    liveryStyle: "f1_camo_livery",
  },
  aeroConfig: {
    ...createDefaultAeroConfig(),
    frontSplitterProfile: "oem_integrated_chin",
    splitterExtensionMm: 0,
    splitterGroundClearanceMm: 165,
    rearWingType: "clean_ducktail_lip",
  },
  lightingConfig: {
    ...createDefaultLightingConfig(),
    fogLightStyle: "rally_quad_pod_hood",
  } as any,
  glassConfig: {
    ...createDefaultGlassConfig(),
  },
  wheelConfig: {
    ...createDefaultWheelConfig(),
    diameterFrontInches: 18,
    diameterRearInches: 18,
    spokePattern: "gt_multi_spoke_10",
    finish: "satin_bronze",
    centerLockNut: false,
  },
  tireConfig: {
    ...createDefaultTireConfig(),
    frontWidthMm: 245,
    frontAspectRatio: 45,
    rearWidthMm: 275,
    rearAspectRatio: 40,
    tireCompound: "wet_weather_grooved",
  },
  brakeConfig: {
    ...createDefaultBrakeVisualConfig(),
    rotorType: "vented_slotted_steel",
    rotorDiameterFrontMm: 355,
    rotorDiameterRearMm: 340,
  },
};

// ── 6. WIDEBODY DRIFT FORMULA ──
const DRIFT_SPEC: ExteriorPresetSpecification = {
  id: "drift_formula_spec",
  name: "Apex Formula D Drift Spec",
  badge: "FORMULA D",
  category: "Motorsport",
  description: "Extreme +65mm widebody flares, aggressive high-AoA rear wing, chopped crash bars, quick-release bumper latches, and ultra-high steering lock clearance.",
  variants: {
    chassis_frame: "cast",
    front_subframe: "forged",
    rear_subframe: "forged",
    floor_pan: "cast",
    firewall_bulkhead: "cast",
    a_pillar_assembly: "cast",
    b_pillar_assembly: "cast",
    c_pillar_assembly: "cast",
    rocker_panels: "cast",
    crash_boxes_front_rear: "forged",
    roll_cage_safety: "titanium",
    suspension_front_assembly: "titanium",
    suspension_rear_assembly: "titanium",
    brake_rotors_calipers: "forged",
    wheels_tires_assembly: "forged",
    hood_panel: "billet",
    front_fenders: "billet",
    doors_assembly: "billet",
    rear_quarter_panels: "billet",
    trunk_decklid: "billet",
    roof_panel: "cast",
    front_bumper_fascia: "cast",
    rear_bumper_fascia: "cast",
    front_splitter_tray: "billet",
    rear_diffuser_tunnel: "billet",
    side_skirts_aero: "billet",
    rear_wing_spoiler: "billet",
    canards_dive_planes: "billet",
    hood_fender_vents: "billet",
    windshield_glass: "forged",
    side_door_glass: "titanium",
    rear_window_backlite: "titanium",
    headlights_matrix: "forged",
    taillights_oled: "forged",
    fog_drl_lights: "cast",
    side_mirrors: "billet",
    front_grille_mesh: "cast",
    exhaust_tips_surround: "titanium",
    door_handles_latches: "cast",
    wiper_cowl_assembly: "cast",
    badges_emblems: "cast",
  },
  exteriorConfig: {
    ...createDefaultExteriorConfig(),
    bodyStyle: "widebody_drift",
    groundClearance: 75,
    widebodyFlareFrontMm: 65,
    widebodyFlareRearMm: 85,
  },
  paintConfig: {
    ...createDefaultPaintConfig(),
    finishType: "candy_translucent_tint",
    primaryColorHex: "#d97706", // Neon Cyberpunk Pink
    secondaryColorHex: "#f59e0b",
    tertiaryColorHex: "#facc15",
    liveryStyle: "f1_camo_livery",
  },
  aeroConfig: {
    ...createDefaultAeroConfig(),
    splitterExtensionMm: 120,
    rearWingType: "gt3_dual_element_airfoil",
    wingSpanMm: 1750,
    wingAngleOfAttackDeg: 28,
  },
  lightingConfig: {
    ...createDefaultLightingConfig(),
    underbodyAmbientGlow: true,
    ambientGlowColorHex: "#ff007f",
  },
  glassConfig: {
    ...createDefaultGlassConfig(),
    sideDoorGlass: "polycarbonate_lexan_race",
    rearBackliteGlass: "polycarbonate_lexan_race",
  },
  wheelConfig: {
    ...createDefaultWheelConfig(),
    spokePattern: "deep_dish" as any,
    diameterFrontInches: 18,
    diameterRearInches: 19,
    widthFrontInches: 10.0,
    widthRearInches: 12.0,
    offsetFrontMm: -15,
    offsetRearMm: -25,
    finish: "hyper_silver",
  },
  tireConfig: {
    ...createDefaultTireConfig(),
    tireCompound: "sport_uhp",
  },
  brakeConfig: {
    ...createDefaultBrakeVisualConfig(),
    caliperColorHex: "#f59e0b",
    rotorType: "vented_slotted_steel",
  },
};

// ── 7. SPEEDSTER TARGA TOP ──
const SPEEDSTER_TARGA: ExteriorPresetSpecification = {
  id: "speedster_targa_pure",
  name: "Apex Spyder Speedster 4.0",
  badge: "SPYDER",
  category: "Sport",
  description: "Cut-down frameless windshield with carbon streamliner rear cowls, targa carbon top, and open-air visceral acoustics.",
  variants: {
    chassis_frame: "billet",
    front_subframe: "forged",
    rear_subframe: "forged",
    floor_pan: "forged",
    firewall_bulkhead: "forged",
    a_pillar_assembly: "billet",
    b_pillar_assembly: "billet",
    c_pillar_assembly: "billet",
    rocker_panels: "billet",
    crash_boxes_front_rear: "forged",
    roll_cage_safety: "forged",
    suspension_front_assembly: "forged",
    suspension_rear_assembly: "forged",
    brake_rotors_calipers: "billet",
    wheels_tires_assembly: "billet",
    hood_panel: "forged",
    front_fenders: "forged",
    doors_assembly: "forged",
    rear_quarter_panels: "forged",
    trunk_decklid: "billet",
    roof_panel: "billet",
    front_bumper_fascia: "forged",
    rear_bumper_fascia: "forged",
    front_splitter_tray: "billet",
    rear_diffuser_tunnel: "billet",
    side_skirts_aero: "billet",
    rear_wing_spoiler: "billet",
    canards_dive_planes: "cast",
    hood_fender_vents: "billet",
    windshield_glass: "forged",
    side_door_glass: "forged",
    rear_window_backlite: "forged",
    headlights_matrix: "forged",
    taillights_oled: "forged",
    fog_drl_lights: "forged",
    side_mirrors: "billet",
    front_grille_mesh: "forged",
    exhaust_tips_surround: "billet",
    door_handles_latches: "forged",
    wiper_cowl_assembly: "forged",
    badges_emblems: "billet",
  },
  exteriorConfig: {
    ...createDefaultExteriorConfig(),
    bodyStyle: "targa_speedster",
    doorOpening: "frameless_coupe",
    roofStyle: "targa_carbon",
    overallHeight: 1140,
    windshieldRakeAngle: 34,
  },
  paintConfig: {
    ...createDefaultPaintConfig(),
    finishType: "liquid_metallic",
    primaryColorHex: "#ea580c", // Papaya Speedster
    secondaryColorHex: "#080c14",
    tertiaryColorHex: "#ea580c",
  },
  aeroConfig: {
    ...createDefaultAeroConfig(),
    rearWingType: "clean_ducktail_lip",
  },
  lightingConfig: {
    ...createDefaultLightingConfig(),
  },
  glassConfig: {
    ...createDefaultGlassConfig(),
    windshieldGlass: "gorilla_glass_thin_film",
  },
  wheelConfig: {
    ...createDefaultWheelConfig(),
    spokePattern: "monoblock_5_spoke",
    finish: "satin_bronze",
  },
  tireConfig: {
    ...createDefaultTireConfig(),
    tireCompound: "sport_uhp",
  },
  brakeConfig: {
    ...createDefaultBrakeVisualConfig(),
    caliperColorHex: "#ea580c",
  },
};

// ── 8. RETRO RESTOMOD CLASSIC ──
const RETRO_RESTOMOD: ExteriorPresetSpecification = {
  id: "retro_restomod_v8",
  name: "Apex Heritage Fastback 1968",
  badge: "RESTOMOD",
  category: "Specialty",
  description: "Classic muscle car silhouette underpinned by modern CAD-sculpted tubular chassis, active coilover suspension, and mirror-chrome trim details.",
  variants: {
    chassis_frame: "forged",
    front_subframe: "forged",
    rear_subframe: "forged",
    floor_pan: "cast",
    firewall_bulkhead: "cast",
    a_pillar_assembly: "cast",
    b_pillar_assembly: "cast",
    c_pillar_assembly: "cast",
    rocker_panels: "cast",
    crash_boxes_front_rear: "cast",
    roll_cage_safety: "forged",
    suspension_front_assembly: "forged",
    suspension_rear_assembly: "forged",
    brake_rotors_calipers: "forged",
    wheels_tires_assembly: "forged",
    hood_panel: "forged",
    front_fenders: "cast",
    doors_assembly: "cast",
    rear_quarter_panels: "cast",
    trunk_decklid: "cast",
    roof_panel: "cast",
    front_bumper_fascia: "cast",
    rear_bumper_fascia: "cast",
    front_splitter_tray: "cast",
    rear_diffuser_tunnel: "cast",
    side_skirts_aero: "cast",
    rear_wing_spoiler: "cast",
    canards_dive_planes: "cast",
    hood_fender_vents: "cast",
    windshield_glass: "cast",
    side_door_glass: "cast",
    rear_window_backlite: "cast",
    headlights_matrix: "forged",
    taillights_oled: "forged",
    fog_drl_lights: "cast",
    side_mirrors: "cast",
    front_grille_mesh: "cast",
    exhaust_tips_surround: "forged",
    door_handles_latches: "cast",
    wiper_cowl_assembly: "cast",
    badges_emblems: "forged",
  },
  exteriorConfig: {
    ...createDefaultExteriorConfig(),
    bodyStyle: "gt_fastback",
    doorOpening: "conventional",
    roofStyle: "fixed_coupe",
    overallLength: 4820,
    overallHeight: 1290,
    groundClearance: 125,
  },
  paintConfig: {
    ...createDefaultPaintConfig(),
    finishType: "high_gloss_mirror",
    primaryColorHex: "#1d4ed8", // Classic American Blue
    secondaryColorHex: "#f8fafc", // White Dual Stripes
    tertiaryColorHex: "#e2e8f0",
    liveryStyle: "centre_racing_stripe",
    stripeWidthMm: 220,
  },
  aeroConfig: {
    ...createDefaultAeroConfig(),
    frontSplitterProfile: "oem_integrated_chin",
    rearWingType: "clean_ducktail_lip",
  },
  lightingConfig: {
    ...createDefaultLightingConfig(),
    drlSignature: "halo_angel_rings",
  },
  glassConfig: {
    ...createDefaultGlassConfig(),
  },
  wheelConfig: {
    ...createDefaultWheelConfig(),
    spokePattern: "monoblock_5_spoke",
    finish: "hyper_silver",
    centerLockNut: false,
  },
  tireConfig: {
    ...createDefaultTireConfig(),
    frontWidthMm: 255,
    rearWidthMm: 315,
    sidewallLettering: "white_stencil_michelin",
  },
  brakeConfig: {
    ...createDefaultBrakeVisualConfig(),
    rotorType: "vented_slotted_steel",
    caliperColorHex: "#dc2626",
  },
};

export const EXTERIOR_PRESET_LIBRARY: ExteriorPresetSpecification[] = [
  GT3_RACE_SPEC,
  HYPERCAR_TRACK,
  LUXURY_GT,
  STREET_SPORT,
  RALLY_CROSS,
  DRIFT_SPEC,
  SPEEDSTER_TARGA,
  RETRO_RESTOMOD,
];

export function getExteriorPresetById(id: string): ExteriorPresetSpecification | undefined {
  return EXTERIOR_PRESET_LIBRARY.find((p) => p.id === id);
}
