import React, { useState, useMemo } from "react";
import { BatteryCharging, Zap, Thermometer, ShieldCheck, Cpu } from "lucide-react";

interface EVBatteryThermalAnalyticsProps {
  packCapacityKwh?: number;
  packVoltage?: 400 | 800;
  cellChemistry?: "lfp" | "nmc811" | "solid_state";
  peakDischargeKw?: number;
}

/**
 * ═════════════════════════════════════════════════════════════════════
 * EV BATTERY PACK & 800V ARCHITECTURE THERMAL ANALYTICS
 * ═════════════════════════════════════════════════════════════════════
 *
 * Implements EV battery engineering guidelines from ev-battery-pack-architect:
 * - Cell Chemistry Comparative Trade-Offs (LFP vs NMC 811 vs Solid-State)
 * - 800V vs 400V I²R Joule Resistive Loss & Harness Copper Weight Delta
 * - Microchannel Liquid Cold Plate Heat Flux & Thermal Gradient
 */
export const EVBatteryThermalAnalytics: React.FC<EVBatteryThermalAnalyticsProps> = ({
  packCapacityKwh = 95,
  packVoltage = 800,
  cellChemistry = "nmc811",
  peakDischargeKw = 480,
}) => {
  const [voltage, setVoltage] = useState<400 | 800>(packVoltage);
  const [chemistry, setChemistry] = useState<"lfp" | "nmc811" | "solid_state">(cellChemistry);
  const [dischargePowerKw, setDischargePowerKw] = useState<number>(peakDischargeKw);
  const [coolantFlowLpm, setCoolantFlowLpm] = useState<number>(18);

  // Chemistry Specifications
  const chemSpecs = useMemo(() => {
    switch (chemistry) {
      case "lfp":
        return {
          name: "Lithium Iron Phosphate (LFP)",
          energyDensityWhKg: 165,
          cycleLife: 3500,
          runawayTempC: 270,
          costPerKwh: 85,
          color: "#10b981",
        };
      case "solid_state":
        return {
          name: "Solid-State Ceramic Electrolyte",
          energyDensityWhKg: 420,
          cycleLife: 2800,
          runawayTempC: 450,
          costPerKwh: 220,
          color: "#a855f7",
        };
      case "nmc811":
      default:
        return {
          name: "Nickel Manganese Cobalt 811 (NMC)",
          energyDensityWhKg: 265,
          cycleLife: 1500,
          runawayTempC: 210,
          costPerKwh: 125,
          color: "#38bdf8",
        };
    }
  }, [chemistry]);

  // Pack Mass based on chemistry
  const packCellMassKg = useMemo(() => {
    return Math.round((packCapacityKwh * 1000) / chemSpecs.energyDensityWhKg);
  }, [packCapacityKwh, chemSpecs]);

  // Electrical Current & I²R Harness Losses
  const electricalMetrics = useMemo(() => {
    const currentAmps = (dischargePowerKw * 1000) / voltage;
    // Typical harness resistance ~0.015 ohms
    const harnessResistanceOhms = voltage === 800 ? 0.012 : 0.018;
    const jouleLossWatts = currentAmps ** 2 * harnessResistanceOhms;
    const harnessMassKg = voltage === 800 ? 18 : 28; // -35% lighter copper harness in 800V

    // Fast Charging Rate (kW)
    const maxChargeKw = voltage === 800 ? 350 : 150;
    const chargeTime10to80Min = Math.round(((packCapacityKwh * 0.7) / maxChargeKw) * 60);

    return {
      currentAmps: Math.round(currentAmps),
      jouleLossWatts: Math.round(jouleLossWatts),
      harnessMassKg,
      maxChargeKw,
      chargeTime10to80Min,
    };
  }, [dischargePowerKw, voltage, packCapacityKwh]);

  // Cooling Plate Heat Flux & Cell Core Temperature
  const thermalMetrics = useMemo(() => {
    // Heat generated by internal cell resistance (R_int ~ 0.02 ohms)
    const cellHeatGenerationWatts = electricalMetrics.currentAmps ** 2 * 0.008;
    // Heat removed by liquid glycol cooling plate
    const coolingCapacityWatts = coolantFlowLpm * 180; // ~180 W per L/min
    const netHeatWatts = Math.max(0, cellHeatGenerationWatts - coolingCapacityWatts);
    const steadyStateCoreTempC = 25 + netHeatWatts / 120;

    return {
      cellHeatGenerationWatts: Math.round(cellHeatGenerationWatts),
      coolingCapacityWatts: Math.round(coolingCapacityWatts),
      coreTempC: Math.round(steadyStateCoreTempC * 10) / 10,
    };
  }, [electricalMetrics.currentAmps, coolantFlowLpm]);

  return (
    <div className="bg-slate-950/95 backdrop-blur-lg border border-purple-500/30 rounded-2xl p-5 shadow-2xl text-slate-100 flex flex-col gap-4">
      {/* ── Header ── */}
      <div className="flex items-center justify-between border-b border-slate-800 pb-3">
        <div className="flex items-center gap-2.5">
          <BatteryCharging className="w-5 h-5 text-purple-400 animate-pulse" />
          <div>
            <h3 className="font-mono text-sm font-bold uppercase tracking-wider text-purple-300">
              EV Battery & 800V Architecture Analytics
            </h3>
            <span className="text-[11px] text-slate-400 font-mono">
              Pack: {packCapacityKwh} kWh | Cell Mass: {packCellMassKg} kg | {chemSpecs.name}
            </span>
          </div>
        </div>

        {/* 800V Fast Charge Badge */}
        <div className={`px-2.5 py-1 rounded-lg text-xs font-mono font-bold flex items-center gap-1.5 border ${
          voltage === 800
            ? "bg-purple-950/60 border-purple-500/40 text-purple-300"
            : "bg-slate-900 border-slate-700 text-slate-400"
        }`}>
          <Zap className="w-3.5 h-3.5" />
          <span>{voltage}V System: 10-80% in {electricalMetrics.chargeTime10to80Min} min</span>
        </div>
      </div>

      {/* ── Grid: Cell Chemistry & 800V Efficiency ── */}
      <div className="grid grid-cols-1 lg:grid-cols-12 gap-5">
        {/* Chemistry Selector Cards */}
        <div className="lg:col-span-6 bg-slate-900/80 border border-slate-800 rounded-xl p-3 flex flex-col gap-2">
          <span className="text-xs font-mono text-slate-400">Cell Chemistry Electrochemistry</span>

          <div className="grid grid-cols-3 gap-2">
            {[
              { id: "lfp", label: "LFP", sub: "165 Wh/kg", desc: "High Safety" },
              { id: "nmc811", label: "NMC 811", sub: "265 Wh/kg", desc: "High Power" },
              { id: "solid_state", label: "Solid-State", sub: "420 Wh/kg", desc: "Ultra Density" },
            ].map((c) => (
              <button
                key={c.id}
                onClick={() => setChemistry(c.id as any)}
                className={`p-2.5 rounded-lg border text-left flex flex-col transition-all ${
                  chemistry === c.id
                    ? "bg-purple-950/60 border-purple-500/80 text-purple-200 shadow-lg"
                    : "bg-slate-950/60 border-slate-800 text-slate-400 hover:border-slate-700"
                }`}
              >
                <span className="font-mono text-xs font-bold">{c.label}</span>
                <span className="text-[10px] text-purple-300 font-mono">{c.sub}</span>
                <span className="text-[9px] text-slate-500">{c.desc}</span>
              </button>
            ))}
          </div>

          <div className="grid grid-cols-3 gap-2 text-[11px] font-mono text-slate-400 pt-2 border-t border-slate-800">
            <div>Cycle Life: <b className="text-emerald-400">{chemSpecs.cycleLife}</b></div>
            <div>Runaway: <b className="text-amber-400">{chemSpecs.runawayTempC}°C</b></div>
            <div>Cost: <b className="text-cyan-400">${chemSpecs.costPerKwh}/kWh</b></div>
          </div>
        </div>

        {/* 800V vs 400V Thermal & Electrical Losses */}
        <div className="lg:col-span-6 bg-slate-900/80 border border-slate-800 rounded-xl p-3 flex flex-col gap-2.5">
          <div className="flex justify-between items-center text-xs font-mono">
            <span className="text-slate-400">Voltage Architecture</span>
            <div className="flex gap-1.5">
              <button
                onClick={() => setVoltage(400)}
                className={`px-2 py-0.5 rounded text-[10px] font-mono ${
                  voltage === 400 ? "bg-slate-700 text-white font-bold" : "bg-slate-950 text-slate-400"
                }`}
              >
                400V
              </button>
              <button
                onClick={() => setVoltage(800)}
                className={`px-2 py-0.5 rounded text-[10px] font-mono ${
                  voltage === 800 ? "bg-purple-600 text-white font-bold" : "bg-slate-950 text-slate-400"
                }`}
              >
                800V (SiC)
              </button>
            </div>
          </div>

          <div className="grid grid-cols-3 gap-2 text-xs font-mono">
            <div className="bg-slate-950/60 p-2 rounded border border-slate-800/80">
              <div className="text-[10px] text-slate-500">Current Load</div>
              <div className="text-amber-300 font-bold">{electricalMetrics.currentAmps} A</div>
            </div>
            <div className="bg-slate-950/60 p-2 rounded border border-slate-800/80">
              <div className="text-[10px] text-slate-500">I²R Heat Loss</div>
              <div className="text-red-400 font-bold">{(electricalMetrics.jouleLossWatts / 1000).toFixed(2)} kW</div>
            </div>
            <div className="bg-slate-950/60 p-2 rounded border border-slate-800/80">
              <div className="text-[10px] text-slate-500">Harness Mass</div>
              <div className="text-cyan-300 font-bold">{electricalMetrics.harnessMassKg} kg</div>
            </div>
          </div>

          {/* Microchannel Cold Plate Thermal Status */}
          <div className="flex items-center justify-between text-xs font-mono pt-1">
            <div className="flex items-center gap-1.5">
              <Thermometer className="w-3.5 h-3.5 text-cyan-400" />
              <span className="text-slate-400">Cell Core Temp:</span>
              <span className={`font-bold ${thermalMetrics.coreTempC > 48 ? "text-red-400" : "text-emerald-400"}`}>
                {thermalMetrics.coreTempC}°C (Safe &lt; 55°C)
              </span>
            </div>
            <span className="text-slate-500 text-[10px]">{coolantFlowLpm} L/min Flow</span>
          </div>
        </div>
      </div>

      {/* ── Interactive Tuning Sliders ── */}
      <div className="grid grid-cols-1 md:grid-cols-2 gap-4 pt-2 border-t border-slate-800/80">
        {/* Peak Discharge Power */}
        <div className="flex flex-col gap-1">
          <div className="flex justify-between text-[11px] font-mono text-slate-400">
            <span>Discharge Demand</span>
            <span className="text-purple-300 font-bold">{dischargePowerKw} kW</span>
          </div>
          <input
            type="range"
            min="100"
            max="1200"
            step="20"
            value={dischargePowerKw}
            onChange={(e) => setDischargePowerKw(parseInt(e.target.value))}
            className="w-full h-1.5 bg-slate-800 rounded appearance-none cursor-pointer accent-purple-400"
          />
        </div>

        {/* Liquid Chiller Flow Rate */}
        <div className="flex flex-col gap-1">
          <div className="flex justify-between text-[11px] font-mono text-slate-400">
            <span>Cooling Chiller Flow Rate</span>
            <span className="text-cyan-300 font-bold">{coolantFlowLpm} L/min</span>
          </div>
          <input
            type="range"
            min="5"
            max="40"
            step="1"
            value={coolantFlowLpm}
            onChange={(e) => setCoolantFlowLpm(parseInt(e.target.value))}
            className="w-full h-1.5 bg-slate-800 rounded appearance-none cursor-pointer accent-cyan-400"
          />
        </div>
      </div>
    </div>
  );
};
