// ============================================================================
// MODULAR glTF VEHICLE CONSTRUCTION SYSTEM — CAR 3D GLB ASSET REGISTRY
// ============================================================================
// Master registry mapping vehicle body styles, chassis platforms, closures,
// aerodynamics, interior cockpit modules, and engines to real production
// .glb / .gltf / .fbx 3D asset files.
// ============================================================================

export type GlbAssetCategory =
  | "SUPERCAR"
  | "HATCHBACK"
  | "SEDAN"
  | "RALLY"
  | "CHASSIS"
  | "ENGINE"
  | "RESTOMOD"
  | "AERO"
  | "CLOSURES"
  | "INTERIOR";

export interface CarGlbAssetDefinition {
  id: string;
  name: string;
  subtitle: string;
  description: string;
  assetPath: string;
  fallbackPath?: string;
  category: GlbAssetCategory;
  wheelbaseMm: number;
  lengthMm: number;
  widthMm: number;
  heightMm: number;
  bodyPaintMaterialNames: string[];
  glassMaterialNames?: string[];
  caliperColorDefault?: string;
  suggestedCameraRadius?: number;
}

export class Car3DGlbAssetRegistry {
  public static readonly ASSETS: Record<string, CarGlbAssetDefinition> = {
    // ─── 1. COMPLETE VEHICLE ASSEMBLIES ───
    SUPERCAR_MID_ENGINE: {
      id: "SUPERCAR_MID_ENGINE",
      name: "BMW i8 Hybrid Supercar GLB",
      subtitle: "Mid-Engine Carbon Monocoque Plug-in Hybrid Supercar",
      description: "High-fidelity 3D GLB model of BMW i8 with carbon tub, butterfly doors, active aero body shell, and photorealistic cockpit.",
      assetPath: "/models/exterior/sports_car_bmw_i8.glb",
      fallbackPath: "/models/extracted/bmw-i8-xs-2015/source/2015-bmw-i8_xs_car.glb",
      category: "SUPERCAR",
      wheelbaseMm: 2800,
      lengthMm: 4689,
      widthMm: 1942,
      heightMm: 1297,
      bodyPaintMaterialNames: ["paint", "car_paint", "body", "car_body", "primary_paint", "exterior_paint", "paint_main"],
      glassMaterialNames: ["glass", "window", "windshield", "rear_window"],
      caliperColorDefault: "#dc2626",
      suggestedCameraRadius: 4.2,
    },
    GT3_RACE_CAR: {
      id: "GT3_RACE_CAR",
      name: "Ford Escort RS Cosworth WRC GLB",
      subtitle: "FIA World Rally Championship Spec 4WD Legend",
      description: "High-fidelity 3D GLB model of Ford Escort RS Cosworth with double-deck wing, hood heat extractors, and rally widebody.",
      assetPath: "/models/exterior/hatchback_ford_escort.glb",
      fallbackPath: "/models/extracted/ford-escort-rs-cosworth-cossie/source/Body_lodA/Body_lodA/fordEscortRSCosworth.glb",
      category: "RALLY",
      wheelbaseMm: 2551,
      lengthMm: 4211,
      widthMm: 1734,
      heightMm: 1425,
      bodyPaintMaterialNames: ["body_paint", "carpaint", "paint_main", "ford_body", "livery", "swatcha"],
      glassMaterialNames: ["glass", "window", "lighta_diffuse"],
      caliperColorDefault: "#0284c7",
      suggestedCameraRadius: 3.8,
    },
    MINI_COUNTRYMAN_JCW: {
      id: "MINI_COUNTRYMAN_JCW",
      name: "Mini Countryman JCW Rally GLB",
      subtitle: "John Cooper Works ALL4 Rally Cross Championship Spec",
      description: "Ultra-detailed glTF 3D model of Mini Countryman JCW with turbo engine bay, rally wheels, badge details, and racing interior.",
      assetPath: "/models/extracted/mini-countryman-jcw/source/Unity2Skfb/Unity2Skfb.gltf",
      category: "RALLY",
      wheelbaseMm: 2670,
      lengthMm: 4299,
      widthMm: 1822,
      heightMm: 1557,
      bodyPaintMaterialNames: ["car_mini_countrymanjcw_2017_body", "paint", "body"],
      caliperColorDefault: "#dc2626",
      suggestedCameraRadius: 3.9,
    },
    VOLVO_P1800_RESTOMOD: {
      id: "VOLVO_P1800_RESTOMOD",
      name: "Volvo P1800 Restomod Widebody FBX/GLB",
      subtitle: "Custom Carbon-Bodied Restomod Touring GT",
      description: "High-density 3D model of custom Volvo P1800 Restomod featuring widened track flares, billet grille, and custom wheels.",
      assetPath: "/models/extracted/volvo-p1800-restomod-widebody-edition/source/car5.fbx",
      category: "RESTOMOD",
      wheelbaseMm: 2450,
      lengthMm: 4400,
      widthMm: 1850,
      heightMm: 1280,
      bodyPaintMaterialNames: ["paint", "body", "car_body"],
      caliperColorDefault: "#eab308",
      suggestedCameraRadius: 4.1,
    },
    APEX_GT3_HYPERCAR: {
      id: "APEX_GT3_HYPERCAR",
      name: "Apex GT3 Le Mans Prototype Hypercar GLB",
      subtitle: "Full Carbon Composite Aerodynamic Hypercar Body",
      description: "Complete 3D GLB model of Apex GT3 Hypercar with shark fin, roof scoop, swan-neck wing, matrix laser headlights, and underbody tunnels.",
      assetPath: "/models/exterior/hypercar_apex_gt3.glb",
      category: "SUPERCAR",
      wheelbaseMm: 2750,
      lengthMm: 4720,
      widthMm: 2040,
      heightMm: 1120,
      bodyPaintMaterialNames: ["car_body", "paint", "primary_paint", "body"],
      glassMaterialNames: ["glass", "canopy", "windshield"],
      caliperColorDefault: "#f59e0b",
      suggestedCameraRadius: 4.4,
    },
    SPORTS_COUPE_GT: {
      id: "SPORTS_COUPE_GT",
      name: "Grand Tourer Fastback Sports Coupe GLB",
      subtitle: "Muscular V8/V12 Grand Tourer with Fastback Roofline",
      description: "Complete 3D GLB model of Sports GT Coupe featuring power-dome hood, flared rear quarter panels, and quad titanium exhaust diffusers.",
      assetPath: "/models/exterior/sports_coupe_gt.glb",
      category: "SUPERCAR",
      wheelbaseMm: 2680,
      lengthMm: 4580,
      widthMm: 1920,
      heightMm: 1260,
      bodyPaintMaterialNames: ["paint", "car_body", "primary_paint", "body"],
      glassMaterialNames: ["glass", "window", "canopy"],
      caliperColorDefault: "#dc2626",
      suggestedCameraRadius: 4.1,
    },
    DOORS_BUTTERFLY_PAIR: {
      id: "DOORS_BUTTERFLY_PAIR",
      name: "Dihedral Butterfly Doors Pair GLB",
      subtitle: "Left & Right Upward-Opening Dihedral Doors",
      description: "Articulated pair of dihedral butterfly doors with carbon inner door cards, window glass, and hydraulic lift actuators.",
      assetPath: "/models/exterior/doors_butterfly_pair.glb",
      category: "CLOSURES",
      wheelbaseMm: 0,
      lengthMm: 1250,
      widthMm: 1880,
      heightMm: 850,
      bodyPaintMaterialNames: ["paint", "door", "skin"],
      glassMaterialNames: ["glass", "window"],
      suggestedCameraRadius: 3.2,
    },
    AERO_WIDEBODY_KIT: {
      id: "AERO_WIDEBODY_KIT",
      name: "Modular Aerodynamic Widebody Kit GLB",
      subtitle: "Carbon Splitter, Side Skirts, Diffuser & Swan-Neck Wing",
      description: "Full modular carbon aerodynamic package including front track splitter, ground-effect side skirts, rear diffuser, and swan-neck wing.",
      assetPath: "/models/exterior/aerodynamic_widebody_kit.glb",
      category: "AERO",
      wheelbaseMm: 0,
      lengthMm: 4650,
      widthMm: 2020,
      heightMm: 1180,
      bodyPaintMaterialNames: ["carbon", "aero", "splitter", "wing"],
      suggestedCameraRadius: 4.2,
    },
    FULL_MODULAR_CAR_MASTER: {
      id: "FULL_MODULAR_CAR_MASTER",
      name: "Full Modular Vehicle Master Assembly GLB",
      subtitle: "Complete Modular Vehicle Assembly with All 40+ Components",
      description: "Master 3D GLB vehicle assembly containing all 40+ modular components, attachment sockets, and PBR material zones.",
      assetPath: "/models/exterior/full_modular_car_assembly.glb",
      category: "SUPERCAR",
      wheelbaseMm: 2750,
      lengthMm: 4680,
      widthMm: 1980,
      heightMm: 1220,
      bodyPaintMaterialNames: ["paint", "car_body", "primary_paint", "body"],
      glassMaterialNames: ["glass", "windshield", "window"],
      caliperColorDefault: "#dc2626",
      suggestedCameraRadius: 4.3,
    },

    // ─── 2. CHASSIS & STRUCTURAL PLATFORMS ───
    SPORTS_CHASSIS_01: {
      id: "SPORTS_CHASSIS_01",
      name: "Sports Car Aluminum Monocoque Chassis GLB",
      subtitle: "Hydroformed Aluminum & Carbon Fiber Structural Skeleton",
      description: "3D structural aluminum & carbon monocoque chassis platform with 36 hardpoint nodes, shock towers, and X-brace bars.",
      assetPath: "/models/chassis/sports_car_chassis_01.glb",
      category: "CHASSIS",
      wheelbaseMm: 2680,
      lengthMm: 4400,
      widthMm: 1880,
      heightMm: 1180,
      bodyPaintMaterialNames: ["frame", "chassis", "aluminum", "tub"],
      caliperColorDefault: "#059669",
      suggestedCameraRadius: 4.0,
    },
    HATCHBACK_CHASSIS_01: {
      id: "HATCHBACK_CHASSIS_01",
      name: "Hatchback Platform Chassis GLB",
      subtitle: "Front-Engine Transverse Unibody Platform Architecture",
      description: "3D unibody platform chassis model with hydroformed front subframe, rear torsion beam, floorpan, and engine cradle.",
      assetPath: "/models/chassis/hatchback_chassis_01.glb",
      category: "CHASSIS",
      wheelbaseMm: 2500,
      lengthMm: 4100,
      widthMm: 1720,
      heightMm: 1350,
      bodyPaintMaterialNames: ["frame", "unibody", "floor"],
      caliperColorDefault: "#dc2626",
      suggestedCameraRadius: 3.7,
    },
    SUPERCAR_MONOCOQUE_01: {
      id: "SUPERCAR_MONOCOQUE_01",
      name: "Hypercar Full Carbon Fiber Monocoque Tub GLB",
      subtitle: "Prepreg Autoclave Carbon Tub with Titanium Subframes",
      description: "Ultra-rigid 65 kNm/deg carbon monocoque cockpit tub with titanium crash subframe, billet aluminum cradle, and inboard pushrods.",
      assetPath: "/models/chassis/supercar_monocoque_chassis_01.glb",
      category: "CHASSIS",
      wheelbaseMm: 2750,
      lengthMm: 4650,
      widthMm: 2020,
      heightMm: 1140,
      bodyPaintMaterialNames: ["frame", "monocoque", "carbon", "tub"],
      caliperColorDefault: "#f59e0b",
      suggestedCameraRadius: 4.2,
    },
    GT3_RACE_CHASSIS_01: {
      id: "GT3_RACE_CHASSIS_01",
      name: "FIA Homologated GT3 Chromoly Rollcage Chassis GLB",
      subtitle: "Full Tubular Spaceframe with Air Jacks & Safety Cell",
      description: "FIA Appendix J GT3 race chassis with gusseted X-door bars, roof diagonals, built-in air jack system, and FT3 fuel cell.",
      assetPath: "/models/chassis/gt3_race_chassis_01.glb",
      category: "CHASSIS",
      wheelbaseMm: 2650,
      lengthMm: 4500,
      widthMm: 1960,
      heightMm: 1220,
      bodyPaintMaterialNames: ["frame", "cage", "rollcage", "chromoly"],
      caliperColorDefault: "#0284c7",
      suggestedCameraRadius: 4.1,
    },
    EV_SKATEBOARD_CHASSIS_01: {
      id: "EV_SKATEBOARD_CHASSIS_01",
      name: "800V Structural Battery Skateboard Chassis GLB",
      subtitle: "Integrated EV Floor Battery Platform with Dual EDUs",
      description: "Low-center-of-gravity 800V EV skateboard platform with multi-chamber side crash rails, cooling manifolds, and dual electric motors.",
      assetPath: "/models/chassis/ev_skateboard_chassis_01.glb",
      category: "CHASSIS",
      wheelbaseMm: 2900,
      lengthMm: 4800,
      widthMm: 1940,
      heightMm: 1380,
      bodyPaintMaterialNames: ["frame", "battery", "skateboard", "enclosure"],
      caliperColorDefault: "#10b981",
      suggestedCameraRadius: 4.3,
    },
    OFFROAD_LADDER_CHASSIS_01: {
      id: "OFFROAD_LADDER_CHASSIS_01",
      name: "Hydroformed Steel Box-Section Ladder Frame GLB",
      subtitle: "High-Strength Steel Ladder Chassis with Underbody Armor",
      description: "Heavy-duty offroad ladder frame with 6 tubular crossmembers, front recovery winch cradle, and Hardox underbody skid armor.",
      assetPath: "/models/chassis/offroad_ladder_chassis_01.glb",
      category: "CHASSIS",
      wheelbaseMm: 3100,
      lengthMm: 5200,
      widthMm: 1980,
      heightMm: 1750,
      bodyPaintMaterialNames: ["frame", "ladder", "rail", "steel"],
      caliperColorDefault: "#d97706",
      suggestedCameraRadius: 4.6,
    },

    // ─── 3. POWERTRAIN MASTER ASSEMBLY ───
    V12_MASTER_ENGINE: {
      id: "V12_MASTER_ENGINE",
      name: "60° V12 Racing Engine & Transaxle GLB",
      subtitle: "3.5L 60° V12 Naturally Aspirated / Twin-Turbo Racing Powertrain",
      description: "Complete master 3D GLB model of 60° V12 Racing Engine with 7-speed sequential transaxle, 12 velocity stacks, and dry sump.",
      assetPath: "/models/v12_racing_engine.glb",
      category: "ENGINE",
      wheelbaseMm: 0,
      lengthMm: 1150,
      widthMm: 720,
      heightMm: 680,
      bodyPaintMaterialNames: ["valve_cover", "intake", "manifold", "block"],
      caliperColorDefault: "#f59e0b",
      suggestedCameraRadius: 2.5,
    },

    // ─── 4. REAR AERODYNAMICS & COMPONENT MODULES ───
    HYPERCAR_REAR_ASSEMBLY: {
      id: "HYPERCAR_REAR_ASSEMBLY",
      name: "Hypercar Rear Assembly & Active Aero GLB",
      subtitle: "Rear Bodywork, Active Swan-Neck Wing, Venturi Diffuser & Quad Titanium Exhaust",
      description: "High-fidelity 3D GLB model of hypercar rear assembly with active swan-neck wing, Venturi diffuser strakes, OLED lightbar, quad titanium exhausts, and rear suspension.",
      assetPath: "/models/exterior/rear_car_assembly.glb",
      category: "AERO",
      wheelbaseMm: 2750,
      lengthMm: 2200,
      widthMm: 1980,
      heightMm: 1180,
      bodyPaintMaterialNames: ["Clearcoat_Apex_Blue_Paint", "paint", "body"],
      glassMaterialNames: ["Smoked_Rear_Backlite_Glass", "glass"],
      caliperColorDefault: "#b91c1c",
      suggestedCameraRadius: 3.5,
    },
    REAR_WING_SWAN_NECK: {
      id: "REAR_WING_SWAN_NECK",
      name: "Active Swan-Neck Carbon Rear Wing GLB",
      subtitle: "High-Downforce DRS-Equipped Carbon Aerofoil",
      description: "Dual-element swan-neck carbon aerofoil with endplates, DRS actuator linkage, and CNC billet mounting pylons.",
      assetPath: "/models/exterior/rear_wing.glb",
      category: "AERO",
      wheelbaseMm: 0,
      lengthMm: 450,
      widthMm: 1650,
      heightMm: 380,
      bodyPaintMaterialNames: ["wing", "aerofoil", "paint", "carbon"],
      suggestedCameraRadius: 2.2,
    },
    REAR_DIFFUSER_VENTURI: {
      id: "REAR_DIFFUSER_VENTURI",
      name: "Venturi Tunnel Rear Diffuser GLB",
      subtitle: "Ground Effect Carbon Diffuser with Strakes",
      description: "Underbody aerodynamic ground-effect diffuser with high-expansion Venturi tunnels and carbon vertical strakes.",
      assetPath: "/models/exterior/rear_diffuser.glb",
      category: "AERO",
      wheelbaseMm: 0,
      lengthMm: 950,
      widthMm: 1720,
      heightMm: 280,
      bodyPaintMaterialNames: ["diffuser", "carbon", "strake"],
      suggestedCameraRadius: 2.4,
    },
    REAR_BUMPER_FASCIA: {
      id: "REAR_BUMPER_FASCIA",
      name: "Aero Rear Bumper & Heat Extractors GLB",
      subtitle: "Widebody Rear Fascia with Thermal Flow Vents",
      description: "Sculpted rear bumper assembly with cooling exhaust cutouts, thermal mesh vents, and integrated aerodynamic ducting.",
      assetPath: "/models/exterior/rear_bumper.glb",
      category: "AERO",
      wheelbaseMm: 0,
      lengthMm: 850,
      widthMm: 1980,
      heightMm: 620,
      bodyPaintMaterialNames: ["bumper", "paint", "body", "fascia"],
      suggestedCameraRadius: 2.6,
    },
    OLED_TAILLIGHTS_MODULE: {
      id: "OLED_TAILLIGHTS_MODULE",
      name: "Continuous OLED Lightbar Taillights GLB",
      subtitle: "Dynamic Signature OLED Surface Light Guide",
      description: "Edge-to-edge curved OLED lightbar assembly with micro-prism internal optics and smoked polycarbonate outer lenses.",
      assetPath: "/models/exterior/taillights.glb",
      category: "AERO",
      wheelbaseMm: 0,
      lengthMm: 220,
      widthMm: 1680,
      heightMm: 120,
      bodyPaintMaterialNames: ["taillight", "light", "lens", "led"],
      glassMaterialNames: ["lens", "glass"],
      suggestedCameraRadius: 2.0,
    },

    // ─── 5. CLOSURES & HOOD PANELS ───
    BMW_I8_HOOD_OPEN: {
      id: "BMW_I8_HOOD_OPEN",
      name: "BMW i8 Supercar Front Hood (Open) GLB",
      subtitle: "Forward-Hinged Carbon Hood with Cooling Ducts (Service Position)",
      description: "Open articulated carbon fiber hood panel revealing electric motor cooling radiators and front suspension geometry.",
      assetPath: "/models/exterior/bmw_i8_supercar_hood_open.glb",
      category: "CLOSURES",
      wheelbaseMm: 0,
      lengthMm: 1450,
      widthMm: 1680,
      heightMm: 650,
      bodyPaintMaterialNames: ["hood", "paint", "carbon", "body"],
      suggestedCameraRadius: 2.5,
    },
    BMW_I8_HOOD_CLOSED: {
      id: "BMW_I8_HOOD_CLOSED",
      name: "BMW i8 Supercar Front Hood (Closed) GLB",
      subtitle: "Aerodynamic Carbon Hood with V-Extractor Ducts",
      description: "Closed aerodynamic carbon composite hood panel flush-mounted to front fenders and headlights.",
      assetPath: "/models/exterior/bmw_i8_supercar_hood_closed.glb",
      category: "CLOSURES",
      wheelbaseMm: 0,
      lengthMm: 1450,
      widthMm: 1680,
      heightMm: 280,
      bodyPaintMaterialNames: ["hood", "paint", "carbon", "body"],
      suggestedCameraRadius: 2.4,
    },
    COSWORTH_HOOD_OPEN: {
      id: "COSWORTH_HOOD_OPEN",
      name: "Ford Cosworth WRC Hood (Open) GLB",
      subtitle: "Rally Hood with Louvered Heat Extractors (Engine Bay Service)",
      description: "Articulated rally hood raised on gas struts displaying twin-louvers and radiator extraction scoops.",
      assetPath: "/models/exterior/ford_escort_rs_cosworth_hood_open.glb",
      category: "CLOSURES",
      wheelbaseMm: 0,
      lengthMm: 1380,
      widthMm: 1520,
      heightMm: 620,
      bodyPaintMaterialNames: ["hood", "paint", "body"],
      suggestedCameraRadius: 2.4,
    },
    COSWORTH_HOOD_CLOSED: {
      id: "COSWORTH_HOOD_CLOSED",
      name: "Ford Cosworth WRC Hood (Closed) GLB",
      subtitle: "Rally Specification Louvered Aluminum Hood Panel",
      description: "Closed hood featuring Cosworth signature heat louvers and rally quick-release pin mounts.",
      assetPath: "/models/exterior/ford_escort_rs_cosworth_hood_closed.glb",
      category: "CLOSURES",
      wheelbaseMm: 0,
      lengthMm: 1380,
      widthMm: 1520,
      heightMm: 220,
      bodyPaintMaterialNames: ["hood", "paint", "body"],
      suggestedCameraRadius: 2.3,
    },
    COSWORTH_GT3_HOOD_OPEN: {
      id: "COSWORTH_GT3_HOOD_OPEN",
      name: "Cosworth GT3 Aero Hood (Open) GLB",
      subtitle: "Circuit GT3 Spec Carbon Extraction Hood (Paddock Open)",
      description: "Ultralight pre-preg carbon fiber GT3 hood in open position showing inner structural skeleton.",
      assetPath: "/models/exterior/ford_escort_rs_cosworth_gt3_hood_open.glb",
      category: "CLOSURES",
      wheelbaseMm: 0,
      lengthMm: 1380,
      widthMm: 1540,
      heightMm: 640,
      bodyPaintMaterialNames: ["hood", "carbon", "paint", "body"],
      suggestedCameraRadius: 2.4,
    },
    COSWORTH_GT3_HOOD_CLOSED: {
      id: "COSWORTH_GT3_HOOD_CLOSED",
      name: "Cosworth GT3 Aero Hood (Closed) GLB",
      subtitle: "Pre-Preg Carbon Fiber Aerodynamic Downforce Hood",
      description: "Low-drag GT3 racing hood with deep radiator chimney relief and NACA air intakes.",
      assetPath: "/models/exterior/ford_escort_rs_cosworth_gt3_hood_closed.glb",
      category: "CLOSURES",
      wheelbaseMm: 0,
      lengthMm: 1380,
      widthMm: 1540,
      heightMm: 220,
      bodyPaintMaterialNames: ["hood", "carbon", "paint", "body"],
      suggestedCameraRadius: 2.3,
    },
    HOOD_VENTED_CARBON: {
      id: "HOOD_VENTED_CARBON",
      name: "Universal Carbon Vented Hood GLB",
      subtitle: "Center-Vented Aerodynamic Carbon Hood",
      description: "Universal performance carbon fiber hood featuring inverted center air extractor duct.",
      assetPath: "/models/exterior/hood.glb",
      category: "CLOSURES",
      wheelbaseMm: 0,
      lengthMm: 1400,
      widthMm: 1560,
      heightMm: 240,
      bodyPaintMaterialNames: ["hood", "carbon", "paint", "body"],
      suggestedCameraRadius: 2.3,
    },
    HOOD_AERO_PANEL: {
      id: "HOOD_AERO_PANEL",
      name: "Aero Powerdome Hood Panel GLB",
      subtitle: "Dual-Vent Aggressive Powerdome Hood Assembly",
      description: "Aggressive powerdome hood assembly with twin side extractors for high-boost engine configurations.",
      assetPath: "/models/exterior/hood_panel.glb",
      category: "CLOSURES",
      wheelbaseMm: 0,
      lengthMm: 1420,
      widthMm: 1580,
      heightMm: 250,
      bodyPaintMaterialNames: ["hood", "paint", "body", "panel"],
      suggestedCameraRadius: 2.3,
    },

    // ─── 6. INTERIOR COCKPIT MODULES ───
    INTERIOR_GT3_YOKE: {
      id: "INTERIOR_GT3_YOKE",
      name: "FIA GT3 Carbon Racing Yoke GLB",
      subtitle: "Billet Carbon Steering Yoke with Integrated OLED Display & Rotary Encoders",
      description: "Full racing yoke steering wheel with Alcantara handgrips, titanium quick-release hub, and paddle shifters.",
      assetPath: "/models/interior/steering_wheel_gt3_yoke.glb",
      category: "INTERIOR",
      wheelbaseMm: 0,
      lengthMm: 180,
      widthMm: 310,
      heightMm: 220,
      bodyPaintMaterialNames: ["yoke", "carbon", "grip", "leather", "alcantara"],
      suggestedCameraRadius: 1.2,
    },
    INTERIOR_SPORT_WHEEL: {
      id: "INTERIOR_SPORT_WHEEL",
      name: "Sport GT Round Steering Wheel GLB",
      subtitle: "Perforated Leather Steering Wheel with Aluminum Spokes",
      description: "Sport GT round steering wheel with perforated Napa leather, contrasting 12 o'clock center stripe, and CNC billet buttons.",
      assetPath: "/models/interior/steering_wheel_sport.glb",
      category: "INTERIOR",
      wheelbaseMm: 0,
      lengthMm: 160,
      widthMm: 360,
      heightMm: 360,
      bodyPaintMaterialNames: ["wheel", "leather", "aluminum", "spoke"],
      suggestedCameraRadius: 1.3,
    },
    INTERIOR_SEAT_CARBON_RACE: {
      id: "INTERIOR_SEAT_CARBON_RACE",
      name: "Carbon Fiber FIA Monocoque Race Seat GLB",
      subtitle: "FIA 8855-2021 Ultralight Carbon Bucket Seat with 6-Point Harness Passages",
      description: "High-rigidity autoclaved carbon monocoque seat with high-density foam padding and Alcantara inserts.",
      assetPath: "/models/interior/seat_carbon_race.glb",
      category: "INTERIOR",
      wheelbaseMm: 0,
      lengthMm: 580,
      widthMm: 520,
      heightMm: 890,
      bodyPaintMaterialNames: ["seat", "carbon", "leather", "alcantara", "cushion"],
      suggestedCameraRadius: 1.8,
    },
    INTERIOR_SEAT_SPORT_BUCKET: {
      id: "INTERIOR_SEAT_SPORT_BUCKET",
      name: "Adaptive Ergonomic Sport Bucket Seat GLB",
      subtitle: "18-Way Adjustable Sport Touring Bucket Seat with Memory Foam",
      description: "Premium leather touring seat with pneumatic lumbar bolsters and heating/ventilation cooling channels.",
      assetPath: "/models/interior/seat_sport_bucket.glb",
      category: "INTERIOR",
      wheelbaseMm: 0,
      lengthMm: 620,
      widthMm: 560,
      heightMm: 920,
      bodyPaintMaterialNames: ["seat", "leather", "bolster", "stitch"],
      suggestedCameraRadius: 1.9,
    },
    INTERIOR_CONSOLE_GT3: {
      id: "INTERIOR_CONSOLE_GT3",
      name: "GT3 Competition Center Console GLB",
      subtitle: "Motorsport Switchgear Panel with Ignition Safety Guard & Brake Bias",
      description: "Race-ready center tunnel console featuring anodized toggle switches, fire extinguisher toggle, and carbon transmission tunnel.",
      assetPath: "/models/interior/center_console_gt3.glb",
      category: "INTERIOR",
      wheelbaseMm: 0,
      lengthMm: 850,
      widthMm: 280,
      heightMm: 340,
      bodyPaintMaterialNames: ["console", "carbon", "switch", "tunnel"],
      suggestedCameraRadius: 1.5,
    },
    INTERIOR_CONSOLE_EXECUTIVE: {
      id: "INTERIOR_CONSOLE_EXECUTIVE",
      name: "Executive Luxury Center Console GLB",
      subtitle: "Leather-Wrapped Tunnel Console with Touch Controller & Haptic Dials",
      description: "Executive grand touring console with dual wireless chargers, knurled aluminum rotary drive mode selectors, and cooled cup holders.",
      assetPath: "/models/interior/center_console_executive.glb",
      category: "INTERIOR",
      wheelbaseMm: 0,
      lengthMm: 920,
      widthMm: 320,
      heightMm: 360,
      bodyPaintMaterialNames: ["console", "leather", "aluminum", "trim"],
      suggestedCameraRadius: 1.6,
    },
    INTERIOR_DOOR_CARDS: {
      id: "INTERIOR_DOOR_CARDS",
      name: "Lightweight Sport Door Cards GLB",
      subtitle: "Carbon Inner Door Cards with Fabric Pull Straps & Armrest",
      description: "Motorsport interior door panels with carbon fiber card inserts, integrated speaker grilles, and woven pull straps.",
      assetPath: "/models/interior/door_cards_sport.glb",
      category: "INTERIOR",
      wheelbaseMm: 0,
      lengthMm: 1100,
      widthMm: 180,
      heightMm: 580,
      bodyPaintMaterialNames: ["door", "leather", "carbon", "armrest"],
      suggestedCameraRadius: 1.7,
    },
    INTERIOR_DASH_EXECUTIVE: {
      id: "INTERIOR_DASH_EXECUTIVE",
      name: "Executive Monolith Dashboard GLB",
      subtitle: "Dual-Tier Leather Waterfall & Open-Pore Wood Fascia",
      description: "Dual-tier executive dashboard with hidden micro-louvre HVAC vents, analog clock inlay, and sweeping dual glass display panels.",
      assetPath: "/models/interior/dashboard_executive.glb",
      category: "INTERIOR",
      wheelbaseMm: 0,
      lengthMm: 580,
      widthMm: 1520,
      heightMm: 380,
      bodyPaintMaterialNames: ["dash", "leather", "wood", "fascia"],
      glassMaterialNames: ["glass", "display"],
      suggestedCameraRadius: 1.8,
    },
    INTERIOR_DASH_SPORT: {
      id: "INTERIOR_DASH_SPORT",
      name: "GT3 Competition Track Cockpit Dashboard GLB",
      subtitle: "Dry-Carbon Fiber Cowl with Titanium Switchbank",
      description: "Pre-preg dry carbon fiber GT3 competition dashboard with exposed rollcage mounting brackets and aircraft-style turbine vents.",
      assetPath: "/models/interior/dashboard_sport.glb",
      category: "INTERIOR",
      wheelbaseMm: 0,
      lengthMm: 460,
      widthMm: 1480,
      heightMm: 320,
      bodyPaintMaterialNames: ["dash", "carbon", "cowl", "toggle"],
      glassMaterialNames: ["glass", "display"],
      suggestedCameraRadius: 1.7,
    },
    INTERIOR_DASH_HYPER: {
      id: "INTERIOR_DASH_HYPER",
      name: "Hyperscreen Blade Pillar-to-Pillar Dashboard GLB",
      subtitle: "Continuous Curved Glass Surface with Triple OLED Screens",
      description: "Hyperscreen minimalist glass dashboard spanning pillar-to-pillar with integrated driver cluster, central HMI, and passenger co-pilot display.",
      assetPath: "/models/interior/dashboard_hyper_glass.glb",
      category: "INTERIOR",
      wheelbaseMm: 0,
      lengthMm: 520,
      widthMm: 1500,
      heightMm: 360,
      bodyPaintMaterialNames: ["dash", "glass", "blade", "leather"],
      glassMaterialNames: ["glass", "screen"],
      suggestedCameraRadius: 1.8,
    },
  };

  public static getAsset(id: string): CarGlbAssetDefinition {
    return this.ASSETS[id] || this.ASSETS.SUPERCAR_MID_ENGINE;
  }

  public static getAllAssets(): CarGlbAssetDefinition[] {
    return Object.values(this.ASSETS);
  }

  public static getAssetsByCategory(category: GlbAssetCategory): CarGlbAssetDefinition[] {
    return Object.values(this.ASSETS).filter((a) => a.category === category);
  }
}
