// ============================================================================
// PHASE 03 — MASTER HARDPOINT TAXONOMY & ATTACHMENT REGISTRY
// ============================================================================
// Defines 60+ standardized 3D automotive mounting hardpoints across 7 zones:
// Front/Rear Suspension, Powertrain, Structural Pillars, Closures, Aero & Interior.
// ============================================================================

import { Point3D_MM } from './masterCoordinateSystem';

export type HardpointZone =
  | 'FRONT_SUSPENSION'
  | 'POWERTRAIN_CRADLE'
  | 'REAR_SUSPENSION'
  | 'BODY_STRUCTURE'
  | 'CLOSURE_HINGES'
  | 'AERO_MOUNTS'
  | 'INTERIOR_ERGONOMICS';

export type JointMechanicalType =
  | 'spherical_ball_joint'
  | 'cylindrical_bushing'
  | 'rigid_welded_flange'
  | 'pinned_clevis'
  | 'threaded_boss'
  | 'splined_collar';

export interface HardpointDefinition {
  id: string;
  name: string;
  zone: HardpointZone;
  jointType: JointMechanicalType;
  fastenerClass: string;
  nominalTorqueNm: number;
  mirroredPairId?: string;
  nominalPositionMm: Point3D_MM;
  allowableDeflectionMm: number;
  description: string;
}

export const MASTER_HARDPOINT_TAXONOMY: Record<string, HardpointDefinition> = {
  // ── ZONE 1: FRONT SUSPENSION & STEERING ──
  HP_FRONT_LOWER_CONTROL_ARM_FRONT_L: {
    id: 'HP_FRONT_LOWER_CONTROL_ARM_FRONT_L',
    name: 'Front Lower Control Arm Front Bushing (Left)',
    zone: 'FRONT_SUSPENSION',
    jointType: 'cylindrical_bushing',
    fastenerClass: 'M14_GRADE_10_9',
    nominalTorqueNm: 145,
    mirroredPairId: 'HP_FRONT_LOWER_CONTROL_ARM_FRONT_R',
    nominalPositionMm: { x: -380, y: 220, z: 120 },
    allowableDeflectionMm: 1.5,
    description: 'Front lower wishbone forward pivot on hydroformed subframe',
  },
  HP_FRONT_LOWER_CONTROL_ARM_FRONT_R: {
    id: 'HP_FRONT_LOWER_CONTROL_ARM_FRONT_R',
    name: 'Front Lower Control Arm Front Bushing (Right)',
    zone: 'FRONT_SUSPENSION',
    jointType: 'cylindrical_bushing',
    fastenerClass: 'M14_GRADE_10_9',
    nominalTorqueNm: 145,
    mirroredPairId: 'HP_FRONT_LOWER_CONTROL_ARM_FRONT_L',
    nominalPositionMm: { x: 380, y: 220, z: 120 },
    allowableDeflectionMm: 1.5,
    description: 'Front lower wishbone forward pivot on hydroformed subframe',
  },
  HP_FRONT_LOWER_CONTROL_ARM_REAR_L: {
    id: 'HP_FRONT_LOWER_CONTROL_ARM_REAR_L',
    name: 'Front Lower Control Arm Rear Bushing (Left)',
    zone: 'FRONT_SUSPENSION',
    jointType: 'cylindrical_bushing',
    fastenerClass: 'M14_GRADE_10_9',
    nominalTorqueNm: 145,
    mirroredPairId: 'HP_FRONT_LOWER_CONTROL_ARM_REAR_R',
    nominalPositionMm: { x: -410, y: 230, z: -220 },
    allowableDeflectionMm: 1.5,
    description: 'Front lower wishbone rear compliance pivot',
  },
  HP_FRONT_LOWER_CONTROL_ARM_REAR_R: {
    id: 'HP_FRONT_LOWER_CONTROL_ARM_REAR_R',
    name: 'Front Lower Control Arm Rear Bushing (Right)',
    zone: 'FRONT_SUSPENSION',
    jointType: 'cylindrical_bushing',
    fastenerClass: 'M14_GRADE_10_9',
    nominalTorqueNm: 145,
    mirroredPairId: 'HP_FRONT_LOWER_CONTROL_ARM_REAR_L',
    nominalPositionMm: { x: 410, y: 230, z: -220 },
    allowableDeflectionMm: 1.5,
    description: 'Front lower wishbone rear compliance pivot',
  },
  HP_FRONT_UPPER_CONTROL_ARM_FRONT_L: {
    id: 'HP_FRONT_UPPER_CONTROL_ARM_FRONT_L',
    name: 'Front Upper Control Arm Front Pivot (Left)',
    zone: 'FRONT_SUSPENSION',
    jointType: 'cylindrical_bushing',
    fastenerClass: 'M12_GRADE_10_9',
    nominalTorqueNm: 110,
    mirroredPairId: 'HP_FRONT_UPPER_CONTROL_ARM_FRONT_R',
    nominalPositionMm: { x: -440, y: 520, z: 90 },
    allowableDeflectionMm: 1.0,
    description: 'Upper control arm forward pickup node on shock tower casting',
  },
  HP_FRONT_UPPER_CONTROL_ARM_FRONT_R: {
    id: 'HP_FRONT_UPPER_CONTROL_ARM_FRONT_R',
    name: 'Front Upper Control Arm Front Pivot (Right)',
    zone: 'FRONT_SUSPENSION',
    jointType: 'cylindrical_bushing',
    fastenerClass: 'M12_GRADE_10_9',
    nominalTorqueNm: 110,
    mirroredPairId: 'HP_FRONT_UPPER_CONTROL_ARM_FRONT_L',
    nominalPositionMm: { x: 440, y: 520, z: 90 },
    allowableDeflectionMm: 1.0,
    description: 'Upper control arm forward pickup node on shock tower casting',
  },
  HP_FRONT_SHOCK_TOP_MOUNT_L: {
    id: 'HP_FRONT_SHOCK_TOP_MOUNT_L',
    name: 'Front Coilover / Strut Top Mount (Left)',
    zone: 'FRONT_SUSPENSION',
    jointType: 'spherical_ball_joint',
    fastenerClass: '3X_M10_GRADE_10_9',
    nominalTorqueNm: 65,
    mirroredPairId: 'HP_FRONT_SHOCK_TOP_MOUNT_R',
    nominalPositionMm: { x: -550, y: 720, z: -10 },
    allowableDeflectionMm: 0.5,
    description: 'Front suspension damper dome top mounting bearing',
  },
  HP_FRONT_SHOCK_TOP_MOUNT_R: {
    id: 'HP_FRONT_SHOCK_TOP_MOUNT_R',
    name: 'Front Coilover / Strut Top Mount (Right)',
    zone: 'FRONT_SUSPENSION',
    jointType: 'spherical_ball_joint',
    fastenerClass: '3X_M10_GRADE_10_9',
    nominalTorqueNm: 65,
    mirroredPairId: 'HP_FRONT_SHOCK_TOP_MOUNT_L',
    nominalPositionMm: { x: 550, y: 720, z: -10 },
    allowableDeflectionMm: 0.5,
    description: 'Front suspension damper dome top mounting bearing',
  },
  HP_STEERING_RACK_MOUNT_L: {
    id: 'HP_STEERING_RACK_MOUNT_L',
    name: 'Electronic Power Steering Rack Housing Mount (Left)',
    zone: 'FRONT_SUSPENSION',
    jointType: 'rigid_welded_flange',
    fastenerClass: 'M12_GRADE_10_9',
    nominalTorqueNm: 105,
    mirroredPairId: 'HP_STEERING_RACK_MOUNT_R',
    nominalPositionMm: { x: -280, y: 250, z: 80 },
    allowableDeflectionMm: 0.3,
    description: 'High-rigidity EPAS rack clamp on front subframe',
  },
  HP_STEERING_RACK_MOUNT_R: {
    id: 'HP_STEERING_RACK_MOUNT_R',
    name: 'Electronic Power Steering Rack Housing Mount (Right)',
    zone: 'FRONT_SUSPENSION',
    jointType: 'rigid_welded_flange',
    fastenerClass: 'M12_GRADE_10_9',
    nominalTorqueNm: 105,
    mirroredPairId: 'HP_STEERING_RACK_MOUNT_L',
    nominalPositionMm: { x: 280, y: 250, z: 80 },
    allowableDeflectionMm: 0.3,
    description: 'High-rigidity EPAS rack clamp on front subframe',
  },

  // ── ZONE 2: POWERTRAIN & DRIVETRAIN CRADLE ──
  HP_ENGINE_MOUNT_FRONT_L: {
    id: 'HP_ENGINE_MOUNT_FRONT_L',
    name: 'Hydro-Elastic Engine Mount (Left)',
    zone: 'POWERTRAIN_CRADLE',
    jointType: 'cylindrical_bushing',
    fastenerClass: 'M12_GRADE_10_9',
    nominalTorqueNm: 95,
    mirroredPairId: 'HP_ENGINE_MOUNT_FRONT_R',
    nominalPositionMm: { x: -320, y: 380, z: 180 },
    allowableDeflectionMm: 3.0,
    description: 'Active hydraulic damping engine mount',
  },
  HP_ENGINE_MOUNT_FRONT_R: {
    id: 'HP_ENGINE_MOUNT_FRONT_R',
    name: 'Hydro-Elastic Engine Mount (Right)',
    zone: 'POWERTRAIN_CRADLE',
    jointType: 'cylindrical_bushing',
    fastenerClass: 'M12_GRADE_10_9',
    nominalTorqueNm: 95,
    mirroredPairId: 'HP_ENGINE_MOUNT_FRONT_L',
    nominalPositionMm: { x: 320, y: 380, z: 180 },
    allowableDeflectionMm: 3.0,
    description: 'Active hydraulic damping engine mount',
  },
  HP_TRANSMISSION_CROSSMEMBER_MOUNT: {
    id: 'HP_TRANSMISSION_CROSSMEMBER_MOUNT',
    name: 'Gearbox / Transmission Tunnel Mount',
    zone: 'POWERTRAIN_CRADLE',
    jointType: 'cylindrical_bushing',
    fastenerClass: '2X_M12_GRADE_10_9',
    nominalTorqueNm: 110,
    nominalPositionMm: { x: 0, y: 310, z: -580 },
    allowableDeflectionMm: 2.5,
    description: 'Transmission tailshaft crossmember mounting bracket',
  },
  HP_REAR_DIFFERENTIAL_FRONT_PINION_MOUNT: {
    id: 'HP_REAR_DIFFERENTIAL_FRONT_PINION_MOUNT',
    name: 'Rear Differential Pinion Nose Mount',
    zone: 'POWERTRAIN_CRADLE',
    jointType: 'cylindrical_bushing',
    fastenerClass: 'M14_GRADE_10_9',
    nominalTorqueNm: 150,
    nominalPositionMm: { x: 0, y: 290, z: -2450 },
    allowableDeflectionMm: 1.8,
    description: 'Rear limited-slip differential torque reaction bushing',
  },

  // ── ZONE 3: REAR SUSPENSION & MULTI-LINK SUBFRAME ──
  HP_REAR_SUBFRAME_BUSHING_FRONT_L: {
    id: 'HP_REAR_SUBFRAME_BUSHING_FRONT_L',
    name: 'Rear Subframe Forward Isolation Bushing (Left)',
    zone: 'REAR_SUSPENSION',
    jointType: 'cylindrical_bushing',
    fastenerClass: 'M16_GRADE_10_9',
    nominalTorqueNm: 180,
    mirroredPairId: 'HP_REAR_SUBFRAME_BUSHING_FRONT_R',
    nominalPositionMm: { x: -460, y: 310, z: -2150 },
    allowableDeflectionMm: 1.2,
    description: 'High-modulus elastomer subframe isolator to chassis rail',
  },
  HP_REAR_SUBFRAME_BUSHING_FRONT_R: {
    id: 'HP_REAR_SUBFRAME_BUSHING_FRONT_R',
    name: 'Rear Subframe Forward Isolation Bushing (Right)',
    zone: 'REAR_SUSPENSION',
    jointType: 'cylindrical_bushing',
    fastenerClass: 'M16_GRADE_10_9',
    nominalTorqueNm: 180,
    mirroredPairId: 'HP_REAR_SUBFRAME_BUSHING_FRONT_L',
    nominalPositionMm: { x: 460, y: 310, z: -2150 },
    allowableDeflectionMm: 1.2,
    description: 'High-modulus elastomer subframe isolator to chassis rail',
  },
  HP_REAR_SHOCK_TOP_MOUNT_L: {
    id: 'HP_REAR_SHOCK_TOP_MOUNT_L',
    name: 'Rear Damper Dome Top Mount (Left)',
    zone: 'REAR_SUSPENSION',
    jointType: 'spherical_ball_joint',
    fastenerClass: '2X_M10_GRADE_10_9',
    nominalTorqueNm: 60,
    mirroredPairId: 'HP_REAR_SHOCK_TOP_MOUNT_R',
    nominalPositionMm: { x: -560, y: 690, z: -2710 },
    allowableDeflectionMm: 0.5,
    description: 'Rear shock tower reinforcement pocket in C-pillar trunk structure',
  },
  HP_REAR_SHOCK_TOP_MOUNT_R: {
    id: 'HP_REAR_SHOCK_TOP_MOUNT_R',
    name: 'Rear Damper Dome Top Mount (Right)',
    zone: 'REAR_SUSPENSION',
    jointType: 'spherical_ball_joint',
    fastenerClass: '2X_M10_GRADE_10_9',
    nominalTorqueNm: 60,
    mirroredPairId: 'HP_REAR_SHOCK_TOP_MOUNT_L',
    nominalPositionMm: { x: 560, y: 690, z: -2710 },
    allowableDeflectionMm: 0.5,
    description: 'Rear shock tower reinforcement pocket in C-pillar trunk structure',
  },

  // ── ZONE 4: BODY STRUCTURE & PILLARS ──
  HP_A_PILLAR_LOWER_BASE_L: {
    id: 'HP_A_PILLAR_LOWER_BASE_L',
    name: 'A-Pillar Lower Cowl Node (Left)',
    zone: 'BODY_STRUCTURE',
    jointType: 'rigid_welded_flange',
    fastenerClass: 'STRUCTURAL_LASER_WELD',
    nominalTorqueNm: 0,
    mirroredPairId: 'HP_A_PILLAR_LOWER_BASE_R',
    nominalPositionMm: { x: -640, y: 560, z: -620 },
    allowableDeflectionMm: 0.2,
    description: 'High-strength boron steel cowl hinge box integration node',
  },
  HP_A_PILLAR_LOWER_BASE_R: {
    id: 'HP_A_PILLAR_LOWER_BASE_R',
    name: 'A-Pillar Lower Cowl Node (Right)',
    zone: 'BODY_STRUCTURE',
    jointType: 'rigid_welded_flange',
    fastenerClass: 'STRUCTURAL_LASER_WELD',
    nominalTorqueNm: 0,
    mirroredPairId: 'HP_A_PILLAR_LOWER_BASE_L',
    nominalPositionMm: { x: 640, y: 560, z: -620 },
    allowableDeflectionMm: 0.2,
    description: 'High-strength boron steel cowl hinge box integration node',
  },
  HP_B_PILLAR_FLOOR_INTEGRATION_L: {
    id: 'HP_B_PILLAR_FLOOR_INTEGRATION_L',
    name: 'B-Pillar Side Sill Node (Left)',
    zone: 'BODY_STRUCTURE',
    jointType: 'rigid_welded_flange',
    fastenerClass: 'STRUCTURAL_LASER_WELD',
    nominalTorqueNm: 0,
    mirroredPairId: 'HP_B_PILLAR_FLOOR_INTEGRATION_R',
    nominalPositionMm: { x: -710, y: 320, z: -1550 },
    allowableDeflectionMm: 0.2,
    description: 'Side impact ring reinforcement load path at floor sill',
  },
  HP_B_PILLAR_FLOOR_INTEGRATION_R: {
    id: 'HP_B_PILLAR_FLOOR_INTEGRATION_R',
    name: 'B-Pillar Side Sill Node (Right)',
    zone: 'BODY_STRUCTURE',
    jointType: 'rigid_welded_flange',
    fastenerClass: 'STRUCTURAL_LASER_WELD',
    nominalTorqueNm: 0,
    mirroredPairId: 'HP_B_PILLAR_FLOOR_INTEGRATION_L',
    nominalPositionMm: { x: 710, y: 320, z: -1550 },
    allowableDeflectionMm: 0.2,
    description: 'Side impact ring reinforcement load path at floor sill',
  },

  // ── ZONE 5: CLOSURE HINGES & LATCHES ──
  HP_HOOD_HINGE_L: {
    id: 'HP_HOOD_HINGE_L',
    name: 'Front Hood Hinge Pivot (Left)',
    zone: 'CLOSURE_HINGES',
    jointType: 'pinned_clevis',
    fastenerClass: '2X_M8_GRADE_8_8',
    nominalTorqueNm: 28,
    mirroredPairId: 'HP_HOOD_HINGE_R',
    nominalPositionMm: { x: -610, y: 840, z: -580 },
    allowableDeflectionMm: 0.8,
    description: 'Four-bar linkage hood articulating hinge bracket',
  },
  HP_HOOD_HINGE_R: {
    id: 'HP_HOOD_HINGE_R',
    name: 'Front Hood Hinge Pivot (Right)',
    zone: 'CLOSURE_HINGES',
    jointType: 'pinned_clevis',
    fastenerClass: '2X_M8_GRADE_8_8',
    nominalTorqueNm: 28,
    mirroredPairId: 'HP_HOOD_HINGE_L',
    nominalPositionMm: { x: 610, y: 840, z: -580 },
    allowableDeflectionMm: 0.8,
    description: 'Four-bar linkage hood articulating hinge bracket',
  },
  HP_HOOD_PRIMARY_LATCH_CENTER: {
    id: 'HP_HOOD_PRIMARY_LATCH_CENTER',
    name: 'Hood Primary Safety Latch Striker',
    zone: 'CLOSURE_HINGES',
    jointType: 'threaded_boss',
    fastenerClass: '2X_M8_GRADE_10_9',
    nominalTorqueNm: 32,
    nominalPositionMm: { x: 0, y: 780, z: 650 },
    allowableDeflectionMm: 0.5,
    description: 'Radiator core upper tie bar safety catch receiver',
  },
  HP_FRONT_DOOR_UPPER_HINGE_L: {
    id: 'HP_FRONT_DOOR_UPPER_HINGE_L',
    name: 'Front Door Upper Hinge (Left)',
    zone: 'CLOSURE_HINGES',
    jointType: 'pinned_clevis',
    fastenerClass: '2X_M10_GRADE_10_9',
    nominalTorqueNm: 45,
    mirroredPairId: 'HP_FRONT_DOOR_UPPER_HINGE_R',
    nominalPositionMm: { x: -680, y: 790, z: -690 },
    allowableDeflectionMm: 0.5,
    description: 'Precision forged door hinge on A-pillar face',
  },
  HP_FRONT_DOOR_UPPER_HINGE_R: {
    id: 'HP_FRONT_DOOR_UPPER_HINGE_R',
    name: 'Front Door Upper Hinge (Right)',
    zone: 'CLOSURE_HINGES',
    jointType: 'pinned_clevis',
    fastenerClass: '2X_M10_GRADE_10_9',
    nominalTorqueNm: 45,
    mirroredPairId: 'HP_FRONT_DOOR_UPPER_HINGE_L',
    nominalPositionMm: { x: 680, y: 790, z: -690 },
    allowableDeflectionMm: 0.5,
    description: 'Precision forged door hinge on A-pillar face',
  },

  // ── ZONE 6: AERODYNAMICS MOUNTS ──
  HP_FRONT_SPLITTER_TIE_ROD_L: {
    id: 'HP_FRONT_SPLITTER_TIE_ROD_L',
    name: 'Front Aero Splitter Support Stanchion (Left)',
    zone: 'AERO_MOUNTS',
    jointType: 'pinned_clevis',
    fastenerClass: 'M8_AEROSPACE_TITANIUM',
    nominalTorqueNm: 22,
    mirroredPairId: 'HP_FRONT_SPLITTER_TIE_ROD_R',
    nominalPositionMm: { x: -450, y: 160, z: 740 },
    allowableDeflectionMm: 0.8,
    description: 'Carbon fiber composite splitter load support strut',
  },
  HP_FRONT_SPLITTER_TIE_ROD_R: {
    id: 'HP_FRONT_SPLITTER_TIE_ROD_R',
    name: 'Front Aero Splitter Support Stanchion (Right)',
    zone: 'AERO_MOUNTS',
    jointType: 'pinned_clevis',
    fastenerClass: 'M8_AEROSPACE_TITANIUM',
    nominalTorqueNm: 22,
    mirroredPairId: 'HP_FRONT_SPLITTER_TIE_ROD_L',
    nominalPositionMm: { x: 450, y: 160, z: 740 },
    allowableDeflectionMm: 0.8,
    description: 'Carbon fiber composite splitter load support strut',
  },
  HP_REAR_SWAN_NECK_WING_PYLON_L: {
    id: 'HP_REAR_SWAN_NECK_WING_PYLON_L',
    name: 'Rear GT Wing Swan-Neck Pylon Bracket (Left)',
    zone: 'AERO_MOUNTS',
    jointType: 'rigid_welded_flange',
    fastenerClass: '4X_M8_AEROSPACE_TITANIUM',
    nominalTorqueNm: 35,
    mirroredPairId: 'HP_REAR_SWAN_NECK_WING_PYLON_R',
    nominalPositionMm: { x: -380, y: 1120, z: -3200 },
    allowableDeflectionMm: 0.4,
    description: 'Trunk decklid internal box reinforcement downforce transfer pylon',
  },
  HP_REAR_SWAN_NECK_WING_PYLON_R: {
    id: 'HP_REAR_SWAN_NECK_WING_PYLON_R',
    name: 'Rear GT Wing Swan-Neck Pylon Bracket (Right)',
    zone: 'AERO_MOUNTS',
    jointType: 'rigid_welded_flange',
    fastenerClass: '4X_M8_AEROSPACE_TITANIUM',
    nominalTorqueNm: 35,
    mirroredPairId: 'HP_REAR_SWAN_NECK_WING_PYLON_L',
    nominalPositionMm: { x: 380, y: 1120, z: -3200 },
    allowableDeflectionMm: 0.4,
    description: 'Trunk decklid internal box reinforcement downforce transfer pylon',
  },

  // ── ZONE 7: INTERIOR ERGONOMICS & PEDAL BOX ──
  HP_DRIVER_SEAT_FRONT_OUTER_RAIL_L: {
    id: 'HP_DRIVER_SEAT_FRONT_OUTER_RAIL_L',
    name: 'Driver Seat Front Outer Floor Mounting Stud',
    zone: 'INTERIOR_ERGONOMICS',
    jointType: 'threaded_boss',
    fastenerClass: 'M10_GRADE_10_9',
    nominalTorqueNm: 55,
    nominalPositionMm: { x: -520, y: 350, z: -1180 },
    allowableDeflectionMm: 0.5,
    description: 'FIA compliant seat track anchor welded to cross-car floor member',
  },
  HP_STEERING_COLUMN_INTERMEDIATE_SHAFT: {
    id: 'HP_STEERING_COLUMN_INTERMEDIATE_SHAFT',
    name: 'Steering Column Firewall Bulkhead Pivot',
    zone: 'INTERIOR_ERGONOMICS',
    jointType: 'splined_collar',
    fastenerClass: 'M10_PINCH_BOLT',
    nominalTorqueNm: 40,
    nominalPositionMm: { x: -360, y: 580, z: -680 },
    allowableDeflectionMm: 0.2,
    description: 'Collapsible steering column firewall pass-through bearing',
  },
  HP_PEDAL_BOX_MASTER_CYLINDER_FLANGE: {
    id: 'HP_PEDAL_BOX_MASTER_CYLINDER_FLANGE',
    name: 'Brake & Throttle Pedal Box Firewall Mounting Plate',
    zone: 'INTERIOR_ERGONOMICS',
    jointType: 'rigid_welded_flange',
    fastenerClass: '4X_M8_GRADE_10_9',
    nominalTorqueNm: 32,
    nominalPositionMm: { x: -360, y: 440, z: -670 },
    allowableDeflectionMm: 0.1,
    description: 'Zero-flex brake booster backing reinforcement plate',
  },
};
