// ===================================================================
// AUTOMOTIVE R&D DEEP MASTERY — 95 MAJOR SUBSYSTEM DISCIPLINES
// Complete automotive engineering branches across all 12 divisions
// ===================================================================
import type {
  SubsystemBranchId,
  SubsystemBranchMeta,
  MasterDivisionId,
  TestingFacilityType,
} from "./rdTreeTypes";

export const SUBSYSTEM_BRANCHES: SubsystemBranchMeta[] = [
  // ─────────────────────────────────────────────────────────────
  // 1. POWERTRAIN (8 branches)
  // ─────────────────────────────────────────────────────────────
  {
    id: "ice_engine",
    divisionId: "powertrain",
    name: "Internal Combustion Engine",
    shortName: "ICE Engine",
    tagline: "Combustion Architecture, Cylinder Heads & Displacement",
    icon: "Cog",
    primaryFacility: "engine_lab",
    requiredTestingType: "dyno_cell",
    subsections: [
      "Engine Architecture",
      "Cylinder Head",
      "Engine Block & Construction",
      "Internal Components",
      "Combustion & Valvetrain",
    ],
  },
  {
    id: "electric_powertrain",
    divisionId: "powertrain",
    name: "Electric Powertrain",
    shortName: "Electric Drive",
    tagline: "Permanent Magnet Motors, Axial Flux & E-Axles",
    icon: "Zap",
    primaryFacility: "battery_lab",
    requiredTestingType: "dyno_cell",
    subsections: [
      "Traction Motors",
      "Axial-Flux Geometry",
      "Integrated E-Axles",
      "Direct Drive Systems",
    ],
  },
  {
    id: "hybrid_powertrain",
    divisionId: "powertrain",
    name: "Hybrid Powertrain Systems",
    shortName: "Hybrid Systems",
    tagline: "Parallel, Series, Plug-in & Kinetic Energy Blending",
    icon: "Cpu",
    primaryFacility: "engine_lab",
    requiredTestingType: "dyno_cell",
    subsections: [
      "Mild Hybrid 48V",
      "Full Parallel Hybrids",
      "PHEV Systems",
      "Performance Hybrid Boost",
    ],
  },
  {
    id: "transmission_systems",
    divisionId: "powertrain",
    name: "Transmission Systems",
    shortName: "Transmissions",
    tagline: "Manual, Torque-Converter, Dual-Clutch & Sequentials",
    icon: "Sliders",
    primaryFacility: "engine_lab",
    requiredTestingType: "dyno_cell",
    subsections: [
      "Manual Transmissions",
      "Automatic & Planetary",
      "Dual-Clutch (DCT)",
      "Sequential Dog-Ring",
      "Multi-Speed EV Gearboxes",
    ],
  },
  {
    id: "differential_drivetrain",
    divisionId: "powertrain",
    name: "Differential & Drivetrain",
    shortName: "Drivetrain",
    tagline: "Mechanical LSDs, Torque Vectoring & All-Wheel Drive",
    icon: "Compass",
    primaryFacility: "engine_lab",
    requiredTestingType: "test_track",
    subsections: [
      "Open & Viscous Differentials",
      "Mechanical Clutch-Type LSD",
      "Active Electronic Differential",
      "Torque-Vectoring AWD",
    ],
  },
  {
    id: "fuel_energy_systems",
    divisionId: "powertrain",
    name: "Fuel & Energy Systems",
    shortName: "Fuel Systems",
    tagline: "Direct Injection, High-Pressure Rails & Alternative Fuels",
    icon: "Flame",
    primaryFacility: "engine_lab",
    requiredTestingType: "dyno_cell",
    subsections: [
      "Carburetion & Low-Pressure",
      "Multi-Point EFI",
      "Direct Gasoline Injection",
      "High-Pressure Common Rail",
      "Hydrogen Fuel Delivery",
    ],
  },
  {
    id: "engine_electronics",
    divisionId: "powertrain",
    name: "Engine Electronics & Mapping",
    shortName: "Engine ECU",
    tagline: "Closed-Loop O2, Knock Retard & Predictive Ignition Maps",
    icon: "CircuitBoard",
    primaryFacility: "electronics_lab",
    requiredTestingType: "dyno_cell",
    subsections: [
      "Ignition Timing Modules",
      "Microprocessor Engine ECUs",
      "Individual Cylinder Knock Control",
      "Drive-by-Wire Throttles",
    ],
  },
  {
    id: "thermal_powertrain",
    divisionId: "powertrain",
    name: "Thermal Powertrain Engineering",
    shortName: "Engine Thermal",
    tagline: "Oil Cooling, Intercoolers & Multi-Loop Heat Rejection",
    icon: "Thermometer",
    primaryFacility: "engine_lab",
    requiredTestingType: "climate_chamber",
    subsections: [
      "Radiator Thermodynamics",
      "Air-to-Air & Water Intercoolers",
      "Thermostatic Oil Coolers",
      "Thermal Insulation & Shields",
    ],
  },

  // ─────────────────────────────────────────────────────────────
  // 2. VEHICLE DYNAMICS (6 branches)
  // ─────────────────────────────────────────────────────────────
  {
    id: "chassis_dynamics",
    divisionId: "vehicle_dynamics",
    name: "Chassis Structure & Torsion",
    shortName: "Chassis",
    tagline: "Torsional Stiffness, Beam Deflection & Hardpoint Loading",
    icon: "Layers",
    primaryFacility: "materials_lab",
    requiredTestingType: "shaker_rig",
    subsections: [
      "Ladder & Perimeter Frames",
      "Tubular Spaceframes",
      "Monocoque Tub Architecture",
      "Carbon Composite Monocoque",
    ],
  },
  {
    id: "suspension_dynamics",
    divisionId: "vehicle_dynamics",
    name: "Suspension & Kinematics",
    shortName: "Suspension",
    tagline: "Double Wishbone, Multi-Link, Pushrod & Camber Curves",
    icon: "Activity",
    primaryFacility: "testing_center",
    requiredTestingType: "shaker_rig",
    subsections: [
      "Live Axle & MacPherson",
      "Double Wishbone Kinematics",
      "Multi-Link Independent",
      "Pushrod & Inboard Dampers",
      "Active Hydraulic Levelling",
    ],
  },
  {
    id: "steering_systems",
    divisionId: "vehicle_dynamics",
    name: "Steering Systems",
    shortName: "Steering",
    tagline: "Rack-and-Pinion, Hydraulic Assist, EPS & Steer-by-Wire",
    icon: "Disc",
    primaryFacility: "testing_center",
    requiredTestingType: "test_track",
    subsections: [
      "Recirculating Ball & Manual Rack",
      "Hydraulic Power Steering",
      "Electric Power Steering (EPS)",
      "Variable-Ratio & Rear Steering",
      "Steer-by-Wire Actuators",
    ],
  },
  {
    id: "brake_systems",
    divisionId: "vehicle_dynamics",
    name: "Brake Systems & Hydraulics",
    shortName: "Braking",
    tagline: "Ventilated Discs, Multi-Piston Monoblocs & Carbon Ceramic",
    icon: "CircleDot",
    primaryFacility: "safety_center",
    requiredTestingType: "dyno_cell",
    subsections: [
      "Drum & Solid Discs",
      "Ventilated High-Carbon Discs",
      "Multi-Piston Monobloc Calipers",
      "Carbon-Ceramic Matrix",
      "Electro-Hydraulic Brake-by-Wire",
    ],
  },
  {
    id: "tyres_wheels_dynamics",
    divisionId: "vehicle_dynamics",
    name: "Tyres & Wheels Dynamics",
    shortName: "Tyres & Wheels",
    tagline: "Radial Plies, Sipes, Racing Slicks & Forged Magnesium",
    icon: "CircleDot",
    primaryFacility: "testing_center",
    requiredTestingType: "test_track",
    subsections: [
      "Bias-Ply to Steel Radial",
      "High-Performance Summer Compounds",
      "Track Semi-Slicks & Slicks",
      "Forged Monoblock Aluminium",
      "Full Carbon-Fiber Wheels",
    ],
  },
  {
    id: "vehicle_dynamics_control",
    divisionId: "vehicle_dynamics",
    name: "Vehicle Dynamics & Stability",
    shortName: "Dynamics Control",
    tagline: "Yaw Moment Control, ESC Algorithms & Active Roll Bars",
    icon: "Maximize2",
    primaryFacility: "testing_center",
    requiredTestingType: "test_track",
    subsections: [
      "Mechanical Anti-Roll Bars",
      "Electronic Stability Control (ESC)",
      "Active Anti-Roll Systems",
      "Integrated Chassis Management",
    ],
  },

  // ─────────────────────────────────────────────────────────────
  // 3. VEHICLE STRUCTURE & DESIGN (8 branches)
  // ─────────────────────────────────────────────────────────────
  {
    id: "body_structure",
    divisionId: "vehicle_design",
    name: "Body Structure Architecture",
    shortName: "Body Structure",
    tagline: "Passenger Safety Cell, Roof Arches & Crash Pillars",
    icon: "Car",
    primaryFacility: "materials_lab",
    requiredTestingType: "crash_barrier",
    subsections: [
      "Body-on-Frame Joints",
      "Steel Unibody Stamping",
      "Aluminium Hybrid Spaceframe",
      "Carbon Tub Integration",
    ],
  },
  {
    id: "exterior_bodywork",
    divisionId: "vehicle_design",
    name: "Exterior Bodywork & Panels",
    shortName: "Exterior Styling",
    tagline: "Shutlines, Stampings, Closures & Class-A Surfaces",
    icon: "Car",
    primaryFacility: "materials_lab",
    requiredTestingType: "wind_tunnel",
    subsections: [
      "Stamped Steel Closures",
      "Pressed Sheet Aluminium",
      "Sheet Molding Compound (SMC)",
      "Autoclave Carbon Panels",
    ],
  },
  {
    id: "lightweight_engineering",
    divisionId: "vehicle_design",
    name: "Lightweight Engineering",
    shortName: "Lightweighting",
    tagline: "Topology Optimization, Hollow Extrusions & Mass Trimming",
    icon: "Feather",
    primaryFacility: "materials_lab",
    requiredTestingType: "shaker_rig",
    subsections: [
      "High-Strength Steel Thinning",
      "Aluminium Extrusion Nodes",
      "Structural Adhesives & Rivets",
      "Generative CAD Topology Optimization",
    ],
  },
  {
    id: "materials_engineering",
    divisionId: "vehicle_design",
    name: "Materials Science & Metallurgy",
    shortName: "Materials",
    tagline: "Alloys, Titanium, Composites, Ceramics & Polymers",
    icon: "Layers",
    primaryFacility: "materials_lab",
    requiredTestingType: "dyno_cell",
    subsections: [
      "Deep-Draw Mild Steel",
      "Automotive 6000 Aluminium",
      "Prepreg Carbon Fiber",
      "Grade 5 Titanium Alloys",
      "Silicon-Carbide Ceramics",
    ],
  },
  {
    id: "nvh_acoustics",
    divisionId: "vehicle_design",
    name: "NVH & Cabin Acoustics",
    shortName: "NVH & Acoustics",
    tagline: "Resonance Damping, Double Glazing & Sound Isolation",
    icon: "Volume2",
    primaryFacility: "nvh_lab",
    requiredTestingType: "shaker_rig",
    subsections: [
      "Bitumen Mastic Damping",
      "Acoustic Glass Glazing",
      "Active Noise Cancellation",
      "Subframe Hydraulic Bushings",
    ],
  },
  {
    id: "interior_cabin",
    divisionId: "vehicle_design",
    name: "Interior Cabin Architecture",
    shortName: "Interior Cabin",
    tagline: "Dashboards, Seating Ergonomics, Consoles & Trims",
    icon: "Armchair",
    primaryFacility: "nvh_lab",
    requiredTestingType: "none",
    subsections: [
      "Padded Vinyl Dashboards",
      "Multi-Density Anatomical Foam",
      "Full Leather Nappa Lofts",
      "Cantilevered Bridge Consoles",
    ],
  },
  {
    id: "ergonomics_hmi",
    divisionId: "vehicle_design",
    name: "Ergonomics & Human Factors",
    shortName: "Ergonomics HMI",
    tagline: "SAE J826 H-Point, Reach Envelopes & Sightline Studies",
    icon: "UserCheck",
    primaryFacility: "nvh_lab",
    requiredTestingType: "none",
    subsections: [
      "SAE J826 Eyellipse Sightlines",
      "Steering Reach Envelopes",
      "Tactile Knurled Switchgear",
      "Heads-Up Display Optical Alignment",
    ],
  },
  {
    id: "comfort_systems",
    divisionId: "vehicle_design",
    name: "Comfort & Climate Systems",
    shortName: "Comfort Systems",
    tagline: "Multi-Zone HVAC, Seat Ventilation & Massage Motors",
    icon: "Wind",
    primaryFacility: "nvh_lab",
    requiredTestingType: "climate_chamber",
    subsections: [
      "Single-Zone Heater Units",
      "Automatic Multi-Zone Climate",
      "Pneumatic Massage Bladders",
      "Micro-Climate Seat Heating/Cooling",
    ],
  },

  // ─────────────────────────────────────────────────────────────
  // 4. AERODYNAMICS (7 branches)
  // ─────────────────────────────────────────────────────────────
  {
    id: "vehicle_aerodynamics",
    divisionId: "aerodynamics",
    name: "Vehicle Aerodynamics",
    shortName: "Vehicle Aero",
    tagline: "Drag Coefficient (Cd), Separation Bubbles & Wake Shaving",
    icon: "Wind",
    primaryFacility: "aero_center",
    requiredTestingType: "wind_tunnel",
    subsections: [
      "Bluff Body Drag Reduction",
      "Kamm-Tail Aerodynamic Truncation",
      "A-Pillar Vortex Tuning",
      "Low-Drag High-Speed Envelopes",
    ],
  },
  {
    id: "underbody_aerodynamics",
    divisionId: "aerodynamics",
    name: "Underbody Aerodynamics",
    shortName: "Underbody Aero",
    tagline: "Flat Underfloors, Venturi Tunnels & Ground Effect",
    icon: "ArrowDown",
    primaryFacility: "aero_center",
    requiredTestingType: "wind_tunnel",
    subsections: [
      "Partial Belly Pans",
      "Full Sealed Flat Underbody",
      "Venturi Expansion Tunnels",
      "Rear Ground-Effect Diffusers",
    ],
  },
  {
    id: "racing_aerodynamics",
    divisionId: "aerodynamics",
    name: "Racing High-Downforce Aero",
    shortName: "Racing Aero",
    tagline: "Multi-Element Wings, Dive Planes, Canards & Vortex Fins",
    icon: "Zap",
    primaryFacility: "aero_center",
    requiredTestingType: "wind_tunnel",
    subsections: [
      "Front Splitters & Strakes",
      "Dual-Element High-Angle Wings",
      "Swan-Neck Wing Mountings",
      "Gurney Flaps & Vortex Generators",
    ],
  },
  {
    id: "active_aerodynamics",
    divisionId: "aerodynamics",
    name: "Active Aerodynamics",
    shortName: "Active Aero",
    tagline: "Deployable DRS Wings, Active Louvers & Brake Flaps",
    icon: "Sliders",
    primaryFacility: "aero_center",
    requiredTestingType: "wind_tunnel",
    subsections: [
      "Speed-Sensitive Rear Spoilers",
      "Active Drag Reduction Systems (DRS)",
      "Active Underbody Air Dams",
      "Aerodynamic Air-Brake Actuation",
    ],
  },
  {
    id: "cfd_simulation",
    divisionId: "aerodynamics",
    name: "Computational Fluid Dynamics",
    shortName: "CFD Modeling",
    tagline: "Navier-Stokes Solvers, Boundary Layers & Wake Turbulence",
    icon: "Cpu",
    primaryFacility: "aero_center",
    requiredTestingType: "hil_simulation_rig",
    subsections: [
      "2D Potential Flow Simulators",
      "Steady-State RANS Mesh Solvers",
      "Large Eddy Simulations (LES)",
      "Real-Time Thermal CFD Modeling",
    ],
  },
  {
    id: "wind_tunnel_tech",
    divisionId: "aerodynamics",
    name: "Wind Tunnel Technology",
    shortName: "Wind Tunnel",
    tagline: "Rolling Roads, Boundary Layer Suction & Scale Models",
    icon: "RotateCw",
    primaryFacility: "aero_center",
    requiredTestingType: "wind_tunnel",
    subsections: [
      "Static Floor Scale Tunnels",
      "Full-Scale Rolling Road Tunnels",
      "Multi-Component Balance Scales",
      "Laser Particle Image Velocimetry (PIV)",
    ],
  },
  {
    id: "thermal_aerodynamics",
    divisionId: "aerodynamics",
    name: "Thermal Aerodynamics & Ducting",
    shortName: "Thermal Aero",
    tagline: "Radiator Inlets, Brake Ducts & Engine Bay Heat Extraction",
    icon: "Flame",
    primaryFacility: "aero_center",
    requiredTestingType: "wind_tunnel",
    subsections: [
      "Front Bumper Cooling Inlets",
      "Wheel Tub High-Pressure Venting",
      "Hood Heat Extractors",
      "Brake Cooling Scoop Optimization",
    ],
  },

  // ─────────────────────────────────────────────────────────────
  // 5. SAFETY (8 branches)
  // ─────────────────────────────────────────────────────────────
  {
    id: "passive_safety",
    divisionId: "safety",
    name: "Passive Structural Safety",
    shortName: "Passive Safety",
    tagline: "Rigid Survival Cells, Intrusion Barriers & Side Beams",
    icon: "Shield",
    primaryFacility: "safety_center",
    requiredTestingType: "crash_barrier",
    subsections: [
      "Reinforced Passenger Cabins",
      "Side Door Intrusion Beams",
      "Roll-Over Roof Reinforcement",
      "B-Pillar Ultra-High-Strength Steel",
    ],
  },
  {
    id: "crash_structures",
    divisionId: "safety",
    name: "Crash Energy Absorption",
    shortName: "Crumple Zones",
    tagline: "Progressive Folding Rails, Honeycomb Crash Boxes & NCAP",
    icon: "ShieldAlert",
    primaryFacility: "safety_center",
    requiredTestingType: "crash_barrier",
    subsections: [
      "Progressive Crumple Zones",
      "Tapered Hexagonal Crash Cans",
      "Engine Drop Subframe Mounts",
      "Pedestrian Impact Soft Cowls",
    ],
  },
  {
    id: "restraint_systems",
    divisionId: "safety",
    name: "Occupant Restraint Systems",
    shortName: "Restraints",
    tagline: "3-Point Belts, Pyrotechnic Pretensioners & Load Limiters",
    icon: "Lock",
    primaryFacility: "safety_center",
    requiredTestingType: "crash_barrier",
    subsections: [
      "Lap Belts to 3-Point Inertia",
      "Pyrotechnic Belt Pretensioners",
      "Torsion Bar Belt Load Limiters",
      "Inflatable In-Belt Airbags",
    ],
  },
  {
    id: "airbags_pyrotechnics",
    divisionId: "safety",
    name: "Airbag Systems & Deployment",
    shortName: "Airbags",
    tagline: "Dual-Stage Steering, Passenger, Curtain & Knee Airbags",
    icon: "LifeBuoy",
    primaryFacility: "safety_center",
    requiredTestingType: "crash_barrier",
    subsections: [
      "Single-Stage Driver Airbags",
      "Dual-Threshold Front Airbags",
      "Side Torso & Pelvis Bags",
      "Full-Length Side Curtain Canopies",
      "Front-Center Far-Side Airbags",
    ],
  },
  {
    id: "active_safety",
    divisionId: "safety",
    name: "Active Safety & Collision Avoidance",
    shortName: "Active Safety",
    tagline: "Anti-Lock Braking, Brake Assist & Evasive Steering",
    icon: "ShieldCheck",
    primaryFacility: "safety_center",
    requiredTestingType: "test_track",
    subsections: [
      "Electronic ABS Braking",
      "Hydraulic Emergency Brake Assist",
      "Pre-Collision System (PCS)",
      "Autonomous Emergency Steering",
    ],
  },
  {
    id: "adas_systems",
    divisionId: "safety",
    name: "Driver Assistance Systems (ADAS)",
    shortName: "ADAS",
    tagline: "Blind Spot Radar, Lane Keep Assist & Adaptive Cruise",
    icon: "Radio",
    primaryFacility: "safety_center",
    requiredTestingType: "test_track",
    subsections: [
      "Ultrasonic Parking Sensors",
      "Blind-Spot Monitoring (BSM)",
      "Lane Departure Warning (LDW)",
      "Full-Speed Range Adaptive Cruise",
      "Lane Centering Assist (LKA)",
    ],
  },
  {
    id: "driver_monitoring",
    divisionId: "safety",
    name: "Driver State & Monitoring",
    shortName: "Driver Monitor",
    tagline: "Infrared Eye Tracking, Drowsiness Detection & Hands-On",
    icon: "Eye",
    primaryFacility: "electronics_lab",
    requiredTestingType: "hil_simulation_rig",
    subsections: [
      "Steering Micro-Correction Heuristics",
      "Infrared Pupil Gaze Cameras",
      "Capacitive Steering Wheel Grips",
      "Driver Incapacitation Pull-Over Mode",
    ],
  },
  {
    id: "autonomous_safety",
    divisionId: "safety",
    name: "Autonomous Safety & Fail-Safe",
    shortName: "Autonomous Safety",
    tagline: "Dual-Channel Computing, Redundant Braking & Safe Stops",
    icon: "CheckCircle",
    primaryFacility: "safety_center",
    requiredTestingType: "hil_simulation_rig",
    subsections: [
      "Dual-Redundant Brake Actuators",
      "Lock-Step ECU Voting Architecture",
      "Isolated Battery Emergency Reserves",
      "Safe-Stop Minimal Risk Maneuvers",
    ],
  },

  // ─────────────────────────────────────────────────────────────
  // 6. ELECTRONICS & SOFTWARE (9 branches)
  // ─────────────────────────────────────────────────────────────
  {
    id: "electrical_architecture",
    divisionId: "electronics_software",
    name: "Electrical Architecture",
    shortName: "Electrical Loom",
    tagline: "12V/48V Harnesses, Smart Power Boxes & High-Current Distribution",
    icon: "Zap",
    primaryFacility: "electronics_lab",
    requiredTestingType: "hil_simulation_rig",
    subsections: [
      "Point-to-Point Copper Wiring",
      "Zonal Power Distribution Modules",
      "Dual-Voltage 12V/48V Architectures",
      "Solid-State Smart Fusing",
    ],
  },
  {
    id: "sensor_technology",
    divisionId: "electronics_software",
    name: "Automotive Sensor Technology",
    shortName: "Sensors",
    tagline: "Hall Effect, 6-Axis IMUs, Wheel Speed & Pressure Transducers",
    icon: "Activity",
    primaryFacility: "electronics_lab",
    requiredTestingType: "hil_simulation_rig",
    subsections: [
      "Analog Temperature & Pressure",
      "Optical Crank & Cam Sensors",
      "Solid-State 6-Axis IMU Gyroscopes",
      "Digital High-Precision Wheel Speed",
    ],
  },
  {
    id: "ecu_hardware",
    divisionId: "electronics_software",
    name: "ECU Hardware & Processors",
    shortName: "ECU Hardware",
    tagline: "8-Bit to 64-Bit Automotive Microcontrollers & Multi-Core SOCs",
    icon: "Cpu",
    primaryFacility: "electronics_lab",
    requiredTestingType: "hil_simulation_rig",
    subsections: [
      "Discrete Analog Ignition Modules",
      "16-Bit Automotive Microcontrollers",
      "32-Bit Multi-Core Lockstep ECUs",
      "Centralized Domain Compute Platforms",
    ],
  },
  {
    id: "vehicle_networks",
    divisionId: "electronics_software",
    name: "Vehicle Networks & Buses",
    shortName: "Vehicle Bus",
    tagline: "CAN Bus, LIN, FlexRay, Automotive Ethernet & Gateways",
    icon: "Share2",
    primaryFacility: "electronics_lab",
    requiredTestingType: "hil_simulation_rig",
    subsections: [
      "High-Speed CAN 2.0B Bus",
      "LIN Local Interconnect Networks",
      "FlexRay Deterministic Buses",
      "Gigabit Automotive Ethernet (BroadR-Reach)",
    ],
  },
  {
    id: "embedded_software",
    divisionId: "electronics_software",
    name: "Embedded Vehicle Software",
    shortName: "Embedded Soft",
    tagline: "AUTOSAR Architecture, Real-Time OS & Firmware Over-the-Air",
    icon: "Code",
    primaryFacility: "ai_software_lab",
    requiredTestingType: "hil_simulation_rig",
    subsections: [
      "Bare-Metal Assembly Algorithms",
      "Real-Time OS (RTOS) Scheduling",
      "Classic AUTOSAR Modular Stacks",
      "Encrypted Over-The-Air (OTA) Updates",
    ],
  },
  {
    id: "infotainment_systems",
    divisionId: "electronics_software",
    name: "Cockpit Infotainment",
    shortName: "Infotainment",
    tagline: "Analogue Radios, Optical Navigation & Curved Touchscreens",
    icon: "Monitor",
    primaryFacility: "electronics_lab",
    requiredTestingType: "none",
    subsections: [
      "AM/FM Cassette & CD Tuners",
      "In-Dash GPS CD/DVD Navigation",
      "Capacitive Touchscreen Interfaces",
      "Curved OLED Seamless Digital Clusters",
    ],
  },
  {
    id: "telematics_connectivity",
    divisionId: "electronics_software",
    name: "Telematics & Connected Car",
    shortName: "Connectivity",
    tagline: "Cellular 4G/5G, Remote Mobile Telematics & V2X",
    icon: "Wifi",
    primaryFacility: "electronics_lab",
    requiredTestingType: "hil_simulation_rig",
    subsections: [
      "Automated Crash Notification (eCall)",
      "4G LTE Smartphone App Pairing",
      "5G Ultra-Low Latency Cloud Linking",
      "Vehicle-to-Everything (V2X) Communications",
    ],
  },
  {
    id: "ai_intelligent_systems",
    divisionId: "electronics_software",
    name: "AI & Neural Processing",
    shortName: "AI Systems",
    tagline: "Machine Vision Transformers, Deep Learning & Predictive Control",
    icon: "Sparkles",
    primaryFacility: "ai_software_lab",
    requiredTestingType: "hil_simulation_rig",
    subsections: [
      "Heuristic Rule Engines",
      "Convolutional Neural Vision Models",
      "Transformer End-to-End Driving Models",
      "Onboard 500 TOPS Neural Accelerators",
    ],
  },
  {
    id: "autonomous_driving",
    divisionId: "electronics_software",
    name: "Autonomous Driving Systems",
    shortName: "Self-Driving",
    tagline: "Level 2+ Hands-Free, Level 3 Highway & Level 4 Urban Chauffeurs",
    icon: "Navigation",
    primaryFacility: "ai_software_lab",
    requiredTestingType: "test_track",
    subsections: [
      "Level 2 Hands-On Highway Piloting",
      "Level 2+ Hands-Free Driver Assist",
      "Level 3 Conditional Traffic Jam Chauffeur",
      "Level 4 Geofenced Robotaxi Autonomous",
    ],
  },

  // ─────────────────────────────────────────────────────────────
  // 7. ELECTRIFICATION (8 branches)
  // ─────────────────────────────────────────────────────────────
  {
    id: "battery_chemistry",
    divisionId: "electrification",
    name: "Battery Chemistry & Cell Design",
    shortName: "Battery Cells",
    tagline: "Lead-Acid, NiMH, NMC 811, LFP & All-Solid-State Chemistries",
    icon: "Battery",
    primaryFacility: "battery_lab",
    requiredTestingType: "climate_chamber",
    subsections: [
      "Lead-Acid Starter Chemistry",
      "Nickel-Metal Hydride (NiMH)",
      "Lithium Nickel Manganese Cobalt (NMC)",
      "Lithium Iron Phosphate (LFP) Pouch",
      "Solid-State Ceramic Electrolytes",
    ],
  },
  {
    id: "battery_packs",
    divisionId: "electrification",
    name: "Battery Pack Engineering",
    shortName: "Battery Packs",
    tagline: "Cell-to-Pack, Structural Monocoque Batteries & Cooling Plates",
    icon: "Box",
    primaryFacility: "battery_lab",
    requiredTestingType: "climate_chamber",
    subsections: [
      "Modular Brick Aluminum Enclosures",
      "Serpentine Liquid Cooling Cold Plates",
      "Cell-to-Pack (CTP) Integrated Trays",
      "Cell-to-Chassis (CTC) Structural Tubs",
    ],
  },
  {
    id: "electric_motors",
    divisionId: "electrification",
    name: "Electric Traction Motors",
    shortName: "E-Motors",
    tagline: "AC Induction, Permanent Magnet Synchronous & Axial-Flux Rotors",
    icon: "RotateCcw",
    primaryFacility: "battery_lab",
    requiredTestingType: "dyno_cell",
    subsections: [
      "Brushed DC Traction Motors",
      "Permanent Magnet Synchronous (PMSM)",
      "Copper-Rotor Induction Motors",
      "High-Torque Dual-Rotor Axial Flux",
    ],
  },
  {
    id: "inverter_technology",
    divisionId: "electrification",
    name: "Inverter Technology",
    shortName: "Inverters",
    tagline: "IGBT Switches, Silicon Carbide (SiC) & High-Frequency PWM",
    icon: "Cpu",
    primaryFacility: "battery_lab",
    requiredTestingType: "dyno_cell",
    subsections: [
      "Silicon IGBT Power Modules",
      "Direct Liquid-Cooled Power Blocks",
      "Silicon Carbide (SiC) MOSFET Inverters",
      "GaN Ultra-High Frequency Converters",
    ],
  },
  {
    id: "power_electronics",
    divisionId: "electrification",
    name: "Power Electronics Systems",
    shortName: "Power Electr",
    tagline: "DC-DC Step-Down, Bi-Directional Inverters & Power Distribution",
    icon: "Shuffle",
    primaryFacility: "battery_lab",
    requiredTestingType: "hil_simulation_rig",
    subsections: [
      "High-Voltage to 12V DC-DC Buck Converters",
      "Bi-Directional Vehicle-to-Load (V2L)",
      "Integrated Onboard Chargers (OBC)",
      "Combined Power Electronics Units",
    ],
  },
  {
    id: "charging_systems",
    divisionId: "electrification",
    name: "Charging Systems & High-Speed Ports",
    shortName: "Charging",
    tagline: "AC Level 2, DC Fast Charging, 350kW High-Speed & Megawatt Plugs",
    icon: "BatteryCharging",
    primaryFacility: "battery_lab",
    requiredTestingType: "climate_chamber",
    subsections: [
      "AC 3.3kW Single-Phase Port",
      "AC 11kW/22kW Three-Phase Ports",
      "DC Fast Charging 150kW (CCS/NACS)",
      "Ultra-Fast 350kW+ 800V Architecture",
    ],
  },
  {
    id: "regenerative_systems",
    divisionId: "electrification",
    name: "Regenerative Braking Systems",
    shortName: "Regen Systems",
    tagline: "Kinetic Energy Harvesters, Blended Deceleration & One-Pedal",
    icon: "RotateCw",
    primaryFacility: "battery_lab",
    requiredTestingType: "test_track",
    subsections: [
      "Coasting Drag Regen",
      "Blended Friction-Regen Calibration",
      "High-Decel One-Pedal Drive Tuning",
      "Multi-Axle Torque-Vectoring Regen",
    ],
  },
  {
    id: "high_voltage_architecture",
    divisionId: "electrification",
    name: "High-Voltage Architecture",
    shortName: "HV 800V+",
    tagline: "400V vs 800V Topologies, Pyrofuses & High-Current Busbars",
    icon: "AlertTriangle",
    primaryFacility: "battery_lab",
    requiredTestingType: "hil_simulation_rig",
    subsections: [
      "Early 200V-300V Hybrid Buses",
      "Industry Standard 400V Pack Topologies",
      "Advanced 800V High-Efficiency Systems",
      "Pyrotechnic High-Voltage Isolation Fuses",
    ],
  },

  // ─────────────────────────────────────────────────────────────
  // 8. MANUFACTURING (10 branches)
  // ─────────────────────────────────────────────────────────────
  {
    id: "casting_manufacturing",
    divisionId: "manufacturing",
    name: "Metal Casting Technology",
    shortName: "Casting",
    tagline: "Sand Casting, High-Pressure Die Casting & Giga-Castings",
    icon: "Box",
    primaryFacility: "manufacturing_center",
    requiredTestingType: "dyno_cell",
    subsections: [
      "Sand Cast Iron Engine Blocks",
      "Permanent Mold Aluminium Pouring",
      "High-Pressure Die Casting (HPDC)",
      "9,000-Tonne Mega/Giga-Casting Press Cells",
    ],
  },
  {
    id: "forging_manufacturing",
    divisionId: "manufacturing",
    name: "Precision Forging Technology",
    shortName: "Forging",
    tagline: "Drop Forging, Closed-Die Presses & Grain-Flow Engineering",
    icon: "Wrench",
    primaryFacility: "manufacturing_center",
    requiredTestingType: "dyno_cell",
    subsections: [
      "Open-Die Hammer Forging",
      "Closed-Die Steel Crankshaft Forging",
      "Cold-Forged Titanium Connecting Rods",
      "Monoblock Wheel Drop Forging",
    ],
  },
  {
    id: "machining_cnc",
    divisionId: "manufacturing",
    name: "CNC Machining & Precision Tooling",
    shortName: "Machining",
    tagline: "Multi-Axis CNC Mills, Micro-Finishing & Cylinder Honing",
    icon: "Tool",
    primaryFacility: "manufacturing_center",
    requiredTestingType: "dyno_cell",
    subsections: [
      "Manual Lathes & Milling Jigs",
      "3-Axis CNC Machining Centers",
      "5-Axis High-Speed Billet Mills",
      "Plateau Honing & Diamond Boring",
    ],
  },
  {
    id: "stamping_presses",
    divisionId: "manufacturing",
    name: "Sheet Metal Stamping",
    shortName: "Stamping",
    tagline: "Transfer Press Lines, Deep-Drawing & Hydroforming",
    icon: "Maximize",
    primaryFacility: "manufacturing_center",
    requiredTestingType: "shaker_rig",
    subsections: [
      "Mechanical Stamping Lines",
      "Multi-Station Transfer Presses",
      "Hot-Stamping Boron Steel Dies",
      "Tubular Frame Hydroforming",
    ],
  },
  {
    id: "welding_joining",
    divisionId: "manufacturing",
    name: "Welding & Fastening Technology",
    shortName: "Welding",
    tagline: "Robotic Resistance Spot Welding, Laser Braze & Structural Adhesives",
    icon: "Sparkles",
    primaryFacility: "manufacturing_center",
    requiredTestingType: "shaker_rig",
    subsections: [
      "Manual Resistance Spot Welding",
      "Multi-Arm Robotic Spot Cells",
      "Continuous Laser Seam Brazing",
      "Structural Polyurethane Adhesive Bonding",
    ],
  },
  {
    id: "composite_manufacturing",
    divisionId: "manufacturing",
    name: "Composite & Carbon Manufacturing",
    shortName: "Composites",
    tagline: "Hand Layup, Autoclaves, Resin Transfer Molding (RTM) & Forged Carbon",
    icon: "Layers",
    primaryFacility: "manufacturing_center",
    requiredTestingType: "dyno_cell",
    subsections: [
      "Wet Hand-Layup Fiberglass",
      "Prepreg Autoclave 7-Bar Curing",
      "High-Pressure Resin Transfer Molding (HP-RTM)",
      "Forged Carbon Fiber Compression Molding",
    ],
  },
  {
    id: "robotics_automation",
    divisionId: "manufacturing",
    name: "Robotic Assembly Systems",
    shortName: "Robotics",
    tagline: "6-Axis Articulated Robots, Collaborative Cobots & Paint Cells",
    icon: "Cpu",
    primaryFacility: "manufacturing_center",
    requiredTestingType: "hil_simulation_rig",
    subsections: [
      "Hydraulic Unimate Arms",
      "6-Axis Electric Servo Robots",
      "High-Speed Electrostatic Paint Bells",
      "Collaborative Assembly Cobots",
    ],
  },
  {
    id: "automation_systems",
    divisionId: "manufacturing",
    name: "Automated Material Handling & AGVs",
    shortName: "Automation",
    tagline: "Autonomous Mobile Robots, Overhead Conveyors & Smart Jigs",
    icon: "Shuffle",
    primaryFacility: "manufacturing_center",
    requiredTestingType: "hil_simulation_rig",
    subsections: [
      "Chain Overhead Monorail Conveyors",
      "Magnetic Strip Guided Carts (AGVs)",
      "Autonomous LiDAR AMR Pallet Shuttles",
      "Automated High-Bay Storage Racks",
    ],
  },
  {
    id: "quality_control",
    divisionId: "manufacturing",
    name: "Metrology & Quality Assurance",
    shortName: "Quality Control",
    tagline: "Coordinate Measuring Machines (CMM), Laser Scanners & Defect AI",
    icon: "CheckSquare",
    primaryFacility: "manufacturing_center",
    requiredTestingType: "hil_simulation_rig",
    subsections: [
      "Manual Go/No-Go Gauge Pins",
      "3D Bridge Coordinate Measuring Machines",
      "Blue-Light Optical Surface Scanners",
      "In-Line Machine Vision Defect AI",
    ],
  },
  {
    id: "factory_systems",
    divisionId: "manufacturing",
    name: "Factory Operating Systems",
    shortName: "Factory Systems",
    tagline: "Just-in-Time (JIT), Kaizen, Digital Twins & Paperless MES",
    icon: "Server",
    primaryFacility: "manufacturing_center",
    requiredTestingType: "none",
    subsections: [
      "Kanban Card Assembly Tracking",
      "Manufacturing Execution Systems (MES)",
      "Full Factory Digital Twin Simulation",
      "Zero-Downtime Predictive Maintenance",
    ],
  },

  // ─────────────────────────────────────────────────────────────
  // 9. INDUSTRIAL / CORPORATE ENGINEERING (8 branches)
  // ─────────────────────────────────────────────────────────────
  {
    id: "production_engineering",
    divisionId: "industrial_supply",
    name: "Production Engineering & Ergonomics",
    shortName: "Production Eng",
    tagline: "Takt Time, Line Balancing, Assembly Jigs & Worker Posture",
    icon: "Sliders",
    primaryFacility: "manufacturing_center",
    requiredTestingType: "none",
    subsections: [
      "Line Bottleneck & Takt Time Analysis",
      "Rotational Chassis Assembly Cradles",
      "Exoskeleton Ergonomic Worker Support",
      "Mixed-Model Flexible Assembly Lines",
    ],
  },
  {
    id: "supply_chain_engineering",
    divisionId: "industrial_supply",
    name: "Supply Chain Engineering",
    shortName: "Supply Chain",
    tagline: "Tier-1 Integration, Inventory Buffers & Risk Hedging",
    icon: "Share2",
    primaryFacility: "corporate_hq",
    requiredTestingType: "none",
    subsections: [
      "Multi-Source Component Contracts",
      "Buffer Stock Optimization Models",
      "Real-Time Supply Chain Visibility",
      "Automated Supplier Quality Auditing",
    ],
  },
  {
    id: "supplier_technology",
    divisionId: "industrial_supply",
    name: "Supplier Technology Co-Development",
    shortName: "Supplier Tech",
    tagline: "Joint R&D, Shared Tooling & Supplier Quality Certification",
    icon: "Users",
    primaryFacility: "corporate_hq",
    requiredTestingType: "none",
    subsections: [
      "Standard Purchasing Catalogs",
      "Tier-1 Co-Design CAD Integrations",
      "Consigned Production Tooling Dies",
      "Strategic Equity Engineering Partnerships",
    ],
  },
  {
    id: "logistics_freight",
    divisionId: "industrial_supply",
    name: "Logistics & Fleet Transport",
    shortName: "Fleet Logistics",
    tagline: "Specialized Car Carriers, Cross-Docking & Route Tuning",
    icon: "Truck",
    primaryFacility: "logistics_hub",
    requiredTestingType: "none",
    subsections: [
      "Multi-Deck Car Hauler Fleets",
      "Cross-Docking Sorting Terminals",
      "GPS Dynamic Route Optimization",
      "Electric Heavy-Duty Distribution Trucks",
    ],
  },
  {
    id: "rail_freight_systems",
    divisionId: "industrial_supply",
    name: "Rail Freight & Intermodal Hubs",
    shortName: "Rail Freight",
    tagline: "Enclosed Auto-Racks, Direct Rail Spurs & Intermodal Yards",
    icon: "Anchor",
    primaryFacility: "logistics_hub",
    requiredTestingType: "none",
    subsections: [
      "Dedicated Plant Rail Spurs",
      "Bi-Level & Tri-Level Auto-Rack Railcars",
      "Intermodal Container Logistics",
      "High-Capacity Transcontinental Rail Links",
    ],
  },
  {
    id: "warehousing_distribution",
    divisionId: "industrial_supply",
    name: "Warehousing & Distribution Hubs",
    shortName: "Warehousing",
    tagline: "Automated Storage, Parts Fulfillment & Global Spare Hubs",
    icon: "Grid",
    primaryFacility: "logistics_hub",
    requiredTestingType: "none",
    subsections: [
      "Regional Distribution Centers",
      "Automated Storage & Retrieval (ASRS)",
      "Same-Day Dealership Parts Fulfillment",
      "Global Spares Lifecycle Depots",
    ],
  },
  {
    id: "modular_platforms",
    divisionId: "industrial_supply",
    name: "Modular Vehicle Platforms",
    shortName: "Modular Base",
    tagline: "Shared Hardpoints, Scalable Wheelbases & Cross-Model Tooling",
    icon: "Grid",
    primaryFacility: "manufacturing_center",
    requiredTestingType: "shaker_rig",
    subsections: [
      "Single-Model Dedicated Floor Pans",
      "Scalable Front Axle-to-Dash Hardpoints",
      "Modular Transverse/Longitudinal Matrices",
      "Universal Skateboard EV Platforms",
    ],
  },
  {
    id: "manufacturing_standardization",
    divisionId: "industrial_supply",
    name: "Manufacturing Standardization",
    shortName: "Standardization",
    tagline: "Global Tolerances, Common Fasteners & Universal Dies",
    icon: "CheckCircle",
    primaryFacility: "manufacturing_center",
    requiredTestingType: "none",
    subsections: [
      "Unified Fastener & Bolt Catalogues",
      "Interchangeable Die Mounting Blocks",
      "Global Tooling Precision Tolerances",
      "Universal Clamp & Jig Fixtures",
    ],
  },

  // ─────────────────────────────────────────────────────────────
  // 10. MOTORSPORT (11 branches)
  // ─────────────────────────────────────────────────────────────
  {
    id: "race_engines",
    divisionId: "motorsport",
    name: "Motorsport Powertrain & Engines",
    shortName: "Race Engines",
    tagline: "Pneumatic Valves, Billet Blocks, Extreme RPMs & MGU-H",
    icon: "Zap",
    primaryFacility: "aero_center",
    requiredTestingType: "dyno_cell",
    subsections: [
      "Blueprinted Balance Racing Blocks",
      "Pneumatic Return Valve Springs (19,000 RPM)",
      "Twin-Turbo V6 Formula 1 Hybrids",
      "Extreme-Boost Le Mans Endurance Units",
    ],
  },
  {
    id: "race_transmission",
    divisionId: "motorsport",
    name: "Motorsport Transmissions",
    shortName: "Race Gearbox",
    tagline: "Straight-Cut Dog Rings, Seamless Shift & Carbon Cases",
    icon: "Sliders",
    primaryFacility: "aero_center",
    requiredTestingType: "dyno_cell",
    subsections: [
      "Straight-Cut H-Pattern Dogboxes",
      "Sequential Ratchet Gearboxes",
      "Seamless-Shift Dual-Barrel Transmissions",
      "Structural Carbon-Fiber Gearbox Casings",
    ],
  },
  {
    id: "race_chassis",
    divisionId: "motorsport",
    name: "Race Chassis & Monocoques",
    shortName: "Race Chassis",
    tagline: "FIA Carbon Safety Cells, Titanium Halos & Torsional Monocoques",
    icon: "Shield",
    primaryFacility: "aero_center",
    requiredTestingType: "shaker_rig",
    subsections: [
      "Tubular FIA Spaceframes & Roll Cages",
      "Autoclaved Carbon-Fiber Survival Cells",
      "Grade 5 Titanium Halo Cockpit Protectors",
      "Ultra-Stiff LMH Carbon Honeycomb Tubs",
    ],
  },
  {
    id: "race_suspension",
    divisionId: "motorsport",
    name: "Competition Suspension Systems",
    shortName: "Race Susp",
    tagline: "Torsion Bars, Inboard Heave Springs & Third Dampers",
    icon: "Activity",
    primaryFacility: "aero_center",
    requiredTestingType: "shaker_rig",
    subsections: [
      "Corner Weight Scale Setup",
      "Inboard Pushrod Bellcranks",
      "Independent Heave Springs (3rd Damper)",
      "Interconnected FRIC Hydraulic Suspension",
    ],
  },
  {
    id: "race_brakes",
    divisionId: "motorsport",
    name: "Motorsport Braking Systems",
    shortName: "Race Brakes",
    tagline: "Carbon-Carbon Rotors, Water-Cooled Calipers & Bias Shifters",
    icon: "CircleDot",
    primaryFacility: "aero_center",
    requiredTestingType: "dyno_cell",
    subsections: [
      "Grooved High-Temp Cast Steel Discs",
      "Formula 1 Carbon-Carbon Discs & Pads",
      "Driver Cockpit Brake Bias Balance Bars",
      "Electro-Hydraulic Rear Brake-by-Wire",
    ],
  },
  {
    id: "race_tyres",
    divisionId: "motorsport",
    name: "Racing Tyres & Compound Engineering",
    shortName: "Race Tyres",
    tagline: "Soft/Medium/Hard Slicks, Intermediate Grooves & Thermal Curing",
    icon: "Disc",
    primaryFacility: "aero_center",
    requiredTestingType: "test_track",
    subsections: [
      "Hand-Cut Rain Tyres",
      "Multi-Compound Radial Slicks",
      "Tire Warmers & Blanket Thermal Cycling",
      "Real-Time Tread Surface Pyrometry",
    ],
  },
  {
    id: "race_aero",
    divisionId: "motorsport",
    name: "Grand Prix Aerodynamics",
    shortName: "Grand Prix Aero",
    tagline: "Downforce-to-Drag Windows, Beam Wings & Diffuser Sealing",
    icon: "Wind",
    primaryFacility: "aero_center",
    requiredTestingType: "wind_tunnel",
    subsections: [
      "Front Wing Outwash Endplates",
      "Floor Edge Vortex Sealing Skirts",
      "Active Rear DRS Deflection Wings",
      "Full Le Mans Low-Drag Aero Packages",
    ],
  },
  {
    id: "telemetry_acquisition",
    divisionId: "motorsport",
    name: "Race Telemetry & Data Logging",
    shortName: "Race Data",
    tagline: "Strain Gauges, Laser Ride Height & 500-Channel Radio Bursts",
    icon: "Radio",
    primaryFacility: "aero_center",
    requiredTestingType: "test_track",
    subsections: [
      "Analog Strip-Chart Onboard Recorders",
      "Digital CAN 100-Channel Loggers",
      "Real-Time Pit-to-Car Radio Telemetry",
      "Tire Grip Real-Time Friction Estimators",
    ],
  },
  {
    id: "endurance_technology",
    divisionId: "motorsport",
    name: "Endurance Racing Engineering",
    shortName: "Endurance Tech",
    tagline: "24-Hour Reliability, Quick-Release Components & Oil Top-Off",
    icon: "Clock",
    primaryFacility: "aero_center",
    requiredTestingType: "test_track",
    subsections: [
      "Dry-Break Quick-Disconnect Fluid Couplings",
      "Quick-Change Brake Caliper Assemblies",
      "Long-Life Ceramic Engine Bearings",
      "Driver Change Ergonomic Cockpit Inserts",
    ],
  },
  {
    id: "pit_equipment",
    divisionId: "motorsport",
    name: "Pit Lane & Servicing Equipment",
    shortName: "Pit Equipment",
    tagline: "Pneumatic Air Jacks, High-Flow Fuel Rigs & 2-Second Wheel Guns",
    icon: "Tool",
    primaryFacility: "aero_center",
    requiredTestingType: "none",
    subsections: [
      "Manual Wheel Nut Breaker Bars",
      "High-Torque Pneumatic Wheel Guns",
      "Onboard Pneumatic Chassis Air Jacks",
      "Pressurized Dry-Break Fueling Rigs",
    ],
  },
  {
    id: "driver_systems",
    divisionId: "motorsport",
    name: "Driver Cockpit Systems",
    shortName: "Driver Systems",
    tagline: "Carbon Molded Seats, Helmet Fluid Drinks & HANS Restraints",
    icon: "User",
    primaryFacility: "aero_center",
    requiredTestingType: "crash_barrier",
    subsections: [
      "Form-Fitting Bead Foam Seat Inserts",
      "HANS Head & Neck Restraint Anchors",
      "Cockpit Drinking Fluid Pumps",
      "Multi-Function OLED Steering Wheels",
    ],
  },

  // ─────────────────────────────────────────────────────────────
  // 11. RELIABILITY & SERVICE (6 branches)
  // ─────────────────────────────────────────────────────────────
  {
    id: "durability_engineering",
    divisionId: "reliability_service",
    name: "Durability & Accelerated Life Testing",
    shortName: "Durability",
    tagline: "1,000,000-km Road Simulators, Thermal Shock & Salt Spray",
    icon: "Shield",
    primaryFacility: "testing_center",
    requiredTestingType: "shaker_rig",
    subsections: [
      "Rough-Road Pave Shaker Testing",
      "Thermal Cycle Shock Chambers (-40°C to +90°C)",
      "Cyclic Component Fatigue Benches",
      "High-Mileage Durability Fleet Testing",
    ],
  },
  {
    id: "corrosion_resistance",
    divisionId: "reliability_service",
    name: "Corrosion & Rust Protection",
    shortName: "Anti-Rust",
    tagline: "Zinc Galvanizing, E-Coat Primers & Cavity Wax Injection",
    icon: "ShieldAlert",
    primaryFacility: "materials_lab",
    requiredTestingType: "climate_chamber",
    subsections: [
      "Petroleum Underbody Undercoating",
      "Electro-Deposition (E-Coat) Dip Tanks",
      "Hot-Dip Double-Sided Galvanized Steel",
      "Inner-Sill Penetrating Cavity Waxes",
    ],
  },
  {
    id: "maintenance_engineering",
    divisionId: "reliability_service",
    name: "Maintenance Interval Engineering",
    shortName: "Maintenance",
    tagline: "Extended Oil Life, Platinum Plugs & Sealed Fluids",
    icon: "Tool",
    primaryFacility: "testing_center",
    requiredTestingType: "dyno_cell",
    subsections: [
      "5,000-km Conventional Oil Intervals",
      "Long-Life Synthetic Lubricants",
      "160,000-km Platinum/Iridium Spark Plugs",
      "Sealed-for-Life Transmissions & Coolants",
    ],
  },
  {
    id: "serviceability_design",
    divisionId: "reliability_service",
    name: "Serviceability & Repair Design",
    shortName: "Serviceability",
    tagline: "Modular Subassemblies, Quick-Release Clips & Labor Hour Trimming",
    icon: "Wrench",
    primaryFacility: "testing_center",
    requiredTestingType: "none",
    subsections: [
      "Accessible Oil Filter & Dipstick Layouts",
      "Quick-Release Headlight Housing Clips",
      "Modular Drop-Down Powertrain Cradles",
      "Repair Labor Time Optimization (Flat-Rate)",
    ],
  },
  {
    id: "diagnostic_systems",
    divisionId: "reliability_service",
    name: "Onboard Diagnostics (OBD)",
    shortName: "Diagnostics",
    tagline: "Blink Codes, OBD-I, OBD-II Ports & Live Freeze Frames",
    icon: "Activity",
    primaryFacility: "electronics_lab",
    requiredTestingType: "hil_simulation_rig",
    subsections: [
      "Check-Engine Flashing Blink Codes",
      "Proprietary Dealership Scan Tool Links",
      "Standardized 16-Pin OBD-II Ports (J1962)",
      "Live Diagnostic Trouble Code Freeze Frames",
    ],
  },
  {
    id: "predictive_maintenance",
    divisionId: "reliability_service",
    name: "Predictive Maintenance & Telematics",
    shortName: "Predictive Maint",
    tagline: "Oil Shearing Estimators, Cloud Diagnostics & Fleet Alerts",
    icon: "Clock",
    primaryFacility: "ai_software_lab",
    requiredTestingType: "hil_simulation_rig",
    subsections: [
      "Engine Revolution & Cold-Start Counters",
      "Calculated Oil Degradation Algorithms",
      "Direct Capacitive Oil Quality Sensors",
      "Cloud-Linked Fleet Health Alerts",
    ],
  },

  // ─────────────────────────────────────────────────────────────
  // 12. ENVIRONMENT / EFFICIENCY (6 branches)
  // ─────────────────────────────────────────────────────────────
  {
    id: "fuel_efficiency",
    divisionId: "environment_efficiency",
    name: "Fuel Economy Optimization",
    shortName: "Fuel Economy",
    tagline: "Low-Friction Bearings, Low-Viscosity Oils & Cylinder Deactivation",
    icon: "Droplet",
    primaryFacility: "engine_lab",
    requiredTestingType: "dyno_cell",
    subsections: [
      "Diamond-Like Carbon (DLC) Tappet Coatings",
      "Variable Displacement Cylinder Deactivation",
      "Ultra-Low Viscosity 0W-16 Lubricants",
      "Atkinson & Miller Thermodynamic Cycles",
    ],
  },
  {
    id: "emissions_reduction",
    divisionId: "environment_efficiency",
    name: "Exhaust Emissions Aftertreatment",
    shortName: "Emissions",
    tagline: "3-Way Catalytic Converters, DPF Filters, SCR Urea & Euro/EPA",
    icon: "CloudRain",
    primaryFacility: "engine_lab",
    requiredTestingType: "dyno_cell",
    subsections: [
      "Exhaust Air Injection Smog Pumps",
      "Ceramic Substrate 3-Way Catalytic Converters",
      "Diesel Particulate Filters (DPF)",
      "Selective Catalytic Reduction (SCR AdBlue)",
      "Close-Coupled Cold-Start Catalysts",
    ],
  },
  {
    id: "energy_recovery",
    divisionId: "environment_efficiency",
    name: "Waste Energy Recovery Systems",
    shortName: "Energy Recovery",
    tagline: "Exhaust Thermoelectrics, Solar Roofs & Heat Exchangers",
    icon: "Sun",
    primaryFacility: "engine_lab",
    requiredTestingType: "dyno_cell",
    subsections: [
      "Exhaust Heat Recirculation for Cabin",
      "Thermoelectric Waste Heat Generators (TEG)",
      "Solar Cell Glass Panoramic Roofs",
      "Suspension Kinetic Energy Recuperation",
    ],
  },
  {
    id: "sustainable_materials",
    divisionId: "environment_efficiency",
    name: "Bio-Based & Sustainable Materials",
    shortName: "Bio Materials",
    tagline: "Recycled PET Fabrics, Flax Bio-Composites & Vegan Leather",
    icon: "Feather",
    primaryFacility: "materials_lab",
    requiredTestingType: "none",
    subsections: [
      "Natural Wood Veneer Inlays",
      "Recycled Ocean Plastic Carpet Yarns",
      "Mushroom Mycelium & Bio-PU Leathers",
      "Flax Fiber Structural Composite Panels",
    ],
  },
  {
    id: "recycling_technology",
    divisionId: "environment_efficiency",
    name: "Closed-Loop Recycling Technology",
    shortName: "Recycling",
    tagline: "Battery Hydrometallurgy, Aluminium Sorting & Circular Design",
    icon: "RotateCw",
    primaryFacility: "manufacturing_center",
    requiredTestingType: "none",
    subsections: [
      "Automobile Shredder Residue Sorting",
      "Closed-Loop Stamping Scrap Remelting",
      "Hydrometallurgical Battery Lithium Stripping",
      "Post-Consumer Bumper Plastic Regrinding",
    ],
  },
  {
    id: "sustainable_manufacturing",
    divisionId: "environment_efficiency",
    name: "Net-Zero Sustainable Manufacturing",
    shortName: "Clean Mfg",
    tagline: "Solar Factory Roofs, Zero-Landfill Stamping & Green Steel",
    icon: "Leaf",
    primaryFacility: "manufacturing_center",
    requiredTestingType: "none",
    subsections: [
      "Factory Heat Waste District Heating",
      "Zero-Landfill Press Stamping Protocol",
      "Hydrogen-Reduced Green Primary Steel",
      "100% Renewable Onsite Factory Microgrids",
    ],
  },
];

// ─────────────────────────────────────────────────────────────
// FAST LOOKUP INDICES & METADATA MAPS
// ─────────────────────────────────────────────────────────────
export const BRANCH_BY_ID: Record<SubsystemBranchId, SubsystemBranchMeta> =
  SUBSYSTEM_BRANCHES.reduce((acc, b) => {
    acc[b.id] = b;
    return acc;
  }, {} as Record<SubsystemBranchId, SubsystemBranchMeta>);

export const BRANCHES_BY_DIVISION: Record<
  MasterDivisionId,
  SubsystemBranchMeta[]
> = SUBSYSTEM_BRANCHES.reduce((acc, b) => {
  if (!acc[b.divisionId]) {
    acc[b.divisionId] = [];
  }
  acc[b.divisionId].push(b);
  return acc;
}, {} as Record<MasterDivisionId, SubsystemBranchMeta[]>);
