// ===================================================================
// AUTOMOTIVE R&D TREE ARCHITECTURE — STATIC DATA & 22 DEPARTMENTS
// ===================================================================
import type {
  MasterDivisionId,
  MasterDivisionMeta,
  RDDepartmentId,
  RDDepartmentMeta,
  RDTechNode,
  SubsystemBranchId,
} from "./rdTreeTypes";

// ===================================================================
// 1. THE 8 MASTER DIVISIONS
// ===================================================================

import {
  SUBSYSTEM_BRANCHES,
  BRANCH_BY_ID,
  BRANCHES_BY_DIVISION,
} from "./rdSubsystemData";

export { SUBSYSTEM_BRANCHES, BRANCH_BY_ID, BRANCHES_BY_DIVISION };

// ===================================================================
// 1. THE 12 MASTER ENGINEERING DIVISIONS
// ===================================================================

export const MASTER_DIVISIONS: MasterDivisionMeta[] = [
  {
    id: "powertrain",
    name: "Powertrain & Propulsion",
    subtitle: "Internal Combustion, Transmissions, Hybrids & Fuel Delivery",
    icon: "Cog",
    description: "Internal combustion engines, gearboxes, differentials, hybrid systems, and high-pressure fuel delivery.",
    departments: ["engine", "transmission", "battery_ev"],
    branches: [
      "ice_engine",
      "electric_powertrain",
      "hybrid_powertrain",
      "transmission_systems",
      "differential_drivetrain",
      "fuel_energy_systems",
      "engine_electronics",
      "thermal_powertrain",
    ],
    color: "#f59e0b",
    badgeBg: "bg-amber-100",
    badgeBorder: "border-amber-300 text-amber-800",
  },
  {
    id: "vehicle_dynamics",
    name: "Vehicle Dynamics",
    subtitle: "Chassis, Suspension, Steering, Braking & Tyre Grip",
    icon: "Activity",
    description: "Structural kinematics, spring/damper compliance, steering agility, brake deceleration, and tyre contact mechanics.",
    departments: ["chassis", "suspension", "tyres_wheels", "braking"],
    branches: [
      "chassis_dynamics",
      "suspension_dynamics",
      "steering_systems",
      "brake_systems",
      "tyres_wheels_dynamics",
      "vehicle_dynamics_control",
    ],
    color: "#06b6d4",
    badgeBg: "bg-cyan-100",
    badgeBorder: "border-cyan-300 text-cyan-800",
  },
  {
    id: "vehicle_design",
    name: "Vehicle Structure & Design",
    subtitle: "Body Structures, Closures, Lightweighting & Cockpit HMI",
    icon: "Car",
    description: "Passenger cell architectures, exterior sheet metal, composite lightweighting, NVH sound isolation, and interior cockpits.",
    departments: ["bodywork", "aero", "interior", "lighting_vision"],
    branches: [
      "body_structure",
      "exterior_bodywork",
      "lightweight_engineering",
      "materials_engineering",
      "nvh_acoustics",
      "interior_cabin",
      "ergonomics_hmi",
      "comfort_systems",
    ],
    color: "#10b981",
    badgeBg: "bg-emerald-100",
    badgeBorder: "border-emerald-300 text-emerald-800",
  },
  {
    id: "aerodynamics",
    name: "Aerodynamics & CFD",
    subtitle: "Drag Minimization, Ground Effect, Active Aero & Wind Tunnels",
    icon: "Wind",
    description: "Computational fluid dynamics, wake vortex control, Venturi underfloors, active spoilers, and boundary layer wind tunnel testing.",
    departments: ["aero"],
    branches: [
      "vehicle_aerodynamics",
      "underbody_aerodynamics",
      "racing_aerodynamics",
      "active_aerodynamics",
      "cfd_simulation",
      "wind_tunnel_tech",
      "thermal_aerodynamics",
    ],
    color: "#14b8a6",
    badgeBg: "bg-teal-100",
    badgeBorder: "border-teal-300 text-teal-800",
  },
  {
    id: "safety",
    name: "Safety & Crash Engineering",
    subtitle: "Survival Cells, Airbags, Restraints, ADAS & Collision Mitigation",
    icon: "ShieldCheck",
    description: "Non-linear crash FEM, crumple cans, multi-stage pyrotechnic airbags, blind-spot radars, and fail-safe autonomous braking.",
    departments: ["safety"],
    branches: [
      "passive_safety",
      "crash_structures",
      "restraint_systems",
      "airbags_pyrotechnics",
      "active_safety",
      "adas_systems",
      "driver_monitoring",
      "autonomous_safety",
    ],
    color: "#dc2626",
    badgeBg: "bg-red-100",
    badgeBorder: "border-red-300 text-red-800",
  },
  {
    id: "electronics_software",
    name: "Electronics & Software",
    subtitle: "Wiring Harnesses, CAN Buses, ECUs, AUTOSAR & Machine AI",
    icon: "Cpu",
    primaryFacility: "electronics_lab",
    description: "Multiplexed vehicle networks, high-reliability microcontrollers, real-time operating systems, and autonomous neural perception.",
    departments: ["electronics", "software_control"],
    branches: [
      "electrical_architecture",
      "sensor_technology",
      "ecu_hardware",
      "vehicle_networks",
      "embedded_software",
      "infotainment_systems",
      "telematics_connectivity",
      "ai_intelligent_systems",
      "autonomous_driving",
    ],
    color: "#8b5cf6",
    badgeBg: "bg-purple-100",
    badgeBorder: "border-purple-300 text-purple-800",
  } as unknown as MasterDivisionMeta,
  {
    id: "electrification",
    name: "Electrification & EV Systems",
    subtitle: "Cell Chemistry, Solid-State, SiC Inverters & 800V Charging",
    icon: "BatteryCharging",
    description: "High-density NMC/LFP/Solid-State batteries, structural cell-to-chassis packs, axial-flux traction motors, and 350kW DC fast charging.",
    departments: ["battery_ev"],
    branches: [
      "battery_chemistry",
      "battery_packs",
      "electric_motors",
      "inverter_technology",
      "power_electronics",
      "charging_systems",
      "regenerative_systems",
      "high_voltage_architecture",
    ],
    color: "#eab308",
    badgeBg: "bg-yellow-100",
    badgeBorder: "border-yellow-300 text-yellow-800",
  },
  {
    id: "manufacturing",
    name: "Manufacturing Technology",
    subtitle: "Die Casting, Giga-Presses, 5-Axis CNC, Robotics & QC Metrology",
    icon: "Wrench",
    description: "High-pressure aluminium die casting, single-piece megacasting, robotic spot-weld lines, composite autoclaves, and in-line optical laser QC.",
    departments: ["manufacturing_tech"],
    branches: [
      "casting_manufacturing",
      "forging_manufacturing",
      "machining_cnc",
      "stamping_presses",
      "welding_joining",
      "composite_manufacturing",
      "robotics_automation",
      "automation_systems",
      "quality_control",
      "factory_systems",
    ],
    color: "#3b82f6",
    badgeBg: "bg-blue-100",
    badgeBorder: "border-blue-300 text-blue-800",
  },
  {
    id: "industrial_supply",
    name: "Industrial & Supply Chain",
    subtitle: "Line Balancing, Logistics Fleets, Rail Spurs & Modular Platforms",
    icon: "Truck",
    description: "Plant throughput balancing, multi-source supplier contracts, transcontinental auto-rack rail logistics, and scalable modular floor pans.",
    departments: ["production_supply"],
    branches: [
      "production_engineering",
      "supply_chain_engineering",
      "supplier_technology",
      "logistics_freight",
      "rail_freight_systems",
      "warehousing_distribution",
      "modular_platforms",
      "manufacturing_standardization",
    ],
    color: "#64748b",
    badgeBg: "bg-slate-100",
    badgeBorder: "border-slate-300 text-slate-800",
  },
  {
    id: "motorsport",
    name: "Motorsport & Competition",
    subtitle: "Pneumatic Valves, Carbon Monocoques, DRS & Real-Time Telemetry",
    icon: "Trophy",
    description: "Formula 1 hybrid kinetic recovery, pneumatic valve springs, FIA carbon survival tubs, 3rd heave dampers, and 2-second pit equipment.",
    departments: ["motorsport_tech"],
    branches: [
      "race_engines",
      "race_transmission",
      "race_chassis",
      "race_suspension",
      "race_brakes",
      "race_tyres",
      "race_aero",
      "telemetry_acquisition",
      "endurance_technology",
      "pit_equipment",
      "driver_systems",
    ],
    color: "#ef4444",
    badgeBg: "bg-rose-100",
    badgeBorder: "border-rose-300 text-rose-800",
  },
  {
    id: "reliability_service",
    name: "Reliability & Service Engineering",
    subtitle: "1,000,000-km Durability, Rust Protection, OBD-II & Telematics",
    icon: "CheckSquare",
    description: "Accelerated road shaker rigs, E-coat zinc dip tanks, long-life sealed lubricants, OBD-II scan protocols, and predictive cloud maintenance.",
    departments: ["service_reliability", "testing_dev"],
    branches: [
      "durability_engineering",
      "corrosion_resistance",
      "maintenance_engineering",
      "serviceability_design",
      "diagnostic_systems",
      "predictive_maintenance",
    ],
    color: "#0284c7",
    badgeBg: "bg-sky-100",
    badgeBorder: "border-sky-300 text-sky-800",
  },
  {
    id: "environment_efficiency",
    name: "Environment & Sustainability",
    subtitle: "Low Friction, Euro/EPA Catalysts, Circular Battery Recycling & Net-Zero",
    icon: "Leaf",
    description: "DLC surface coatings, close-coupled 3-way catalysts, thermoelectric heat harvesters, bio-composite panels, and closed-loop aluminium recycling.",
    departments: ["environment_efficiency"],
    branches: [
      "fuel_efficiency",
      "emissions_reduction",
      "energy_recovery",
      "sustainable_materials",
      "recycling_technology",
      "sustainable_manufacturing",
    ],
    color: "#14b8a6",
    badgeBg: "bg-teal-100",
    badgeBorder: "border-teal-300 text-teal-800",
  },
];

// ===================================================================
// 2. THE 22 SPECIALIZED DEPARTMENTS
// ===================================================================

export const RD_DEPARTMENTS: RDDepartmentMeta[] = [
  // --- Powertrain ---
  {
    id: "engine",
    name: "Engine / Power Unit",
    divisionId: "powertrain",
    icon: "Cog",
    tagline: "Combustion Architecture, Forced Induction & Powertrain",
    description: "Engine block casting, valvetrain mechanics, fuel injection, turbocharging, and hybrid power unit integration.",
    subsections: [
      "Engine Architecture",
      "Engine Block & Construction",
      "Cylinder Head",
      "Induction",
      "Internal Components",
      "Combustion & Efficiency",
      "Cooling & Lubrication",
      "Engine Electronics",
      "Hybrid / Electrification",
      "Fuel Technology",
    ],
    primaryColor: "amber",
    badgeBg: "bg-amber-100",
    badgeText: "text-amber-800",
    buildingId: "engine_lab",
  },
  {
    id: "transmission",
    name: "Transmission & Drivetrain",
    divisionId: "powertrain",
    icon: "Sliders",
    tagline: "Gearboxes, Differentials, AWD & Torque Vectoring",
    description: "Manual, automatic, dual-clutch, and sequential transmissions along with mechanical and electronic LSDs.",
    subsections: [
      "Transmission Types",
      "Gear Technology",
      "Differential",
      "Drivetrain Layout",
      "Advanced Drivetrain",
    ],
    primaryColor: "amber",
    badgeBg: "bg-amber-100",
    badgeText: "text-amber-800",
    buildingId: "engine_lab",
  },
  {
    id: "battery_ev",
    name: "Battery & Electrification",
    divisionId: "powertrain",
    icon: "BatteryCharging",
    tagline: "Cell Chemistry, Axial Motors, Inverters & 800V Systems",
    description: "High-density lithium and solid-state batteries, permanent magnet motors, silicon carbide inverters, and fast charging.",
    subsections: [
      "Battery Chemistry",
      "Battery Engineering",
      "Electric Motors",
      "Power Electronics",
      "EV Performance",
    ],
    primaryColor: "yellow",
    badgeBg: "bg-yellow-100",
    badgeText: "text-yellow-800",
    buildingId: "battery_lab",
  },

  // --- Vehicle Dynamics ---
  {
    id: "chassis",
    name: "Chassis & Spaceframe",
    divisionId: "vehicle_dynamics",
    icon: "Layers",
    tagline: "Tub Architecture, Torsional Rigidity & Modular Hardpoints",
    description: "Steel spaceframes, monocoques, carbon tubs, and torsional stiffness tuning for precise cornering response.",
    subsections: [
      "Chassis Structure",
      "Rigidity",
      "Weight Distribution",
      "Chassis Development",
    ],
    primaryColor: "cyan",
    badgeBg: "bg-cyan-100",
    badgeText: "text-cyan-800",
    buildingId: "materials_lab",
  },
  {
    id: "suspension",
    name: "Suspension & Kinematics",
    divisionId: "vehicle_dynamics",
    icon: "Activity",
    tagline: "Double Wishbone, Pushrod, Adaptive Dampers & Anti-Roll",
    description: "Suspension geometries, anti-dive/anti-squat curves, active hydraulics, and semi-active magnetorheological damping.",
    subsections: [
      "Suspension Types",
      "Spring Technology",
      "Dampers",
      "Anti-Roll",
      "Geometry",
      "Advanced Suspension",
    ],
    primaryColor: "cyan",
    badgeBg: "bg-cyan-100",
    badgeText: "text-cyan-800",
    buildingId: "testing_center",
  },
  {
    id: "tyres_wheels",
    name: "Tyres & Wheels",
    divisionId: "vehicle_dynamics",
    icon: "Disc",
    tagline: "Radial Plies, Racing Slicks, Forged Alloys & Contact Patch",
    description: "Tire compounds, carcass construction, thermal hysteresis, low rolling resistance, and lightweight forged/carbon wheels.",
    subsections: [
      "Tyre Construction",
      "Compound",
      "Tyre Technology",
      "Wheel Technology",
      "Advanced Tyres",
    ],
    primaryColor: "cyan",
    badgeBg: "bg-cyan-100",
    badgeText: "text-cyan-800",
    buildingId: "testing_center",
  },
  {
    id: "braking",
    name: "Braking System",
    divisionId: "vehicle_dynamics",
    icon: "CircleDot",
    tagline: "Ventilated Rotors, Carbon Ceramics, ABS & Brake-by-Wire",
    description: "Multi-piston monobloc calipers, carbon-ceramic composites, thermal dissipation vanes, and regenerative blending.",
    subsections: [
      "Basic Brakes",
      "Performance Brakes",
      "Materials",
      "Brake Control",
      "Motorsport Brakes",
    ],
    primaryColor: "cyan",
    badgeBg: "bg-cyan-100",
    badgeText: "text-cyan-800",
    buildingId: "safety_center",
  },

  // --- Vehicle Design ---
  {
    id: "bodywork",
    name: "Bodywork & Architecture",
    divisionId: "vehicle_design",
    icon: "Car",
    tagline: "Body-on-Frame, Monocoque, Stamping & Exterior Aesthetics",
    description: "Sedan, Coupe, Supercar, and SUV body architectures, lightweight exterior closures, and sheet-metal shutlines.",
    subsections: [
      "Vehicle Architecture",
      "Body Construction",
      "Materials",
      "Lightweight Engineering",
      "Exterior Design",
      "Aerodynamic Body Shape",
    ],
    primaryColor: "emerald",
    badgeBg: "bg-emerald-100",
    badgeText: "text-emerald-800",
    buildingId: "materials_lab",
  },
  {
    id: "aero",
    name: "Aerodynamics & CFD",
    divisionId: "vehicle_design",
    icon: "Wind",
    tagline: "Downforce, Drag, Venturi Tunnels, Active Wings & CFD",
    description: "Virtual wind tunnels, active DRS spoilers, ground effect diffusers, front splitters, and boundary layer control.",
    subsections: [
      "Basic Aerodynamics",
      "Front Aero",
      "Rear Aero",
      "Underbody",
      "Racing Aero",
      "Active Aero",
      "Advanced CFD",
      "Wind Tunnel",
    ],
    primaryColor: "emerald",
    badgeBg: "bg-emerald-100",
    badgeText: "text-emerald-800",
    buildingId: "aero_center",
  },
  {
    id: "interior",
    name: "Interior & Cockpit HMI",
    divisionId: "vehicle_design",
    icon: "Armchair",
    tagline: "Cabin Ergonomics, Curved OLED Displays & Acoustic NVH",
    description: "SAE J826 H-Point posture, digital instrument clusters, luxury Nappa leather, and head-up display avionics.",
    subsections: [
      "Basic Interior",
      "Comfort",
      "Luxury",
      "Driver Interface",
      "Infotainment",
      "Advanced Cockpit",
    ],
    primaryColor: "emerald",
    badgeBg: "bg-emerald-100",
    badgeText: "text-emerald-800",
    buildingId: "nvh_lab",
  },
  {
    id: "lighting_vision",
    name: "Lighting & Vision",
    divisionId: "vehicle_design",
    icon: "Sun",
    tagline: "Halogen, Xenon, Matrix LED, Laser Lights & Night Vision",
    description: "Adaptive driving beam headlights, OLED signature tail lamps, surround cameras, and infrared thermal vision.",
    subsections: [
      "Lighting",
      "Visibility",
    ],
    primaryColor: "emerald",
    badgeBg: "bg-emerald-100",
    badgeText: "text-emerald-800",
    buildingId: "electronics_lab",
  },

  // --- Vehicle Technology ---
  {
    id: "safety",
    name: "Safety & Crash Engineering",
    divisionId: "vehicle_technology",
    icon: "ShieldCheck",
    tagline: "Crumple Zones, Airbags, NCAP Ratings & Active ADAS",
    description: "Passive passenger safety cells, multi-stage curtain airbags, non-linear FEM collision modeling, and collision avoidance.",
    subsections: [
      "Passive Safety",
      "Restraint Systems",
      "Airbags",
      "Crash Engineering",
      "Active Safety",
      "Driver Assistance",
      "Advanced Safety",
    ],
    primaryColor: "purple",
    badgeBg: "bg-purple-100",
    badgeText: "text-purple-800",
    buildingId: "safety_center",
  },
  {
    id: "electronics",
    name: "Electronics & Electrical",
    divisionId: "vehicle_technology",
    icon: "CircuitBoard",
    tagline: "Multiplex Wiring, CAN Bus, Sensors & Central Gateway",
    description: "12V/48V vehicle architectures, high-speed data buses, inertial measurement units, and drive-by-wire servos.",
    subsections: [
      "Electrical Architecture",
      "Sensors",
      "ECU Systems",
      "Controls",
      "Advanced Vehicle Electronics",
    ],
    primaryColor: "purple",
    badgeBg: "bg-purple-100",
    badgeText: "text-purple-800",
    buildingId: "electronics_lab",
  },
  {
    id: "software_control",
    name: "Software & Vehicle Control",
    divisionId: "vehicle_technology",
    icon: "Code",
    tagline: "Drive Modes, Stability Algorithms & AI Telemetry",
    description: "Launch control logic, active yaw control maps, predictive slip estimators, and over-the-air firmware updates.",
    subsections: [
      "Vehicle Software",
      "Performance Control",
      "Advanced Predictive Control",
    ],
    primaryColor: "purple",
    badgeBg: "bg-purple-100",
    badgeText: "text-purple-800",
    buildingId: "ai_software_lab",
  },
  {
    id: "thermal_management",
    name: "Thermal Management",
    divisionId: "vehicle_technology",
    icon: "Thermometer",
    tagline: "Radiator Heat Rejection, Oil Cooling & Battery Chilling",
    description: "Multi-loop cooling circuits, water-to-air intercoolers, phase-change materials, and exhaust thermal insulation.",
    subsections: [
      "Cooling",
      "Thermal Engineering",
      "Advanced Integrated Systems",
    ],
    primaryColor: "purple",
    badgeBg: "bg-purple-100",
    badgeText: "text-purple-800",
    buildingId: "engine_lab",
  },

  // --- Engineering Science ---
  {
    id: "materials_science",
    name: "Materials Science",
    divisionId: "engineering_science",
    icon: "Layers",
    tagline: "Aluminium, Titanium, Carbon Composites & Ceramics",
    description: "High-strength alloys, autoclave prepreg carbon fiber, ceramic matrix composites, and graphene nanosheets.",
    subsections: [
      "Metals",
      "Polymers",
      "Composites",
      "Advanced Materials",
    ],
    primaryColor: "blue",
    badgeBg: "bg-blue-100",
    badgeText: "text-blue-800",
    buildingId: "materials_lab",
  },
  {
    id: "manufacturing_tech",
    name: "Manufacturing Technology",
    divisionId: "engineering_science",
    icon: "Wrench",
    tagline: "Automated Tooling, Stamping Dies, CNC & 3D Printing",
    description: "Press lines, robotic spot welding, CNC cylinder machining, 3D laser powder bed additive manufacturing, and QC vision.",
    subsections: [
      "Manufacturing",
      "Body Manufacturing",
      "Joining",
      "Engine Manufacturing",
      "Advanced Manufacturing",
      "Quality Control",
    ],
    primaryColor: "blue",
    badgeBg: "bg-blue-100",
    badgeText: "text-blue-800",
    buildingId: "manufacturing_center",
  },
  {
    id: "testing_dev",
    name: "Testing & Development",
    divisionId: "engineering_science",
    icon: "FlaskConical",
    tagline: "720° Dyno, 4-Post Shaker Rig, Hardware-in-the-Loop & Twin",
    description: "Physical crash barriers, climate test cells, hardware-in-the-loop validation, and real-time digital twin analytics.",
    subsections: [
      "Physical Testing",
      "Simulation",
      "Advanced Testing",
    ],
    primaryColor: "blue",
    badgeBg: "bg-blue-100",
    badgeText: "text-blue-800",
    buildingId: "testing_center",
  },
  {
    id: "service_reliability",
    name: "Service & Reliability",
    divisionId: "engineering_science",
    icon: "CheckSquare",
    tagline: "Component Lifespan, OBD Diagnostics & Modular Service",
    description: "Extended warranty durability, modular component replacement, onboard OBD-II telematics, and predictive failure prevention.",
    subsections: [
      "Reliability",
      "Serviceability",
      "Longevity",
    ],
    primaryColor: "blue",
    badgeBg: "bg-blue-100",
    badgeText: "text-blue-800",
    buildingId: "testing_center",
  },

  // --- Motorsport ---
  {
    id: "motorsport_tech",
    name: "Motorsport Technology",
    divisionId: "motorsport",
    icon: "Trophy",
    tagline: "Grand Prix Aero, Extreme RPMs, MGU-K/MGU-H & Pit Tech",
    description: "Formula 1 hybrid kinetic recovery, Le Mans high-speed aero, pneumatic valve springs, and live telemetry radio links.",
    subsections: [
      "Race Engineering",
      "Powertrain",
      "Endurance",
      "Advanced Motorsport",
    ],
    primaryColor: "rose",
    badgeBg: "bg-rose-100",
    badgeText: "text-rose-800",
    buildingId: "aero_center",
  },

  // --- Industrial ---
  {
    id: "production_supply",
    name: "Production & Supply Chain",
    divisionId: "industrial",
    icon: "Truck",
    tagline: "Mega-Plants, JIT Logistics, Sourcing & Global Freight",
    description: "Gigafactory stamping lines, automated automated guided vehicles (AGVs), localized assembly, and Tier-1 raw material supply contracts.",
    subsections: [
      "Factory Technology",
      "Logistics",
      "Supply Chain",
      "Supplier Technology",
    ],
    primaryColor: "slate",
    badgeBg: "bg-slate-100",
    badgeText: "text-slate-800",
    buildingId: "manufacturing_center",
  },

  // --- Environment ---
  {
    id: "environment_efficiency",
    name: "Environment & Emissions",
    divisionId: "environment",
    icon: "Leaf",
    tagline: "Catalysts, Particulate Traps, Synthetic Fuels & Recycling",
    description: "Three-way catalytic converters, selective catalytic reduction (SCR), closed-loop carbon accounting, and battery mineral recycling.",
    subsections: [
      "Efficiency",
      "Emissions",
      "Electrification",
      "Sustainability",
    ],
    primaryColor: "teal",
    badgeBg: "bg-teal-100",
    badgeText: "text-teal-800",
    buildingId: "engine_lab",
  },
];

// ===================================================================
// 3. COMPLETE TECHNOLOGY NODES DATABASE (1970–2026+)
// ===================================================================

export const RD_TECH_NODES: RDTechNode[] = [
  // ─────────────────────────────────────────────────────────────
  // 1. ENGINE / POWER UNIT
  // ─────────────────────────────────────────────────────────────
  // Subsection: Engine Architecture
  {
    id: "eng_arch_baseline",
    name: "Classic Inline-4 Architecture",
    departmentId: "engine",
    divisionId: "powertrain",
    subsection: "Engine Architecture",
    yearAvailable: 1970,
    era: "classic_1970",
    cost: 0,
    months: 0,
    scientists: 0,
    buildingId: "engine_lab",
    buildingLevel: 1,
    ekCost: 0,
    description: "Standard 4-cylinder cast-iron configuration. Baseline automotive architecture.",
    requires: [],
    effects: [],
    unlocks: [{ studio: "engine", featureKey: "layout_i4", label: "Inline-4 Engine" }],
    failureRisk: 0,
  },
  {
    id: "eng_arch_i6",
    name: "Naturally Balanced Inline-6",
    departmentId: "engine",
    divisionId: "powertrain",
    subsection: "Engine Architecture",
    yearAvailable: 1970,
    era: "classic_1970",
    cost: 15_000_000,
    months: 10,
    scientists: 12,
    buildingId: "engine_lab",
    buildingLevel: 1,
    ekCost: 30,
    description: "Perfect primary and secondary harmonic balance. Smooth power delivery for executive and grand touring vehicles.",
    requires: ["eng_arch_baseline"],
    effects: [{ stat: "power", magnitude: 0.15, label: "+15% power potential" }, { stat: "smoothness", magnitude: 0.25, label: "+25% NVH smoothness" }],
    unlocks: [{ studio: "engine", featureKey: "layout_i6", label: "Inline-6 Engine" }],
    failureRisk: 0.05,
  },
  {
    id: "eng_arch_v8",
    name: "Cross-Plane V8 Powerhouse",
    departmentId: "engine",
    divisionId: "powertrain",
    subsection: "Engine Architecture",
    yearAvailable: 1970,
    era: "classic_1970",
    cost: 25_000_000,
    months: 12,
    scientists: 16,
    buildingId: "engine_lab",
    buildingLevel: 2,
    ekCost: 50,
    description: "Classic 90-degree V8 block with cross-plane crankshaft. Rich low-end torque and thunderous exhaust acoustic rumble.",
    requires: ["eng_arch_baseline"],
    effects: [{ stat: "torque", magnitude: 0.35, label: "+35% peak torque" }, { stat: "power", magnitude: 0.30, label: "+30% peak power" }],
    unlocks: [{ studio: "engine", featureKey: "layout_v8", label: "V8 Engine Architecture" }],
    failureRisk: 0.06,
  },
  {
    id: "eng_arch_v12",
    name: "Masterstroke V12 Grand Tourer",
    departmentId: "engine",
    divisionId: "powertrain",
    subsection: "Engine Architecture",
    yearAvailable: 1972,
    era: "classic_1970",
    cost: 50_000_000,
    months: 18,
    scientists: 22,
    buildingId: "engine_lab",
    buildingLevel: 3,
    ekCost: 100,
    description: "Silky 60-degree V12 architecture. The pinnacle of luxury GT and supercar propulsion with zero harmonic vibration.",
    requires: ["eng_arch_i6"],
    effects: [{ stat: "power", magnitude: 0.60, label: "+60% high-RPM power" }, { stat: "smoothness", magnitude: 0.40, label: "+40% smoothness" }],
    unlocks: [{ studio: "engine", featureKey: "layout_v12", label: "V12 Engine Architecture" }],
    failureRisk: 0.08,
  },
  {
    id: "eng_arch_boxer",
    name: "Horizontally Opposed Boxer-6",
    departmentId: "engine",
    divisionId: "powertrain",
    subsection: "Engine Architecture",
    yearAvailable: 1974,
    era: "classic_1970",
    cost: 30_000_000,
    months: 14,
    scientists: 15,
    buildingId: "engine_lab",
    buildingLevel: 2,
    ekCost: 65,
    description: "Flat-6 layout lowering center of gravity significantly. Superior handling dynamics for sports coupes.",
    requires: ["eng_arch_i6"],
    effects: [{ stat: "handling", magnitude: 0.10, label: "-80mm lower engine CG" }, { stat: "smoothness", magnitude: 0.20, label: "+20% rotational balance" }],
    unlocks: [{ studio: "engine", featureKey: "layout_boxer6", label: "Flat-6 Boxer Engine" }],
    failureRisk: 0.07,
  },
  {
    id: "eng_arch_rotary",
    name: "Alternative Powertrain Research Lab",
    departmentId: "engine",
    divisionId: "powertrain",
    subsection: "Engine Architecture",
    yearAvailable: 1972,
    era: "classic_1970",
    cost: 55_000_000,
    months: 18,
    scientists: 18,
    buildingId: "engine_lab",
    buildingLevel: 3,
    ekCost: 75,
    description: "Experimental alternative combustion and rotary propulsion research facility exploring high-RPM trochoidal dynamics.",
    requires: ["eng_arch_baseline"],
    effects: [{ stat: "weight", magnitude: -0.25, label: "-25% engine mass" }, { stat: "redline", magnitude: 2000, label: "+2,000 RPM redline" }],
    unlocks: [{ studio: "engine", featureKey: "layout_rotary", label: "Rotary Engine" }],
    failureRisk: 0.15,
  },
  {
    id: "eng_rotary_twin",
    name: "Twin-Rotor Rotary Performance Kit",
    departmentId: "engine",
    divisionId: "powertrain",
    subsection: "Engine Architecture",
    yearAvailable: 1979,
    era: "classic_1970",
    cost: 75_000_000,
    months: 32,
    scientists: 24,
    buildingId: "engine_lab",
    buildingLevel: 4,
    ekCost: 110,
    description: "Sequential twin-rotor housing with lightweight apex seals delivering soaring 9,000+ RPM redline.",
    requires: ["eng_arch_rotary"],
    effects: [{ stat: "power", magnitude: 0.40, label: "+40% rotary power" }, { stat: "redline", magnitude: 1500, label: "+1,500 RPM" }],
    unlocks: [{ studio: "engine", featureKey: "twin_rotary_kit", label: "Twin-Rotor Rotary Kit" }],
    failureRisk: 0.18,
  },
  {
    id: "eng_ind_turbo_flat6",
    name: "Turbocharged Flat-6 Kit",
    departmentId: "engine",
    divisionId: "powertrain",
    subsection: "Engine Architecture",
    yearAvailable: 1978,
    era: "classic_1970",
    cost: 15_000_000,
    months: 18,
    scientists: 16,
    buildingId: "engine_lab",
    buildingLevel: 3,
    ekCost: 65,
    description: "Dedicated exhaust-driven turbocharging system tailored for boxer engine packaging and rapid spool response.",
    requires: ["eng_arch_boxer"],
    effects: [{ stat: "power", magnitude: 0.45, label: "+45% boost power" }, { stat: "torque", magnitude: 0.35, label: "+35% mid-range torque" }],
    unlocks: [{ studio: "engine", featureKey: "turbo_flat6", label: "Turbocharged Flat-6 Kit" }],
    failureRisk: 0.10,
  },
  {
    id: "eng_ind_itb_v12",
    name: "Individually Throttled V12 (ITB)",
    departmentId: "engine",
    divisionId: "powertrain",
    subsection: "Engine Architecture",
    yearAvailable: 1982,
    era: "turbo_wedge_1980",
    cost: 25_000_000,
    months: 12,
    scientists: 20,
    buildingId: "engine_lab",
    buildingLevel: 4,
    ekCost: 85,
    description: "12 individual precision butterfly throttles with tuned velocity stacks for instantaneous throttle acoustics.",
    requires: ["eng_arch_v12"],
    effects: [{ stat: "throttleResponse", magnitude: 0.40, label: "+40% instant throttle response" }, { stat: "power", magnitude: 0.15, label: "+15% high-rev scream" }],
    unlocks: [{ studio: "engine", featureKey: "itb_v12", label: "Individually Throttled V12" }],
    failureRisk: 0.08,
  },
  {
    id: "eng_arch_w16",
    name: "Quad-Turbo W16 Hyper-Engine",
    departmentId: "engine",
    divisionId: "powertrain",
    subsection: "Engine Architecture",
    yearAvailable: 2005,
    era: "hybrid_2000",
    cost: 160_000_000,
    months: 32,
    scientists: 40,
    buildingId: "engine_lab",
    buildingLevel: 8,
    ekCost: 350,
    description: "Twin-VR8 dual bank architecture creating an 8.0-liter W16 titan delivering unprecedented mega-watt power.",
    requires: ["eng_arch_v8", "eng_ind_turbo_twin", "mat_carbon_fiber"],
    effects: [{ stat: "power", magnitude: 1.5, label: "+150% power ceiling (1,000+ HP)" }],
    unlocks: [{ studio: "engine", featureKey: "layout_w16", label: "W16 Hypercar Power Unit" }],
    failureRisk: 0.20,
  },

  // Subsection: Engine Block & Construction
  {
    id: "eng_blk_cast_iron",
    name: "Heavy-Duty Cast Iron Block",
    departmentId: "engine",
    divisionId: "powertrain",
    subsection: "Engine Block & Construction",
    yearAvailable: 1970,
    era: "classic_1970",
    cost: 0,
    months: 0,
    scientists: 0,
    buildingId: "engine_lab",
    buildingLevel: 1,
    ekCost: 0,
    description: "Durable, high-damping cast grey iron block.",
    requires: [],
    effects: [],
    unlocks: [],
    failureRisk: 0,
  },
  {
    id: "eng_blk_aluminum",
    name: "Cast Aluminium Alloy Block",
    departmentId: "engine",
    divisionId: "powertrain",
    subsection: "Engine Block & Construction",
    yearAvailable: 1975,
    era: "classic_1970",
    cost: 28_000_000,
    months: 12,
    scientists: 14,
    buildingId: "engine_lab",
    buildingLevel: 2,
    ekCost: 60,
    description: "Drastically trims block weight over front axle. Requires cross-tree aluminium metallurgy research.",
    requires: ["eng_blk_cast_iron", "mat_aluminum"], // Cross-tree to materials
    effects: [{ stat: "weight", magnitude: -0.35, label: "-35% engine block weight" }],
    unlocks: [{ studio: "engine", featureKey: "block_aluminum", label: "Aluminium Block Casting" }],
    failureRisk: 0.08,
  },
  {
    id: "eng_blk_closed_deck",
    name: "Reinforced Closed-Deck Construction",
    departmentId: "engine",
    divisionId: "powertrain",
    subsection: "Engine Block & Construction",
    yearAvailable: 1985,
    era: "turbo_wedge_1980",
    cost: 45_000_000,
    months: 16,
    scientists: 20,
    buildingId: "engine_lab",
    buildingLevel: 4,
    ekCost: 95,
    description: "Reinforced cylinder top deck preventing cylinder bore walk under severe forced-induction cylinder pressures.",
    requires: ["eng_blk_aluminum"],
    effects: [{ stat: "boostLimit", magnitude: 1.5, label: "+1.5 bar max boost tolerance" }, { stat: "reliability", magnitude: 0.15, label: "+15% durability" }],
    unlocks: [{ studio: "engine", featureKey: "deck_closed", label: "Closed Deck Reinforcement" }],
    failureRisk: 0.10,
  },
  {
    id: "eng_blk_cgi",
    name: "Compacted Graphite Iron (CGI)",
    departmentId: "engine",
    divisionId: "powertrain",
    subsection: "Engine Block & Construction",
    yearAvailable: 2000,
    era: "hybrid_2000",
    cost: 75_000_000,
    months: 20,
    scientists: 25,
    buildingId: "engine_lab",
    buildingLevel: 6,
    ekCost: 175,
    description: "75% stronger and 40% stiffer than conventional grey iron, permitting ultra-thin lightweight structural walls.",
    requires: ["eng_blk_closed_deck", "mat_hss"],
    effects: [{ stat: "strength", magnitude: 0.75, label: "+75% tensile strength" }, { stat: "weight", magnitude: -0.15, label: "-15% block weight" }],
    unlocks: [{ studio: "engine", featureKey: "block_cgi", label: "CGI Engine Block" }],
    failureRisk: 0.12,
  },

  // Subsection: Cylinder Head
  {
    id: "eng_head_ohv",
    name: "Overhead Valve (OHV) 2-Valve Head",
    departmentId: "engine",
    divisionId: "powertrain",
    subsection: "Cylinder Head",
    yearAvailable: 1970,
    era: "classic_1970",
    cost: 0,
    months: 0,
    scientists: 0,
    buildingId: "engine_lab",
    buildingLevel: 1,
    ekCost: 0,
    description: "Pushrod actuated two-valve per cylinder combustion chamber.",
    requires: [],
    effects: [],
    unlocks: [{ studio: "engine", featureKey: "valvetrain_ohv", label: "OHV 2V" }],
    failureRisk: 0,
  },
  {
    id: "eng_head_sohc",
    name: "Single Overhead Cam (SOHC)",
    departmentId: "engine",
    divisionId: "powertrain",
    subsection: "Cylinder Head",
    yearAvailable: 1971,
    era: "classic_1970",
    cost: 12_000_000,
    months: 8,
    scientists: 10,
    buildingId: "engine_lab",
    buildingLevel: 1,
    ekCost: 25,
    description: "Direct camshaft actuation in the cylinder head, eliminating heavy pushrod inertia for crisper revs.",
    requires: ["eng_head_ohv"],
    effects: [{ stat: "redline", magnitude: 600, label: "+600 RPM redline" }],
    unlocks: [{ studio: "engine", featureKey: "valvetrain_sohc", label: "SOHC Head" }],
    failureRisk: 0.04,
  },
  {
    id: "eng_head_dohc_4v",
    name: "Double Overhead Cam (DOHC) 4-Valve Head",
    departmentId: "engine",
    divisionId: "powertrain",
    subsection: "Cylinder Head",
    yearAvailable: 1978,
    era: "classic_1970",
    cost: 32_000_000,
    months: 14,
    scientists: 16,
    buildingId: "engine_lab",
    buildingLevel: 3,
    ekCost: 70,
    description: "Twin cams with dual intake and exhaust valves. Massive airflow volumetric efficiency jump at high RPM.",
    requires: ["eng_head_sohc"],
    effects: [{ stat: "volumetricEfficiency", magnitude: 0.20, label: "+20% volumetric airflow" }, { stat: "power", magnitude: 0.15, label: "+15% top-end power" }],
    unlocks: [{ studio: "engine", featureKey: "valvetrain_dohc", label: "DOHC 4V" }],
    failureRisk: 0.07,
  },
  {
    id: "eng_head_vvt",
    name: "Variable Valve Timing (VVT)",
    departmentId: "engine",
    divisionId: "powertrain",
    subsection: "Cylinder Head",
    yearAvailable: 1991,
    era: "electronic_1990",
    cost: 55_000_000,
    months: 18,
    scientists: 22,
    buildingId: "engine_lab",
    buildingLevel: 5,
    ekCost: 130,
    description: "Continuous camshaft phasing adapting to engine speed and load for flat torque curve and clean emissions.",
    requires: ["eng_head_dohc_4v", "elec_ecu_electronic"], // Cross-tree to electronics
    effects: [{ stat: "power", magnitude: 0.10, label: "+10% power" }, { stat: "fuelEconomy", magnitude: 0.08, label: "+8% fuel economy" }],
    unlocks: [{ studio: "engine", featureKey: "valvetrain_vvt", label: "Variable Valve Timing" }],
    failureRisk: 0.09,
  },
  {
    id: "eng_head_freevalve",
    name: "Camless Pneumatic Freevalve System",
    departmentId: "engine",
    divisionId: "powertrain",
    subsection: "Cylinder Head",
    yearAvailable: 2020,
    era: "modern_2015",
    cost: 140_000_000,
    months: 30,
    scientists: 35,
    buildingId: "engine_lab",
    buildingLevel: 9,
    ekCost: 380,
    description: "Independent electro-hydraulic-pneumatic valve actuators replacing traditional camshafts completely.",
    requires: ["eng_head_vvt", "elec_drive_by_wire", "mat_titanium"],
    effects: [{ stat: "efficiency", magnitude: 0.15, label: "+15% thermal efficiency" }, { stat: "torque", magnitude: 0.20, label: "+20% low-end torque" }],
    unlocks: [{ studio: "engine", featureKey: "valvetrain_freevalve", label: "Camless Freevalve" }],
    failureRisk: 0.22,
  },

  // Subsection: Induction
  {
    id: "eng_ind_carb_single",
    name: "Single Downdraft Carburettor",
    departmentId: "engine",
    divisionId: "powertrain",
    subsection: "Induction",
    yearAvailable: 1970,
    era: "classic_1970",
    cost: 0,
    months: 0,
    scientists: 0,
    buildingId: "engine_lab",
    buildingLevel: 1,
    ekCost: 0,
    description: "Mechanical venturi fuel metering.",
    requires: [],
    effects: [],
    unlocks: [{ studio: "engine", featureKey: "intake_single_carb", label: "Single Carb" }],
    failureRisk: 0,
  },
  {
    id: "eng_ind_carb_multi",
    name: "Dual/Triple Weber Side-Draft Carburettors",
    departmentId: "engine",
    divisionId: "powertrain",
    subsection: "Induction",
    yearAvailable: 1972,
    era: "classic_1970",
    cost: 14_000_000,
    months: 8,
    scientists: 10,
    buildingId: "engine_lab",
    buildingLevel: 1,
    ekCost: 30,
    description: "Dedicated carburettor barrels per cylinder runner for rapid throttle snap response and roaring intake roar.",
    requires: ["eng_ind_carb_single"],
    effects: [{ stat: "throttleResponse", magnitude: 0.25, label: "+25% throttle response" }, { stat: "power", magnitude: 0.08, label: "+8% power" }],
    unlocks: [{ studio: "engine", featureKey: "intake_multi_carb", label: "Multi Carburettor" }],
    failureRisk: 0.04,
  },
  {
    id: "eng_ind_turbo_single",
    name: "Exhaust-Gas Turbocharger",
    departmentId: "engine",
    divisionId: "powertrain",
    subsection: "Induction",
    yearAvailable: 1975,
    era: "classic_1970",
    cost: 38_000_000,
    months: 15,
    scientists: 18,
    buildingId: "engine_lab",
    buildingLevel: 3,
    ekCost: 85,
    description: "Harnessing waste exhaust kinetic energy to force-feed compressed intake air into the combustion chambers.",
    requires: ["eng_ind_carb_multi", "mat_hss"], // Cross-tree to materials
    effects: [{ stat: "power", magnitude: 0.35, label: "+35% peak power" }, { stat: "turboLag", magnitude: 0.5, label: "Noticeable turbo lag" }],
    unlocks: [{ studio: "engine", featureKey: "intake_turbo_single", label: "Single Turbocharger" }],
    failureRisk: 0.12,
  },
  {
    id: "eng_ind_efi",
    name: "Electronic Multi-Point Fuel Injection (EFI)",
    departmentId: "engine",
    divisionId: "powertrain",
    subsection: "Induction",
    yearAvailable: 1982,
    era: "turbo_wedge_1980",
    cost: 42_000_000,
    months: 14,
    scientists: 16,
    buildingId: "engine_lab",
    buildingLevel: 4,
    ekCost: 90,
    description: "Microprocessor-timed solenoid fuel injectors delivering precise stoichiometric air-fuel ratios.",
    requires: ["eng_ind_carb_multi", "elec_ecu_early"], // Cross-tree to electronics
    effects: [{ stat: "fuelEfficiency", magnitude: 0.18, label: "+18% fuel efficiency" }, { stat: "coldStart", magnitude: 0.9, label: "Flawless cold starting" }],
    unlocks: [{ studio: "engine", featureKey: "intake_efi", label: "Electronic Fuel Injection" }],
    failureRisk: 0.06,
  },
  {
    id: "eng_ind_turbo_twin",
    name: "Twin-Turbocharger & Intercooler",
    departmentId: "engine",
    divisionId: "powertrain",
    subsection: "Induction",
    yearAvailable: 1986,
    era: "turbo_wedge_1980",
    cost: 65_000_000,
    months: 18,
    scientists: 24,
    buildingId: "engine_lab",
    buildingLevel: 5,
    ekCost: 150,
    description: "Parallel or sequential turbochargers with air-to-air charge coolers to slash intake charge temperatures.",
    requires: ["eng_ind_turbo_single", "eng_ind_efi", "therm_radiators"], // Cross-tree to thermal
    effects: [{ stat: "power", magnitude: 0.60, label: "+60% power" }, { stat: "turboLag", magnitude: -0.4, label: "-40% turbo lag" }],
    unlocks: [{ studio: "engine", featureKey: "intake_turbo_twin", label: "Twin Turbo + Intercooler" }],
    failureRisk: 0.14,
  },
  {
    id: "eng_ind_direct_injection",
    name: "High-Pressure Direct Gasoline Injection (GDI)",
    departmentId: "engine",
    divisionId: "powertrain",
    subsection: "Induction",
    yearAvailable: 1999,
    era: "electronic_1990",
    cost: 70_000_000,
    months: 20,
    scientists: 26,
    buildingId: "engine_lab",
    buildingLevel: 6,
    ekCost: 180,
    description: "200-bar fuel injection directly into the cylinder crown providing in-cylinder evaporative charge cooling.",
    requires: ["eng_ind_efi", "eng_head_dohc_4v"],
    effects: [{ stat: "compressionRatio", magnitude: 1.5, label: "+1.5 compression ratio allowance" }, { stat: "efficiency", magnitude: 0.10, label: "+10% efficiency" }],
    unlocks: [{ studio: "engine", featureKey: "fuel_direct_injection", label: "Direct Injection" }],
    failureRisk: 0.11,
  },
  {
    id: "eng_ind_vgt",
    name: "Variable Geometry Turbocharging (VGT)",
    departmentId: "engine",
    divisionId: "powertrain",
    subsection: "Induction",
    yearAvailable: 2006,
    era: "hybrid_2000",
    cost: 95_000_000,
    months: 22,
    scientists: 28,
    buildingId: "engine_lab",
    buildingLevel: 7,
    ekCost: 220,
    description: "Adjustable turbine guide vanes varying aspect ratio dynamically for instantaneous spool and top-end boost.",
    requires: ["eng_ind_turbo_twin", "mat_titanium"],
    effects: [{ stat: "turboLag", magnitude: -0.75, label: "-75% turbo lag" }, { stat: "power", magnitude: 0.15, label: "+15% broad torque" }],
    unlocks: [{ studio: "engine", featureKey: "turbo_vgt", label: "Variable Geometry Turbo" }],
    failureRisk: 0.16,
  },

  // ─────────────────────────────────────────────────────────────
  // 2. TRANSMISSION & DRIVETRAIN
  // ─────────────────────────────────────────────────────────────
  {
    id: "trans_3spd_manual",
    name: "3-Speed Floor Shift Manual",
    departmentId: "transmission",
    divisionId: "powertrain",
    subsection: "Transmission Types",
    yearAvailable: 1970,
    era: "classic_1970",
    cost: 0,
    months: 0,
    scientists: 0,
    buildingId: "engine_lab",
    buildingLevel: 1,
    ekCost: 0,
    description: "Baseline synchromesh 3-speed manual gearbox.",
    requires: [],
    effects: [],
    unlocks: [{ studio: "engine", featureKey: "trans_manual_3", label: "3-Speed Manual" }],
    failureRisk: 0,
  },
  {
    id: "trans_4spd_manual",
    name: "4-Speed Synchromesh Manual",
    departmentId: "transmission",
    divisionId: "powertrain",
    subsection: "Transmission Types",
    yearAvailable: 1970,
    era: "classic_1970",
    cost: 10_000_000,
    months: 6,
    scientists: 8,
    buildingId: "engine_lab",
    buildingLevel: 1,
    ekCost: 20,
    description: "Standard four forward speeds providing improved highway cruising ratio.",
    requires: ["trans_3spd_manual"],
    effects: [{ stat: "topSpeed", magnitude: 12, label: "+12 mph top speed" }],
    unlocks: [{ studio: "engine", featureKey: "trans_manual_4", label: "4-Speed Manual" }],
    failureRisk: 0.02,
  },
  {
    id: "trans_5spd_manual",
    name: "5-Speed Overdrive Manual",
    departmentId: "transmission",
    divisionId: "powertrain",
    subsection: "Transmission Types",
    yearAvailable: 1976,
    era: "classic_1970",
    cost: 22_000_000,
    months: 10,
    scientists: 12,
    buildingId: "engine_lab",
    buildingLevel: 2,
    ekCost: 45,
    description: "Fifth gear overdrive drastically lowering engine cruising RPM and fuel consumption on open highways.",
    requires: ["trans_4spd_manual"],
    effects: [{ stat: "highwayFuel", magnitude: 0.15, label: "+15% highway fuel economy" }],
    unlocks: [{ studio: "engine", featureKey: "trans_manual_5", label: "5-Speed Manual" }],
    failureRisk: 0.04,
  },
  {
    id: "trans_6spd_manual",
    name: "Close-Ratio 6-Speed Manual",
    departmentId: "transmission",
    divisionId: "powertrain",
    subsection: "Transmission Types",
    yearAvailable: 1993,
    era: "electronic_1990",
    cost: 38_000_000,
    months: 14,
    scientists: 18,
    buildingId: "engine_lab",
    buildingLevel: 4,
    ekCost: 95,
    description: "Tight gear steps keeping the engine tightly in its peak powerband.",
    requires: ["trans_5spd_manual"],
    effects: [{ stat: "accel", magnitude: 0.08, label: "+8% track acceleration" }],
    unlocks: [{ studio: "engine", featureKey: "trans_manual_6", label: "6-Speed Manual" }],
    failureRisk: 0.05,
  },
  {
    id: "trans_dct",
    name: "Dual-Clutch Transmission (DCT)",
    departmentId: "transmission",
    divisionId: "powertrain",
    subsection: "Transmission Types",
    yearAvailable: 2003,
    era: "hybrid_2000",
    cost: 85_000_000,
    months: 22,
    scientists: 28,
    buildingId: "engine_lab",
    buildingLevel: 6,
    ekCost: 220,
    description: "Twin wet-clutch automated system pre-selecting adjacent gears for 8ms lightning-fast uninterrupted shifts.",
    requires: ["trans_6spd_manual", "elec_ecu_electronic"], // Cross-tree to electronics
    effects: [{ stat: "shiftSpeed", magnitude: 0.85, label: "-85% shift duration (8ms)" }, { stat: "accel0_60", magnitude: -0.3, label: "-0.3s 0-60 mph" }],
    unlocks: [{ studio: "engine", featureKey: "trans_dct_7", label: "Dual-Clutch Transmission" }],
    failureRisk: 0.15,
  },
  {
    id: "trans_lsd_mech",
    name: "Mechanical Limited-Slip Differential (LSD)",
    departmentId: "transmission",
    divisionId: "powertrain",
    subsection: "Differential",
    yearAvailable: 1972,
    era: "classic_1970",
    cost: 16_000_000,
    months: 8,
    scientists: 10,
    buildingId: "engine_lab",
    buildingLevel: 2,
    ekCost: 35,
    description: "Multi-plate clutch or helical differential transferring torque away from slipping inside wheels in hard corners.",
    requires: ["trans_4spd_manual"],
    effects: [{ stat: "traction", magnitude: 0.25, label: "+25% corner exit grip" }],
    unlocks: [{ studio: "vehicle", featureKey: "diff_mechanical_lsd", label: "Mechanical LSD" }],
    failureRisk: 0.04,
  },
  {
    id: "trans_torque_vectoring",
    name: "Active Electro-Hydraulic Torque Vectoring",
    departmentId: "transmission",
    divisionId: "powertrain",
    subsection: "Advanced Drivetrain",
    yearAvailable: 2008,
    era: "hybrid_2000",
    cost: 95_000_000,
    months: 24,
    scientists: 30,
    buildingId: "engine_lab",
    buildingLevel: 7,
    ekCost: 260,
    description: "Actively overdriving the outside rear tire to eliminate understeer and generate agile turn-in yaw torque.",
    requires: ["trans_lsd_mech", "elec_imu_sensors"], // Cross-tree to electronics
    effects: [{ stat: "lateralG", magnitude: 0.12, label: "+0.12g cornering grip" }, { stat: "understeer", magnitude: -0.5, label: "-50% turn-in understeer" }],
    unlocks: [{ studio: "vehicle", featureKey: "diff_torque_vectoring", label: "Active Torque Vectoring" }],
    failureRisk: 0.16,
  },

  // ─────────────────────────────────────────────────────────────
  // 3. CHASSIS & VEHICLE DYNAMICS
  // ─────────────────────────────────────────────────────────────
  {
    id: "chas_ladder_frame",
    name: "Perimeter Ladder Chassis",
    departmentId: "chassis",
    divisionId: "vehicle_dynamics",
    subsection: "Chassis Structure",
    yearAvailable: 1970,
    era: "classic_1970",
    cost: 0,
    months: 0,
    scientists: 0,
    buildingId: "materials_lab",
    buildingLevel: 1,
    ekCost: 0,
    description: "Rugged steel perimeter rails supporting detached coachwork.",
    requires: [],
    effects: [],
    unlocks: [{ studio: "vehicle", featureKey: "platform_ladder", label: "Ladder Frame" }],
    failureRisk: 0,
  },
  {
    id: "chas_steel_unibody",
    name: "Unitized Steel Monocoque (Unibody)",
    departmentId: "chassis",
    divisionId: "vehicle_dynamics",
    subsection: "Chassis Structure",
    yearAvailable: 1972,
    era: "classic_1970",
    cost: 24_000_000,
    months: 12,
    scientists: 14,
    buildingId: "materials_lab",
    buildingLevel: 2,
    ekCost: 55,
    description: "Stamped steel floor pan and pillars welded into an integrated stress-bearing shell for improved torsional rigidity.",
    requires: ["chas_ladder_frame", "mat_hss"], // Cross-tree to materials
    effects: [{ stat: "rigidity", magnitude: 0.40, label: "+40% torsional rigidity" }, { stat: "weight", magnitude: -0.15, label: "-15% vehicle weight" }],
    unlocks: [{ studio: "vehicle", featureKey: "platform_unibody", label: "Steel Monocoque" }],
    failureRisk: 0.05,
  },
  {
    id: "chas_aluminum_spaceframe",
    name: "Hydroformed Aluminium Spaceframe",
    departmentId: "chassis",
    divisionId: "vehicle_dynamics",
    subsection: "Chassis Structure",
    yearAvailable: 1994,
    era: "electronic_1990",
    cost: 80_000_000,
    months: 22,
    scientists: 28,
    buildingId: "materials_lab",
    buildingLevel: 6,
    ekCost: 200,
    description: "Extruded aluminium sections joined by cast alloy vacuum nodes providing immense stiffness at half steel weight.",
    requires: ["chas_steel_unibody", "mat_aluminum"], // Cross-tree to materials
    effects: [{ stat: "weight", magnitude: -0.30, label: "-30% structural weight" }, { stat: "rigidity", magnitude: 0.60, label: "+60% rigidity (24 kNm/deg)" }],
    unlocks: [{ studio: "vehicle", featureKey: "platform_aluminum_spaceframe", label: "Aluminium Spaceframe" }],
    failureRisk: 0.12,
  },
  {
    id: "chas_carbon_monocoque",
    name: "Autoclave Carbon-Fibre Monocoque Tub",
    departmentId: "chassis",
    divisionId: "vehicle_dynamics",
    subsection: "Chassis Structure",
    yearAvailable: 2002,
    era: "hybrid_2000",
    cost: 150_000_000,
    months: 28,
    scientists: 36,
    buildingId: "materials_lab",
    buildingLevel: 8,
    ekCost: 360,
    description: "One-piece carbon composite tub with aluminium honeycombed crush zones. Unyielding 45,000 Nm/deg torsional rigidity.",
    requires: ["chas_aluminum_spaceframe", "mat_carbon_fiber"], // Cross-tree to materials
    effects: [{ stat: "rigidity", magnitude: 1.20, label: "+120% rigidity (45 kNm/deg)" }, { stat: "crashSafety", magnitude: 0.50, label: "+50% passenger survival shell" }],
    unlocks: [{ studio: "vehicle", featureKey: "platform_carbon_monocoque", label: "Carbon Monocoque Tub" }],
    failureRisk: 0.18,
  },

  // ─────────────────────────────────────────────────────────────
  // 4. SUSPENSION
  // ─────────────────────────────────────────────────────────────
  {
    id: "susp_solid_axle",
    name: "Live Axle with Leaf Springs",
    departmentId: "suspension",
    divisionId: "vehicle_dynamics",
    subsection: "Suspension Types",
    yearAvailable: 1970,
    era: "classic_1970",
    cost: 0,
    months: 0,
    scientists: 0,
    buildingId: "testing_center",
    buildingLevel: 1,
    ekCost: 0,
    description: "Rigid beam axle supported by multi-leaf elliptic springs.",
    requires: [],
    effects: [],
    unlocks: [{ studio: "vehicle", featureKey: "susp_solid_axle", label: "Solid Live Axle" }],
    failureRisk: 0,
  },
  {
    id: "susp_macpherson",
    name: "Independent MacPherson Struts",
    departmentId: "suspension",
    divisionId: "vehicle_dynamics",
    subsection: "Suspension Types",
    yearAvailable: 1971,
    era: "classic_1970",
    cost: 14_000_000,
    months: 8,
    scientists: 10,
    buildingId: "testing_center",
    buildingLevel: 1,
    ekCost: 30,
    description: "Compact telescopic strut combining shock absorber and coil spring for packaged space efficiency.",
    requires: ["susp_solid_axle"],
    effects: [{ stat: "rideComfort", magnitude: 0.20, label: "+20% ride compliance" }, { stat: "roadHolding", magnitude: 0.15, label: "+15% road holding" }],
    unlocks: [{ studio: "vehicle", featureKey: "susp_macpherson", label: "MacPherson Struts" }],
    failureRisk: 0.03,
  },
  {
    id: "susp_double_wishbone",
    name: "Double Wishbone (SLA) Suspension",
    departmentId: "suspension",
    divisionId: "vehicle_dynamics",
    subsection: "Suspension Types",
    yearAvailable: 1976,
    era: "classic_1970",
    cost: 32_000_000,
    months: 14,
    scientists: 16,
    buildingId: "testing_center",
    buildingLevel: 3,
    ekCost: 75,
    description: "Upper and lower unequal A-arms maintaining optimal tire contact patch camber through full wheel jounce and rebound.",
    requires: ["susp_macpherson"],
    effects: [{ stat: "camberControl", magnitude: 0.40, label: "Precise camber curve tracking" }, { stat: "grip", magnitude: 0.12, label: "+12% lateral cornering grip" }],
    unlocks: [{ studio: "vehicle", featureKey: "susp_double_wishbone", label: "Double Wishbone" }],
    failureRisk: 0.06,
  },
  {
    id: "susp_multilink",
    name: "5-Link Independent Rear Suspension",
    departmentId: "suspension",
    divisionId: "vehicle_dynamics",
    subsection: "Suspension Types",
    yearAvailable: 1988,
    era: "turbo_wedge_1980",
    cost: 55_000_000,
    months: 18,
    scientists: 22,
    buildingId: "testing_center",
    buildingLevel: 4,
    ekCost: 130,
    description: "Five individual control links isolating longitudinal compliance from lateral cornering stiffness.",
    requires: ["susp_double_wishbone"],
    effects: [{ stat: "stability", magnitude: 0.25, label: "+25% high-speed braking stability" }],
    unlocks: [{ studio: "vehicle", featureKey: "susp_multilink", label: "5-Link Multi-Link" }],
    failureRisk: 0.08,
  },
  {
    id: "susp_pushrod",
    name: "Pushrod Actuated Inboard Coilovers",
    departmentId: "suspension",
    divisionId: "vehicle_dynamics",
    subsection: "Suspension Types",
    yearAvailable: 1996,
    era: "electronic_1990",
    cost: 75_000_000,
    months: 20,
    scientists: 26,
    buildingId: "testing_center",
    buildingLevel: 6,
    ekCost: 190,
    description: "Inboard horizontal coilovers activated by carbon pushrods and bellcranks. Drastically cuts unsprung mass.",
    requires: ["susp_double_wishbone", "mat_carbon_fiber"], // Cross-tree to materials
    effects: [{ stat: "unsprungMass", magnitude: -0.45, label: "-45% unsprung corner mass" }, { stat: "aeroCleanliness", magnitude: 0.15, label: "+15% underbody airflow cleanliness" }],
    unlocks: [{ studio: "vehicle", featureKey: "susp_pushrod", label: "Inboard Pushrod Suspension" }],
    failureRisk: 0.12,
  },
  {
    id: "susp_magneride",
    name: "Magnetorheological (MagneRide) Dampers",
    departmentId: "suspension",
    divisionId: "vehicle_dynamics",
    subsection: "Dampers",
    yearAvailable: 2004,
    era: "hybrid_2000",
    cost: 95_000_000,
    months: 24,
    scientists: 30,
    buildingId: "testing_center",
    buildingLevel: 7,
    ekCost: 250,
    description: "Shock absorbers filled with magnetic fluid that alters viscosity in 1 millisecond upon electromagnetic coil excitation.",
    requires: ["susp_multilink", "elec_imu_sensors"], // Cross-tree to electronics
    effects: [{ stat: "rollResistance", magnitude: 0.35, label: "Zero body roll in corners" }, { stat: "bumpAbsorption", magnitude: 0.30, label: "+30% harsh bump isolation" }],
    unlocks: [{ studio: "vehicle", featureKey: "dampers_adaptive_magne", label: "Adaptive MagneRide" }],
    failureRisk: 0.16,
  },

  // ─────────────────────────────────────────────────────────────
  // 5. AERODYNAMICS & CFD
  // ─────────────────────────────────────────────────────────────
  {
    id: "aero_drag_reduction",
    name: "Streamlined Body Curvature",
    departmentId: "aero",
    divisionId: "vehicle_design",
    subsection: "Basic Aerodynamics",
    yearAvailable: 1970,
    era: "classic_1970",
    cost: 0,
    months: 0,
    scientists: 0,
    buildingId: "aero_center",
    buildingLevel: 1,
    ekCost: 0,
    description: "Basic front nose rounding reducing aerodynamic blunt drag.",
    requires: [],
    effects: [],
    unlocks: [],
    failureRisk: 0,
  },
  {
    id: "aero_front_spoiler",
    name: "Front Air Dam & Chin Spoiler",
    departmentId: "aero",
    divisionId: "vehicle_design",
    subsection: "Front Aero",
    yearAvailable: 1973,
    era: "classic_1970",
    cost: 15_000_000,
    months: 8,
    scientists: 10,
    buildingId: "aero_center",
    buildingLevel: 1,
    ekCost: 35,
    description: "Deflects turbulent airflow around the vehicle instead of allowing high drag air underneath the chassis.",
    requires: ["aero_drag_reduction"],
    effects: [{ stat: "frontLift", magnitude: -0.25, label: "-25% front axle lift" }, { stat: "cd", magnitude: -0.02, label: "-0.02 drag coefficient" }],
    unlocks: [{ studio: "aero", featureKey: "front_air_dam", label: "Front Air Dam" }],
    failureRisk: 0.03,
  },
  {
    id: "aero_rear_wing_fixed",
    name: "Pedestal Rear Aerodynamic Wing",
    departmentId: "aero",
    divisionId: "vehicle_design",
    subsection: "Rear Aero",
    yearAvailable: 1975,
    era: "classic_1970",
    cost: 25_000_000,
    months: 12,
    scientists: 14,
    buildingId: "aero_center",
    buildingLevel: 2,
    ekCost: 60,
    description: "Inverted airfoil wing profile mounted on decklid stanchions generating substantial rear wheel downforce.",
    requires: ["aero_front_spoiler"],
    effects: [{ stat: "downforce", magnitude: 0.35, label: "+35% rear high-speed downforce" }],
    unlocks: [{ studio: "aero", featureKey: "rear_wing_fixed", label: "Fixed Rear Wing" }],
    failureRisk: 0.05,
  },
  {
    id: "aero_venturi_ground_effect",
    name: "Underbody Venturi Tunnels (Ground Effect)",
    departmentId: "aero",
    divisionId: "vehicle_design",
    subsection: "Underbody",
    yearAvailable: 1980,
    era: "turbo_wedge_1980",
    cost: 65_000_000,
    months: 18,
    scientists: 22,
    buildingId: "aero_center",
    buildingLevel: 4,
    ekCost: 150,
    description: "Shaped underfloor tunnels expanding into a high-angle rear diffuser to create low pressure suction without induced drag.",
    requires: ["aero_rear_wing_fixed", "chas_steel_unibody"],
    effects: [{ stat: "downforce", magnitude: 0.80, label: "+80% total downforce" }, { stat: "cd", magnitude: 0.05, label: "High aerodynamic efficiency (L/D > 3:1)" }],
    unlocks: [{ studio: "aero", featureKey: "aero_venturi_floor", label: "Venturi Ground Effect Floor" }],
    failureRisk: 0.12,
  },
  {
    id: "aero_active_drs",
    name: "Active Aerodynamic DRS & Airbrake",
    departmentId: "aero",
    divisionId: "vehicle_design",
    subsection: "Active Aero",
    yearAvailable: 2013,
    era: "modern_2015",
    cost: 110_000_000,
    months: 24,
    scientists: 32,
    buildingId: "aero_center",
    buildingLevel: 7,
    ekCost: 280,
    description: "High-speed electro-hydraulic rear wing actuators deploying in 0.2s for DRS drag shedding or 80-degree emergency airbraking.",
    requires: ["aero_venturi_ground_effect", "elec_drive_by_wire"], // Cross-tree to electronics
    effects: [{ stat: "brakingDist", magnitude: -0.15, label: "-15% high-speed stopping distance" }, { stat: "vmax", magnitude: 18, label: "+18 mph DRS top speed" }],
    unlocks: [{ studio: "aero", featureKey: "aero_active_drs", label: "Active DRS Wing" }],
    failureRisk: 0.17,
  },

  // ─────────────────────────────────────────────────────────────
  // 6. MATERIALS SCIENCE
  // ─────────────────────────────────────────────────────────────
  {
    id: "mat_mild_steel",
    name: "Standard Mild Carbon Steel",
    departmentId: "materials_science",
    divisionId: "engineering_science",
    subsection: "Metals",
    yearAvailable: 1970,
    era: "classic_1970",
    cost: 0,
    months: 0,
    scientists: 0,
    buildingId: "materials_lab",
    buildingLevel: 1,
    ekCost: 0,
    description: "Standard stamped automotive carbon steel.",
    requires: [],
    effects: [],
    unlocks: [],
    failureRisk: 0,
  },
  {
    id: "mat_hss",
    name: "High-Strength Steel (HSS)",
    departmentId: "materials_science",
    divisionId: "engineering_science",
    subsection: "Metals",
    yearAvailable: 1974,
    era: "classic_1970",
    cost: 18_000_000,
    months: 9,
    scientists: 10,
    buildingId: "materials_lab",
    buildingLevel: 2,
    ekCost: 35,
    description: "Micro-alloyed steel yielding higher tensile strength for thinner, lighter crash-resistant pillars.",
    requires: ["mat_mild_steel"],
    effects: [{ stat: "weight", magnitude: -0.05, label: "-5% weight" }, { stat: "safety", magnitude: 0.05, label: "+5% crash safety" }],
    unlocks: [],
    failureRisk: 0.03,
  },
  {
    id: "mat_aluminum",
    name: "Automotive-Grade 6000 Aluminium Alloys",
    departmentId: "materials_science",
    divisionId: "engineering_science",
    subsection: "Metals",
    yearAvailable: 1982,
    era: "turbo_wedge_1980",
    cost: 32_000_000,
    months: 12,
    scientists: 14,
    buildingId: "materials_lab",
    buildingLevel: 3,
    ekCost: 70,
    description: "Corrosion-resistant structural sheet aluminium cutting vehicle body and subframe weight dramatically.",
    requires: ["mat_hss"],
    effects: [{ stat: "weight", magnitude: -0.15, label: "-15% body panel weight" }],
    unlocks: [],
    failureRisk: 0.05,
  },
  {
    id: "mat_carbon_fiber",
    name: "T700 Autoclave Prepreg Carbon Fibre",
    departmentId: "materials_science",
    divisionId: "engineering_science",
    subsection: "Composites",
    yearAvailable: 1992,
    era: "electronic_1990",
    cost: 85_000_000,
    months: 22,
    scientists: 26,
    buildingId: "materials_lab",
    buildingLevel: 6,
    ekCost: 210,
    description: "Woven carbon matrix cured under 7 bar autoclave pressure, providing extraordinary tensile strength-to-weight ratio.",
    requires: ["mat_aluminum"],
    effects: [{ stat: "weight", magnitude: -0.35, label: "-35% component weight" }, { stat: "stiffness", magnitude: 0.80, label: "+80% structural stiffness" }],
    unlocks: [],
    failureRisk: 0.14,
  },
  {
    id: "mat_titanium",
    name: "Grade 5 Titanium (Ti-6Al-4V) Alloys",
    departmentId: "materials_science",
    divisionId: "engineering_science",
    subsection: "Metals",
    yearAvailable: 1998,
    era: "electronic_1990",
    cost: 75_000_000,
    months: 20,
    scientists: 24,
    buildingId: "materials_lab",
    buildingLevel: 6,
    ekCost: 180,
    description: "Extreme heat tolerance and specific strength for connecting rods, valvetrain, exhaust systems, and suspension springs.",
    requires: ["mat_carbon_fiber"],
    effects: [{ stat: "heatResistance", magnitude: 0.50, label: "+50% exhaust heat tolerance" }, { stat: "valvetrainSpeed", magnitude: 0.15, label: "+15% reciprocating redline" }],
    unlocks: [],
    failureRisk: 0.12,
  },

  // ─────────────────────────────────────────────────────────────
  // 7. ELECTRONICS & ELECTRICAL SYSTEMS
  // ─────────────────────────────────────────────────────────────
  {
    id: "elec_wiring_12v",
    name: "Point-to-Point 12V Harness",
    departmentId: "electronics",
    divisionId: "vehicle_technology",
    subsection: "Electrical Architecture",
    yearAvailable: 1970,
    era: "classic_1970",
    cost: 0,
    months: 0,
    scientists: 0,
    buildingId: "electronics_lab",
    buildingLevel: 1,
    ekCost: 0,
    description: "Conventional analog copper wiring loom.",
    requires: [],
    effects: [],
    unlocks: [],
    failureRisk: 0,
  },
  {
    id: "elec_ecu_early",
    name: "Discrete Solid-State Ignition Box",
    departmentId: "electronics",
    divisionId: "vehicle_technology",
    subsection: "ECU Systems",
    yearAvailable: 1975,
    era: "classic_1970",
    cost: 16_000_000,
    months: 8,
    scientists: 10,
    buildingId: "electronics_lab",
    buildingLevel: 2,
    ekCost: 40,
    description: "Transistorized ignition control replacing mechanical distributor contact breaker points.",
    requires: ["elec_wiring_12v"],
    effects: [{ stat: "sparkReliability", magnitude: 0.25, label: "+25% ignition spark reliability" }],
    unlocks: [],
    failureRisk: 0.04,
  },
  {
    id: "elec_ecu_electronic",
    name: "16-Bit Integrated Powertrain ECU",
    departmentId: "electronics",
    divisionId: "vehicle_technology",
    subsection: "ECU Systems",
    yearAvailable: 1989,
    era: "turbo_wedge_1980",
    cost: 45_000_000,
    months: 16,
    scientists: 20,
    buildingId: "electronics_lab",
    buildingLevel: 4,
    ekCost: 110,
    description: "Microprocessor-based engine control unit managing closed-loop O2 sensors, ignition timing tables, and turbo boost maps.",
    requires: ["elec_ecu_early"],
    effects: [{ stat: "engineControl", magnitude: 0.20, label: "+20% calibration precision" }],
    unlocks: [],
    failureRisk: 0.07,
  },
  {
    id: "elec_can_bus",
    name: "Controller Area Network (CAN Bus)",
    departmentId: "electronics",
    divisionId: "vehicle_technology",
    subsection: "Electrical Architecture",
    yearAvailable: 1993,
    era: "electronic_1990",
    cost: 60_000_000,
    months: 18,
    scientists: 22,
    buildingId: "electronics_lab",
    buildingLevel: 5,
    ekCost: 140,
    description: "High-speed twisted-pair bus linking Engine, Transmission, ABS, and Dashboard controllers with 60% less wiring harness weight.",
    requires: ["elec_ecu_electronic"],
    effects: [{ stat: "wiringWeight", magnitude: -0.60, label: "-60% wiring loom weight" }, { stat: "diagnosticSpeed", magnitude: 1.0, label: "OBD diagnostic compliance" }],
    unlocks: [],
    failureRisk: 0.08,
  },
  {
    id: "elec_imu_sensors",
    name: "6-Axis Inertial Measurement Unit (IMU)",
    departmentId: "electronics",
    divisionId: "vehicle_technology",
    subsection: "Sensors",
    yearAvailable: 2004,
    era: "hybrid_2000",
    cost: 70_000_000,
    months: 20,
    scientists: 24,
    buildingId: "electronics_lab",
    buildingLevel: 6,
    ekCost: 170,
    description: "Solid-state gyroscopes and accelerometers measuring pitch, roll, yaw, and cornering lateral-G forces at 1,000 Hz.",
    requires: ["elec_can_bus"],
    effects: [{ stat: "dynamicStability", magnitude: 0.35, label: "+35% stability control accuracy" }],
    unlocks: [],
    failureRisk: 0.10,
  },
  {
    id: "elec_drive_by_wire",
    name: "Full Electronic Drive-by-Wire Servos",
    departmentId: "electronics",
    divisionId: "vehicle_technology",
    subsection: "Controls",
    yearAvailable: 2008,
    era: "hybrid_2000",
    cost: 85_000_000,
    months: 22,
    scientists: 28,
    buildingId: "electronics_lab",
    buildingLevel: 7,
    ekCost: 210,
    description: "Electronic throttle, steer-by-wire, and electro-mechanical actuators replacing physical steel cables and linkages.",
    requires: ["elec_imu_sensors"],
    effects: [{ stat: "responseLatency", magnitude: -0.70, label: "-70% actuator response latency" }],
    unlocks: [],
    failureRisk: 0.12,
  },

  // ─────────────────────────────────────────────────────────────
  // 8. BATTERY & ELECTRIFICATION
  // ─────────────────────────────────────────────────────────────
  {
    id: "bat_lead_acid",
    name: "12V Lead-Acid Starter Battery",
    departmentId: "battery_ev",
    divisionId: "powertrain",
    subsection: "Battery Chemistry",
    yearAvailable: 1970,
    era: "classic_1970",
    cost: 0,
    months: 0,
    scientists: 0,
    buildingId: "battery_lab",
    buildingLevel: 1,
    ekCost: 0,
    description: "Standard automotive starter battery.",
    requires: [],
    effects: [],
    unlocks: [],
    failureRisk: 0,
  },
  {
    id: "bat_mild_hybrid_48v",
    name: "48V Belt-Alternator Starter (Mild Hybrid)",
    departmentId: "battery_ev",
    divisionId: "powertrain",
    subsection: "EV Performance",
    yearAvailable: 2000,
    era: "hybrid_2000",
    cost: 45_000_000,
    months: 16,
    scientists: 20,
    buildingId: "battery_lab",
    buildingLevel: 4,
    ekCost: 110,
    description: "48V lithium auxiliary pack capturing braking kinetic energy to torque-fill combustion engine lag seamlessly.",
    requires: ["bat_lead_acid", "elec_can_bus"], // Cross-tree to electronics
    effects: [{ stat: "cityFuel", magnitude: 0.15, label: "+15% urban fuel economy" }, { stat: "torqueFill", magnitude: 0.10, label: "+10% low-RPM torque fill" }],
    unlocks: [{ studio: "engine", featureKey: "hybrid_48v_mild", label: "48V Mild Hybrid" }],
    failureRisk: 0.08,
  },
  {
    id: "bat_lithium_pack",
    name: "High-Voltage Lithium-Ion Battery Pack",
    departmentId: "battery_ev",
    divisionId: "powertrain",
    subsection: "Battery Chemistry",
    yearAvailable: 2012,
    era: "modern_2015",
    cost: 95_000_000,
    months: 24,
    scientists: 30,
    buildingId: "battery_lab",
    buildingLevel: 6,
    ekCost: 240,
    description: "NMC pouch/cylindrical cell architecture operating at 400V delivering 160 Wh/kg volumetric energy density.",
    requires: ["bat_mild_hybrid_48v", "therm_radiators"], // Cross-tree to thermal
    effects: [{ stat: "evRange", magnitude: 250, label: "+250 miles EV range" }],
    unlocks: [{ studio: "engine", featureKey: "powertrain_ev_full", label: "Pure Electric Powertrain" }],
    failureRisk: 0.15,
  },
  {
    id: "bat_solid_state_800v",
    name: "Solid-State 800V Hyper-Battery Architecture",
    departmentId: "battery_ev",
    divisionId: "powertrain",
    subsection: "Battery Chemistry",
    yearAvailable: 2024,
    era: "hyper_2026",
    cost: 180_000_000,
    months: 34,
    scientists: 42,
    buildingId: "battery_lab",
    buildingLevel: 9,
    ekCost: 450,
    description: "Solid ceramic electrolyte with non-flammable silicon-carbon anodes. 450 Wh/kg energy density and 10-minute 800V fast charging.",
    requires: ["bat_lithium_pack", "mat_carbon_fiber"], // Cross-tree to materials
    effects: [{ stat: "energyDensity", magnitude: 1.8, label: "+180% energy density" }, { stat: "chargeTime", magnitude: -0.75, label: "-75% ultra-fast charging time" }],
    unlocks: [{ studio: "engine", featureKey: "battery_solid_state", label: "Solid-State 800V Battery" }],
    failureRisk: 0.25,
  },

  // ─────────────────────────────────────────────────────────────
  // 9. SAFETY & CRASH ENGINEERING
  // ─────────────────────────────────────────────────────────────
  {
    id: "safe_seatbelts_2pt",
    name: "2-Point Lap Seatbelts",
    departmentId: "safety",
    divisionId: "vehicle_technology",
    subsection: "Restraint Systems",
    yearAvailable: 1970,
    era: "classic_1970",
    cost: 0,
    months: 0,
    scientists: 0,
    buildingId: "safety_center",
    buildingLevel: 1,
    ekCost: 0,
    description: "Standard lap restraint belt.",
    requires: [],
    effects: [],
    unlocks: [{ studio: "safety", featureKey: "belts_2pt", label: "2-Point Belts" }],
    failureRisk: 0,
  },
  {
    id: "safe_3pt_belts",
    name: "3-Point Inertia-Reel Seatbelts",
    departmentId: "safety",
    divisionId: "vehicle_technology",
    subsection: "Restraint Systems",
    yearAvailable: 1971,
    era: "classic_1970",
    cost: 8_000_000,
    months: 6,
    scientists: 8,
    buildingId: "safety_center",
    buildingLevel: 1,
    ekCost: 20,
    description: "Diagonal torso sash and lap restraint with emergency pendulum centrifugal locking inertia reels.",
    requires: ["safe_seatbelts_2pt"],
    effects: [{ stat: "injuryReduction", magnitude: 0.40, label: "-40% fatal impact injury" }],
    unlocks: [{ studio: "safety", featureKey: "belts_3pt", label: "3-Point Inertia Belts" }],
    failureRisk: 0.02,
  },
  {
    id: "safe_crumple_zones",
    name: "Béla Barényi Frontal Crumple Zones",
    departmentId: "safety",
    divisionId: "vehicle_technology",
    subsection: "Crash Engineering",
    yearAvailable: 1973,
    era: "classic_1970",
    cost: 20_000_000,
    months: 10,
    scientists: 12,
    buildingId: "safety_center",
    buildingLevel: 2,
    ekCost: 45,
    description: "Sacrificial front rail deformation stages absorbing kinetic crash energy before intrusion into passenger survival cell.",
    requires: ["safe_3pt_belts", "chas_steel_unibody"], // Cross-tree to chassis
    effects: [{ stat: "ncapScore", magnitude: 25, label: "+25 NCAP crash points" }],
    unlocks: [{ studio: "safety", featureKey: "crumple_progressive", label: "Progressive Crumple Zones" }],
    failureRisk: 0.04,
  },
  {
    id: "safe_abs_system",
    name: "Electronic Anti-Lock Braking System (ABS)",
    departmentId: "safety",
    divisionId: "vehicle_technology",
    subsection: "Active Safety",
    yearAvailable: 1978,
    era: "classic_1970",
    cost: 45_000_000,
    months: 16,
    scientists: 20,
    buildingId: "safety_center",
    buildingLevel: 3,
    ekCost: 100,
    description: "Multi-channel electronic modulation preventing tire wheel lockup and maintaining steering control under threshold braking.",
    requires: ["safe_crumple_zones", "elec_ecu_early"], // Cross-tree to electronics
    effects: [{ stat: "wetBraking", magnitude: -0.30, label: "-30% wet braking stopping distance" }],
    unlocks: [{ studio: "braking", featureKey: "brake_abs", label: "Electronic ABS" }],
    failureRisk: 0.08,
  },
  {
    id: "safe_airbags_curtain",
    name: "Dual Front & Side Curtain Airbags",
    departmentId: "safety",
    divisionId: "vehicle_technology",
    subsection: "Airbags",
    yearAvailable: 1995,
    era: "electronic_1990",
    cost: 65_000_000,
    months: 18,
    scientists: 22,
    buildingId: "safety_center",
    buildingLevel: 5,
    ekCost: 150,
    description: "Pyrotechnic gas inflators deploying steering wheel, passenger dash, and roof rail head-protection curtains in 25 milliseconds.",
    requires: ["safe_crumple_zones", "elec_can_bus"], // Cross-tree to electronics
    effects: [{ stat: "sideImpactScore", magnitude: 0.60, label: "+60% side collision survival rating" }, { stat: "ncapStars", magnitude: 2, label: "+2 EuroNCAP stars" }],
    unlocks: [{ studio: "safety", featureKey: "airbag_full_curtain", label: "Full Curtain Airbags" }],
    failureRisk: 0.09,
  },
  {
    id: "safe_adas_autonomous",
    name: "Level 3 Autonomous Emergency Braking & Radar",
    departmentId: "safety",
    divisionId: "vehicle_technology",
    subsection: "Advanced Safety",
    yearAvailable: 2018,
    era: "modern_2015",
    cost: 130_000_000,
    months: 28,
    scientists: 35,
    buildingId: "safety_center",
    buildingLevel: 8,
    ekCost: 320,
    description: "Forward mmWave radar fused with stereoscopic machine vision cameras detecting pedestrian and vehicle cross-traffic hazards.",
    requires: ["safe_airbags_curtain", "elec_imu_sensors", "elec_drive_by_wire"], // Cross-tree to electronics
    effects: [{ stat: "collisionPrevention", magnitude: 0.85, label: "-85% low-speed urban collisions" }],
    unlocks: [{ studio: "safety", featureKey: "adas_aeb_radar", label: "Autonomous Radar Emergency Braking" }],
    failureRisk: 0.18,
  },

  // ─────────────────────────────────────────────────────────────
  // 10. THERMAL MANAGEMENT
  // ─────────────────────────────────────────────────────────────
  {
    id: "therm_radiators",
    name: "Copper-Brass Downflow Radiator",
    departmentId: "thermal_management",
    divisionId: "vehicle_technology",
    subsection: "Cooling",
    yearAvailable: 1970,
    era: "classic_1970",
    cost: 0,
    months: 0,
    scientists: 0,
    buildingId: "engine_lab",
    buildingLevel: 1,
    ekCost: 0,
    description: "Standard liquid-to-air heat exchanger with engine fan belt drive.",
    requires: [],
    effects: [],
    unlocks: [],
    failureRisk: 0,
  },
  {
    id: "therm_oil_cooler",
    name: "Thermostatic Engine Oil Cooler",
    departmentId: "thermal_management",
    divisionId: "vehicle_technology",
    subsection: "Cooling",
    yearAvailable: 1976,
    era: "classic_1970",
    cost: 14_000_000,
    months: 8,
    scientists: 10,
    buildingId: "engine_lab",
    buildingLevel: 2,
    ekCost: 35,
    description: "Auxiliary multi-row oil cooler preventing oil shearing degradation under sustained high-RPM and heavy towing.",
    requires: ["therm_radiators"],
    effects: [{ stat: "oilTemp", magnitude: -20, label: "-20°C oil operating temperature" }, { stat: "engineLifespan", magnitude: 0.25, label: "+25% engine lifespan" }],
    unlocks: [],
    failureRisk: 0.03,
  },
  {
    id: "therm_battery_chilling",
    name: "Refrigerant Direct Battery Chiller",
    departmentId: "thermal_management",
    divisionId: "vehicle_technology",
    subsection: "Advanced Integrated Systems",
    yearAvailable: 2016,
    era: "modern_2015",
    cost: 75_000_000,
    months: 20,
    scientists: 26,
    buildingId: "engine_lab",
    buildingLevel: 7,
    ekCost: 190,
    description: "Dedicated A/C heat pump chiller loop maintaining battery pouch cells strictly within the optimal 25°C - 35°C thermal window.",
    requires: ["therm_oil_cooler", "bat_lithium_pack"], // Cross-tree to battery
    effects: [{ stat: "batteryDegradation", magnitude: -0.50, label: "-50% cell capacity fade" }, { stat: "peakFastCharge", magnitude: 0.40, label: "+40% sustained fast charge duration" }],
    unlocks: [],
    failureRisk: 0.12,
  },

  // ─────────────────────────────────────────────────────────────
  // 11. MOTORSPORT TECHNOLOGY
  // ─────────────────────────────────────────────────────────────
  {
    id: "moto_race_springs",
    name: "Competition Valving & Corner Weighting",
    departmentId: "motorsport_tech",
    divisionId: "motorsport",
    subsection: "Race Engineering",
    yearAvailable: 1972,
    era: "classic_1970",
    cost: 20_000_000,
    months: 10,
    scientists: 12,
    buildingId: "aero_center",
    buildingLevel: 2,
    ekCost: 45,
    description: "Individual 4-wheel corner balance scales and competition shim valving for circuit racing agility.",
    requires: ["susp_macpherson"], // Cross-tree to suspension
    effects: [{ stat: "lapTime", magnitude: -1.2, label: "-1.2s per lap circuit pace" }],
    unlocks: [{ studio: "motorsport", featureKey: "corner_balancing", label: "Corner Weight Balancing" }],
    failureRisk: 0.05,
  },
  {
    id: "moto_pneumatic_valves",
    name: "Formula 1 Pneumatic Valve Return Springs",
    departmentId: "motorsport_tech",
    divisionId: "motorsport",
    subsection: "Powertrain",
    yearAvailable: 1990,
    era: "electronic_1990",
    cost: 95_000_000,
    months: 22,
    scientists: 28,
    buildingId: "aero_center",
    buildingLevel: 6,
    ekCost: 240,
    description: "Nitrogen gas pressure reservoirs replacing steel valve springs to completely eliminate valve float at 18,000+ RPM.",
    requires: ["moto_race_springs", "eng_head_dohc_4v", "mat_titanium"], // Cross-tree to engine and materials
    effects: [{ stat: "maxRpm", magnitude: 6000, label: "+6,000 RPM ceiling (19,000 RPM max)" }, { stat: "power", magnitude: 0.45, label: "+45% naturally aspirated race power" }],
    unlocks: [{ studio: "engine", featureKey: "valves_pneumatic", label: "Pneumatic Valve Return" }],
    failureRisk: 0.20,
  },
  {
    id: "moto_mgu_kh",
    name: "FIA MGU-K & MGU-H Hybrid Turbo Powertrain",
    departmentId: "motorsport_tech",
    divisionId: "motorsport",
    subsection: "Powertrain",
    yearAvailable: 2014,
    era: "modern_2015",
    cost: 160_000_000,
    months: 30,
    scientists: 40,
    buildingId: "aero_center",
    buildingLevel: 9,
    ekCost: 420,
    description: "Direct crankshaft kinetic motor generator (120 kW MGU-K) fused with exhaust turbine motor generator (MGU-H) for zero-lag 52% thermal efficiency.",
    requires: ["moto_pneumatic_valves", "bat_lithium_pack", "eng_ind_vgt"], // Cross-tree to battery and engine
    effects: [{ stat: "thermalEfficiency", magnitude: 0.52, label: "Unprecedented 52% thermal efficiency" }, { stat: "turboLag", magnitude: -1.0, label: "Zero turbo lag (electric spool)" }],
    unlocks: [{ studio: "engine", featureKey: "hybrid_mguk_mguh", label: "Formula 1 MGU-K/MGU-H Unit" }],
    failureRisk: 0.25,
  },

  // ─────────────────────────────────────────────────────────────
  // 12. MANUFACTURING TECHNOLOGY
  // ─────────────────────────────────────────────────────────────
  {
    id: "mfg_manual_line",
    name: "Manual Tooling & Jig Assembly",
    departmentId: "manufacturing_tech",
    divisionId: "engineering_science",
    subsection: "Manufacturing",
    yearAvailable: 1970,
    era: "classic_1970",
    cost: 0,
    months: 0,
    scientists: 0,
    buildingId: "manufacturing_center",
    buildingLevel: 1,
    ekCost: 0,
    description: "Human-operated manual jigs and hand welding.",
    requires: [],
    effects: [],
    unlocks: [],
    failureRisk: 0,
  },
  {
    id: "mfg_robotic_welding",
    name: "Robotic Spot Welding Body Line",
    departmentId: "manufacturing_tech",
    divisionId: "engineering_science",
    subsection: "Joining",
    yearAvailable: 1980,
    era: "turbo_wedge_1980",
    cost: 50_000_000,
    months: 16,
    scientists: 18,
    buildingId: "manufacturing_center",
    buildingLevel: 3,
    ekCost: 110,
    description: "6-axis Unimate robotic arms executing uniform, defect-free resistance spot welds on unibody structural seams.",
    requires: ["mfg_manual_line", "chas_steel_unibody"],
    effects: [{ stat: "buildSpeed", magnitude: 0.40, label: "+40% line throughput" }, { stat: "weldDefects", magnitude: -0.80, label: "-80% weld defects" }],
    unlocks: [{ studio: "manufacturing", featureKey: "mfg_robotic_welding", label: "Robotic Spot Welding" }],
    failureRisk: 0.08,
  },
  {
    id: "mfg_cnc_5axis",
    name: "5-Axis High-Speed CNC Machining Cells",
    departmentId: "manufacturing_tech",
    divisionId: "engineering_science",
    subsection: "Engine Manufacturing",
    yearAvailable: 1996,
    era: "electronic_1990",
    cost: 75_000_000,
    months: 20,
    scientists: 24,
    buildingId: "manufacturing_center",
    buildingLevel: 5,
    ekCost: 180,
    description: "High-precision computer numerical control machining for combustion chambers, ports, and billet crankshafts with micron tolerances.",
    requires: ["mfg_robotic_welding"],
    effects: [{ stat: "machiningTolerance", magnitude: 0.005, label: "5-micron precision tolerance" }],
    unlocks: [{ studio: "manufacturing", featureKey: "mfg_cnc_5axis", label: "5-Axis CNC Machining" }],
    failureRisk: 0.10,
  },
  {
    id: "mfg_gigacasting",
    name: "Single-Piece High-Pressure Giga-Casting",
    departmentId: "manufacturing_tech",
    divisionId: "engineering_science",
    subsection: "Body Manufacturing",
    yearAvailable: 2021,
    era: "modern_2015",
    cost: 160_000_000,
    months: 30,
    scientists: 38,
    buildingId: "manufacturing_center",
    buildingLevel: 9,
    ekCost: 400,
    description: "9,000-tonne die casting press stamping entire front and rear underbody assemblies in a single 90-second shot.",
    requires: ["mfg_cnc_5axis", "mat_aluminum"], // Cross-tree to materials
    effects: [{ stat: "partCount", magnitude: -120, label: "-120 individual sheet parts eliminated" }, { stat: "mfgCost", magnitude: -0.25, label: "-25% chassis assembly cost" }],
    unlocks: [{ studio: "manufacturing", featureKey: "mfg_gigacasting", label: "Megacasting Press Cell" }],
    failureRisk: 0.22,
  },
];

// ===================================================================
// 4. HELPER INDICES & MAPS
// ===================================================================

export const TECH_NODE_BY_ID: Record<string, RDTechNode> = RD_TECH_NODES.reduce(
  (acc, node) => {
    acc[node.id] = node;
    return acc;
  },
  {} as Record<string, RDTechNode>
);

export const TECH_NODES_BY_DEPARTMENT: Record<RDDepartmentId, RDTechNode[]> =
  RD_DEPARTMENTS.reduce((acc, dep) => {
    acc[dep.id] = RD_TECH_NODES.filter((n) => n.departmentId === dep.id);
    return acc;
  }, {} as Record<RDDepartmentId, RDTechNode[]>);

export const TECH_NODES_BY_DIVISION: Record<MasterDivisionId, RDTechNode[]> =
  MASTER_DIVISIONS.reduce((acc, div) => {
    acc[div.id] = RD_TECH_NODES.filter((n) => n.divisionId === div.id);
    return acc;
  }, {} as Record<MasterDivisionId, RDTechNode[]>);

export const DEPARTMENT_BY_ID: Record<RDDepartmentId, RDDepartmentMeta> =
  RD_DEPARTMENTS.reduce((acc, dep) => {
    acc[dep.id] = dep;
    return acc;
  }, {} as Record<RDDepartmentId, RDDepartmentMeta>);

export const DIVISION_BY_ID: Record<MasterDivisionId, MasterDivisionMeta> =
  MASTER_DIVISIONS.reduce((acc, div) => {
    acc[div.id] = div;
    return acc;
  }, {} as Record<MasterDivisionId, MasterDivisionMeta>);

// Backward compatibility aliases for legacy division IDs
const legacyDivAliases: Record<string, MasterDivisionMeta> = {
  vehicle_technology: DIVISION_BY_ID["safety"],
  engineering_science: DIVISION_BY_ID["manufacturing"],
  industrial: DIVISION_BY_ID["industrial_supply"],
  environment: DIVISION_BY_ID["environment_efficiency"],
};
Object.assign(DIVISION_BY_ID, legacyDivAliases);

export const TECH_NODES_BY_BRANCH: Record<SubsystemBranchId, RDTechNode[]> =
  SUBSYSTEM_BRANCHES.reduce((acc, b) => {
    acc[b.id] = RD_TECH_NODES.filter(
      (n) => n.departmentId === (b.id as unknown as RDDepartmentId)
    );
    return acc;
  }, {} as Record<SubsystemBranchId, RDTechNode[]>);

