// ============================================================================
// F1 CONSTRUCTOR EXPERIENCE — 24-RACE OFFICIAL WORLD CHAMPIONSHIP CALENDAR
// ============================================================================
// Complete circuit database with track profiles, lengths, tire stress ratings,
// brake severities, downforce requirements, altitude, and weather probabilities.
// ============================================================================

import type { F1CircuitProfile } from "../types/f1Interfaces";

export type F1Circuit = F1CircuitProfile;
export const F1_OFFICIAL_CALENDAR: F1CircuitProfile[] = [
  {
    id: "bahrain_sakhir",
    name: "Bahrain GP",
    officialTitle: "Formula 1 Gulf Air Bahrain Grand Prix",
    country: "Bahrain",
    city: "Sakhir",
    flagEmoji: "🇧🇭",
    lapLengthMeters: 5412,
    turnsCount: 15,
    raceLapsCount: 57,
    totalRaceDistanceKm: 308.238,
    drsZoneCount: 3,
    baseLapRecordSec: 91.447,
    trackGripIndex: 1.10,
    tireStressLevel: 4,
    brakeSeverityLevel: 4,
    downforceRequirement: "MEDIUM",
    altitudeMeters: 10,
    averageAmbientTempC: 28,
    rainProbabilityPercent: 2,
    safetyCarProbabilityPercent: 45,
  },
  {
    id: "saudi_jeddah",
    name: "Saudi Arabian GP",
    officialTitle: "Formula 1 STC Saudi Arabian Grand Prix",
    country: "Saudi Arabia",
    city: "Jeddah",
    flagEmoji: "🇸🇦",
    lapLengthMeters: 6174,
    turnsCount: 27,
    raceLapsCount: 50,
    totalRaceDistanceKm: 308.450,
    drsZoneCount: 3,
    baseLapRecordSec: 87.546,
    trackGripIndex: 1.18,
    tireStressLevel: 3,
    brakeSeverityLevel: 2,
    downforceRequirement: "LOW",
    altitudeMeters: 5,
    averageAmbientTempC: 30,
    rainProbabilityPercent: 1,
    safetyCarProbabilityPercent: 70,
  },
  {
    id: "australia_melbourne",
    name: "Australian GP",
    officialTitle: "Formula 1 Rolex Australian Grand Prix",
    country: "Australia",
    city: "Melbourne",
    flagEmoji: "🇦🇺",
    lapLengthMeters: 5278,
    turnsCount: 14,
    raceLapsCount: 58,
    totalRaceDistanceKm: 306.124,
    drsZoneCount: 4,
    baseLapRecordSec: 80.260,
    trackGripIndex: 1.05,
    tireStressLevel: 3,
    brakeSeverityLevel: 4,
    downforceRequirement: "MEDIUM",
    altitudeMeters: 12,
    averageAmbientTempC: 22,
    rainProbabilityPercent: 20,
    safetyCarProbabilityPercent: 65,
  },
  {
    id: "japan_suzuka",
    name: "Japanese GP",
    officialTitle: "Formula 1 MSC Cruises Japanese Grand Prix",
    country: "Japan",
    city: "Suzuka",
    flagEmoji: "🇯🇵",
    lapLengthMeters: 5807,
    turnsCount: 18,
    raceLapsCount: 53,
    totalRaceDistanceKm: 307.471,
    drsZoneCount: 1,
    baseLapRecordSec: 88.083,
    trackGripIndex: 1.25,
    tireStressLevel: 5,
    brakeSeverityLevel: 2,
    downforceRequirement: "HIGH",
    altitudeMeters: 45,
    averageAmbientTempC: 18,
    rainProbabilityPercent: 35,
    safetyCarProbabilityPercent: 40,
  },
  {
    id: "china_shanghai",
    name: "Chinese GP",
    officialTitle: "Formula 1 Lenovo Chinese Grand Prix",
    country: "China",
    city: "Shanghai",
    flagEmoji: "🇨🇳",
    lapLengthMeters: 5451,
    turnsCount: 16,
    raceLapsCount: 56,
    totalRaceDistanceKm: 305.066,
    drsZoneCount: 2,
    baseLapRecordSec: 92.238,
    trackGripIndex: 1.08,
    tireStressLevel: 4,
    brakeSeverityLevel: 3,
    downforceRequirement: "MEDIUM",
    altitudeMeters: 6,
    averageAmbientTempC: 20,
    rainProbabilityPercent: 25,
    safetyCarProbabilityPercent: 45,
  },
  {
    id: "usa_miami",
    name: "Miami GP",
    officialTitle: "Formula 1 Crypto.com Miami Grand Prix",
    country: "United States",
    city: "Miami",
    flagEmoji: "🇺🇸",
    lapLengthMeters: 5412,
    turnsCount: 19,
    raceLapsCount: 57,
    totalRaceDistanceKm: 308.326,
    drsZoneCount: 3,
    baseLapRecordSec: 87.215,
    trackGripIndex: 1.12,
    tireStressLevel: 3,
    brakeSeverityLevel: 4,
    downforceRequirement: "MEDIUM",
    altitudeMeters: 3,
    averageAmbientTempC: 31,
    rainProbabilityPercent: 20,
    safetyCarProbabilityPercent: 60,
  },
  {
    id: "italy_imola",
    name: "Emilia Romagna GP",
    officialTitle: "Formula 1 MSC Cruises Gran Premio dell'Emilia-Romagna",
    country: "Italy",
    city: "Imola",
    flagEmoji: "🇮🇹",
    lapLengthMeters: 4909,
    turnsCount: 19,
    raceLapsCount: 63,
    totalRaceDistanceKm: 309.049,
    drsZoneCount: 1,
    baseLapRecordSec: 75.484,
    trackGripIndex: 1.15,
    tireStressLevel: 3,
    brakeSeverityLevel: 3,
    downforceRequirement: "HIGH",
    altitudeMeters: 40,
    averageAmbientTempC: 23,
    rainProbabilityPercent: 28,
    safetyCarProbabilityPercent: 50,
  },
  {
    id: "monaco_montecarlo",
    name: "Monaco GP",
    officialTitle: "Formula 1 Grand Prix de Monaco",
    country: "Monaco",
    city: "Monte Carlo",
    flagEmoji: "🇲🇨",
    lapLengthMeters: 3337,
    turnsCount: 19,
    raceLapsCount: 78,
    totalRaceDistanceKm: 260.286,
    drsZoneCount: 1,
    baseLapRecordSec: 72.909,
    trackGripIndex: 0.92,
    tireStressLevel: 1,
    brakeSeverityLevel: 3,
    downforceRequirement: "MAXIMUM",
    altitudeMeters: 15,
    averageAmbientTempC: 24,
    rainProbabilityPercent: 15,
    safetyCarProbabilityPercent: 80,
  },
  {
    id: "canada_montreal",
    name: "Canadian GP",
    officialTitle: "Formula 1 AWS Grand Prix du Canada",
    country: "Canada",
    city: "Montreal",
    flagEmoji: "🇨🇦",
    lapLengthMeters: 4361,
    turnsCount: 14,
    raceLapsCount: 70,
    totalRaceDistanceKm: 305.270,
    drsZoneCount: 2,
    baseLapRecordSec: 73.078,
    trackGripIndex: 0.98,
    tireStressLevel: 3,
    brakeSeverityLevel: 5,
    downforceRequirement: "LOW",
    altitudeMeters: 14,
    averageAmbientTempC: 21,
    rainProbabilityPercent: 30,
    safetyCarProbabilityPercent: 65,
  },
  {
    id: "spain_barcelona",
    name: "Spanish GP",
    officialTitle: "Formula 1 Aramco Gran Premio de España",
    country: "Spain",
    city: "Barcelona",
    flagEmoji: "🇪🇸",
    lapLengthMeters: 4657,
    turnsCount: 14,
    raceLapsCount: 66,
    totalRaceDistanceKm: 307.236,
    drsZoneCount: 2,
    baseLapRecordSec: 76.330,
    trackGripIndex: 1.22,
    tireStressLevel: 5,
    brakeSeverityLevel: 3,
    downforceRequirement: "HIGH",
    altitudeMeters: 120,
    averageAmbientTempC: 29,
    rainProbabilityPercent: 10,
    safetyCarProbabilityPercent: 35,
  },
  {
    id: "austria_spielberg",
    name: "Austrian GP",
    officialTitle: "Formula 1 Qatar Airways Austrian Grand Prix",
    country: "Austria",
    city: "Spielberg",
    flagEmoji: "🇦🇹",
    lapLengthMeters: 4318,
    turnsCount: 10,
    raceLapsCount: 71,
    totalRaceDistanceKm: 306.452,
    drsZoneCount: 3,
    baseLapRecordSec: 65.619,
    trackGripIndex: 1.16,
    tireStressLevel: 4,
    brakeSeverityLevel: 4,
    downforceRequirement: "MEDIUM",
    altitudeMeters: 677,
    averageAmbientTempC: 22,
    rainProbabilityPercent: 32,
    safetyCarProbabilityPercent: 45,
  },
  {
    id: "uk_silverstone",
    name: "British GP",
    officialTitle: "Formula 1 Qatar Airways British Grand Prix",
    country: "United Kingdom",
    city: "Silverstone",
    flagEmoji: "🇬🇧",
    lapLengthMeters: 5891,
    turnsCount: 18,
    raceLapsCount: 52,
    totalRaceDistanceKm: 306.198,
    drsZoneCount: 2,
    baseLapRecordSec: 87.097,
    trackGripIndex: 1.24,
    tireStressLevel: 5,
    brakeSeverityLevel: 2,
    downforceRequirement: "HIGH",
    altitudeMeters: 153,
    averageAmbientTempC: 19,
    rainProbabilityPercent: 40,
    safetyCarProbabilityPercent: 55,
  },
  {
    id: "hungary_budapest",
    name: "Hungarian GP",
    officialTitle: "Formula 1 Hungarian Grand Prix",
    country: "Hungary",
    city: "Budapest",
    flagEmoji: "🇭🇺",
    lapLengthMeters: 4381,
    turnsCount: 14,
    raceLapsCount: 70,
    totalRaceDistanceKm: 306.630,
    drsZoneCount: 2,
    baseLapRecordSec: 76.627,
    trackGripIndex: 1.14,
    tireStressLevel: 3,
    brakeSeverityLevel: 4,
    downforceRequirement: "MAXIMUM",
    altitudeMeters: 236,
    averageAmbientTempC: 32,
    rainProbabilityPercent: 18,
    safetyCarProbabilityPercent: 30,
  },
  {
    id: "belgium_spa",
    name: "Belgian GP",
    officialTitle: "Formula 1 Rolex Belgian Grand Prix",
    country: "Belgium",
    city: "Stavelot",
    flagEmoji: "🇧🇪",
    lapLengthMeters: 7004,
    turnsCount: 19,
    raceLapsCount: 44,
    totalRaceDistanceKm: 308.052,
    drsZoneCount: 2,
    baseLapRecordSec: 106.286,
    trackGripIndex: 1.18,
    tireStressLevel: 5,
    brakeSeverityLevel: 3,
    downforceRequirement: "LOW",
    altitudeMeters: 410,
    averageAmbientTempC: 17,
    rainProbabilityPercent: 55,
    safetyCarProbabilityPercent: 60,
  },
  {
    id: "netherlands_zandvoort",
    name: "Dutch GP",
    officialTitle: "Formula 1 Heineken Dutch Grand Prix",
    country: "Netherlands",
    city: "Zandvoort",
    flagEmoji: "🇳🇱",
    lapLengthMeters: 4259,
    turnsCount: 14,
    raceLapsCount: 72,
    totalRaceDistanceKm: 306.587,
    drsZoneCount: 2,
    baseLapRecordSec: 71.097,
    trackGripIndex: 1.20,
    tireStressLevel: 4,
    brakeSeverityLevel: 3,
    downforceRequirement: "HIGH",
    altitudeMeters: 6,
    averageAmbientTempC: 19,
    rainProbabilityPercent: 38,
    safetyCarProbabilityPercent: 50,
  },
  {
    id: "italy_monza",
    name: "Italian GP",
    officialTitle: "Formula 1 Pirelli Gran Premio d'Italia",
    country: "Italy",
    city: "Monza",
    flagEmoji: "🇮🇹",
    lapLengthMeters: 5793,
    turnsCount: 11,
    raceLapsCount: 53,
    totalRaceDistanceKm: 306.720,
    drsZoneCount: 2,
    baseLapRecordSec: 81.046,
    trackGripIndex: 1.10,
    tireStressLevel: 3,
    brakeSeverityLevel: 5,
    downforceRequirement: "LOW",
    altitudeMeters: 162,
    averageAmbientTempC: 27,
    rainProbabilityPercent: 12,
    safetyCarProbabilityPercent: 40,
  },
  {
    id: "azerbaijan_baku",
    name: "Azerbaijan GP",
    officialTitle: "Formula 1 Qatar Airways Azerbaijan Grand Prix",
    country: "Azerbaijan",
    city: "Baku",
    flagEmoji: "🇦🇿",
    lapLengthMeters: 6003,
    turnsCount: 20,
    raceLapsCount: 51,
    totalRaceDistanceKm: 306.049,
    drsZoneCount: 2,
    baseLapRecordSec: 103.009,
    trackGripIndex: 0.94,
    tireStressLevel: 3,
    brakeSeverityLevel: 5,
    downforceRequirement: "LOW",
    altitudeMeters: -28,
    averageAmbientTempC: 25,
    rainProbabilityPercent: 4,
    safetyCarProbabilityPercent: 75,
  },
  {
    id: "singapore_marinabay",
    name: "Singapore GP",
    officialTitle: "Formula 1 Singapore Airlines Singapore Grand Prix",
    country: "Singapore",
    city: "Singapore",
    flagEmoji: "🇸🇬",
    lapLengthMeters: 4940,
    turnsCount: 19,
    raceLapsCount: 62,
    totalRaceDistanceKm: 306.143,
    drsZoneCount: 4,
    baseLapRecordSec: 95.841,
    trackGripIndex: 1.02,
    tireStressLevel: 3,
    brakeSeverityLevel: 5,
    downforceRequirement: "MAXIMUM",
    altitudeMeters: 15,
    averageAmbientTempC: 30,
    rainProbabilityPercent: 42,
    safetyCarProbabilityPercent: 100,
  },
  {
    id: "usa_cota",
    name: "United States GP",
    officialTitle: "Formula 1 Pirelli United States Grand Prix",
    country: "United States",
    city: "Austin",
    flagEmoji: "🇺🇸",
    lapLengthMeters: 5513,
    turnsCount: 20,
    raceLapsCount: 56,
    totalRaceDistanceKm: 308.405,
    drsZoneCount: 2,
    baseLapRecordSec: 96.169,
    trackGripIndex: 1.15,
    tireStressLevel: 4,
    brakeSeverityLevel: 3,
    downforceRequirement: "HIGH",
    altitudeMeters: 160,
    averageAmbientTempC: 27,
    rainProbabilityPercent: 15,
    safetyCarProbabilityPercent: 50,
  },
  {
    id: "mexico_hermanosrodriguez",
    name: "Mexico City GP",
    officialTitle: "Formula 1 Gran Premio de la Ciudad de México",
    country: "Mexico",
    city: "Mexico City",
    flagEmoji: "🇲🇽",
    lapLengthMeters: 4304,
    turnsCount: 17,
    raceLapsCount: 71,
    totalRaceDistanceKm: 305.354,
    drsZoneCount: 3,
    baseLapRecordSec: 77.774,
    trackGripIndex: 1.04,
    tireStressLevel: 3,
    brakeSeverityLevel: 5,
    downforceRequirement: "MAXIMUM",
    altitudeMeters: 2285,
    averageAmbientTempC: 22,
    rainProbabilityPercent: 20,
    safetyCarProbabilityPercent: 55,
  },
  {
    id: "brazil_interlagos",
    name: "São Paulo GP",
    officialTitle: "Formula 1 Lenovo Grande Prêmio de São Paulo",
    country: "Brazil",
    city: "São Paulo",
    flagEmoji: "🇧🇷",
    lapLengthMeters: 4309,
    turnsCount: 15,
    raceLapsCount: 71,
    totalRaceDistanceKm: 305.879,
    drsZoneCount: 2,
    baseLapRecordSec: 70.540,
    trackGripIndex: 1.16,
    tireStressLevel: 4,
    brakeSeverityLevel: 3,
    downforceRequirement: "MEDIUM",
    altitudeMeters: 785,
    averageAmbientTempC: 24,
    rainProbabilityPercent: 48,
    safetyCarProbabilityPercent: 65,
  },
  {
    id: "usa_lasvegas",
    name: "Las Vegas GP",
    officialTitle: "Formula 1 Heineken Silver Las Vegas Grand Prix",
    country: "United States",
    city: "Las Vegas",
    flagEmoji: "🇺🇸",
    lapLengthMeters: 6201,
    turnsCount: 17,
    raceLapsCount: 50,
    totalRaceDistanceKm: 309.958,
    drsZoneCount: 2,
    baseLapRecordSec: 94.876,
    trackGripIndex: 0.90,
    tireStressLevel: 2,
    brakeSeverityLevel: 5,
    downforceRequirement: "LOW",
    altitudeMeters: 610,
    averageAmbientTempC: 12,
    rainProbabilityPercent: 2,
    safetyCarProbabilityPercent: 60,
  },
  {
    id: "qatar_lusail",
    name: "Qatar GP",
    officialTitle: "Formula 1 Qatar Airways Qatar Grand Prix",
    country: "Qatar",
    city: "Lusail",
    flagEmoji: "🇶🇦",
    lapLengthMeters: 5419,
    turnsCount: 16,
    raceLapsCount: 57,
    totalRaceDistanceKm: 308.611,
    drsZoneCount: 1,
    baseLapRecordSec: 84.319,
    trackGripIndex: 1.22,
    tireStressLevel: 5,
    brakeSeverityLevel: 3,
    downforceRequirement: "HIGH",
    altitudeMeters: 12,
    averageAmbientTempC: 31,
    rainProbabilityPercent: 0,
    safetyCarProbabilityPercent: 40,
  },
  {
    id: "uae_abudhabi",
    name: "Abu Dhabi GP",
    officialTitle: "Formula 1 Etihad Airways Abu Dhabi Grand Prix",
    country: "United Arab Emirates",
    city: "Abu Dhabi",
    flagEmoji: "🇦🇪",
    lapLengthMeters: 5281,
    turnsCount: 16,
    raceLapsCount: 58,
    totalRaceDistanceKm: 306.183,
    drsZoneCount: 2,
    baseLapRecordSec: 86.103,
    trackGripIndex: 1.14,
    tireStressLevel: 3,
    brakeSeverityLevel: 4,
    downforceRequirement: "MEDIUM",
    altitudeMeters: 5,
    averageAmbientTempC: 26,
    rainProbabilityPercent: 1,
    safetyCarProbabilityPercent: 40,
  },
];

export const F1_CIRCUITS = F1_OFFICIAL_CALENDAR;
