// ============================================================================
// F1 CONSTRUCTOR EXPERIENCE — 10 RIVAL AI CONSTRUCTOR TEAMS
// ============================================================================

import type { F1RivalTeamSpec } from "../types/f1Interfaces";

export const F1_RIVAL_TEAMS: F1RivalTeamSpec[] = [
  {
    teamId: "red_bull_racing",
    teamName: "Oracle Red Bull Racing",
    colorHex: "#1E3A8A",
    engineSupplier: "HONDA_RBPT",
    powerUnitRating: 96,
    aerodynamicsRating: 98,
    chassisMechanicalRating: 94,
    reliabilityRating: 95,
    driver1Name: "Max Verstappen",
    driver1Rating: 99,
    driver2Name: "Sergio Pérez",
    driver2Rating: 88,
    estimatedLapTimeOffsetSec: 0.00,
  },
  {
    teamId: "scuderia_ferrari",
    teamName: "Scuderia Ferrari",
    colorHex: "#DC2626",
    engineSupplier: "FERRARI",
    powerUnitRating: 97,
    aerodynamicsRating: 93,
    chassisMechanicalRating: 95,
    reliabilityRating: 91,
    driver1Name: "Charles Leclerc",
    driver1Rating: 96,
    driver2Name: "Lewis Hamilton",
    driver2Rating: 97,
    estimatedLapTimeOffsetSec: 0.12,
  },
  {
    teamId: "mclaren_f1",
    teamName: "McLaren Formula 1 Team",
    colorHex: "#F97316",
    engineSupplier: "MERCEDES",
    powerUnitRating: 95,
    aerodynamicsRating: 97,
    chassisMechanicalRating: 94,
    reliabilityRating: 94,
    driver1Name: "Lando Norris",
    driver1Rating: 95,
    driver2Name: "Oscar Piastri",
    driver2Rating: 93,
    estimatedLapTimeOffsetSec: 0.08,
  },
  {
    teamId: "mercedes_amg",
    teamName: "Mercedes-AMG PETRONAS F1 Team",
    colorHex: "#0D9488",
    engineSupplier: "MERCEDES",
    powerUnitRating: 95,
    aerodynamicsRating: 92,
    chassisMechanicalRating: 93,
    reliabilityRating: 96,
    driver1Name: "George Russell",
    driver1Rating: 94,
    driver2Name: "Kimi Antonelli",
    driver2Rating: 89,
    estimatedLapTimeOffsetSec: 0.28,
  },
  {
    teamId: "aston_martin",
    teamName: "Aston Martin Aramco F1 Team",
    colorHex: "#065F46",
    engineSupplier: "MERCEDES",
    powerUnitRating: 93,
    aerodynamicsRating: 89,
    chassisMechanicalRating: 90,
    reliabilityRating: 92,
    driver1Name: "Fernando Alonso",
    driver1Rating: 95,
    driver2Name: "Lance Stroll",
    driver2Rating: 84,
    estimatedLapTimeOffsetSec: 0.55,
  },
  {
    teamId: "rb_honda",
    teamName: "Visa Cash App RB F1 Team",
    colorHex: "#2563EB",
    engineSupplier: "HONDA_RBPT",
    powerUnitRating: 94,
    aerodynamicsRating: 86,
    chassisMechanicalRating: 87,
    reliabilityRating: 91,
    driver1Name: "Yuki Tsunoda",
    driver1Rating: 88,
    driver2Name: "Liam Lawson",
    driver2Rating: 87,
    estimatedLapTimeOffsetSec: 0.85,
  },
  {
    teamId: "haas_f1",
    teamName: "MoneyGram Haas F1 Team",
    colorHex: "#E2E8F0",
    engineSupplier: "FERRARI",
    powerUnitRating: 95,
    aerodynamicsRating: 84,
    chassisMechanicalRating: 85,
    reliabilityRating: 89,
    driver1Name: "Esteban Ocon",
    driver1Rating: 89,
    driver2Name: "Oliver Bearman",
    driver2Rating: 86,
    estimatedLapTimeOffsetSec: 1.05,
  },
  {
    teamId: "williams_racing",
    teamName: "Williams Racing",
    colorHex: "#0284C7",
    engineSupplier: "MERCEDES",
    powerUnitRating: 94,
    aerodynamicsRating: 83,
    chassisMechanicalRating: 84,
    reliabilityRating: 90,
    driver1Name: "Alexander Albon",
    driver1Rating: 91,
    driver2Name: "Carlos Sainz",
    driver2Rating: 94,
    estimatedLapTimeOffsetSec: 0.95,
  },
  {
    teamId: "alpine_f1",
    teamName: "BWT Alpine F1 Team",
    colorHex: "#EC4899",
    engineSupplier: "RENAULT",
    powerUnitRating: 88,
    aerodynamicsRating: 83,
    chassisMechanicalRating: 84,
    reliabilityRating: 86,
    driver1Name: "Pierre Gasly",
    driver1Rating: 90,
    driver2Name: "Jack Doohan",
    driver2Rating: 83,
    estimatedLapTimeOffsetSec: 1.25,
  },
  {
    teamId: "sauber_audi",
    teamName: "Stake F1 Team Kick Sauber (Audi)",
    colorHex: "#84CC16",
    engineSupplier: "AUDI",
    powerUnitRating: 87,
    aerodynamicsRating: 81,
    chassisMechanicalRating: 82,
    reliabilityRating: 85,
    driver1Name: "Nico Hülkenberg",
    driver1Rating: 89,
    driver2Name: "Gabriel Bortoleto",
    driver2Rating: 85,
    estimatedLapTimeOffsetSec: 1.45,
  },
];
