// ============================================================================
// MODULAR glTF VEHICLE CONSTRUCTION SYSTEM — 10 BODY-TYPE MANIFEST
// ============================================================================
// Comprehensive registry for all 10 automotive body types with dimensions,
// wheelbase limits, track widths, default drag coefficients, and compatible chassis.
// ============================================================================

import { BodyTypeMetadata, VehicleBodyType } from '../types/vehicleConstructionTypes';

export const BODY_TYPE_REGISTRY: Record<VehicleBodyType, BodyTypeMetadata> = {
  sedan: {
    id: 'sedan',
    name: 'Executive Sedan',
    category: 'Passenger',
    description: 'Classic three-box luxury/executive passenger architecture with optimal balance of cabin isolation, high torsional rigidity, and aerodynamic efficiency.',
    typicalWheelbaseMm: { min: 2650, max: 3200, default: 2850 },
    typicalTrackWidthMm: { min: 1540, max: 1680, default: 1600 },
    typicalLengthMm: 4850,
    typicalWidthMm: 1870,
    typicalHeightMm: 1440,
    baseDragCoefficientCd: 0.26,
    frontalAreaSqM: 2.22,
    compatibleChassisIds: [
      'SEDAN_CHASSIS_01',
      'SEDAN_CHASSIS_02',
      'SEDAN_CHASSIS_03',
      'SEDAN_CHASSIS_04',
      'SEDAN_CHASSIS_05',
    ],
    icon: 'Car',
    badge: '3-BOX SEDAN',
  },
  coupe: {
    id: 'coupe',
    name: 'Grand Touring Coupe',
    category: 'Performance',
    description: 'Sleek two-door fastback silhouette featuring a shortened wheelbase, reinforced rocker sills, and lowered center of gravity for sharp dynamic agility.',
    typicalWheelbaseMm: { min: 2500, max: 2900, default: 2720 },
    typicalTrackWidthMm: { min: 1580, max: 1720, default: 1640 },
    typicalLengthMm: 4680,
    typicalWidthMm: 1910,
    typicalHeightMm: 1360,
    baseDragCoefficientCd: 0.28,
    frontalAreaSqM: 2.12,
    compatibleChassisIds: [
      'COUPE_CHASSIS_01',
      'COUPE_CHASSIS_02',
      'COUPE_CHASSIS_03',
      'COUPE_CHASSIS_04',
      'COUPE_CHASSIS_05',
    ],
    icon: 'Zap',
    badge: '2-DOOR GT',
  },
  hatchback: {
    id: 'hatchback',
    name: 'Hot Hatchback',
    category: 'Performance',
    description: 'Two-box compact performance architecture with steep rear glass hatch, rigid rear torsion-beam or multilink carrier, and outstanding urban maneuverability.',
    typicalWheelbaseMm: { min: 2450, max: 2750, default: 2600 },
    typicalTrackWidthMm: { min: 1520, max: 1620, default: 1560 },
    typicalLengthMm: 4320,
    typicalWidthMm: 1800,
    typicalHeightMm: 1430,
    baseDragCoefficientCd: 0.31,
    frontalAreaSqM: 2.18,
    compatibleChassisIds: [
      'HATCHBACK_CHASSIS_01',
      'HATCHBACK_CHASSIS_02',
      'HATCHBACK_CHASSIS_03',
      'HATCHBACK_CHASSIS_04',
      'HATCHBACK_CHASSIS_05',
    ],
    icon: 'Layers',
    badge: '2-BOX HATCH',
  },
  suv: {
    id: 'suv',
    name: 'Performance SUV & Crossover',
    category: 'Utility',
    description: 'Elevated ride-height platform with high structural cross-members, reinforced shock towers for off-camber terrain loads, and robust all-wheel-drive clearance.',
    typicalWheelbaseMm: { min: 2750, max: 3300, default: 2980 },
    typicalTrackWidthMm: { min: 1640, max: 1780, default: 1700 },
    typicalLengthMm: 4950,
    typicalWidthMm: 1980,
    typicalHeightMm: 1720,
    baseDragCoefficientCd: 0.34,
    frontalAreaSqM: 2.75,
    compatibleChassisIds: [
      'SUV_CHASSIS_01',
      'SUV_CHASSIS_02',
      'SUV_CHASSIS_03',
      'SUV_CHASSIS_04',
      'SUV_CHASSIS_05',
    ],
    icon: 'Shield',
    badge: '4X4 AWD SUV',
  },
  wagon: {
    id: 'wagon',
    name: 'Sport Wagon / Avant',
    category: 'Passenger',
    description: 'Extended flat roofline estate vehicle offering maximum rear cargo utility while maintaining executive sedan chassis kinematics and high-speed stability.',
    typicalWheelbaseMm: { min: 2700, max: 3100, default: 2880 },
    typicalTrackWidthMm: { min: 1560, max: 1660, default: 1610 },
    typicalLengthMm: 4900,
    typicalWidthMm: 1880,
    typicalHeightMm: 1460,
    baseDragCoefficientCd: 0.29,
    frontalAreaSqM: 2.28,
    compatibleChassisIds: [
      'WAGON_CHASSIS_01',
      'WAGON_CHASSIS_02',
      'WAGON_CHASSIS_03',
      'WAGON_CHASSIS_04',
      'WAGON_CHASSIS_05',
    ],
    icon: 'Car',
    badge: 'LONG ROOF WAGON',
  },
  convertible: {
    id: 'convertible',
    name: 'Roadster & Convertible',
    category: 'Performance',
    description: 'Open-top roadster engineered with hydroformed diagonal underfloor X-braces and ultra-high-strength steel A-pillars to counteract roof-loss torsional shear.',
    typicalWheelbaseMm: { min: 2400, max: 2750, default: 2550 },
    typicalTrackWidthMm: { min: 1540, max: 1660, default: 1590 },
    typicalLengthMm: 4400,
    typicalWidthMm: 1850,
    typicalHeightMm: 1280,
    baseDragCoefficientCd: 0.33,
    frontalAreaSqM: 1.98,
    compatibleChassisIds: [
      'CONVERTIBLE_CHASSIS_01',
      'CONVERTIBLE_CHASSIS_02',
      'CONVERTIBLE_CHASSIS_03',
      'CONVERTIBLE_CHASSIS_04',
      'CONVERTIBLE_CHASSIS_05',
    ],
    icon: 'Sun',
    badge: 'OPEN TOP SPYDER',
  },
  sports_car: {
    id: 'sports_car',
    name: 'Pure Sports Car',
    category: 'Performance',
    description: 'Lightweight front-mid or rear-mid engine sports car platform with extruded aluminum tub, 50:50 weight bias, and razor-sharp steering feedback.',
    typicalWheelbaseMm: { min: 2380, max: 2650, default: 2480 },
    typicalTrackWidthMm: { min: 1560, max: 1680, default: 1620 },
    typicalLengthMm: 4350,
    typicalWidthMm: 1890,
    typicalHeightMm: 1250,
    baseDragCoefficientCd: 0.30,
    frontalAreaSqM: 1.95,
    compatibleChassisIds: [
      'SPORTS_CAR_CHASSIS_01',
      'SPORTS_CAR_CHASSIS_02',
      'SPORTS_CAR_CHASSIS_03',
      'SPORTS_CAR_CHASSIS_04',
      'SPORTS_CAR_CHASSIS_05',
    ],
    icon: 'Flame',
    badge: 'TRACK SPORT',
  },
  supercar: {
    id: 'supercar',
    name: 'Mid-Engine Supercar',
    category: 'Exotic',
    description: 'High-rigidity central carbon-fiber monocoque tub with bolt-on front/rear aluminum subframes accommodating longitudinal V8/V10/V12 powertrains.',
    typicalWheelbaseMm: { min: 2600, max: 2850, default: 2700 },
    typicalTrackWidthMm: { min: 1660, max: 1780, default: 1720 },
    typicalLengthMm: 4620,
    typicalWidthMm: 2020,
    typicalHeightMm: 1180,
    baseDragCoefficientCd: 0.32,
    frontalAreaSqM: 1.90,
    compatibleChassisIds: [
      'SUPERCAR_CHASSIS_01',
      'SUPERCAR_CHASSIS_02',
      'SUPERCAR_CHASSIS_03',
      'SUPERCAR_CHASSIS_04',
      'SUPERCAR_CHASSIS_05',
    ],
    icon: 'Trophy',
    badge: 'MID-ENGINE EXOTIC',
  },
  hypercar: {
    id: 'hypercar',
    name: 'Aerospace Hypercar',
    category: 'Exotic',
    description: 'Extreme motorsport-derived full pre-preg autoclave carbon-composite monocell with integrated ground-effect venturi tunnels and F1-style pushrod bellcranks.',
    typicalWheelbaseMm: { min: 2680, max: 2950, default: 2780 },
    typicalTrackWidthMm: { min: 1700, max: 1840, default: 1760 },
    typicalLengthMm: 4780,
    typicalWidthMm: 2060,
    typicalHeightMm: 1120,
    baseDragCoefficientCd: 0.35,
    frontalAreaSqM: 1.84,
    compatibleChassisIds: [
      'HYPERCAR_CHASSIS_01',
      'HYPERCAR_CHASSIS_02',
      'HYPERCAR_CHASSIS_03',
      'HYPERCAR_CHASSIS_04',
      'HYPERCAR_CHASSIS_05',
    ],
    icon: 'Sparkles',
    badge: 'HYPERCARBON LMP',
  },
  pickup: {
    id: 'pickup',
    name: 'Heavy-Duty Pickup Truck',
    category: 'Utility',
    description: 'High-strength hydroformed steel ladder-frame chassis with separate isolated cabin and high-payload reinforced rear cargo bed with live axle leaves.',
    typicalWheelbaseMm: { min: 3100, max: 3700, default: 3350 },
    typicalTrackWidthMm: { min: 1680, max: 1820, default: 1740 },
    typicalLengthMm: 5400,
    typicalWidthMm: 2040,
    typicalHeightMm: 1850,
    baseDragCoefficientCd: 0.42,
    frontalAreaSqM: 3.15,
    compatibleChassisIds: [
      'PICKUP_CHASSIS_01',
      'PICKUP_CHASSIS_02',
      'PICKUP_CHASSIS_03',
      'PICKUP_CHASSIS_04',
      'PICKUP_CHASSIS_05',
    ],
    icon: 'Truck',
    badge: 'BOXED LADDER 4X4',
  },
};

export const ALL_BODY_TYPES: VehicleBodyType[] = Object.keys(BODY_TYPE_REGISTRY) as VehicleBodyType[];
