// ============================================================================
// MODULAR glTF VEHICLE CONSTRUCTION SYSTEM — 50-CHASSIS ASSET MANIFEST
// ============================================================================
// Defines all 50 unique chassis architectures (10 Body Types × 5 Chassis Choices).
// Every chassis specifies: mass, torsional rigidity (kNm/deg), wheelbase, track,
// engine bay envelope, attachment hardpoints, and manufacturing BOM cost.
// ============================================================================

import { Chassis50Definition, VehicleBodyType, ChassisHardpointSpec } from '../types/vehicleConstructionTypes';

/** Helper to generate standard chassis hardpoint list */
function createStandardHardpoints(wheelbaseMm: number, trackMm: number): ChassisHardpointSpec[] {
  const halfTrack = trackMm / 2;
  const halfWb = wheelbaseMm / 2;

  return [
    // Powertrain Mounts (Front Bay)
    {
      nodeId: 'ENGINE_MOUNT_FL',
      relativePosMm: [550, 180, -220],
      normalAxis: [0, 1, 0],
      allowedComponentTypes: ['powertrain_engine'],
      maxPayloadKg: 180,
      description: 'Front Left Hydraulic Engine Mount Bushing',
    },
    {
      nodeId: 'ENGINE_MOUNT_FR',
      relativePosMm: [550, 180, 220],
      normalAxis: [0, 1, 0],
      allowedComponentTypes: ['powertrain_engine'],
      maxPayloadKg: 180,
      description: 'Front Right Hydraulic Engine Mount Bushing',
    },
    {
      nodeId: 'TRANS_MOUNT_REAR',
      relativePosMm: [-150, 120, 0],
      normalAxis: [0, 1, 0],
      allowedComponentTypes: ['transmission'],
      maxPayloadKg: 120,
      description: 'Transmission Rear Crossmember Vibration Damper',
    },

    // Front Running Gear
    {
      nodeId: 'SUSP_MOUNT_FL',
      relativePosMm: [0, 0, -halfTrack],
      normalAxis: [0, 1, 0],
      allowedComponentTypes: ['suspension', 'wheels_brakes'],
      maxPayloadKg: 450,
      description: 'Front Left Upper Shock Tower & Wishbone Knuckle',
    },
    {
      nodeId: 'SUSP_MOUNT_FR',
      relativePosMm: [0, 0, halfTrack],
      normalAxis: [0, 1, 0],
      allowedComponentTypes: ['suspension', 'wheels_brakes'],
      maxPayloadKg: 450,
      description: 'Front Right Upper Shock Tower & Wishbone Knuckle',
    },

    // Rear Running Gear
    {
      nodeId: 'SUSP_MOUNT_RL',
      relativePosMm: [-wheelbaseMm, 0, -halfTrack],
      normalAxis: [0, 1, 0],
      allowedComponentTypes: ['suspension', 'wheels_brakes'],
      maxPayloadKg: 500,
      description: 'Rear Left Subframe Carrier & Spring Perch',
    },
    {
      nodeId: 'SUSP_MOUNT_RR',
      relativePosMm: [-wheelbaseMm, 0, halfTrack],
      normalAxis: [0, 1, 0],
      allowedComponentTypes: ['suspension', 'wheels_brakes'],
      maxPayloadKg: 500,
      description: 'Rear Right Subframe Carrier & Spring Perch',
    },

    // Cabin Safety Cell & Structural Pillars
    {
      nodeId: 'CABIN_MOUNT_A_PILLAR_L',
      relativePosMm: [250, 680, -680],
      normalAxis: [0, 1, 0],
      allowedComponentTypes: ['body_structure', 'lighting_glass'],
      maxPayloadKg: 200,
      description: 'A-Pillar Windshield Base Node Left',
    },
    {
      nodeId: 'CABIN_MOUNT_A_PILLAR_R',
      relativePosMm: [250, 680, 680],
      normalAxis: [0, 1, 0],
      allowedComponentTypes: ['body_structure', 'lighting_glass'],
      maxPayloadKg: 200,
      description: 'A-Pillar Windshield Base Node Right',
    },
    {
      nodeId: 'CABIN_MOUNT_B_PILLAR_L',
      relativePosMm: [-halfWb, 720, -700],
      normalAxis: [0, 0, -1],
      allowedComponentTypes: ['body_structure', 'exterior_panels'],
      maxPayloadKg: 250,
      description: 'B-Pillar Center Safety Ring Left',
    },
    {
      nodeId: 'CABIN_MOUNT_B_PILLAR_R',
      relativePosMm: [-halfWb, 720, 700],
      normalAxis: [0, 0, 1],
      allowedComponentTypes: ['body_structure', 'exterior_panels'],
      maxPayloadKg: 250,
      description: 'B-Pillar Center Safety Ring Right',
    },
    {
      nodeId: 'CABIN_MOUNT_C_PILLAR_L',
      relativePosMm: [-wheelbaseMm + 200, 680, -680],
      normalAxis: [0, 1, 0],
      allowedComponentTypes: ['body_structure', 'lighting_glass'],
      maxPayloadKg: 200,
      description: 'C-Pillar Rear Parcel Shelf Anchor Left',
    },
    {
      nodeId: 'CABIN_MOUNT_C_PILLAR_R',
      relativePosMm: [-wheelbaseMm + 200, 680, 680],
      normalAxis: [0, 1, 0],
      allowedComponentTypes: ['body_structure', 'lighting_glass'],
      maxPayloadKg: 200,
      description: 'C-Pillar Rear Parcel Shelf Anchor Right',
    },

    // Aerodynamics & Front/Rear Clips
    {
      nodeId: 'AERO_FRONT_SPLITTER',
      relativePosMm: [950, -120, 0],
      normalAxis: [1, 0, 0],
      allowedComponentTypes: ['aerodynamics', 'exterior_panels'],
      maxPayloadKg: 100,
      description: 'Front Radiator Core Support & Splitter Sub-frame',
    },
    {
      nodeId: 'AERO_REAR_DIFFUSER',
      relativePosMm: [-wheelbaseMm - 750, -100, 0],
      normalAxis: [-1, 0, 0],
      allowedComponentTypes: ['aerodynamics', 'exterior_panels'],
      maxPayloadKg: 120,
      description: 'Rear Impact Beam & Venturi Diffuser Mount',
    },
  ];
}

// ============================================================================
// 50 CHASSIS DEFINITIONS ARRAY
// ============================================================================

export const CHASSIS_50_REGISTRY: Chassis50Definition[] = [
  // ──────────────────────────────────────────────────────────────────────────
  // 1. SEDAN CHASSIS FAMILY (01 to 05)
  // ──────────────────────────────────────────────────────────────────────────
  {
    id: 'SEDAN_CHASSIS_01',
    bodyType: 'sedan',
    chassisIndex: 1,
    name: 'Executive Luxury Monocoque',
    architectureClass: 'aluminum_monocoque',
    tagline: 'Die-cast multi-chamber aluminum platform with acoustically isolated subframes',
    description: 'Engineered for smooth executive cruising with laser-welded aluminum shock towers and isolated hydraulic bushings.',
    baseMassKg: 385,
    torsionalRigidityKNmPerDeg: 32.5,
    wheelbaseMm: 2880,
    trackWidthFrontMm: 1610,
    trackWidthRearMm: 1620,
    rideHeightMm: 130,
    groundClearanceMm: 145,
    engineBayVolumeLitres: 280,
    supportedEngineLayouts: ['I4', 'V6', 'V8', 'EV_DUAL'],
    supportedDriveTypes: ['rwd', 'awd'],
    manufacturingCostBOM: 6400,
    keyAdvantages: ['Ultra-low NVH cabin isolation', '40% weight reduction vs steel', 'Exceptional crash box energy absorption'],
    materialGradeDefault: 'forged',
    hardpoints: createStandardHardpoints(2880, 1615),
  },
  {
    id: 'SEDAN_CHASSIS_02',
    bodyType: 'sedan',
    chassisIndex: 2,
    name: 'Sport Performance Spaceframe',
    architectureClass: 'hydroformed_spaceframe',
    tagline: 'Hydroformed high-strength steel frame with integrated diagonal cowl bracing',
    description: 'Rigid sports sedan architecture with triangulated strut-to-firewall braces and reinforced sill rails.',
    baseMassKg: 420,
    torsionalRigidityKNmPerDeg: 36.0,
    wheelbaseMm: 2820,
    trackWidthFrontMm: 1625,
    trackWidthRearMm: 1635,
    rideHeightMm: 115,
    groundClearanceMm: 125,
    engineBayVolumeLitres: 310,
    supportedEngineLayouts: ['I4', 'V6', 'V8', 'V10', 'V12'],
    supportedDriveTypes: ['rwd', 'awd'],
    manufacturingCostBOM: 5800,
    keyAdvantages: ['High lateral cornering stiffness', 'Direct steering feedback', 'Accepts longitudinal high-displacement engines'],
    materialGradeDefault: 'forged',
    hardpoints: createStandardHardpoints(2820, 1630),
  },
  {
    id: 'SEDAN_CHASSIS_03',
    bodyType: 'sedan',
    chassisIndex: 3,
    name: 'Long-Wheelbase Flagship Platform',
    architectureClass: 'hybrid_cast_extruded',
    tagline: 'Extended wheelbase with cast aluminum nodes and carbon-core roof bows',
    description: 'Prestige luxury chassis providing maximum rear passenger legroom and unyielding high-speed autobahn tracking.',
    baseMassKg: 460,
    torsionalRigidityKNmPerDeg: 38.0,
    wheelbaseMm: 3120,
    trackWidthFrontMm: 1640,
    trackWidthRearMm: 1650,
    rideHeightMm: 135,
    groundClearanceMm: 150,
    engineBayVolumeLitres: 340,
    supportedEngineLayouts: ['V6', 'V8', 'V12', 'EV_DUAL'],
    supportedDriveTypes: ['rwd', 'awd'],
    manufacturingCostBOM: 8900,
    keyAdvantages: ['Unmatched high-speed directional stability', 'Spacious cabin volume', 'Composite carbon-core reinforcement'],
    materialGradeDefault: 'billet',
    hardpoints: createStandardHardpoints(3120, 1645),
  },
  {
    id: 'SEDAN_CHASSIS_04',
    bodyType: 'sedan',
    chassisIndex: 4,
    name: 'Compact Touring Unibody',
    architectureClass: 'steel_unibody',
    tagline: 'Deep-drawn stamped Boron UHSS unibody shell for high-volume agile touring',
    description: 'Nimble compact sports sedan platform with hot-stamped 22MnB5 safety cage and responsive double-wishbone hardpoints.',
    baseMassKg: 360,
    torsionalRigidityKNmPerDeg: 29.5,
    wheelbaseMm: 2710,
    trackWidthFrontMm: 1570,
    trackWidthRearMm: 1580,
    rideHeightMm: 120,
    groundClearanceMm: 135,
    engineBayVolumeLitres: 240,
    supportedEngineLayouts: ['I4', 'V6', 'BOXER_4'],
    supportedDriveTypes: ['fwd', 'rwd', 'awd'],
    manufacturingCostBOM: 4200,
    keyAdvantages: ['Low manufacturing cost', 'Agile curb weight', 'High repairability'],
    materialGradeDefault: 'cast',
    hardpoints: createStandardHardpoints(2710, 1575),
  },
  {
    id: 'SEDAN_CHASSIS_05',
    bodyType: 'sedan',
    chassisIndex: 5,
    name: 'Motorsport Carbon Monocell',
    architectureClass: 'carbon_composite_monocell',
    tagline: 'Autoclave pre-preg carbon fiber passenger tub with FIA homologated rollcage',
    description: 'Track-focused touring race car monocoque with extreme torsional rigidity and ultra-lightweight structural mass.',
    baseMassKg: 285,
    torsionalRigidityKNmPerDeg: 52.0,
    wheelbaseMm: 2840,
    trackWidthFrontMm: 1660,
    trackWidthRearMm: 1670,
    rideHeightMm: 95,
    groundClearanceMm: 100,
    engineBayVolumeLitres: 320,
    supportedEngineLayouts: ['V6', 'V8', 'V10', 'EV_QUAD'],
    supportedDriveTypes: ['rwd', 'awd'],
    manufacturingCostBOM: 18500,
    keyAdvantages: ['F1-grade 52 kNm/deg rigidity', '285 kg ultra-light chassis', 'Extreme lateral grip capacity'],
    materialGradeDefault: 'titanium',
    hardpoints: createStandardHardpoints(2840, 1665),
  },

  // ──────────────────────────────────────────────────────────────────────────
  // 2. COUPE CHASSIS FAMILY (01 to 05)
  // ──────────────────────────────────────────────────────────────────────────
  {
    id: 'COUPE_CHASSIS_01',
    bodyType: 'coupe',
    chassisIndex: 1,
    name: 'Grand Touring Aluminum Tub',
    architectureClass: 'aluminum_monocoque',
    tagline: 'Short-wheelbase GT platform with reinforced B-pillar door rings',
    description: 'Balanced GT coupe platform engineered for effortless cross-continental touring with refined suspension geometry.',
    baseMassKg: 365,
    torsionalRigidityKNmPerDeg: 34.0,
    wheelbaseMm: 2740,
    trackWidthFrontMm: 1630,
    trackWidthRearMm: 1650,
    rideHeightMm: 120,
    groundClearanceMm: 130,
    engineBayVolumeLitres: 290,
    supportedEngineLayouts: ['I4', 'V6', 'V8', 'V12'],
    supportedDriveTypes: ['rwd', 'awd'],
    manufacturingCostBOM: 6800,
    keyAdvantages: ['Optimal GT weight distribution', 'High structural door aperture stiffness', 'Smooth aerodynamic flow'],
    materialGradeDefault: 'forged',
    hardpoints: createStandardHardpoints(2740, 1640),
  },
  {
    id: 'COUPE_CHASSIS_02',
    bodyType: 'coupe',
    chassisIndex: 2,
    name: 'Short-Wheelbase Drift Platform',
    architectureClass: 'hydroformed_spaceframe',
    tagline: 'High-angle steering geometry clearance with reinforced rear subframe carrier',
    description: 'Designed for extreme drift angle transitions with dual-caliper hydro e-brake mounts and stiffened strut towers.',
    baseMassKg: 390,
    torsionalRigidityKNmPerDeg: 37.5,
    wheelbaseMm: 2620,
    trackWidthFrontMm: 1650,
    trackWidthRearMm: 1660,
    rideHeightMm: 105,
    groundClearanceMm: 115,
    engineBayVolumeLitres: 310,
    supportedEngineLayouts: ['I4', 'V6', 'V8'],
    supportedDriveTypes: ['rwd'],
    manufacturingCostBOM: 5900,
    keyAdvantages: ['70-degree steering lock clearance', 'Instant yaw rotation response', 'Reinforced rear differential mounting'],
    materialGradeDefault: 'forged',
    hardpoints: createStandardHardpoints(2620, 1655),
  },
  {
    id: 'COUPE_CHASSIS_03',
    bodyType: 'coupe',
    chassisIndex: 3,
    name: 'Transaxle Sports Backbone',
    architectureClass: 'transaxle_backbone',
    tagline: 'Torque-tube backbone with rear transaxle gearbox for perfect 50:50 weight bias',
    description: 'Classic front-mid engine layout with rigid torque tube connecting the front engine directly to the rear transaxle.',
    baseMassKg: 375,
    torsionalRigidityKNmPerDeg: 41.0,
    wheelbaseMm: 2700,
    trackWidthFrontMm: 1640,
    trackWidthRearMm: 1660,
    rideHeightMm: 110,
    groundClearanceMm: 120,
    engineBayVolumeLitres: 300,
    supportedEngineLayouts: ['V6', 'V8', 'V12'],
    supportedDriveTypes: ['rwd'],
    manufacturingCostBOM: 9200,
    keyAdvantages: ['Exact 50:50 dynamic weight distribution', 'Ultra-low polar moment of inertia', 'Extreme powertrain rigidity'],
    materialGradeDefault: 'billet',
    hardpoints: createStandardHardpoints(2700, 1650),
  },
  {
    id: 'COUPE_CHASSIS_04',
    bodyType: 'coupe',
    chassisIndex: 4,
    name: 'Steel Unibody Sport Fastback',
    architectureClass: 'steel_unibody',
    tagline: 'Economical high-volume fastback coupe with deep-stamped quarter panels',
    description: 'High-strength steel unibody engineered for accessible performance coupes with low maintenance and robust crash safety.',
    baseMassKg: 405,
    torsionalRigidityKNmPerDeg: 30.5,
    wheelbaseMm: 2680,
    trackWidthFrontMm: 1590,
    trackWidthRearMm: 1600,
    rideHeightMm: 125,
    groundClearanceMm: 135,
    engineBayVolumeLitres: 260,
    supportedEngineLayouts: ['I4', 'V6'],
    supportedDriveTypes: ['fwd', 'rwd', 'awd'],
    manufacturingCostBOM: 4500,
    keyAdvantages: ['Low cost', 'Robust daily durability', 'Wide parts availability'],
    materialGradeDefault: 'cast',
    hardpoints: createStandardHardpoints(2680, 1595),
  },
  {
    id: 'COUPE_CHASSIS_05',
    bodyType: 'coupe',
    chassisIndex: 5,
    name: 'GT3 Carbon Monocoque',
    architectureClass: 'carbon_composite_monocell',
    tagline: 'FIA GT3 homologated full carbon tub with pushrod suspension towers',
    description: 'Championship-winning GT3 race platform with autoclave carbon chassis tub, air jacks, and center-lock wheel hubs.',
    baseMassKg: 265,
    torsionalRigidityKNmPerDeg: 54.0,
    wheelbaseMm: 2720,
    trackWidthFrontMm: 1680,
    trackWidthRearMm: 1690,
    rideHeightMm: 85,
    groundClearanceMm: 90,
    engineBayVolumeLitres: 330,
    supportedEngineLayouts: ['V6', 'V8', 'V10', 'BOXER_6'],
    supportedDriveTypes: ['rwd'],
    manufacturingCostBOM: 21000,
    keyAdvantages: ['54 kNm/deg race stiffness', '265 kg weight', 'Aero underbody tunnel integration'],
    materialGradeDefault: 'titanium',
    hardpoints: createStandardHardpoints(2720, 1685),
  },

  // ──────────────────────────────────────────────────────────────────────────
  // 3. HATCHBACK CHASSIS FAMILY (01 to 05)
  // ──────────────────────────────────────────────────────────────────────────
  {
    id: 'HATCHBACK_CHASSIS_01',
    bodyType: 'hatchback',
    chassisIndex: 1,
    name: 'Hot-Hatch Performance Unibody',
    architectureClass: 'steel_unibody',
    tagline: 'Transverse engine layout with reinforced rear hatch ring frame',
    description: 'Hot-hatch platform engineered with reinforced rear suspension towers and high-rate front anti-roll bar hardpoints.',
    baseMassKg: 340,
    torsionalRigidityKNmPerDeg: 28.0,
    wheelbaseMm: 2600,
    trackWidthFrontMm: 1560,
    trackWidthRearMm: 1550,
    rideHeightMm: 125,
    groundClearanceMm: 135,
    engineBayVolumeLitres: 220,
    supportedEngineLayouts: ['I4', 'BOXER_4'],
    supportedDriveTypes: ['fwd', 'awd'],
    manufacturingCostBOM: 3800,
    keyAdvantages: ['Compact urban footprint', 'Low mass', 'Excellent hatchback practicality'],
    materialGradeDefault: 'cast',
    hardpoints: createStandardHardpoints(2600, 1555),
  },
  {
    id: 'HATCHBACK_CHASSIS_02',
    bodyType: 'hatchback',
    chassisIndex: 2,
    name: 'Rally Group-A Spaceframe',
    architectureClass: 'tubular_spaceframe',
    tagline: 'T45 chromoly tubular spaceframe with long-travel suspension turrets',
    description: 'Designed for extreme stage rally jumps and heavy gravel impact loads with integrated multi-point cage.',
    baseMassKg: 325,
    torsionalRigidityKNmPerDeg: 39.0,
    wheelbaseMm: 2560,
    trackWidthFrontMm: 1600,
    trackWidthRearMm: 1600,
    rideHeightMm: 160,
    groundClearanceMm: 180,
    engineBayVolumeLitres: 240,
    supportedEngineLayouts: ['I4', 'BOXER_4'],
    supportedDriveTypes: ['awd'],
    manufacturingCostBOM: 9500,
    keyAdvantages: ['250mm suspension travel clearance', 'High impact jump resilience', 'Underbody Kevlar armor mounts'],
    materialGradeDefault: 'billet',
    hardpoints: createStandardHardpoints(2560, 1600),
  },
  {
    id: 'HATCHBACK_CHASSIS_03',
    bodyType: 'hatchback',
    chassisIndex: 3,
    name: 'City Commuter Hybrid Platform',
    architectureClass: 'steel_unibody',
    tagline: 'Optimized high-efficiency unibody with underfloor hybrid battery tray',
    description: 'Lightweight city chassis designed for optimal fuel efficiency and low powertrain vibration.',
    baseMassKg: 320,
    torsionalRigidityKNmPerDeg: 26.0,
    wheelbaseMm: 2520,
    trackWidthFrontMm: 1520,
    trackWidthRearMm: 1520,
    rideHeightMm: 140,
    groundClearanceMm: 150,
    engineBayVolumeLitres: 190,
    supportedEngineLayouts: ['I4'],
    supportedDriveTypes: ['fwd'],
    manufacturingCostBOM: 3200,
    keyAdvantages: ['Lowest production cost', 'Tight turning circle', 'Lightweight commute economy'],
    materialGradeDefault: 'cast',
    hardpoints: createStandardHardpoints(2520, 1520),
  },
  {
    id: 'HATCHBACK_CHASSIS_04',
    bodyType: 'hatchback',
    chassisIndex: 4,
    name: 'Widebody TCR Touring Platform',
    architectureClass: 'aluminum_monocoque',
    tagline: 'Touring Car Racing spec with widened track and front splitter mounting box',
    description: 'TCR competition platform with seam-welded front cradle and low-center-of-gravity floor stamping.',
    baseMassKg: 310,
    torsionalRigidityKNmPerDeg: 35.0,
    wheelbaseMm: 2640,
    trackWidthFrontMm: 1640,
    trackWidthRearMm: 1630,
    rideHeightMm: 95,
    groundClearanceMm: 105,
    engineBayVolumeLitres: 230,
    supportedEngineLayouts: ['I4'],
    supportedDriveTypes: ['fwd'],
    manufacturingCostBOM: 7200,
    keyAdvantages: ['TCR homologated safety cell', 'Wide track stability', 'Quick-change bumper mounts'],
    materialGradeDefault: 'forged',
    hardpoints: createStandardHardpoints(2640, 1635),
  },
  {
    id: 'HATCHBACK_CHASSIS_05',
    bodyType: 'hatchback',
    chassisIndex: 5,
    name: 'Mid-Engine Turbo Hatch Tub',
    architectureClass: 'carbon_composite_monocell',
    tagline: 'Group-B homage mid-mounted engine carbon tub with rear transaxle',
    description: 'Extreme layout placing the turbocharged engine directly behind the driver in a central carbon monocell.',
    baseMassKg: 250,
    torsionalRigidityKNmPerDeg: 48.0,
    wheelbaseMm: 2580,
    trackWidthFrontMm: 1650,
    trackWidthRearMm: 1670,
    rideHeightMm: 100,
    groundClearanceMm: 110,
    engineBayVolumeLitres: 290,
    supportedEngineLayouts: ['I4', 'V6'],
    supportedDriveTypes: ['rwd', 'awd'],
    manufacturingCostBOM: 16500,
    keyAdvantages: ['Mid-engine 42:58 weight bias', 'Supercar cornering in a hatch silhouette', 'Ultra-stiff carbon tub'],
    materialGradeDefault: 'titanium',
    hardpoints: createStandardHardpoints(2580, 1660),
  },

  // ──────────────────────────────────────────────────────────────────────────
  // 4. SUV & CROSSOVER CHASSIS FAMILY (01 to 05)
  // ──────────────────────────────────────────────────────────────────────────
  {
    id: 'SUV_CHASSIS_01',
    bodyType: 'suv',
    chassisIndex: 1,
    name: 'Heavy-Duty Off-Road Ladder Frame',
    architectureClass: 'heavy_duty_ladder_frame',
    tagline: 'Boxed high-tensile steel ladder frame with solid rear axle perches',
    description: 'Indestructible off-road platform designed for extreme wheel articulation, winch loads, and rock crawling.',
    baseMassKg: 580,
    torsionalRigidityKNmPerDeg: 24.0,
    wheelbaseMm: 2950,
    trackWidthFrontMm: 1690,
    trackWidthRearMm: 1690,
    rideHeightMm: 220,
    groundClearanceMm: 245,
    engineBayVolumeLitres: 360,
    supportedEngineLayouts: ['I4', 'V6', 'V8'],
    supportedDriveTypes: ['awd'],
    manufacturingCostBOM: 5400,
    keyAdvantages: ['Massive towing capacity', 'Frame flex durability on boulders', 'Body-on-frame vibration isolation'],
    materialGradeDefault: 'cast',
    hardpoints: createStandardHardpoints(2950, 1690),
  },
  {
    id: 'SUV_CHASSIS_02',
    bodyType: 'suv',
    chassisIndex: 2,
    name: 'Performance Crossover Monocoque',
    architectureClass: 'aluminum_monocoque',
    tagline: 'High-rigidity aluminum unibody with low-profile subframes for sports handling',
    description: 'Engineered for high-performance super-SUVs demanding sports-car cornering Gs and high-speed stability.',
    baseMassKg: 490,
    torsionalRigidityKNmPerDeg: 38.5,
    wheelbaseMm: 2920,
    trackWidthFrontMm: 1710,
    trackWidthRearMm: 1720,
    rideHeightMm: 165,
    groundClearanceMm: 185,
    engineBayVolumeLitres: 340,
    supportedEngineLayouts: ['V6', 'V8', 'V12'],
    supportedDriveTypes: ['awd'],
    manufacturingCostBOM: 8200,
    keyAdvantages: ['Over 1.0G lateral grip capability', '45% lighter than steel ladder frames', 'Precision active damper mounting'],
    materialGradeDefault: 'forged',
    hardpoints: createStandardHardpoints(2920, 1715),
  },
  {
    id: 'SUV_CHASSIS_03',
    bodyType: 'suv',
    chassisIndex: 3,
    name: 'Luxury Air-Suspension Platform',
    architectureClass: 'hybrid_cast_extruded',
    tagline: 'Three-chamber air suspension subframes with active roll stabilization',
    description: 'Supreme luxury SUV platform delivering a carpet-smooth ride over all terrain conditions.',
    baseMassKg: 520,
    torsionalRigidityKNmPerDeg: 36.0,
    wheelbaseMm: 3080,
    trackWidthFrontMm: 1720,
    trackWidthRearMm: 1730,
    rideHeightMm: 190,
    groundClearanceMm: 215,
    engineBayVolumeLitres: 370,
    supportedEngineLayouts: ['V6', 'V8', 'V12', 'EV_DUAL'],
    supportedDriveTypes: ['awd'],
    manufacturingCostBOM: 9600,
    keyAdvantages: ['Variable ride height (+/- 80mm)', 'Acoustic glass subframe isolators', 'High payload capacity'],
    materialGradeDefault: 'billet',
    hardpoints: createStandardHardpoints(3080, 1725),
  },
  {
    id: 'SUV_CHASSIS_04',
    bodyType: 'suv',
    chassisIndex: 4,
    name: 'Baja 1000 Trophy Frame',
    architectureClass: 'tubular_spaceframe',
    tagline: 'Full 4130 chromoly tube chassis with 30-inch trailing arm bypass shock geometry',
    description: 'Desert racing trophy truck chassis engineered to withstand 120 mph desert whoops and massive dune landings.',
    baseMassKg: 460,
    torsionalRigidityKNmPerDeg: 42.0,
    wheelbaseMm: 3180,
    trackWidthFrontMm: 1780,
    trackWidthRearMm: 1780,
    rideHeightMm: 280,
    groundClearanceMm: 310,
    engineBayVolumeLitres: 380,
    supportedEngineLayouts: ['V8'],
    supportedDriveTypes: ['rwd', 'awd'],
    manufacturingCostBOM: 14200,
    keyAdvantages: ['750mm suspension travel', 'Extreme dune impact resistance', 'Dual spare tire cage integrated'],
    materialGradeDefault: 'billet',
    hardpoints: createStandardHardpoints(3180, 1780),
  },
  {
    id: 'SUV_CHASSIS_05',
    bodyType: 'suv',
    chassisIndex: 5,
    name: 'Skateboard EV Architecture',
    architectureClass: 'skateboard_ev_platform',
    tagline: 'Structural 800V battery pack integrated directly into extruded aluminum sills',
    description: 'Flat skateboard chassis with low center of gravity, dual or tri-motor electric drives, and flat floor cabin.',
    baseMassKg: 510,
    torsionalRigidityKNmPerDeg: 45.0,
    wheelbaseMm: 3020,
    trackWidthFrontMm: 1700,
    trackWidthRearMm: 1710,
    rideHeightMm: 170,
    groundClearanceMm: 190,
    engineBayVolumeLitres: 120, // Frunk
    supportedEngineLayouts: ['EV_DUAL', 'EV_QUAD'],
    supportedDriveTypes: ['awd'],
    manufacturingCostBOM: 12800,
    keyAdvantages: ['Ultra-low center of gravity', 'Maximum cabin passenger flat floor', 'Instant dual-motor torque vectoring'],
    materialGradeDefault: 'titanium',
    hardpoints: createStandardHardpoints(3020, 1705),
  },

  // ──────────────────────────────────────────────────────────────────────────
  // 5. WAGON / AVANT CHASSIS FAMILY (01 to 05)
  // ──────────────────────────────────────────────────────────────────────────
  {
    id: 'WAGON_CHASSIS_01',
    bodyType: 'wagon',
    chassisIndex: 1,
    name: 'Executive Long-Roof Monocoque',
    architectureClass: 'aluminum_monocoque',
    tagline: 'Extended roof rails with reinforced D-pillar luggage ring',
    description: 'Long-roof executive estate platform combining high-speed autobahn touring with massive cargo volume.',
    baseMassKg: 410,
    torsionalRigidityKNmPerDeg: 33.0,
    wheelbaseMm: 2900,
    trackWidthFrontMm: 1610,
    trackWidthRearMm: 1620,
    rideHeightMm: 130,
    groundClearanceMm: 145,
    engineBayVolumeLitres: 290,
    supportedEngineLayouts: ['I4', 'V6', 'V8'],
    supportedDriveTypes: ['rwd', 'awd'],
    manufacturingCostBOM: 6700,
    keyAdvantages: ['Huge cargo utility', 'Low drag coefficient', 'Sedan-like cornering dynamics'],
    materialGradeDefault: 'forged',
    hardpoints: createStandardHardpoints(2900, 1615),
  },
  {
    id: 'WAGON_CHASSIS_02',
    bodyType: 'wagon',
    chassisIndex: 2,
    name: 'All-Terrain Lifted Estate Frame',
    architectureClass: 'steel_unibody',
    tagline: 'Lifted ride height with underbody skid plates and plastic cladding anchors',
    description: 'All-weather adventure wagon chassis designed for unpaved mountain roads and snowy alpine conditions.',
    baseMassKg: 435,
    torsionalRigidityKNmPerDeg: 31.5,
    wheelbaseMm: 2880,
    trackWidthFrontMm: 1630,
    trackWidthRearMm: 1630,
    rideHeightMm: 165,
    groundClearanceMm: 185,
    engineBayVolumeLitres: 280,
    supportedEngineLayouts: ['I4', 'V6', 'BOXER_6'],
    supportedDriveTypes: ['awd'],
    manufacturingCostBOM: 5200,
    keyAdvantages: ['Underbody rock protection', 'Snow & mud ground clearance', 'Durable steel unibody'],
    materialGradeDefault: 'cast',
    hardpoints: createStandardHardpoints(2880, 1630),
  },
  {
    id: 'WAGON_CHASSIS_03',
    bodyType: 'wagon',
    chassisIndex: 3,
    name: 'High-Speed Autobahn GT Chassis',
    architectureClass: 'hydroformed_spaceframe',
    tagline: 'Reinforced rear damper crossbar for 300+ km/h loaded stability',
    description: 'V8 twin-turbo sport wagon platform built to cruise effortlessly at 300 km/h with a full family luggage payload.',
    baseMassKg: 440,
    torsionalRigidityKNmPerDeg: 37.0,
    wheelbaseMm: 2920,
    trackWidthFrontMm: 1640,
    trackWidthRearMm: 1650,
    rideHeightMm: 115,
    groundClearanceMm: 130,
    engineBayVolumeLitres: 330,
    supportedEngineLayouts: ['V6', 'V8', 'V10'],
    supportedDriveTypes: ['awd'],
    manufacturingCostBOM: 8400,
    keyAdvantages: ['300+ km/h aerodynamic stability', 'Rear axle steer compatibility', 'Stiff anti-squat rear geometry'],
    materialGradeDefault: 'forged',
    hardpoints: createStandardHardpoints(2920, 1645),
  },
  {
    id: 'WAGON_CHASSIS_04',
    bodyType: 'wagon',
    chassisIndex: 4,
    name: 'Reinforced Cargo Utility Unibody',
    architectureClass: 'steel_unibody',
    tagline: 'High-payload rear floor stamping with heavy-duty helper spring mounts',
    description: 'Economical commercial and family estate platform with flat-folding floor and wide rear opening aperture.',
    baseMassKg: 395,
    torsionalRigidityKNmPerDeg: 28.5,
    wheelbaseMm: 2820,
    trackWidthFrontMm: 1580,
    trackWidthRearMm: 1590,
    rideHeightMm: 135,
    groundClearanceMm: 150,
    engineBayVolumeLitres: 250,
    supportedEngineLayouts: ['I4', 'V6'],
    supportedDriveTypes: ['fwd', 'awd'],
    manufacturingCostBOM: 4300,
    keyAdvantages: ['Lowest wagon BOM cost', '800 kg cargo payload capability', 'Flat loading sill'],
    materialGradeDefault: 'cast',
    hardpoints: createStandardHardpoints(2820, 1585),
  },
  {
    id: 'WAGON_CHASSIS_05',
    bodyType: 'wagon',
    chassisIndex: 5,
    name: 'Carbon-Core Super-Wagon Monocell',
    architectureClass: 'carbon_composite_monocell',
    tagline: 'Carbon fiber roof frame and luggage tub with ceramic brake clearances',
    description: 'The ultimate performance wagon combining lightweight carbon technology with 700+ hp V8 powertrain capacity.',
    baseMassKg: 310,
    torsionalRigidityKNmPerDeg: 49.0,
    wheelbaseMm: 2910,
    trackWidthFrontMm: 1670,
    trackWidthRearMm: 1680,
    rideHeightMm: 100,
    groundClearanceMm: 110,
    engineBayVolumeLitres: 340,
    supportedEngineLayouts: ['V8', 'V10', 'V12'],
    supportedDriveTypes: ['awd'],
    manufacturingCostBOM: 19500,
    keyAdvantages: ['49 kNm/deg torsional rigidity', '310 kg ultra-light estate mass', 'Supercar performance envelope'],
    materialGradeDefault: 'titanium',
    hardpoints: createStandardHardpoints(2910, 1675),
  },

  // ──────────────────────────────────────────────────────────────────────────
  // 6. CONVERTIBLE / ROADSTER CHASSIS FAMILY (01 to 05)
  // ──────────────────────────────────────────────────────────────────────────
  {
    id: 'CONVERTIBLE_CHASSIS_01',
    bodyType: 'convertible',
    chassisIndex: 1,
    name: 'Roadster X-Frame Aluminum Tub',
    architectureClass: 'aluminum_monocoque',
    tagline: 'Extruded aluminum side sills with underfloor diagonal shear X-brace',
    description: 'Engineered specifically for roofless open-air motoring with reinforced windshield header and underbody diagonal truss.',
    baseMassKg: 345,
    torsionalRigidityKNmPerDeg: 27.5,
    wheelbaseMm: 2540,
    trackWidthFrontMm: 1580,
    trackWidthRearMm: 1590,
    rideHeightMm: 115,
    groundClearanceMm: 125,
    engineBayVolumeLitres: 240,
    supportedEngineLayouts: ['I4', 'V6', 'BOXER_4'],
    supportedDriveTypes: ['rwd'],
    manufacturingCostBOM: 6200,
    keyAdvantages: ['Zero scuttle shake over bumps', 'Lightweight 345 kg open-top platform', 'Integral roll hoop anchors'],
    materialGradeDefault: 'forged',
    hardpoints: createStandardHardpoints(2540, 1585),
  },
  {
    id: 'CONVERTIBLE_CHASSIS_02',
    bodyType: 'convertible',
    chassisIndex: 2,
    name: '2+2 Cabriolet Reinforced Sill Platform',
    architectureClass: 'steel_unibody',
    tagline: 'Ultra-high-strength steel door sills with motorized soft-top stowage well',
    description: 'Full four-seater cabriolet chassis with reinforced A-pillars capable of supporting 3.5x vehicle weight in rollover tests.',
    baseMassKg: 420,
    torsionalRigidityKNmPerDeg: 25.0,
    wheelbaseMm: 2750,
    trackWidthFrontMm: 1610,
    trackWidthRearMm: 1620,
    rideHeightMm: 125,
    groundClearanceMm: 135,
    engineBayVolumeLitres: 280,
    supportedEngineLayouts: ['I4', 'V6', 'V8'],
    supportedDriveTypes: ['rwd', 'awd'],
    manufacturingCostBOM: 5600,
    keyAdvantages: ['Full 4-passenger cabin space', 'Active pyrotechnic roll bar pop-up modules', 'High impact side-sill crash protection'],
    materialGradeDefault: 'cast',
    hardpoints: createStandardHardpoints(2750, 1615),
  },
  {
    id: 'CONVERTIBLE_CHASSIS_03',
    bodyType: 'convertible',
    chassisIndex: 3,
    name: 'Targa Structural Backbone Frame',
    architectureClass: 'hydroformed_spaceframe',
    tagline: 'Fixed stainless steel B-pillar roll hoop with removable roof panel channel',
    description: 'Combines open-top sunshine with coupe-like rigidity through a structural stainless steel Targa safety hoop.',
    baseMassKg: 365,
    torsionalRigidityKNmPerDeg: 33.0,
    wheelbaseMm: 2580,
    trackWidthFrontMm: 1620,
    trackWidthRearMm: 1640,
    rideHeightMm: 110,
    groundClearanceMm: 120,
    engineBayVolumeLitres: 260,
    supportedEngineLayouts: ['V6', 'BOXER_6', 'V8'],
    supportedDriveTypes: ['rwd', 'awd'],
    manufacturingCostBOM: 7800,
    keyAdvantages: ['Near-coupe 33 kNm/deg stiffness', 'Iconic structural roll hoop aesthetic', 'Removable roof stowage in front bay'],
    materialGradeDefault: 'forged',
    hardpoints: createStandardHardpoints(2580, 1630),
  },
  {
    id: 'CONVERTIBLE_CHASSIS_04',
    bodyType: 'convertible',
    chassisIndex: 4,
    name: 'Retractable Hardtop Chassis',
    architectureClass: 'hybrid_cast_extruded',
    tagline: 'Electro-hydraulic hardtop kinematics cradle with rear luggage shelf split',
    description: 'Engineered with precision hinge nodes for a 3-piece folding metal roof providing total coupe refinement when closed.',
    baseMassKg: 430,
    torsionalRigidityKNmPerDeg: 28.0,
    wheelbaseMm: 2680,
    trackWidthFrontMm: 1600,
    trackWidthRearMm: 1610,
    rideHeightMm: 120,
    groundClearanceMm: 130,
    engineBayVolumeLitres: 270,
    supportedEngineLayouts: ['I4', 'V6', 'V8'],
    supportedDriveTypes: ['rwd'],
    manufacturingCostBOM: 8100,
    keyAdvantages: ['True all-season coupe insulation', 'Ultra-quiet acoustic cabin', 'Automatic 15-second roof mechanism mounts'],
    materialGradeDefault: 'billet',
    hardpoints: createStandardHardpoints(2680, 1605),
  },
  {
    id: 'CONVERTIBLE_CHASSIS_05',
    bodyType: 'convertible',
    chassisIndex: 5,
    name: 'Spyder Carbon Monocell Tub',
    architectureClass: 'carbon_composite_monocell',
    tagline: 'Full carbon tub requiring zero added underfloor braces to maintain 46 kNm/deg',
    description: 'Pure supercar speedster tub crafted from Toray high-modulus carbon fiber with twin aerodynamic rear fairing cowls.',
    baseMassKg: 245,
    torsionalRigidityKNmPerDeg: 46.0,
    wheelbaseMm: 2620,
    trackWidthFrontMm: 1670,
    trackWidthRearMm: 1680,
    rideHeightMm: 90,
    groundClearanceMm: 100,
    engineBayVolumeLitres: 310,
    supportedEngineLayouts: ['V8', 'V10', 'V12'],
    supportedDriveTypes: ['rwd', 'awd'],
    manufacturingCostBOM: 22000,
    keyAdvantages: ['Ultra-light 245 kg mass', 'No weight penalty vs coupe', 'Aerodynamic speedster headrest streamliners'],
    materialGradeDefault: 'titanium',
    hardpoints: createStandardHardpoints(2620, 1675),
  },

  // ──────────────────────────────────────────────────────────────────────────
  // 7. SPORTS CAR CHASSIS FAMILY (01 to 05)
  // ──────────────────────────────────────────────────────────────────────────
  {
    id: 'SPORTS_CAR_CHASSIS_01',
    bodyType: 'sports_car',
    chassisIndex: 1,
    name: 'Classic Front-Mid RWD Backbone',
    architectureClass: 'aluminum_monocoque',
    tagline: 'Front-midship engine placement completely behind the front axle center line',
    description: 'Achieves pure mechanical balance with engine pushed behind the front axle and driver positioned near rear pivot.',
    baseMassKg: 315,
    torsionalRigidityKNmPerDeg: 35.0,
    wheelbaseMm: 2480,
    trackWidthFrontMm: 1610,
    trackWidthRearMm: 1620,
    rideHeightMm: 110,
    groundClearanceMm: 120,
    engineBayVolumeLitres: 230,
    supportedEngineLayouts: ['I4', 'V6', 'BOXER_4'],
    supportedDriveTypes: ['rwd'],
    manufacturingCostBOM: 6100,
    keyAdvantages: ['50:50 weight balance', 'Pure mechanical steering feel', 'Low polar yaw moment'],
    materialGradeDefault: 'forged',
    hardpoints: createStandardHardpoints(2480, 1615),
  },
  {
    id: 'SPORTS_CAR_CHASSIS_02',
    bodyType: 'sports_car',
    chassisIndex: 2,
    name: 'Extruded Bonded Aluminum Tub',
    architectureClass: 'hybrid_cast_extruded',
    tagline: 'Aerospace epoxy-bonded extruded aluminum tub inspired by British sportscars',
    description: 'Featherweight extruded tub joined with structural aviation adhesive and rivets for unparalleled power-to-weight agility.',
    baseMassKg: 240,
    torsionalRigidityKNmPerDeg: 32.0,
    wheelbaseMm: 2420,
    trackWidthFrontMm: 1580,
    trackWidthRearMm: 1600,
    rideHeightMm: 100,
    groundClearanceMm: 110,
    engineBayVolumeLitres: 210,
    supportedEngineLayouts: ['I4', 'V6'],
    supportedDriveTypes: ['rwd'],
    manufacturingCostBOM: 7400,
    keyAdvantages: ['Under 250 kg chassis mass', 'Raw telepathic road feedback', 'Corrosion-proof bonded aluminum'],
    materialGradeDefault: 'forged',
    hardpoints: createStandardHardpoints(2420, 1590),
  },
  {
    id: 'SPORTS_CAR_CHASSIS_03',
    bodyType: 'sports_car',
    chassisIndex: 3,
    name: 'Mid-Engine Boxer Platform',
    architectureClass: 'aluminum_monocoque',
    tagline: 'Flat-engine mid-mounted architecture with ultra-low crankshaft center of mass',
    description: 'Central engine bay tailored specifically for horizontally opposed flat-4 and flat-6 engines with central fuel cell.',
    baseMassKg: 295,
    torsionalRigidityKNmPerDeg: 39.0,
    wheelbaseMm: 2490,
    trackWidthFrontMm: 1630,
    trackWidthRearMm: 1640,
    rideHeightMm: 105,
    groundClearanceMm: 115,
    engineBayVolumeLitres: 250,
    supportedEngineLayouts: ['BOXER_4', 'BOXER_6'],
    supportedDriveTypes: ['rwd', 'awd'],
    manufacturingCostBOM: 8800,
    keyAdvantages: ['Extremely low center of gravity (360mm)', 'Zero body roll in chicanes', 'Front and rear dual luggage trunks'],
    materialGradeDefault: 'billet',
    hardpoints: createStandardHardpoints(2490, 1635),
  },
  {
    id: 'SPORTS_CAR_CHASSIS_04',
    bodyType: 'sports_car',
    chassisIndex: 4,
    name: 'Clubsport Tubular Spaceframe',
    architectureClass: 'tubular_spaceframe',
    tagline: 'Multi-tubular triangulated frame with quick-access suspension adjusters',
    description: 'Grassroots weekend racer spaceframe offering effortless body panel swaps and infinite coilover tuning positions.',
    baseMassKg: 280,
    torsionalRigidityKNmPerDeg: 36.5,
    wheelbaseMm: 2450,
    trackWidthFrontMm: 1600,
    trackWidthRearMm: 1610,
    rideHeightMm: 95,
    groundClearanceMm: 105,
    engineBayVolumeLitres: 240,
    supportedEngineLayouts: ['I4', 'V6', 'V8'],
    supportedDriveTypes: ['rwd'],
    manufacturingCostBOM: 5800,
    keyAdvantages: ['Easy trackside repairs', 'Lightweight 280 kg chassis', 'Integrated fire suppression nozzle mounts'],
    materialGradeDefault: 'cast',
    hardpoints: createStandardHardpoints(2450, 1605),
  },
  {
    id: 'SPORTS_CAR_CHASSIS_05',
    bodyType: 'sports_car',
    chassisIndex: 5,
    name: 'Time-Attack Carbon Tub',
    architectureClass: 'carbon_composite_monocell',
    tagline: 'Full carbon passenger tub with integrated chassis aero tunnels',
    description: 'Unlimited time-attack carbon tub designed to generate 1,200 kg of aerodynamic downforce at 240 km/h without chassis flex.',
    baseMassKg: 215,
    torsionalRigidityKNmPerDeg: 56.0,
    wheelbaseMm: 2510,
    trackWidthFrontMm: 1680,
    trackWidthRearMm: 1690,
    rideHeightMm: 75,
    groundClearanceMm: 80,
    engineBayVolumeLitres: 280,
    supportedEngineLayouts: ['I4', 'V6', 'BOXER_6', 'EV_DUAL'],
    supportedDriveTypes: ['awd'],
    manufacturingCostBOM: 24000,
    keyAdvantages: ['56 kNm/deg extreme stiffness', '215 kg featherweight mass', 'Massive floor venturi tunnels'],
    materialGradeDefault: 'titanium',
    hardpoints: createStandardHardpoints(2510, 1685),
  },

  // ──────────────────────────────────────────────────────────────────────────
  // 8. SUPERCAR CHASSIS FAMILY (01 to 05)
  // ──────────────────────────────────────────────────────────────────────────
  {
    id: 'SUPERCAR_CHASSIS_01',
    bodyType: 'supercar',
    chassisIndex: 1,
    name: 'Carbon Tub with Aluminum Subframes',
    architectureClass: 'carbon_composite_monocell',
    tagline: 'Central high-tensile carbon cockpit tub with modular bolt-on alloy subframes',
    description: 'The premier supercar standard: ultra-rigid carbon occupant survival cell with serviceable aluminum crash structures.',
    baseMassKg: 275,
    torsionalRigidityKNmPerDeg: 50.0,
    wheelbaseMm: 2710,
    trackWidthFrontMm: 1710,
    trackWidthRearMm: 1730,
    rideHeightMm: 95,
    groundClearanceMm: 105,
    engineBayVolumeLitres: 340,
    supportedEngineLayouts: ['V8', 'V10', 'V12'],
    supportedDriveTypes: ['rwd', 'awd'],
    manufacturingCostBOM: 21500,
    keyAdvantages: ['50 kNm/deg torsional rigidity', 'Replaceable front/rear subframes for crash economy', 'Dihedral door hinge nodes'],
    materialGradeDefault: 'titanium',
    hardpoints: createStandardHardpoints(2710, 1720),
  },
  {
    id: 'SUPERCAR_CHASSIS_02',
    bodyType: 'supercar',
    chassisIndex: 2,
    name: 'Longitudinal V12 Bay Architecture',
    architectureClass: 'aluminum_monocoque',
    tagline: 'Elongated mid-engine bay built specifically for massive 6.5L naturally aspirated V12s',
    description: 'Engineered with long engine mounts and dual side radiator duct tunnels to cool screaming 9,000 RPM V12 engines.',
    baseMassKg: 330,
    torsionalRigidityKNmPerDeg: 42.0,
    wheelbaseMm: 2780,
    trackWidthFrontMm: 1730,
    trackWidthRearMm: 1750,
    rideHeightMm: 100,
    groundClearanceMm: 110,
    engineBayVolumeLitres: 410,
    supportedEngineLayouts: ['V10', 'V12'],
    supportedDriveTypes: ['rwd', 'awd'],
    manufacturingCostBOM: 16000,
    keyAdvantages: ['Accommodates full 12-cylinder powertrains', 'Massive thermal cooling tunnels', 'Exotic exhaust acoustic tunnel'],
    materialGradeDefault: 'billet',
    hardpoints: createStandardHardpoints(2780, 1740),
  },
  {
    id: 'SUPERCAR_CHASSIS_03',
    bodyType: 'supercar',
    chassisIndex: 3,
    name: 'Dihedral Door Superleggera Tub',
    architectureClass: 'carbon_composite_monocell',
    tagline: 'Forged carbon composite tub with integrated upward-swinging butterfly door mounts',
    description: 'Forged carbon sheet molding compound tub with integrated A-pillar door hinges and low side sill entry step.',
    baseMassKg: 255,
    torsionalRigidityKNmPerDeg: 55.0,
    wheelbaseMm: 2680,
    trackWidthFrontMm: 1720,
    trackWidthRearMm: 1740,
    rideHeightMm: 90,
    groundClearanceMm: 100,
    engineBayVolumeLitres: 350,
    supportedEngineLayouts: ['V6', 'V8'],
    supportedDriveTypes: ['rwd'],
    manufacturingCostBOM: 25000,
    keyAdvantages: ['Breathtaking butterfly door kinematics', '255 kg ultra-lightweight carbon tub', 'Exceptional driver ergonomics'],
    materialGradeDefault: 'titanium',
    hardpoints: createStandardHardpoints(2680, 1730),
  },
  {
    id: 'SUPERCAR_CHASSIS_04',
    bodyType: 'supercar',
    chassisIndex: 4,
    name: 'Active Aero Hardpoint Platform',
    architectureClass: 'hybrid_cast_extruded',
    tagline: 'Chassis with integrated hydraulic actuators for active front flaps and rear airbrake',
    description: 'Engineered with reinforced structural anchor points for active aero flap actuators and high-speed braking deployment.',
    baseMassKg: 310,
    torsionalRigidityKNmPerDeg: 44.0,
    wheelbaseMm: 2730,
    trackWidthFrontMm: 1710,
    trackWidthRearMm: 1720,
    rideHeightMm: 95,
    groundClearanceMm: 105,
    engineBayVolumeLitres: 360,
    supportedEngineLayouts: ['V8', 'V10'],
    supportedDriveTypes: ['awd'],
    manufacturingCostBOM: 18500,
    keyAdvantages: ['Supports 800 kg active downforce load', 'Active front underbody flap channels', 'High-speed airbrake stability'],
    materialGradeDefault: 'billet',
    hardpoints: createStandardHardpoints(2730, 1715),
  },
  {
    id: 'SUPERCAR_CHASSIS_05',
    bodyType: 'supercar',
    chassisIndex: 5,
    name: 'GTE Homologation Carbon Chassis',
    architectureClass: 'f1_prepreg_monocoque',
    tagline: 'Le Mans 24h GTE endurance racing spec with quick-change carbon front nose clip',
    description: 'Designed for 24-hour endurance punishment with titanium suspension pickup points and integral fuel cell armor.',
    baseMassKg: 240,
    torsionalRigidityKNmPerDeg: 62.0,
    wheelbaseMm: 2750,
    trackWidthFrontMm: 1760,
    trackWidthRearMm: 1770,
    rideHeightMm: 70,
    groundClearanceMm: 75,
    engineBayVolumeLitres: 370,
    supportedEngineLayouts: ['V8', 'V10', 'V12'],
    supportedDriveTypes: ['rwd'],
    manufacturingCostBOM: 32000,
    keyAdvantages: ['62 kNm/deg endurance racing rigidity', 'Quick-change body panel fasteners', 'FIA rollcage safety cell'],
    materialGradeDefault: 'titanium',
    hardpoints: createStandardHardpoints(2750, 1765),
  },

  // ──────────────────────────────────────────────────────────────────────────
  // 9. HYPERCAR CHASSIS FAMILY (01 to 05)
  // ──────────────────────────────────────────────────────────────────────────
  {
    id: 'HYPERCAR_CHASSIS_01',
    bodyType: 'hypercar',
    chassisIndex: 1,
    name: 'Full Pre-Preg Carbon Monocell',
    architectureClass: 'f1_prepreg_monocoque',
    tagline: 'Autoclave cured Toray T1100 carbon fiber tub with integral seat shells and roof canopy',
    description: 'Highest echelon of composite engineering: full carbon monocell where seats, roof canopy, and dash form a single rigid piece.',
    baseMassKg: 195,
    torsionalRigidityKNmPerDeg: 68.0,
    wheelbaseMm: 2780,
    trackWidthFrontMm: 1760,
    trackWidthRearMm: 1780,
    rideHeightMm: 80,
    groundClearanceMm: 85,
    engineBayVolumeLitres: 360,
    supportedEngineLayouts: ['V8', 'V12', 'EV_QUAD'],
    supportedDriveTypes: ['rwd', 'awd'],
    manufacturingCostBOM: 45000,
    keyAdvantages: ['68 kNm/deg aerospace stiffness', 'Sub-200 kg chassis mass', 'Seamless one-piece carbon monocell'],
    materialGradeDefault: 'titanium',
    hardpoints: createStandardHardpoints(2780, 1770),
  },
  {
    id: 'HYPERCAR_CHASSIS_02',
    bodyType: 'hypercar',
    chassisIndex: 2,
    name: '800V Hybrid Backbone Monocoque',
    architectureClass: 'f1_prepreg_monocoque',
    tagline: 'High-voltage cylindrical cell battery array housed directly inside structural carbon tunnel',
    description: 'Central carbon tunnel serves dual role as main structural torsion beam and thermally managed 800V battery enclosure.',
    baseMassKg: 235,
    torsionalRigidityKNmPerDeg: 65.0,
    wheelbaseMm: 2820,
    trackWidthFrontMm: 1770,
    trackWidthRearMm: 1790,
    rideHeightMm: 85,
    groundClearanceMm: 90,
    engineBayVolumeLitres: 330,
    supportedEngineLayouts: ['V6', 'V8', 'EV_DUAL', 'EV_QUAD'],
    supportedDriveTypes: ['awd'],
    manufacturingCostBOM: 52000,
    keyAdvantages: ['Integrated 800V structural battery backbone', '1,000+ kW electrical discharge capability', 'Low center of gravity'],
    materialGradeDefault: 'titanium',
    hardpoints: createStandardHardpoints(2820, 1780),
  },
  {
    id: 'HYPERCAR_CHASSIS_03',
    bodyType: 'hypercar',
    chassisIndex: 3,
    name: 'LMP1 Inboard Pushrod Architecture',
    architectureClass: 'f1_prepreg_monocoque',
    tagline: 'Inboard horizontal Multimatic spool-valve dampers with heave spring bellcranks',
    description: 'Le Mans Prototype prototype suspension architecture packaging all dampers horizontally inside the carbon nose for pure aerodynamic flow.',
    baseMassKg: 205,
    torsionalRigidityKNmPerDeg: 72.0,
    wheelbaseMm: 2790,
    trackWidthFrontMm: 1780,
    trackWidthRearMm: 1800,
    rideHeightMm: 65,
    groundClearanceMm: 70,
    engineBayVolumeLitres: 340,
    supportedEngineLayouts: ['V6', 'V8'],
    supportedDriveTypes: ['awd'],
    manufacturingCostBOM: 58000,
    keyAdvantages: ['72 kNm/deg ultimate stiffness', 'Zero turbulent air through wheelarches', 'Third heave damper pitch control'],
    materialGradeDefault: 'titanium',
    hardpoints: createStandardHardpoints(2790, 1790),
  },
  {
    id: 'HYPERCAR_CHASSIS_04',
    bodyType: 'hypercar',
    chassisIndex: 4,
    name: 'Ground-Effect Venturi Tunnel Platform',
    architectureClass: 'f1_prepreg_monocoque',
    tagline: 'Twin underfloor venturi tunnels generating 2,000 kg suction downforce without wing drag',
    description: 'Formula 1 ground-effect chassis with shaped floor tunnels running from front axle to massive rear diffuser.',
    baseMassKg: 220,
    torsionalRigidityKNmPerDeg: 70.0,
    wheelbaseMm: 2840,
    trackWidthFrontMm: 1790,
    trackWidthRearMm: 1810,
    rideHeightMm: 60,
    groundClearanceMm: 65,
    engineBayVolumeLitres: 320,
    supportedEngineLayouts: ['V8', 'V12', 'EV_QUAD'],
    supportedDriveTypes: ['rwd', 'awd'],
    manufacturingCostBOM: 62000,
    keyAdvantages: ['2,000 kg ground-effect downforce', '3.5G lateral cornering potential', 'Minimal straight-line aerodynamic drag'],
    materialGradeDefault: 'titanium',
    hardpoints: createStandardHardpoints(2840, 1800),
  },
  {
    id: 'HYPERCAR_CHASSIS_05',
    bodyType: 'hypercar',
    chassisIndex: 5,
    name: 'F1 V10 Stressed Powertrain Tub',
    architectureClass: 'f1_prepreg_monocoque',
    tagline: 'High-revving V10 engine acts as a fully stressed structural member bolted to carbon tub',
    description: 'Pure Formula 1 engineering where the engine block and gearbox housing form the entire rear structural chassis.',
    baseMassKg: 180,
    torsionalRigidityKNmPerDeg: 78.0,
    wheelbaseMm: 2760,
    trackWidthFrontMm: 1800,
    trackWidthRearMm: 1820,
    rideHeightMm: 55,
    groundClearanceMm: 60,
    engineBayVolumeLitres: 310,
    supportedEngineLayouts: ['V8', 'V10', 'V12'],
    supportedDriveTypes: ['rwd'],
    manufacturingCostBOM: 75000,
    keyAdvantages: ['78 kNm/deg record-breaking rigidity', '180 kg lightest chassis in existence', 'Powertrain eliminates rear subframe'],
    materialGradeDefault: 'titanium',
    hardpoints: createStandardHardpoints(2760, 1810),
  },

  // ──────────────────────────────────────────────────────────────────────────
  // 10. PICKUP TRUCK CHASSIS FAMILY (01 to 05)
  // ──────────────────────────────────────────────────────────────────────────
  {
    id: 'PICKUP_CHASSIS_01',
    bodyType: 'pickup',
    chassisIndex: 1,
    name: 'Hydroformed Heavy-Duty Steel Ladder',
    architectureClass: 'heavy_duty_ladder_frame',
    tagline: 'Fully boxed steel frame with high-capacity leaf spring perches and Class-V tow hitch',
    description: 'Traditional heavy-duty pickup platform built for maximum payload hauling, trailer towing, and durability.',
    baseMassKg: 620,
    torsionalRigidityKNmPerDeg: 22.0,
    wheelbaseMm: 3400,
    trackWidthFrontMm: 1740,
    trackWidthRearMm: 1740,
    rideHeightMm: 230,
    groundClearanceMm: 260,
    engineBayVolumeLitres: 420,
    supportedEngineLayouts: ['I4', 'V6', 'V8'],
    supportedDriveTypes: ['rwd', 'awd'],
    manufacturingCostBOM: 4900,
    keyAdvantages: ['5,000 kg towing capacity', 'High-strength steel frame impact resilience', 'Isolated cabin body mounts'],
    materialGradeDefault: 'cast',
    hardpoints: createStandardHardpoints(3400, 1740),
  },
  {
    id: 'PICKUP_CHASSIS_02',
    bodyType: 'pickup',
    chassisIndex: 2,
    name: 'Desert Raptor Long-Travel Frame',
    architectureClass: 'tubular_spaceframe',
    tagline: 'Reinforced frame with external bypass shock mounts and high-speed jump crossmembers',
    description: 'High-speed off-road performance pickup chassis engineered for high-altitude jumps and whoops in desert terrain.',
    baseMassKg: 560,
    torsionalRigidityKNmPerDeg: 34.0,
    wheelbaseMm: 3350,
    trackWidthFrontMm: 1820,
    trackWidthRearMm: 1820,
    rideHeightMm: 270,
    groundClearanceMm: 300,
    engineBayVolumeLitres: 400,
    supportedEngineLayouts: ['V6', 'V8'],
    supportedDriveTypes: ['awd'],
    manufacturingCostBOM: 12500,
    keyAdvantages: ['Wide track desert stability', '600mm suspension travel clearance', 'Reinforced frame jump gussets'],
    materialGradeDefault: 'billet',
    hardpoints: createStandardHardpoints(3350, 1820),
  },
  {
    id: 'PICKUP_CHASSIS_03',
    bodyType: 'pickup',
    chassisIndex: 3,
    name: 'Unibody Lifestyle Sport Truck',
    architectureClass: 'steel_unibody',
    tagline: 'Rigid unibody with integrated composite cargo bed for car-like ride and handling',
    description: 'Modern lifestyle unibody pickup platform offering crossover comfort, nimble handling, and flexible cargo bed.',
    baseMassKg: 440,
    torsionalRigidityKNmPerDeg: 32.0,
    wheelbaseMm: 3100,
    trackWidthFrontMm: 1670,
    trackWidthRearMm: 1670,
    rideHeightMm: 175,
    groundClearanceMm: 195,
    engineBayVolumeLitres: 260,
    supportedEngineLayouts: ['I4', 'V6'],
    supportedDriveTypes: ['fwd', 'awd'],
    manufacturingCostBOM: 4600,
    keyAdvantages: ['Car-like highway handling', 'Lightweight 440 kg chassis', 'Under-bed weatherproof storage trunk'],
    materialGradeDefault: 'cast',
    hardpoints: createStandardHardpoints(3100, 1670),
  },
  {
    id: 'PICKUP_CHASSIS_04',
    bodyType: 'pickup',
    chassisIndex: 4,
    name: 'Commercial Dual-Rear-Wheel (Dually)',
    architectureClass: 'heavy_duty_ladder_frame',
    tagline: 'Wide-track rear dual wheel carrier with 8-lug hubs and reinforced leaf spring pack',
    description: 'Commercial hauler platform with dual rear wheels for supreme fifth-wheel gooseneck trailer stability.',
    baseMassKg: 690,
    torsionalRigidityKNmPerDeg: 26.0,
    wheelbaseMm: 3650,
    trackWidthFrontMm: 1750,
    trackWidthRearMm: 1920,
    rideHeightMm: 240,
    groundClearanceMm: 265,
    engineBayVolumeLitres: 450,
    supportedEngineLayouts: ['V8'],
    supportedDriveTypes: ['rwd', 'awd'],
    manufacturingCostBOM: 6800,
    keyAdvantages: ['12,000 kg gooseneck towing rating', 'Dual-wheel rear axle stability', 'Commercial duty frame rails'],
    materialGradeDefault: 'cast',
    hardpoints: createStandardHardpoints(3650, 1835),
  },
  {
    id: 'PICKUP_CHASSIS_05',
    bodyType: 'pickup',
    chassisIndex: 5,
    name: 'Electric Skateboard Truck Platform',
    architectureClass: 'skateboard_ev_platform',
    tagline: 'High-voltage 200 kWh structural battery pack with 4 independent hub motors and crab walk',
    description: 'Revolutionary all-electric pickup platform with quad-motor torque vectoring, 4-wheel steering crab walk, and giant frunk.',
    baseMassKg: 580,
    torsionalRigidityKNmPerDeg: 46.0,
    wheelbaseMm: 3450,
    trackWidthFrontMm: 1760,
    trackWidthRearMm: 1760,
    rideHeightMm: 220,
    groundClearanceMm: 250,
    engineBayVolumeLitres: 350, // Massive Frunk
    supportedEngineLayouts: ['EV_DUAL', 'EV_QUAD'],
    supportedDriveTypes: ['awd'],
    manufacturingCostBOM: 16500,
    keyAdvantages: ['Quad-motor tank turn & crab walk', 'Huge 350L power frunk', 'Instant 1,400 Nm electric torque'],
    materialGradeDefault: 'titanium',
    hardpoints: createStandardHardpoints(3450, 1760),
  },
];

/** Index mapping chassis ID to its definition */
export const CHASSIS_50_MAP: Record<string, Chassis50Definition> = CHASSIS_50_REGISTRY.reduce(
  (acc, def) => {
    acc[def.id] = def;
    return acc;
  },
  {} as Record<string, Chassis50Definition>
);

/** Master catalog of all 50 chassis architecture manifests */
export const CHASSIS_50_CATALOG: Chassis50Definition[] = CHASSIS_50_REGISTRY;

/** Helper to retrieve the 5 chassis for a given body type */
export function getChassisForBodyType(bodyType: VehicleBodyType): Chassis50Definition[] {
  return CHASSIS_50_REGISTRY.filter((c) => c.bodyType === bodyType);
}

