// ===================================================================
// EXTERIOR 3D GLB ASSET MANIFEST & ATTACHMENT REGISTRY
// ===================================================================
// Declares asset paths, 3D metric coordinate offsets, exploded vectors,
// and paint zone material mapping for all 40+ exterior components.
// ===================================================================

import type { ExteriorComponent3DType, ExteriorManifestRef } from "../types";

export const EXTERIOR_3D_MANIFEST: Record<ExteriorComponent3DType, ExteriorManifestRef> = {
  chassis_frame: {
    componentType: "chassis_frame",
    assetPath: "/models/exterior/chassis_frame.glb",
    defaultTransform: {
      position: { x: 0, y: 0, z: 0 },
      rotation: { x: 0, y: 0, z: 0 },
      scale: { x: 1, y: 1, z: 1 },
    },
    explodedVector: { x: 0, y: -0.8, z: 0 },
    massKg: 320,
    paintZone: "UNPAINTED_CARBON",
    submeshNames: {
      primaryBody: ["Chassis_Main_Tub", "Firewall_Cowl"],
      fasteners: ["Subframe_Mount_Bolts"],
    },
  },
  front_subframe: {
    componentType: "front_subframe",
    assetPath: "/models/exterior/front_subframe.glb",
    defaultTransform: {
      position: { x: 1.35, y: 0.15, z: 0 },
      rotation: { x: 0, y: 0, z: 0 },
      scale: { x: 1, y: 1, z: 1 },
    },
    explodedVector: { x: 0.8, y: -0.3, z: 0 },
    massKg: 42,
    paintZone: "UNPAINTED_CARBON",
  },
  rear_subframe: {
    componentType: "rear_subframe",
    assetPath: "/models/exterior/rear_subframe.glb",
    defaultTransform: {
      position: { x: -1.35, y: 0.15, z: 0 },
      rotation: { x: 0, y: 0, z: 0 },
      scale: { x: 1, y: 1, z: 1 },
    },
    explodedVector: { x: -0.8, y: -0.3, z: 0 },
    massKg: 48,
    paintZone: "UNPAINTED_CARBON",
  },
  floor_pan: {
    componentType: "floor_pan",
    assetPath: "/models/exterior/floor_pan.glb",
    defaultTransform: {
      position: { x: 0, y: -0.15, z: 0 },
      rotation: { x: 0, y: 0, z: 0 },
      scale: { x: 1, y: 1, z: 1 },
    },
    explodedVector: { x: 0, y: -0.6, z: 0 },
    massKg: 35,
    paintZone: "UNPAINTED_CARBON",
  },
  firewall_bulkhead: {
    componentType: "firewall_bulkhead",
    assetPath: "/models/exterior/firewall_bulkhead.glb",
    defaultTransform: {
      position: { x: 0.65, y: 0.45, z: 0 },
      rotation: { x: 0, y: 0, z: 0 },
      scale: { x: 1, y: 1, z: 1 },
    },
    explodedVector: { x: 0.4, y: 0.2, z: 0 },
    massKg: 18,
    paintZone: "UNPAINTED_CARBON",
  },
  a_pillar_assembly: {
    componentType: "a_pillar_assembly",
    assetPath: "/models/exterior/a_pillar.glb",
    defaultTransform: {
      position: { x: 0.45, y: 0.85, z: 0 },
      rotation: { x: 0, y: 0, z: 0 },
      scale: { x: 1, y: 1, z: 1 },
    },
    explodedVector: { x: 0.3, y: 0.6, z: 0 },
    massKg: 24,
    paintZone: "BODY_PAINTED",
  },
  b_pillar_assembly: {
    componentType: "b_pillar_assembly",
    assetPath: "/models/exterior/b_pillar.glb",
    defaultTransform: {
      position: { x: 0, y: 0.85, z: 0 },
      rotation: { x: 0, y: 0, z: 0 },
      scale: { x: 1, y: 1, z: 1 },
    },
    explodedVector: { x: 0, y: 0.6, z: 0 },
    massKg: 28,
    paintZone: "BODY_PAINTED",
  },
  c_pillar_assembly: {
    componentType: "c_pillar_assembly",
    assetPath: "/models/exterior/c_pillar.glb",
    defaultTransform: {
      position: { x: -0.65, y: 0.85, z: 0 },
      rotation: { x: 0, y: 0, z: 0 },
      scale: { x: 1, y: 1, z: 1 },
    },
    explodedVector: { x: -0.3, y: 0.6, z: 0 },
    massKg: 26,
    paintZone: "BODY_PAINTED",
  },
  rocker_panels: {
    componentType: "rocker_panels",
    assetPath: "/models/exterior/rocker_panels.glb",
    defaultTransform: {
      position: { x: 0, y: -0.05, z: 0 },
      rotation: { x: 0, y: 0, z: 0 },
      scale: { x: 1, y: 1, z: 1 },
    },
    explodedVector: { x: 0, y: 0, z: 0.6 },
    massKg: 22,
    paintZone: "BODY_PAINTED",
  },
  crash_boxes_front_rear: {
    componentType: "crash_boxes_front_rear",
    assetPath: "/models/exterior/crash_boxes.glb",
    defaultTransform: {
      position: { x: 1.85, y: 0.15, z: 0 },
      rotation: { x: 0, y: 0, z: 0 },
      scale: { x: 1, y: 1, z: 1 },
    },
    explodedVector: { x: 1.0, y: 0, z: 0 },
    massKg: 14,
    paintZone: "UNPAINTED_CARBON",
  },
  roll_cage_safety: {
    componentType: "roll_cage_safety",
    assetPath: "/models/exterior/roll_cage.glb",
    defaultTransform: {
      position: { x: 0, y: 0.75, z: 0 },
      rotation: { x: 0, y: 0, z: 0 },
      scale: { x: 1, y: 1, z: 1 },
    },
    explodedVector: { x: 0, y: 0.8, z: 0 },
    massKg: 38,
    paintZone: "CONTRAST_ROOF",
  },
  suspension_front_assembly: {
    componentType: "suspension_front_assembly",
    assetPath: "/models/exterior/suspension_front.glb",
    defaultTransform: {
      position: { x: 1.35, y: 0.25, z: 0 },
      rotation: { x: 0, y: 0, z: 0 },
      scale: { x: 1, y: 1, z: 1 },
    },
    explodedVector: { x: 0.6, y: -0.2, z: 0.5 },
    massKg: 38,
    paintZone: "CHROME_POLISHED",
  },
  suspension_rear_assembly: {
    componentType: "suspension_rear_assembly",
    assetPath: "/models/exterior/suspension_rear.glb",
    defaultTransform: {
      position: { x: -1.35, y: 0.25, z: 0 },
      rotation: { x: 0, y: 0, z: 0 },
      scale: { x: 1, y: 1, z: 1 },
    },
    explodedVector: { x: -0.6, y: -0.2, z: 0.5 },
    massKg: 42,
    paintZone: "CHROME_POLISHED",
  },
  brake_rotors_calipers: {
    componentType: "brake_rotors_calipers",
    assetPath: "/models/exterior/brakes.glb",
    defaultTransform: {
      position: { x: 0, y: 0.25, z: 0 },
      rotation: { x: 0, y: 0, z: 0 },
      scale: { x: 1, y: 1, z: 1 },
    },
    explodedVector: { x: 0, y: 0, z: 0.8 },
    massKg: 28,
    paintZone: "BRAKE_CALIPER",
  },
  wheels_tires_assembly: {
    componentType: "wheels_tires_assembly",
    assetPath: "/models/exterior/wheels.glb",
    defaultTransform: {
      position: { x: 0, y: 0.25, z: 0 },
      rotation: { x: 0, y: 0, z: 0 },
      scale: { x: 1, y: 1, z: 1 },
    },
    explodedVector: { x: 0, y: 0, z: 1.1 },
    massKg: 76,
    paintZone: "WHEEL_FINISH",
  },
  hood_panel: {
    componentType: "hood_panel",
    assetPath: "/models/exterior/hood_panel.glb",
    defaultTransform: {
      position: { x: 1.1, y: 0.75, z: 0 },
      rotation: { x: 0, y: 0, z: 0 },
      scale: { x: 1, y: 1, z: 1 },
    },
    explodedVector: { x: 0.5, y: 0.6, z: 0 },
    massKg: 14,
    paintZone: "BODY_PAINTED",
  },
  front_fenders: {
    componentType: "front_fenders",
    assetPath: "/models/exterior/front_fenders.glb",
    defaultTransform: {
      position: { x: 1.25, y: 0.65, z: 0 },
      rotation: { x: 0, y: 0, z: 0 },
      scale: { x: 1, y: 1, z: 1 },
    },
    explodedVector: { x: 0.6, y: 0.2, z: 0.7 },
    massKg: 16,
    paintZone: "BODY_PAINTED",
  },
  doors_assembly: {
    componentType: "doors_assembly",
    assetPath: "/models/exterior/doors.glb",
    defaultTransform: {
      position: { x: 0, y: 0.65, z: 0 },
      rotation: { x: 0, y: 0, z: 0 },
      scale: { x: 1, y: 1, z: 1 },
    },
    explodedVector: { x: 0, y: 0.4, z: 0.8 },
    massKg: 36,
    paintZone: "BODY_PAINTED",
  },
  rear_quarter_panels: {
    componentType: "rear_quarter_panels",
    assetPath: "/models/exterior/rear_quarters.glb",
    defaultTransform: {
      position: { x: -1.15, y: 0.65, z: 0 },
      rotation: { x: 0, y: 0, z: 0 },
      scale: { x: 1, y: 1, z: 1 },
    },
    explodedVector: { x: -0.6, y: 0.2, z: 0.7 },
    massKg: 24,
    paintZone: "BODY_PAINTED",
  },
  trunk_decklid: {
    componentType: "trunk_decklid",
    assetPath: "/models/exterior/trunk_decklid.glb",
    defaultTransform: {
      position: { x: -1.05, y: 0.75, z: 0 },
      rotation: { x: 0, y: 0, z: 0 },
      scale: { x: 1, y: 1, z: 1 },
    },
    explodedVector: { x: -0.5, y: 0.6, z: 0 },
    massKg: 15,
    paintZone: "BODY_PAINTED",
  },
  roof_panel: {
    componentType: "roof_panel",
    assetPath: "/models/exterior/roof_panel.glb",
    defaultTransform: {
      position: { x: 0, y: 1.15, z: 0 },
      rotation: { x: 0, y: 0, z: 0 },
      scale: { x: 1, y: 1, z: 1 },
    },
    explodedVector: { x: 0, y: 0.9, z: 0 },
    massKg: 9,
    paintZone: "CONTRAST_ROOF",
  },
  front_bumper_fascia: {
    componentType: "front_bumper_fascia",
    assetPath: "/models/exterior/front_bumper.glb",
    defaultTransform: {
      position: { x: 2.1, y: 0.35, z: 0 },
      rotation: { x: 0, y: 0, z: 0 },
      scale: { x: 1, y: 1, z: 1 },
    },
    explodedVector: { x: 1.1, y: 0, z: 0 },
    massKg: 12,
    paintZone: "BODY_PAINTED",
  },
  rear_bumper_fascia: {
    componentType: "rear_bumper_fascia",
    assetPath: "/models/exterior/rear_bumper.glb",
    defaultTransform: {
      position: { x: -2.1, y: 0.35, z: 0 },
      rotation: { x: 0, y: 0, z: 0 },
      scale: { x: 1, y: 1, z: 1 },
    },
    explodedVector: { x: -1.1, y: 0, z: 0 },
    massKg: 13,
    paintZone: "BODY_PAINTED",
  },
  front_splitter_tray: {
    componentType: "front_splitter_tray",
    assetPath: "/models/exterior/front_splitter.glb",
    defaultTransform: {
      position: { x: 2.2, y: 0.05, z: 0 },
      rotation: { x: 0, y: 0, z: 0 },
      scale: { x: 1, y: 1, z: 1 },
    },
    explodedVector: { x: 1.3, y: -0.2, z: 0 },
    massKg: 6,
    paintZone: "UNPAINTED_CARBON",
  },
  rear_diffuser_tunnel: {
    componentType: "rear_diffuser_tunnel",
    assetPath: "/models/exterior/rear_diffuser.glb",
    defaultTransform: {
      position: { x: -2.15, y: 0.05, z: 0 },
      rotation: { x: 0, y: 0, z: 0 },
      scale: { x: 1, y: 1, z: 1 },
    },
    explodedVector: { x: -1.3, y: -0.2, z: 0 },
    massKg: 8,
    paintZone: "UNPAINTED_CARBON",
  },
  side_skirts_aero: {
    componentType: "side_skirts_aero",
    assetPath: "/models/exterior/side_skirts.glb",
    defaultTransform: {
      position: { x: 0, y: 0.02, z: 0 },
      rotation: { x: 0, y: 0, z: 0 },
      scale: { x: 1, y: 1, z: 1 },
    },
    explodedVector: { x: 0, y: -0.1, z: 0.9 },
    massKg: 7,
    paintZone: "UNPAINTED_CARBON",
  },
  rear_wing_spoiler: {
    componentType: "rear_wing_spoiler",
    assetPath: "/models/exterior/rear_wing.glb",
    defaultTransform: {
      position: { x: -1.8, y: 1.15, z: 0 },
      rotation: { x: 0, y: 0, z: 0 },
      scale: { x: 1, y: 1, z: 1 },
    },
    explodedVector: { x: -0.8, y: 0.9, z: 0 },
    massKg: 14,
    paintZone: "UNPAINTED_CARBON",
  },
  canards_dive_planes: {
    componentType: "canards_dive_planes",
    assetPath: "/models/exterior/canards.glb",
    defaultTransform: {
      position: { x: 2.05, y: 0.45, z: 0 },
      rotation: { x: 0, y: 0, z: 0 },
      scale: { x: 1, y: 1, z: 1 },
    },
    explodedVector: { x: 1.1, y: 0.2, z: 0.6 },
    massKg: 2,
    paintZone: "UNPAINTED_CARBON",
  },
  hood_fender_vents: {
    componentType: "hood_fender_vents",
    assetPath: "/models/exterior/vents.glb",
    defaultTransform: {
      position: { x: 1.0, y: 0.8, z: 0 },
      rotation: { x: 0, y: 0, z: 0 },
      scale: { x: 1, y: 1, z: 1 },
    },
    explodedVector: { x: 0.3, y: 0.5, z: 0.3 },
    massKg: 1,
    paintZone: "UNPAINTED_CARBON",
  },
  windshield_glass: {
    componentType: "windshield_glass",
    assetPath: "/models/exterior/windshield.glb",
    defaultTransform: {
      position: { x: 0.55, y: 0.85, z: 0 },
      rotation: { x: 0, y: 0, z: 0 },
      scale: { x: 1, y: 1, z: 1 },
    },
    explodedVector: { x: 0.4, y: 0.7, z: 0 },
    massKg: 13,
    paintZone: "GLASS_TRANSMISSIVE",
  },
  side_door_glass: {
    componentType: "side_door_glass",
    assetPath: "/models/exterior/side_glass.glb",
    defaultTransform: {
      position: { x: 0, y: 0.85, z: 0 },
      rotation: { x: 0, y: 0, z: 0 },
      scale: { x: 1, y: 1, z: 1 },
    },
    explodedVector: { x: 0, y: 0.5, z: 0.8 },
    massKg: 8,
    paintZone: "GLASS_TRANSMISSIVE",
  },
  rear_window_backlite: {
    componentType: "rear_window_backlite",
    assetPath: "/models/exterior/rear_window.glb",
    defaultTransform: {
      position: { x: -0.75, y: 0.85, z: 0 },
      rotation: { x: 0, y: 0, z: 0 },
      scale: { x: 1, y: 1, z: 1 },
    },
    explodedVector: { x: -0.4, y: 0.7, z: 0 },
    massKg: 9,
    paintZone: "GLASS_TRANSMISSIVE",
  },
  headlights_matrix: {
    componentType: "headlights_matrix",
    assetPath: "/models/exterior/headlights.glb",
    defaultTransform: {
      position: { x: 1.85, y: 0.55, z: 0 },
      rotation: { x: 0, y: 0, z: 0 },
      scale: { x: 1, y: 1, z: 1 },
    },
    explodedVector: { x: 0.9, y: 0.3, z: 0.5 },
    massKg: 6,
    paintZone: "LIGHTING_EMISSIVE",
  },
  taillights_oled: {
    componentType: "taillights_oled",
    assetPath: "/models/exterior/taillights.glb",
    defaultTransform: {
      position: { x: -1.95, y: 0.55, z: 0 },
      rotation: { x: 0, y: 0, z: 0 },
      scale: { x: 1, y: 1, z: 1 },
    },
    explodedVector: { x: -0.9, y: 0.3, z: 0.5 },
    massKg: 5,
    paintZone: "LIGHTING_EMISSIVE",
  },
  fog_drl_lights: {
    componentType: "fog_drl_lights",
    assetPath: "/models/exterior/fog_lights.glb",
    defaultTransform: {
      position: { x: 1.95, y: 0.25, z: 0 },
      rotation: { x: 0, y: 0, z: 0 },
      scale: { x: 1, y: 1, z: 1 },
    },
    explodedVector: { x: 1.0, y: 0.1, z: 0.4 },
    massKg: 2,
    paintZone: "LIGHTING_EMISSIVE",
  },
  side_mirrors: {
    componentType: "side_mirrors",
    assetPath: "/models/exterior/mirrors.glb",
    defaultTransform: {
      position: { x: 0.45, y: 0.75, z: 0 },
      rotation: { x: 0, y: 0, z: 0 },
      scale: { x: 1, y: 1, z: 1 },
    },
    explodedVector: { x: 0.2, y: 0.4, z: 0.9 },
    massKg: 3,
    paintZone: "UNPAINTED_CARBON",
  },
  front_grille_mesh: {
    componentType: "front_grille_mesh",
    assetPath: "/models/exterior/grille.glb",
    defaultTransform: {
      position: { x: 2.12, y: 0.35, z: 0 },
      rotation: { x: 0, y: 0, z: 0 },
      scale: { x: 1, y: 1, z: 1 },
    },
    explodedVector: { x: 1.2, y: 0, z: 0 },
    massKg: 2,
    paintZone: "UNPAINTED_CARBON",
  },
  exhaust_tips_surround: {
    componentType: "exhaust_tips_surround",
    assetPath: "/models/exterior/exhaust_tips.glb",
    defaultTransform: {
      position: { x: -2.12, y: 0.35, z: 0 },
      rotation: { x: 0, y: 0, z: 0 },
      scale: { x: 1, y: 1, z: 1 },
    },
    explodedVector: { x: -1.2, y: 0, z: 0 },
    massKg: 3,
    paintZone: "CHROME_POLISHED",
  },
  door_handles_latches: {
    componentType: "door_handles_latches",
    assetPath: "/models/exterior/door_handles.glb",
    defaultTransform: {
      position: { x: 0.15, y: 0.65, z: 0 },
      rotation: { x: 0, y: 0, z: 0 },
      scale: { x: 1, y: 1, z: 1 },
    },
    explodedVector: { x: 0.1, y: 0.2, z: 0.85 },
    massKg: 2,
    paintZone: "BODY_PAINTED",
  },
  wiper_cowl_assembly: {
    componentType: "wiper_cowl_assembly",
    assetPath: "/models/exterior/wipers.glb",
    defaultTransform: {
      position: { x: 0.65, y: 0.65, z: 0 },
      rotation: { x: 0, y: 0, z: 0 },
      scale: { x: 1, y: 1, z: 1 },
    },
    explodedVector: { x: 0.3, y: 0.4, z: 0 },
    massKg: 3,
    paintZone: "RUBBER_MATTE",
  },
  badges_emblems: {
    componentType: "badges_emblems",
    assetPath: "/models/exterior/badges.glb",
    defaultTransform: {
      position: { x: 2.15, y: 0.55, z: 0 },
      rotation: { x: 0, y: 0, z: 0 },
      scale: { x: 1, y: 1, z: 1 },
    },
    explodedVector: { x: 1.3, y: 0.2, z: 0 },
    massKg: 0.3,
    paintZone: "CHROME_POLISHED",
  },
};
