// ============================================================================
// ULTRA-FIDELITY 3D INTERIOR STUDIO — MASTER CATALOG & PRESET REGISTRY
// ============================================================================
// Complete catalog of 5 Dashboards, 6 Steering Wheels, 5 Seating Systems,
// 5 Center Consoles, 4 Audio Systems, and 6 Curated Cockpit Design Themes.
// ============================================================================

import {
  DashboardSpecification,
  SteeringWheelSpecification,
  SeatingSpecification,
  CenterConsoleSpecification,
  AudioSystemSpecification,
  MasterInteriorConfiguration,
} from '../types/interiorStudioTypes';

// ============================================================================
// 1. DASHBOARDS REGISTRY (5 Distinct Architectures)
// ============================================================================

export const DASHBOARD_CATALOG: Record<string, DashboardSpecification> = {
  DASH_EXECUTIVE_01: {
    id: 'DASH_EXECUTIVE_01',
    name: 'Monolithic Executive Dual-Tier',
    architectureClass: 'executive_monolith',
    compatibleBodyTypes: ['sedan', 'suv', 'coupe'],
    massKg: 28.5,
    costUSD: 4200,
    widthM: 1.48,
    depthM: 0.58,
    heightM: 0.38,
    hvacVentStyle: 'hidden_slits',
    hasGloveboxChiller: true,
    hasHeadsUpDisplaySlot: true,
    hasAmbientLightbar: true,
    hasPassengerDisplaySlot: true,
    trimPanelLocations: ['center_waterfall', 'passenger_fascia', 'driver_cowl'],
    description: 'Sweeping dual-pane glass, open-pore wood waterfall veneer, hidden micro-louvre HVAC slats, and analog clock inlay.',
  },
  DASH_GT3_TRACK_02: {
    id: 'DASH_GT3_TRACK_02',
    name: 'GT3 Competition Dry-Carbon Cockpit',
    architectureClass: 'gt3_track_cockpit',
    compatibleBodyTypes: ['hypercar', 'supercar', 'coupe', 'sports_car'],
    massKg: 9.8,
    costUSD: 7800,
    widthM: 1.38,
    depthM: 0.46,
    heightM: 0.32,
    hvacVentStyle: 'aircraft_nozzle',
    hasGloveboxChiller: false,
    hasHeadsUpDisplaySlot: true,
    hasAmbientLightbar: false,
    hasPassengerDisplaySlot: false,
    trimPanelLocations: ['cowl_top', 'rollcage_brackets'],
    description: 'Ultra-lightweight pre-preg carbon fiber cowl with exposed roll-cage mounting brackets and titanium toggle switchbank.',
  },
  DASH_HYPER_GLASS_03: {
    id: 'DASH_HYPER_GLASS_03',
    name: 'Pillar-to-Pillar Hyperscreen Blade',
    architectureClass: 'hyper_minimalist_glass',
    compatibleBodyTypes: ['hypercar', 'sedan', 'suv', 'coupe'],
    massKg: 22.0,
    costUSD: 8500,
    widthM: 1.52,
    depthM: 0.52,
    heightM: 0.36,
    hvacVentStyle: 'linear_slot',
    hasGloveboxChiller: true,
    hasHeadsUpDisplaySlot: true,
    hasAmbientLightbar: true,
    hasPassengerDisplaySlot: true,
    trimPanelLocations: ['under_screen_blade', 'endcap_louvres'],
    description: 'Continuous curved 56-inch glass surface integrating triple OLED displays, seamless haptic buttons, and perimeter ambient halo.',
  },
  DASH_LUXURY_GT_04: {
    id: 'DASH_LUXURY_GT_04',
    name: 'Grand Tourer Hand-Crafted Leather Cowl',
    architectureClass: 'luxury_grand_tourer',
    compatibleBodyTypes: ['sports_car', 'coupe', 'convertible', 'sedan'],
    massKg: 31.0,
    costUSD: 5600,
    widthM: 1.46,
    depthM: 0.56,
    heightM: 0.39,
    hvacVentStyle: 'turbine_rotary',
    hasGloveboxChiller: true,
    hasHeadsUpDisplaySlot: true,
    hasAmbientLightbar: true,
    hasPassengerDisplaySlot: true,
    trimPanelLocations: ['lower_knee_bolsters', 'upper_dash_crest', 'center_stack'],
    description: 'Hand-stitched French seam dual-tone Nappa leather dash cap, knurled aluminum rotary turbine vents, and crystal push-buttons.',
  },
  DASH_CLASSIC_05: {
    id: 'DASH_CLASSIC_05',
    name: 'Classic Heritage Brushed Chrome Cockpit',
    architectureClass: 'classic_heritage_sport',
    compatibleBodyTypes: ['convertible', 'coupe', 'pickup', 'wagon'],
    massKg: 19.5,
    costUSD: 3400,
    widthM: 1.40,
    depthM: 0.50,
    heightM: 0.35,
    hvacVentStyle: 'classic_mesh',
    hasGloveboxChiller: false,
    hasHeadsUpDisplaySlot: false,
    hasAmbientLightbar: false,
    hasPassengerDisplaySlot: false,
    trimPanelLocations: ['gauge_binnacle', 'center_toggle_rack'],
    description: 'Deep-set round brushed chrome bezels, retro aircraft toggle switches, analog dials with orange needles, and leather knee bolsters.',
  },
};

// ============================================================================
// 2. STEERING WHEELS REGISTRY (6 Typologies)
// ============================================================================

export const STEERING_WHEEL_CATALOG: Record<string, SteeringWheelSpecification> = {
  STEER_GT3_YOKE: {
    id: 'STEER_GT3_YOKE',
    name: 'Formula & GT3 Competition Carbon Yoke',
    typology: 'gt3_race_yoke',
    diameterMm: 290,
    gripThicknessMm: 34,
    dishOffsetMm: 0,
    hasPaddleShifters: true,
    paddleMaterial: 'titanium_magnetic',
    hasRotaryManettino: true,
    hasRpmLedBar: true,
    hasCapacitiveHandsOnDetection: false,
    massKg: 1.35,
    costUSD: 2400,
    description: 'Open-top high-modulus carbon yoke with textured polyurethane grips, 16-LED shift light bar, dual rotary thumb dials, and magnetic titanium shifters.',
  },
  STEER_FLAT_BOTTOM: {
    id: 'STEER_FLAT_BOTTOM',
    name: 'Flat-Bottom Alcantara Sport Wheel',
    typology: 'flat_bottom_sport',
    diameterMm: 340,
    gripThicknessMm: 36,
    dishOffsetMm: 25,
    hasPaddleShifters: true,
    paddleMaterial: 'carbon_fiber',
    hasRotaryManettino: true,
    hasRpmLedBar: false,
    hasCapacitiveHandsOnDetection: true,
    massKg: 2.10,
    costUSD: 1650,
    description: 'Motorsport flat-bottom profile with perforated leather sides, Alcantara top/bottom, 12 o’clock center stripe, and CNC aluminum paddle shifters.',
  },
  STEER_CLASSIC_ROUND: {
    id: 'STEER_CLASSIC_ROUND',
    name: 'Classic Heritage 3-Spoke Polished Rim',
    typology: 'classic_3_spoke_round',
    diameterMm: 370,
    gripThicknessMm: 30,
    dishOffsetMm: 45,
    hasPaddleShifters: false,
    paddleMaterial: 'billet_aluminum',
    hasRotaryManettino: false,
    hasRpmLedBar: false,
    hasCapacitiveHandsOnDetection: false,
    massKg: 1.80,
    costUSD: 950,
    description: 'Polished mirror-finish aluminum spokes with lightening holes, mahogany wood / black leather rim, and retro center horn push-button.',
  },
  STEER_EXEC_2SPOKE: {
    id: 'STEER_EXEC_2SPOKE',
    name: 'Executive Two-Spoke Heated Luxury Wheel',
    typology: 'executive_2_spoke',
    diameterMm: 360,
    gripThicknessMm: 38,
    dishOffsetMm: 15,
    hasPaddleShifters: true,
    paddleMaterial: 'billet_aluminum',
    hasRotaryManettino: false,
    hasRpmLedBar: false,
    hasCapacitiveHandsOnDetection: true,
    massKg: 2.45,
    costUSD: 1850,
    description: 'Dual-spoke luxury design wrapped in semi-aniline leather with integrated heating, capacitive touch control pads, and crystal haptic scroll wheels.',
  },
  STEER_DRIFT_DISH: {
    id: 'STEER_DRIFT_DISH',
    name: 'Pro-Drift 90mm Deep Dish Suede Wheel',
    typology: 'drift_deep_dish',
    diameterMm: 330,
    gripThicknessMm: 35,
    dishOffsetMm: 90,
    hasPaddleShifters: false,
    paddleMaterial: 'billet_aluminum',
    hasRotaryManettino: false,
    hasRpmLedBar: false,
    hasCapacitiveHandsOnDetection: false,
    massKg: 1.25,
    costUSD: 780,
    description: 'Extreme 90mm deep dish architecture for maximum steering wheel leverage, wrapped in ultra-grip Italian suede with quick-release splined hub.',
  },
  STEER_AUTONOMOUS: {
    id: 'STEER_AUTONOMOUS',
    name: 'Cyber-Steer Retractable Folding Yoke',
    typology: 'autonomous_retractable',
    diameterMm: 320,
    gripThicknessMm: 32,
    dishOffsetMm: 0,
    hasPaddleShifters: true,
    paddleMaterial: 'forged_composite',
    hasRotaryManettino: true,
    hasRpmLedBar: true,
    hasCapacitiveHandsOnDetection: true,
    massKg: 3.20,
    costUSD: 3900,
    description: 'Steer-by-wire dual-grip yoke with motorized folding handles that seamlessly retract flush into the dashboard during Level 4 autonomous cruising.',
  },
};

// ============================================================================
// 3. SEATING REGISTRY (5 Architectures)
// ============================================================================

export const SEATING_CATALOG: Record<string, SeatingSpecification> = {
  SEAT_CARBON_BUCKET: {
    id: 'SEAT_CARBON_BUCKET',
    name: 'High-Modulus Carbon Monocoque Bucket',
    architectureClass: 'carbon_fixed_bucket',
    seatCount: 2,
    seatMassKgPerUnit: 6.8,
    costUSDPerUnit: 4500,
    adjustmentAxes: 2,
    lateralGSupportPercent: 98,
    comfortRatingPercent: 62,
    hasActiveVentilation: false,
    hasPneumaticMassage: false,
    hasHeatedSeatBase: true,
    hasNearfieldHeadrestSpeakers: false,
    harnessType: 'sabelt_6_point_f1',
    seatbackShellMaterial: 'gloss_forged_carbon',
    description: 'Ultra-lightweight FIA 8855-1999 homologated carbon-aramid shell with high-density shock absorbing memory pads and 6-point harness cam-lock slots.',
  },
  SEAT_SPORT_RECARO: {
    id: 'SEAT_SPORT_RECARO',
    name: '14-Way Power Sport Bolstered Bucket',
    architectureClass: 'sport_bolstered_recaro',
    seatCount: 2,
    seatMassKgPerUnit: 18.5,
    costUSDPerUnit: 2800,
    adjustmentAxes: 14,
    lateralGSupportPercent: 88,
    comfortRatingPercent: 84,
    hasActiveVentilation: true,
    hasPneumaticMassage: false,
    hasHeatedSeatBase: true,
    hasNearfieldHeadrestSpeakers: true,
    harnessType: 'standard_3_point',
    seatbackShellMaterial: 'matte_carbon',
    description: 'Deep lateral side and thigh bolsters with power pneumatic tightening, integrated headrest with illuminated model crest, and contrast stitch piping.',
  },
  SEAT_VIP_OTTOMAN: {
    id: 'SEAT_VIP_OTTOMAN',
    name: 'Executive 22-Way Pneumatic Lounge Ottoman',
    architectureClass: 'executive_vip_ottoman',
    seatCount: 4,
    seatMassKgPerUnit: 29.0,
    costUSDPerUnit: 3900,
    adjustmentAxes: 22,
    lateralGSupportPercent: 64,
    comfortRatingPercent: 99,
    hasActiveVentilation: true,
    hasPneumaticMassage: true,
    hasHeatedSeatBase: true,
    hasNearfieldHeadrestSpeakers: true,
    harnessType: 'standard_3_point',
    seatbackShellMaterial: 'leather_wrapped',
    description: 'First-class aviation-inspired seating with hot-stone pneumatic massage chambers, motorized calf ottoman, and heated armrests.',
  },
  SEAT_CLASSIC_FLUTED: {
    id: 'SEAT_CLASSIC_FLUTED',
    name: 'Heritage Horizontal-Fluted Leather Seat',
    architectureClass: 'classic_fluted_leather',
    seatCount: 2,
    seatMassKgPerUnit: 14.2,
    costUSDPerUnit: 1900,
    adjustmentAxes: 6,
    lateralGSupportPercent: 70,
    comfortRatingPercent: 78,
    hasActiveVentilation: false,
    hasPneumaticMassage: false,
    hasHeatedSeatBase: true,
    hasNearfieldHeadrestSpeakers: false,
    harnessType: 'standard_3_point',
    seatbackShellMaterial: 'leather_wrapped',
    description: 'Authentic 1960s sports car aesthetics featuring horizontal padded leather flutes, chrome recline handles, and low-profile cushion design.',
  },
  SEAT_ACTIVE_MATRIX: {
    id: 'SEAT_ACTIVE_MATRIX',
    name: 'Dynamic G-Force Adaptive Matrix Seat',
    architectureClass: 'active_dynamic_matrix',
    seatCount: 2,
    seatMassKgPerUnit: 22.0,
    costUSDPerUnit: 3400,
    adjustmentAxes: 18,
    lateralGSupportPercent: 94,
    comfortRatingPercent: 92,
    hasActiveVentilation: true,
    hasPneumaticMassage: true,
    hasHeatedSeatBase: true,
    hasNearfieldHeadrestSpeakers: true,
    harnessType: 'schroth_enduro_pro',
    seatbackShellMaterial: 'gloss_forged_carbon',
    description: 'Active dynamic air bladders that inflate on the opposite side of lateral cornering forces within 80 milliseconds to eliminate driver fatigue.',
  },
};

// ============================================================================
// 4. CENTER CONSOLES REGISTRY (5 Styles)
// ============================================================================

export const CENTER_CONSOLE_CATALOG: Record<string, CenterConsoleSpecification> = {
  CONSOLE_GATED_H: {
    id: 'CONSOLE_GATED_H',
    name: 'Open-Gated Manual Shifter Tunnel',
    style: 'gated_manual_h_pattern',
    hasWirelessPhoneCharger: true,
    hasCupholderCover: true,
    hasCoolerCompartment: false,
    armrestStyle: 'leather_pad',
    massKg: 11.5,
    costUSD: 2100,
    description: 'Mirror-polished stainless steel 6-speed gate with audible metallic shift clicks, exposed mechanical gear linkages, and dual cupholders.',
  },
  CONSOLE_SEQUENTIAL: {
    id: 'CONSOLE_SEQUENTIAL',
    name: 'Sequential Dog-Ring Race Shifter Tower',
    style: 'sequential_dog_box',
    hasWirelessPhoneCharger: false,
    hasCupholderCover: false,
    hasCoolerCompartment: false,
    armrestStyle: 'carbon_cantilever',
    massKg: 7.2,
    costUSD: 3600,
    description: 'CNC-machined aircraft aluminum sequential shift lever with knurled grip, reverse lockout collar, and exposed return spring assembly.',
  },
  CONSOLE_ROTARY_CRYSTAL: {
    id: 'CONSOLE_ROTARY_CRYSTAL',
    name: 'Crystal Glass Monostable Rotary Console',
    style: 'crystal_rotary_dial',
    hasWirelessPhoneCharger: true,
    hasCupholderCover: true,
    hasCoolerCompartment: true,
    armrestStyle: 'split_butterfly',
    massKg: 14.8,
    costUSD: 2900,
    description: 'Precision-cut faceted crystal glass rotary gear selector, dual 50W fast wireless phone charging pads, and refrigerated center chiller box.',
  },
  CONSOLE_AIRCRAFT_START: {
    id: 'CONSOLE_AIRCRAFT_START',
    name: 'Fighter-Jet Start Flap & Toggle Matrix',
    style: 'aircraft_start_flap',
    hasWirelessPhoneCharger: true,
    hasCupholderCover: true,
    hasCoolerCompartment: false,
    armrestStyle: 'single_sliding',
    massKg: 12.0,
    costUSD: 2500,
    description: 'Red anodized flip-up safety guard covering the illuminated engine start/stop button, accompanied by billet anodized drive mode toggles.',
  },
  CONSOLE_TRACK_STACK: {
    id: 'CONSOLE_TRACK_STACK',
    name: 'Track Competition Console with Fire Suppression',
    style: 'track_carbon_stack',
    hasWirelessPhoneCharger: false,
    hasCupholderCover: false,
    hasCoolerCompartment: false,
    armrestStyle: 'carbon_cantilever',
    massKg: 5.5,
    costUSD: 4100,
    description: 'Full carbon fiber minimalist bridge containing remote brake bias dial, master electrical cutoff switch, and plumbed fire extinguisher bottle.',
  },
};

// ============================================================================
// 5. AUDIO SYSTEMS REGISTRY (4 Classes)
// ============================================================================

export const AUDIO_SYSTEM_CATALOG: Record<string, AudioSystemSpecification> = {
  AUDIO_BASE_8: {
    id: 'AUDIO_BASE_8',
    name: 'Standard Studio 8-Speaker Sound',
    systemClass: 'base_studio_8_speaker',
    speakerCount: 8,
    totalAmplifierWattsRMS: 240,
    hasDolbyAtmos3D: false,
    hasActiveNoiseCancellation: false,
    hasNearfieldHeadrestArray: false,
    hasUnderseatTactileTransducers: false,
    grilleFinish: 'matte_black_mesh',
    massKg: 4.5,
    costUSD: 0,
    description: 'Clear stereo sound with silk-dome door tweeters and 6.5-inch composite cone door mid-woofers.',
  },
  AUDIO_PREMIUM_16: {
    id: 'AUDIO_PREMIUM_16',
    name: 'Premium Surround 16-Speaker 720W System',
    systemClass: 'premium_surround_16',
    speakerCount: 16,
    totalAmplifierWattsRMS: 720,
    hasDolbyAtmos3D: true,
    hasActiveNoiseCancellation: true,
    hasNearfieldHeadrestArray: false,
    hasUnderseatTactileTransducers: false,
    grilleFinish: 'laser_cut_aluminum',
    massKg: 11.2,
    costUSD: 1850,
    description: '16 high-efficiency transducers, dual 10-inch rear deck subwoofers, Class-D multi-channel DSP amp, and active road noise cancellation.',
  },
  AUDIO_SPATIAL_24: {
    id: 'AUDIO_SPATIAL_24',
    name: '3D Spatial Audio 24-Speaker 1450W Dolby Atmos',
    systemClass: 'ultra_3d_spatial_24',
    speakerCount: 24,
    totalAmplifierWattsRMS: 1450,
    hasDolbyAtmos3D: true,
    hasActiveNoiseCancellation: true,
    hasNearfieldHeadrestArray: true,
    hasUnderseatTactileTransducers: true,
    grilleFinish: 'laser_cut_aluminum',
    massKg: 18.5,
    costUSD: 4200,
    description: 'Full 3D immersive sound stage with ceiling height speakers, dual nearfield headrest drivers per seat, and tactile seat bass shakers.',
  },
  AUDIO_AUDIOPHILE_32: {
    id: 'AUDIO_AUDIOPHILE_32',
    name: 'Bespoke Audiophile Diamond & Beryllium 32-Speaker 2100W',
    systemClass: 'bespoke_audiophile_32',
    speakerCount: 32,
    totalAmplifierWattsRMS: 2100,
    hasDolbyAtmos3D: true,
    hasActiveNoiseCancellation: true,
    hasNearfieldHeadrestArray: true,
    hasUnderseatTactileTransducers: true,
    grilleFinish: 'illuminated_crystal',
    massKg: 26.0,
    costUSD: 8900,
    description: 'Diamond dome tweeters, motorized acoustic lens prisms that rise from the dashboard, illuminated micro-perforated grilles, and 32-channel DSP.',
  },
};

// ============================================================================
// 6. CURATED COCKPIT DESIGN THEMES (6 Presets)
// ============================================================================

export const COCKPIT_THEME_PRESETS: Record<string, { name: string; config: Partial<MasterInteriorConfiguration> }> = {
  THEME_MIDNIGHT_STEALTH: {
    name: 'Midnight Stealth Monolith',
    config: {
      dashboardId: 'DASH_HYPER_GLASS_03',
      dashboardClass: 'hyper_minimalist_glass',
      steeringWheelId: 'STEER_FLAT_BOTTOM',
      steeringTypology: 'flat_bottom_sport',
      frontSeatsId: 'SEAT_SPORT_RECARO',
      seatingClass: 'sport_bolstered_recaro',
      centerConsoleId: 'CONSOLE_ROTARY_CRYSTAL',
      centerConsoleStyle: 'crystal_rotary_dial',
      audioSystemId: 'AUDIO_SPATIAL_24',
      materials: {
        primaryUpholstery: 'alcantara_suede',
        secondaryUpholstery: 'nappa_leather',
        primaryColorHex: '#12151c',
        secondaryColorHex: '#1f2430',
        stitchingPattern: 'hexagonal_honeycomb',
        stitchingColorHex: '#00f0ff',
        trimAccents: 'forged_matte_carbon',
        seatBeltColorHex: '#00f0ff',
        carpetColorHex: '#0b0d13',
        headlinerMaterial: 'starlight_fiber_optic',
        headlinerColorHex: '#07090d',
      },
      ambientLighting: {
        enabled: true,
        brightnessPercent: 85,
        primaryColorHex: '#00f0ff',
        secondaryColorHex: '#d97706',
        colorMode: 'dual_zone_gradient',
        activeZones: ['dashboard_contour', 'center_console_halo', 'door_spear_accents', 'footwell_mood', 'speaker_grille_halo'],
        fiberOpticDiffuserDiffusion: 0.8,
      },
      digitalCockpit: {
        layoutType: 'pillar_to_pillar_hyperscreen',
        uiTheme: 'cyberpunk_neon_cyan',
        virtualClusterSizeInches: 12.3,
        infotainmentSizeInches: 17.7,
        passengerScreenSizeInches: 12.3,
        hasHolographicHUD: true,
        hudProjectionDistanceM: 2.5,
        hudFieldOfViewDeg: 12.0,
        touchscreenHapticFeedback: true,
        glassAntiReflectiveCoating: true,
        ambientLightSync: true,
      },
    },
  },
  THEME_ROSSO_CORSA_TRACK: {
    name: 'Scuderia Corsa Trackday',
    config: {
      dashboardId: 'DASH_GT3_TRACK_02',
      dashboardClass: 'gt3_track_cockpit',
      steeringWheelId: 'STEER_GT3_YOKE',
      steeringTypology: 'gt3_race_yoke',
      frontSeatsId: 'SEAT_CARBON_BUCKET',
      seatingClass: 'carbon_fixed_bucket',
      centerConsoleId: 'CONSOLE_SEQUENTIAL',
      centerConsoleStyle: 'sequential_dog_box',
      audioSystemId: 'AUDIO_BASE_8',
      materials: {
        primaryUpholstery: 'alcantara_suede',
        secondaryUpholstery: 'matte_dry_carbon',
        primaryColorHex: '#141416',
        secondaryColorHex: '#dc2626',
        stitchingPattern: 'double_contrast_stitch',
        stitchingColorHex: '#ef4444',
        trimAccents: 'twill_gloss_carbon',
        seatBeltColorHex: '#dc2626',
        carpetColorHex: '#090a0d',
        headlinerMaterial: 'alcantara_suede',
        headlinerColorHex: '#101217',
      },
      ambientLighting: {
        enabled: true,
        brightnessPercent: 70,
        primaryColorHex: '#ef4444',
        secondaryColorHex: '#f59e0b',
        colorMode: 'rpm_shift_reactive',
        activeZones: ['dashboard_contour', 'door_spear_accents'],
        fiberOpticDiffuserDiffusion: 0.6,
      },
      digitalCockpit: {
        layoutType: 'driver_centric_track_cluster',
        uiTheme: 'motorsport_track_telemetry',
        virtualClusterSizeInches: 10.25,
        infotainmentSizeInches: 8.0,
        passengerScreenSizeInches: 0,
        hasHolographicHUD: true,
        hudProjectionDistanceM: 3.0,
        hudFieldOfViewDeg: 14.0,
        touchscreenHapticFeedback: true,
        glassAntiReflectiveCoating: true,
        ambientLightSync: true,
      },
    },
  },
  THEME_COGNAC_LUXURY: {
    name: 'Cognac Executive Grand Tourer',
    config: {
      dashboardId: 'DASH_LUXURY_GT_04',
      dashboardClass: 'luxury_grand_tourer',
      steeringWheelId: 'STEER_EXEC_2SPOKE',
      steeringTypology: 'executive_2_spoke',
      frontSeatsId: 'SEAT_VIP_OTTOMAN',
      seatingClass: 'executive_vip_ottoman',
      centerConsoleId: 'CONSOLE_ROTARY_CRYSTAL',
      centerConsoleStyle: 'crystal_rotary_dial',
      audioSystemId: 'AUDIO_AUDIOPHILE_32',
      materials: {
        primaryUpholstery: 'semi_aniline_leather',
        secondaryUpholstery: 'nappa_leather',
        primaryColorHex: '#9a4e28', // Rich warm cognac
        secondaryColorHex: '#1c1714', // Deep espresso
        stitchingPattern: 'diamond_quilted',
        stitchingColorHex: '#f3d9b1', // Cream stitch
        trimAccents: 'open_pore_walnut',
        seatBeltColorHex: '#9a4e28',
        carpetColorHex: '#181310',
        headlinerMaterial: 'starlight_fiber_optic',
        headlinerColorHex: '#120f0d',
      },
      ambientLighting: {
        enabled: true,
        brightnessPercent: 90,
        primaryColorHex: '#f59e0b',
        secondaryColorHex: '#d97706',
        colorMode: 'single_tone',
        activeZones: ['dashboard_contour', 'center_console_halo', 'door_spear_accents', 'footwell_mood', 'air_vent_turbine_glow', 'speaker_grille_halo', 'skylight_perimeter'],
        fiberOpticDiffuserDiffusion: 0.9,
      },
      digitalCockpit: {
        layoutType: 'dual_screen_cockpit',
        uiTheme: 'luxury_gold_elegance',
        virtualClusterSizeInches: 12.3,
        infotainmentSizeInches: 14.5,
        passengerScreenSizeInches: 10.25,
        hasHolographicHUD: true,
        hudProjectionDistanceM: 2.2,
        hudFieldOfViewDeg: 10.0,
        touchscreenHapticFeedback: true,
        glassAntiReflectiveCoating: true,
        ambientLightSync: true,
      },
    },
  },
  THEME_CYBERPUNK_NEON: {
    name: 'Neo-Tokyo Cyberpunk Synthwave',
    config: {
      dashboardId: 'DASH_HYPER_GLASS_03',
      dashboardClass: 'hyper_minimalist_glass',
      steeringWheelId: 'STEER_AUTONOMOUS',
      steeringTypology: 'autonomous_retractable',
      frontSeatsId: 'SEAT_ACTIVE_MATRIX',
      seatingClass: 'active_dynamic_matrix',
      centerConsoleId: 'CONSOLE_AIRCRAFT_START',
      centerConsoleStyle: 'aircraft_start_flap',
      audioSystemId: 'AUDIO_SPATIAL_24',
      materials: {
        primaryUpholstery: 'vegan_bamboo_silk',
        secondaryUpholstery: 'ballistic_cordura',
        primaryColorHex: '#0d111a',
        secondaryColorHex: '#1e1028',
        stitchingPattern: 'hexagonal_honeycomb',
        stitchingColorHex: '#d97706', // Hot Pink
        trimAccents: 'anodized_dark_titanium',
        seatBeltColorHex: '#d97706',
        carpetColorHex: '#080a0f',
        headlinerMaterial: 'panoramic_electrochromic_glass',
        headlinerColorHex: '#05070a',
      },
      ambientLighting: {
        enabled: true,
        brightnessPercent: 100,
        primaryColorHex: '#d97706', // Magenta
        secondaryColorHex: '#f59e0b', // Cyan
        colorMode: 'dual_zone_gradient',
        activeZones: ['dashboard_contour', 'center_console_halo', 'door_spear_accents', 'footwell_mood', 'air_vent_turbine_glow', 'speaker_grille_halo', 'seatback_crest', 'skylight_perimeter'],
        fiberOpticDiffuserDiffusion: 0.95,
      },
      digitalCockpit: {
        layoutType: 'pillar_to_pillar_hyperscreen',
        uiTheme: 'cyberpunk_neon_cyan',
        virtualClusterSizeInches: 12.3,
        infotainmentSizeInches: 17.7,
        passengerScreenSizeInches: 12.3,
        hasHolographicHUD: true,
        hudProjectionDistanceM: 2.8,
        hudFieldOfViewDeg: 15.0,
        touchscreenHapticFeedback: true,
        glassAntiReflectiveCoating: true,
        ambientLightSync: true,
      },
    },
  },
  THEME_HERITAGE_TARTAN: {
    name: '1970s Heritage Houndstooth Classic',
    config: {
      dashboardId: 'DASH_CLASSIC_05',
      dashboardClass: 'classic_heritage_sport',
      steeringWheelId: 'STEER_CLASSIC_ROUND',
      steeringTypology: 'classic_3_spoke_round',
      frontSeatsId: 'SEAT_CLASSIC_FLUTED',
      seatingClass: 'classic_fluted_leather',
      centerConsoleId: 'CONSOLE_GATED_H',
      centerConsoleStyle: 'gated_manual_h_pattern',
      audioSystemId: 'AUDIO_BASE_8',
      materials: {
        primaryUpholstery: 'wool_heritage_tartan',
        secondaryUpholstery: 'nappa_leather',
        primaryColorHex: '#1e2420', // British Racing Green tone
        secondaryColorHex: '#151714',
        stitchingPattern: 'single_french_seam',
        stitchingColorHex: '#e5e7eb',
        trimAccents: 'satin_brushed_aluminum',
        seatBeltColorHex: '#1f2937',
        carpetColorHex: '#141815',
        headlinerMaterial: 'woven_fabric',
        headlinerColorHex: '#1c201d',
      },
      ambientLighting: {
        enabled: false,
        brightnessPercent: 0,
        primaryColorHex: '#ffffff',
        secondaryColorHex: '#ffffff',
        colorMode: 'single_tone',
        activeZones: [],
        fiberOpticDiffuserDiffusion: 0.5,
      },
      digitalCockpit: {
        layoutType: 'classic_analog_hybrid',
        uiTheme: 'heritage_classic_analog',
        virtualClusterSizeInches: 7.0,
        infotainmentSizeInches: 0,
        passengerScreenSizeInches: 0,
        hasHolographicHUD: false,
        hudProjectionDistanceM: 0,
        hudFieldOfViewDeg: 0,
        touchscreenHapticFeedback: false,
        glassAntiReflectiveCoating: false,
        ambientLightSync: false,
      },
    },
  },
  THEME_ARCTIC_WHITE_YACHT: {
    name: 'Arctic White Nautical Yacht',
    config: {
      dashboardId: 'DASH_EXECUTIVE_01',
      dashboardClass: 'executive_monolith',
      steeringWheelId: 'STEER_EXEC_2SPOKE',
      steeringTypology: 'executive_2_spoke',
      frontSeatsId: 'SEAT_VIP_OTTOMAN',
      seatingClass: 'executive_vip_ottoman',
      centerConsoleId: 'CONSOLE_ROTARY_CRYSTAL',
      centerConsoleStyle: 'crystal_rotary_dial',
      audioSystemId: 'AUDIO_AUDIOPHILE_32',
      materials: {
        primaryUpholstery: 'nappa_leather',
        secondaryUpholstery: 'semi_aniline_leather',
        primaryColorHex: '#f1f5f9', // Clean Arctic White
        secondaryColorHex: '#1e293b', // Marine Blue contrast
        stitchingPattern: 'double_contrast_stitch',
        stitchingColorHex: '#0284c7', // Marine blue stitch
        trimAccents: 'open_pore_walnut',
        seatBeltColorHex: '#0284c7',
        carpetColorHex: '#0f172a',
        headlinerMaterial: 'panoramic_electrochromic_glass',
        headlinerColorHex: '#f8fafc',
      },
      ambientLighting: {
        enabled: true,
        brightnessPercent: 85,
        primaryColorHex: '#0284c7',
        secondaryColorHex: '#fbbf24',
        colorMode: 'dual_zone_gradient',
        activeZones: ['dashboard_contour', 'center_console_halo', 'door_spear_accents', 'footwell_mood', 'speaker_grille_halo', 'skylight_perimeter'],
        fiberOpticDiffuserDiffusion: 0.85,
      },
      digitalCockpit: {
        layoutType: 'dual_screen_cockpit',
        uiTheme: 'luxury_gold_elegance',
        virtualClusterSizeInches: 12.3,
        infotainmentSizeInches: 14.5,
        passengerScreenSizeInches: 10.25,
        hasHolographicHUD: true,
        hudProjectionDistanceM: 2.4,
        hudFieldOfViewDeg: 11.0,
        touchscreenHapticFeedback: true,
        glassAntiReflectiveCoating: true,
        ambientLightSync: true,
      },
    },
  },
};
