// ============================================================================
// MODULAR glTF VEHICLE CONSTRUCTION SYSTEM — COMPONENT MANIFEST
// ============================================================================
// Comprehensive catalog of modular components across all 12 assembly stages.
// Each component specifies its parent hardpoint, mass, aerodynamic deltas,
// cost, and available metallurgical grades.
// ============================================================================

import {
  ModularComponentMeta,
  VehicleSubsystemStage,
  SubsystemStageMeta,
} from '../types/vehicleConstructionTypes';

// ============================================================================
// 1. 12 ASSEMBLY SUBSYSTEM STAGES METADATA
// ============================================================================

export const SUBSYSTEM_STAGES: SubsystemStageMeta[] = [
  {
    stage: 'architecture',
    stageNumber: 0,
    title: 'Platform Architecture & Layout',
    shortName: 'Architecture',
    category: 'Foundation',
    icon: 'Layers',
    requiredParentStages: [],
    description: 'Select vehicle body type, drive configuration (FWD/RWD/AWD), engine placement, and dimensional envelope.',
  },
  {
    stage: 'chassis_platform',
    stageNumber: 1,
    title: 'Chassis Platform & Monocoque',
    shortName: 'Chassis',
    category: 'Foundation',
    icon: 'Shield',
    requiredParentStages: ['architecture'],
    description: 'Select 1 of 5 dedicated structural chassis platforms with specific torsional rigidity ratings and hardpoints.',
  },
  {
    stage: 'powertrain_engine',
    stageNumber: 2,
    title: 'Powertrain & Engine Bay',
    shortName: 'Engine',
    category: 'Mechanical',
    icon: 'Flame',
    requiredParentStages: ['chassis_platform'],
    description: 'Integrate high-output engine module (I4, V6, V8, V10, V12, Boxer, Dual EV) onto hydraulic chassis mounts.',
  },
  {
    stage: 'transmission',
    stageNumber: 3,
    title: 'Transmission & Driveline',
    shortName: 'Transmission',
    category: 'Mechanical',
    icon: 'Settings',
    requiredParentStages: ['powertrain_engine'],
    description: 'Select gearbox (7-Speed Dual Clutch, 6-Speed Manual, Sequential), prop-shaft, and limited-slip differential.',
  },
  {
    stage: 'suspension',
    stageNumber: 4,
    title: 'Suspension Kinematics & Subframes',
    shortName: 'Suspension',
    category: 'Mechanical',
    icon: 'Activity',
    requiredParentStages: ['chassis_platform'],
    description: 'Mount front/rear subframes, double wishbones, 5-link multilink arms, coilovers, and anti-roll sway bars.',
  },
  {
    stage: 'wheels_brakes',
    stageNumber: 5,
    title: 'Wheels, Tires & Braking System',
    shortName: 'Wheels & Brakes',
    category: 'Mechanical',
    icon: 'Disc',
    requiredParentStages: ['suspension'],
    description: 'Install slotted ventilated or carbon-ceramic brake rotors, monobloc calipers, forged wheel rims, and performance tires.',
  },
  {
    stage: 'body_structure',
    stageNumber: 6,
    title: 'Body Safety Cell & Bulkhead',
    shortName: 'Safety Cell',
    category: 'Structural',
    icon: 'Lock',
    requiredParentStages: ['chassis_platform'],
    description: 'Weld and bolt cowl trays, firewall bulkheads, A/B/C pillar safety rings, and roof cross-bow framework.',
  },
  {
    stage: 'exterior_panels',
    stageNumber: 7,
    title: 'Exterior Panels & Closures',
    shortName: 'Body Panels',
    category: 'Exterior',
    icon: 'Car',
    requiredParentStages: ['body_structure'],
    description: 'Attach doors, hood/bonnet, fenders, rear quarter panels, trunk decklid, and front/rear bumper fascias.',
  },
  {
    stage: 'lighting_glass',
    stageNumber: 8,
    title: 'Lighting & Optical Glass',
    shortName: 'Lighting & Glass',
    category: 'Exterior',
    icon: 'Zap',
    requiredParentStages: ['exterior_panels'],
    description: 'Install matrix LED headlights, OLED taillight bars, laminated acoustic windshield, and tinted side drop-glass.',
  },
  {
    stage: 'aerodynamics',
    stageNumber: 9,
    title: 'Aerodynamics & Ground Effects',
    shortName: 'Aerodynamics',
    category: 'Exterior',
    icon: 'Wind',
    requiredParentStages: ['exterior_panels'],
    description: 'Fit carbon front splitter, underbody venturi floor, rear aerodynamic diffuser, and active DRS rear wing.',
  },
  {
    stage: 'interior_cabin',
    stageNumber: 10,
    title: 'Interior Cabin & Cockpit',
    shortName: 'Interior',
    category: 'Cabin & Systems',
    icon: 'Armchair',
    requiredParentStages: ['body_structure'],
    description: 'Install dashboard binnacle, multifunction sport steering wheel, ergonomic bucket seats, and center console.',
  },
  {
    stage: 'electronics',
    stageNumber: 11,
    title: 'Electronics, Sensors & Battery',
    shortName: 'Electronics',
    category: 'Cabin & Systems',
    icon: 'Cpu',
    requiredParentStages: ['interior_cabin', 'powertrain_engine'],
    description: 'Install curved digital virtual cockpit, ADAS radar/cameras, master ECU, wiring harness, and high-voltage battery.',
  },
];

// ============================================================================
// 2. MODULAR COMPONENT CATALOG
// ============================================================================

export const MODULAR_COMPONENTS: ModularComponentMeta[] = [
  // ── 1. POWERTRAIN ENGINES ──
  {
    id: 'ENGINE_MODULAR_V8_TWIN_TURBO',
    name: '4.0L Twin-Turbo DOHC V8 (650 HP)',
    subsystem: 'powertrain_engine',
    compatibleBodyTypes: ['sedan', 'coupe', 'suv', 'wagon', 'convertible', 'sports_car', 'supercar', 'hypercar', 'pickup'],
    compatibleChassisIds: [], // universal
    parentAttachmentNodeId: 'ENGINE_MOUNT_FL',
    localOffsetMeters: [0.55, 0.18, 0],
    localRotationEuler: [0, 0, 0],
    massKg: 195,
    dragDeltaCd: 0,
    downforceKgAt200Kph: 0,
    torsionalStiffnessDeltaKNm: 4.5,
    costUSD: 14500,
    availableMaterials: ['cast', 'forged', 'billet', 'titanium'],
    defaultMaterial: 'forged',
    description: 'Cross-plane 90-degree V8 with hot-inside-V twin twin-scroll turbochargers and dry-sump lubrication.',
  },
  {
    id: 'ENGINE_MODULAR_V12_RACING',
    name: '6.5L Naturally Aspirated V12 (800 HP)',
    subsystem: 'powertrain_engine',
    compatibleBodyTypes: ['sedan', 'coupe', 'supercar', 'hypercar'],
    compatibleChassisIds: [],
    parentAttachmentNodeId: 'ENGINE_MOUNT_FL',
    localOffsetMeters: [0.6, 0.18, 0],
    localRotationEuler: [0, 0, 0],
    massKg: 245,
    dragDeltaCd: 0,
    downforceKgAt200Kph: 0,
    torsionalStiffnessDeltaKNm: 6.0,
    costUSD: 28000,
    availableMaterials: ['forged', 'billet', 'titanium'],
    defaultMaterial: 'billet',
    description: 'Screaming 9,500 RPM 65-degree V12 with individual throttle bodies and titanium connecting rods.',
  },
  {
    id: 'ENGINE_MODULAR_I4_TURBO',
    name: '2.0L Turbocharged Inline-4 (340 HP)',
    subsystem: 'powertrain_engine',
    compatibleBodyTypes: ['sedan', 'coupe', 'hatchback', 'wagon', 'convertible', 'sports_car', 'pickup'],
    compatibleChassisIds: [],
    parentAttachmentNodeId: 'ENGINE_MOUNT_FL',
    localOffsetMeters: [0.45, 0.18, 0],
    localRotationEuler: [0, 0, 0],
    massKg: 135,
    dragDeltaCd: 0,
    downforceKgAt200Kph: 0,
    torsionalStiffnessDeltaKNm: 2.0,
    costUSD: 6500,
    availableMaterials: ['cast', 'forged', 'billet'],
    defaultMaterial: 'cast',
    description: 'Compact high-boost direct-injected 4-cylinder engine with dual variable valve timing.',
  },
  {
    id: 'ENGINE_MODULAR_DUAL_EV_MOTOR',
    name: 'Dual-Motor Permanent Magnet Electric Drive (700 HP)',
    subsystem: 'powertrain_engine',
    compatibleBodyTypes: ['sedan', 'coupe', 'suv', 'hypercar', 'pickup'],
    compatibleChassisIds: [],
    parentAttachmentNodeId: 'ENGINE_MOUNT_FL',
    localOffsetMeters: [0.35, 0.12, 0],
    localRotationEuler: [0, 0, 0],
    massKg: 160,
    dragDeltaCd: 0,
    downforceKgAt200Kph: 0,
    torsionalStiffnessDeltaKNm: 8.0,
    costUSD: 16000,
    availableMaterials: ['forged', 'billet', 'titanium'],
    defaultMaterial: 'billet',
    description: '800V silicon-carbide inverter dual electric motors delivering instantaneous 1,050 Nm torque.',
  },

  // ── 2. TRANSMISSIONS ──
  {
    id: 'TRANS_7_SPEED_DCT',
    name: '7-Speed Dual-Clutch Transmission (DCT)',
    subsystem: 'transmission',
    compatibleBodyTypes: ['sedan', 'coupe', 'hatchback', 'suv', 'wagon', 'convertible', 'sports_car', 'supercar'],
    compatibleChassisIds: [],
    parentAttachmentNodeId: 'TRANS_MOUNT_REAR',
    localOffsetMeters: [-0.15, 0.12, 0],
    localRotationEuler: [0, 0, 0],
    massKg: 85,
    dragDeltaCd: 0,
    downforceKgAt200Kph: 0,
    torsionalStiffnessDeltaKNm: 1.5,
    costUSD: 5400,
    availableMaterials: ['cast', 'forged', 'billet'],
    defaultMaterial: 'forged',
    description: 'Wet multi-plate dual-clutch transmission executing lightning 80-millisecond paddle shifts.',
  },
  {
    id: 'TRANS_6_SPEED_MANUAL',
    name: '6-Speed Close-Ratio Manual (H-Pattern)',
    subsystem: 'transmission',
    compatibleBodyTypes: ['sedan', 'coupe', 'hatchback', 'wagon', 'convertible', 'sports_car'],
    compatibleChassisIds: [],
    parentAttachmentNodeId: 'TRANS_MOUNT_REAR',
    localOffsetMeters: [-0.15, 0.12, 0],
    localRotationEuler: [0, 0, 0],
    massKg: 62,
    dragDeltaCd: 0,
    downforceKgAt200Kph: 0,
    torsionalStiffnessDeltaKNm: 1.0,
    costUSD: 3200,
    availableMaterials: ['cast', 'forged', 'billet'],
    defaultMaterial: 'forged',
    description: 'Pure mechanical engagement with triple-cone brass synchros and short-throw shifter linkage.',
  },

  // ── 3. SUSPENSION HARDWARE ──
  {
    id: 'SUSP_DOUBLE_WISHBONE_RACE',
    name: 'Forged Aluminum Double-Wishbone Assembly',
    subsystem: 'suspension',
    compatibleBodyTypes: ['sedan', 'coupe', 'sports_car', 'supercar', 'hypercar', 'wagon'],
    compatibleChassisIds: [],
    parentAttachmentNodeId: 'SUSP_MOUNT_FL',
    localOffsetMeters: [0, 0, 0],
    localRotationEuler: [0, 0, 0],
    massKg: 48,
    dragDeltaCd: -0.005,
    downforceKgAt200Kph: 0,
    torsionalStiffnessDeltaKNm: 3.5,
    costUSD: 4200,
    availableMaterials: ['forged', 'billet', 'titanium'],
    defaultMaterial: 'forged',
    description: 'Dual A-arm geometry maintaining optimal camber angle under maximum cornering roll angles.',
  },
  {
    id: 'SUSP_MULTILINK_5_LINK',
    name: '5-Link Precision Multilink Rear Carrier',
    subsystem: 'suspension',
    compatibleBodyTypes: ['sedan', 'coupe', 'hatchback', 'suv', 'wagon', 'convertible', 'sports_car'],
    compatibleChassisIds: [],
    parentAttachmentNodeId: 'SUSP_MOUNT_RL',
    localOffsetMeters: [0, 0, 0],
    localRotationEuler: [0, 0, 0],
    massKg: 54,
    dragDeltaCd: 0,
    downforceKgAt200Kph: 0,
    torsionalStiffnessDeltaKNm: 4.0,
    costUSD: 3800,
    availableMaterials: ['forged', 'billet', 'titanium'],
    defaultMaterial: 'forged',
    description: 'Decoupled longitudinal and lateral force paths for superb bump compliance and wheel location.',
  },

  // ── 4. BRAKES & WHEELS ──
  {
    id: 'BRAKES_CARBON_CERAMIC_420',
    name: '420mm Carbon-Ceramic Matrix Rotors & 6-Piston Monoblocs',
    subsystem: 'wheels_brakes',
    compatibleBodyTypes: ['sedan', 'coupe', 'sports_car', 'supercar', 'hypercar'],
    compatibleChassisIds: [],
    parentAttachmentNodeId: 'SUSP_MOUNT_FL',
    localOffsetMeters: [0, 0, 0],
    localRotationEuler: [0, 0, 0],
    massKg: 28,
    dragDeltaCd: 0,
    downforceKgAt200Kph: 0,
    torsionalStiffnessDeltaKNm: 0,
    costUSD: 9500,
    availableMaterials: ['titanium', 'billet'],
    defaultMaterial: 'titanium',
    description: 'Carbon-silicon carbide discs offering fade-free 1,000°C thermal endurance and 50% unsprung mass reduction.',
  },
  {
    id: 'WHEELS_FORGED_19_LIGHTWEIGHT',
    name: '19-Inch Forged Monoblock Alloys & R-Spec Tires',
    subsystem: 'wheels_brakes',
    compatibleBodyTypes: ['sedan', 'coupe', 'hatchback', 'wagon', 'convertible', 'sports_car', 'supercar'],
    compatibleChassisIds: [],
    parentAttachmentNodeId: 'SUSP_MOUNT_FL',
    localOffsetMeters: [0, 0, 0],
    localRotationEuler: [0, 0, 0],
    massKg: 78,
    dragDeltaCd: -0.008,
    downforceKgAt200Kph: 0,
    torsionalStiffnessDeltaKNm: 0,
    costUSD: 4800,
    availableMaterials: ['forged', 'billet', 'titanium'],
    defaultMaterial: 'forged',
    description: 'Aircraft 6061-T6 forged monoblock wheels with 265/35R19 front and 295/30R19 rear sticky R-compounds.',
  },

  // ── 5. AERODYNAMICS ──
  {
    id: 'AERO_GT_PACKAGE_FULL',
    name: 'Motorsport Carbon Aero Suite (Splitter, Diffuser & Active Wing)',
    subsystem: 'aerodynamics',
    compatibleBodyTypes: ['sedan', 'coupe', 'sports_car', 'supercar', 'hypercar'],
    compatibleChassisIds: [],
    parentAttachmentNodeId: 'AERO_FRONT_SPLITTER',
    localOffsetMeters: [0, 0, 0],
    localRotationEuler: [0, 0, 0],
    massKg: 24,
    dragDeltaCd: 0.035,
    downforceKgAt200Kph: 340,
    torsionalStiffnessDeltaKNm: 1.0,
    costUSD: 8500,
    availableMaterials: ['billet', 'titanium'],
    defaultMaterial: 'titanium',
    description: 'Autoclave pre-preg carbon front splitter with dive planes, floor strakes, and hydraulic active DRS rear wing.',
  },

  // ── 6. INTERIOR & CABIN ──
  {
    id: 'CABIN_CARBON_SPORT_BUCKETS',
    name: 'Nappa Leather & Carbon Race Shell Interior',
    subsystem: 'interior_cabin',
    compatibleBodyTypes: ['sedan', 'coupe', 'sports_car', 'supercar', 'hypercar'],
    compatibleChassisIds: [],
    parentAttachmentNodeId: 'CABIN_MOUNT_B_PILLAR_L',
    localOffsetMeters: [0, 0, 0],
    localRotationEuler: [0, 0, 0],
    massKg: 52,
    dragDeltaCd: 0,
    downforceKgAt200Kph: 0,
    torsionalStiffnessDeltaKNm: 2.0,
    costUSD: 7200,
    availableMaterials: ['forged', 'billet', 'titanium'],
    defaultMaterial: 'forged',
    description: 'Ultra-light carbon fiber bucket seat shells upholstered in semi-aniline Nappa leather and Alcantara.',
  },

  // ── 7. ELECTRONICS & VIRTUAL COCKPIT ──
  {
    id: 'ELEC_VIRTUAL_COCKPIT_PRO',
    name: 'Tri-Screen OLED Virtual Cockpit & Level-2 ADAS Radar',
    subsystem: 'electronics',
    compatibleBodyTypes: ['sedan', 'coupe', 'hatchback', 'suv', 'wagon', 'convertible', 'sports_car', 'supercar', 'hypercar', 'pickup'],
    compatibleChassisIds: [],
    parentAttachmentNodeId: 'CABIN_MOUNT_A_PILLAR_L',
    localOffsetMeters: [0, 0, 0],
    localRotationEuler: [0, 0, 0],
    massKg: 18,
    dragDeltaCd: 0,
    downforceKgAt200Kph: 0,
    torsionalStiffnessDeltaKNm: 0,
    costUSD: 4900,
    availableMaterials: ['billet', 'titanium'],
    defaultMaterial: 'billet',
    description: 'Seamless glass curved dual 14.9-inch displays with real-time CAN-FD telemetry and forward phased-array radar.',
  },
];
