// ============================================================================
// CAR MODEL REGISTRY - GLB EXTERIOR MODEL CATALOG
// ============================================================================

export interface CarModelEntry {
  id: string;
  name: string;
  subtitle: string;
  glbPath: string;
  defaultPaint: number;
  caliperColor: string;
  tier: string;
  year: number;
  origin: string;
  power: string;
  weight: string;
  paintFinish: string;
}

export const CAR_MODEL_REGISTRY: CarModelEntry[] = [
  {
    id: "bmw_i8",
    name: "BMW i8",
    subtitle: "Hybrid Supercar",
    glbPath: "/models/exterior/sports_car_bmw_i8.glb",
    defaultPaint: 0x0044cc,
    caliperColor: "#ff1100",
    tier: "supercar",
    year: 2023,
    origin: "Germany",
    power: "570 HP",
    weight: "1,490 kg",
  },
  {
    id: "sports_coupe_gt",
    name: "Sports Coupe GT",
    subtitle: "Grand Touring",
    glbPath: "/models/exterior/sports_coupe_gt.glb",
    defaultPaint: 0x8b0000,
    caliperColor: "#222222",
    tier: "gt",
    year: 2024,
    origin: "UK",
    power: "620 HP",
    weight: "1,580 kg",
  },
  {
    id: "ford_escort_cosworth",
    name: "Ford Escort RS Cosworth",
    subtitle: "Rally Homologation",
    glbPath: "/models/exterior/ford_escort_rs_cosworth_hood_closed.glb",
    defaultPaint: 0xffffff,
    caliperColor: "#ffcc00",
    tier: "rally",
    year: 1996,
    origin: "UK",
    power: "227 HP",
    weight: "1,275 kg",
  },
  {
    id: "ford_escort_gt3",
    name: "Ford Escort Cosworth GT3",
    subtitle: "Track Edition",
    glbPath: "/models/exterior/ford_escort_rs_cosworth_gt3_hood_closed.glb",
    defaultPaint: 0x1a1a2e,
    caliperColor: "#ff4444",
    tier: "rally",
    year: 2024,
    origin: "UK",
    power: "450 HP",
    weight: "1,150 kg",
  },
  {
    id: "hypercar_apex_gt3",
    name: "Apex GT3 Hypercar",
    subtitle: "Race Hypercar",
    glbPath: "/models/exterior/vehicle_hypercar_apex_gt3.glb",
    defaultPaint: 0xcc0000,
    caliperColor: "#00ff88",
    tier: "hypercar",
    year: 2024,
    origin: "Italy",
    power: "1,000 HP",
    weight: "1,050 kg",
  },
  {
    id: "apex_gt_stradale",
    name: "Apex GT Stradale",
    subtitle: "Road-Legal Hypercar",
    glbPath: "/models/exterior/vehicle_apex_hyper_gt_stradale.glb",
    defaultPaint: 0x2d5016,
    caliperColor: "#ffd700",
    tier: "hypercar",
    year: 2024,
    origin: "Italy",
    power: "840 HP",
    weight: "1,300 kg",
  },
  {
    id: "valkyrie_lmh",
    name: "Valkyrie LMH",
    subtitle: "Le Mans Hybrid",
    glbPath: "/models/exterior/vehicle_apex_hyper_valkyrie_lmh.glb",
    defaultPaint: 0x0a0a0a,
    caliperColor: "#ff6600",
    tier: "hypercar",
    year: 2024,
    origin: "UK",
    power: "1,100 HP",
    weight: "1,030 kg",
  },
  {
    id: "lemans_prototype",
    name: "Le Mans Prototype",
    subtitle: "LMP Race Car",
    glbPath: "/models/exterior/vehicle_lemans_prototype.glb",
    defaultPaint: 0x003399,
    caliperColor: "#ffcc00",
    tier: "prototype",
    year: 2024,
    origin: "France",
    power: "700 HP",
    weight: "930 kg",
  },
  {
    id: "wec_hypercar",
    name: "WEC Hypercar",
    subtitle: "FIA WEC Entry",
    glbPath: "/models/exterior/vehicle_wec_le_mans_hypercar_prototype.glb",
    defaultPaint: 0xff0000,
    caliperColor: "#0088ff",
    tier: "prototype",
    year: 2024,
    origin: "Germany",
    power: "680 HP",
    weight: "1,030 kg",
  },
  {
    id: "cyber_pursuit_gt",
    name: "Cyber Pursuit GT",
    subtitle: "Autonomous Concept",
    glbPath: "/models/exterior/vehicle_cyber_autonomous_pursuit_gt.glb",
    defaultPaint: 0x111122,
    caliperColor: "#00ffff",
    tier: "concept",
    year: 2030,
    origin: "Japan",
    power: "850 HP",
    weight: "1,650 kg",
  },
  {
    id: "phantom_carbon_gt",
    name: "Phantom Carbon GT",
    subtitle: "Forged Carbon Edition",
    glbPath: "/models/exterior/vehicle_phantom_forged_carbon_gt.glb",
    defaultPaint: 0x222222,
    caliperColor: "#ff3366",
    tier: "concept",
    year: 2024,
    origin: "Italy",
    power: "780 HP",
    weight: "1,420 kg",
  },
  {
    id: "grand_tourer",
    name: "Grand Tourer Coupe",
    subtitle: "Luxury Performance",
    glbPath: "/models/exterior/vehicle_grand_tourer_coupe.glb",
    defaultPaint: 0x2c3e50,
    caliperColor: "#bdc3c7",
    tier: "production",
    year: 2024,
    origin: "Germany",
    power: "630 HP",
    weight: "1,720 kg",
  },
  {
    id: "nurburgring_stance",
    name: "Nurburgring Stance King",
    subtitle: "Widebody Build",
    glbPath: "/models/exterior/vehicle_nurburgring_dssv_stance_king.glb",
    defaultPaint: 0x800080,
    caliperColor: "#ffd700",
    tier: "production",
    year: 2024,
    origin: "Japan",
    power: "520 HP",
    weight: "1,350 kg",
  },
  {
    id: "time_attack",
    name: "Time Attack Phantom",
    subtitle: "Track Weapon",
    glbPath: "/models/exterior/vehicle_time_attack_carbon_phantom.glb",
    defaultPaint: 0x333333,
    caliperColor: "#00ff00",
    tier: "production",
    year: 2024,
    origin: "Japan",
    power: "600 HP",
    weight: "1,180 kg",
  },
  {
    id: "formula_supremacy",
    name: "Formula Supremacy",
    subtitle: "Aero Spec",
    glbPath: "/models/exterior/vehicle_formula_supremacy_aero_spec.glb",
    defaultPaint: 0xcc0000,
    caliperColor: "#ffffff",
    tier: "prototype",
    year: 2024,
    origin: "UK",
    power: "900 HP",
    weight: "780 kg",
  },
];

export const TIER_LABELS: Record<string, string> = {
  supercar: "Supercars",
  gt: "Grand Tourers",
  rally: "Rally & Touring",
  hypercar: "Hypercars",
  prototype: "Prototypes",
  concept: "Concepts",
  production: "Production",
};

export const findModelById = (id: string): CarModelEntry =>
  CAR_MODEL_REGISTRY.find(m => m.id === id) ?? CAR_MODEL_REGISTRY[0];
